parameters:
  name: ''
  iosVersion: ''
  tvosVersion: ''
  xcodeVersion: ''
  deviceName: 'iphone simulator'
  skipTvOs: False
  tvosName: ''
  tvosDeviceName: ''
  nodeVersion: 16.x
  launchWithIDB: false
  vmImage: 'macOS-10.15'
jobs:
  - template: ./ios-e2e-template.yml
    parameters:
      name: e2e_basic_${{ parameters.name }}
      iosVersion: ${{ parameters.iosVersion }}
      xcodeVersion: ${{ parameters.xcodeVersion }}
      deviceName: ${{ parameters.deviceName }}
      vmImage: ${{ parameters.vmImage }}
      nodeVersion: ${{ parameters.nodeVersion }}
      script: npm run e2e-test
