function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var e=this||self;try{var f=window}catch(a){f=e};function k(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function l(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function m(a){var b=l(a);return b=="array"||b=="object"&&typeof a.length=="number"};function n(a,b){this.code=a;this.state=p[a]||q;this.message=b||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(b<0||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}(function(){function a(){}a.prototype=Error.prototype;n.prototype=new a;n.prototype.constructor=n})();var q="unknown error",p={15:"element not selectable",11:"element not visible"};p[31]=q;p[30]=q;
p[24]="invalid cookie domain";p[29]="invalid element coordinates";p[12]="invalid element state";p[32]="invalid selector";p[51]="invalid selector";p[52]="invalid selector";p[17]="javascript error";p[405]="unsupported operation";p[34]="move target out of bounds";p[27]="no such alert";p[7]="no such element";p[8]="no such frame";p[23]="no such window";p[28]="script timeout";p[33]="session not created";p[10]="stale element reference";p[21]="timeout";p[25]="unable to set cookie";p[26]="unexpected alert open";
p[13]=q;p[9]="unknown command";n.prototype.toString=function(){return this.name+": "+this.message};const u=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){var c=a.length,d=Array(c),g=typeof a==="string"?a.split(""):a;for(let h=0;h<c;h++)h in g&&(d[h]=b.call(void 0,g[h],h,a));return d};var w=class{constructor(a){if(v!==v)throw Error("SafeUrl is not meant to be built directly");this.l=a}toString(){return this.l.toString()}},v={};new w("about:invalid#zClosurez");new w("about:blank");const x={};class y{constructor(){if(x!==x)throw Error("SafeStyle is not meant to be built directly");this.j=""}toString(){return this.j.toString()}}new y;function z(a,b){var c={};for(let d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function A(a,b){var c={};for(let d in a)c[d]=b.call(void 0,a[d],d,a);return c}function B(a,b){return a!==null&&b in a}function C(a,b){for(let c in a)if(b.call(void 0,a[c],c,a))return c};const D={};class E{constructor(){if(D!==D)throw Error("SafeStyleSheet is not meant to be built directly");this.i=""}toString(){return this.i.toString()}}new E;function F(){var a=e.navigator;return a&&(a=a.userAgent)?a:""}function G(a){return F().indexOf(a)!=-1};function H(){return G("Firefox")||G("FxiOS")}function I(){return(G("Chrome")||G("CriOS"))&&!G("Edge")||G("Silk")};const J={};class K{constructor(){var a=e.trustedTypes&&e.trustedTypes.emptyHTML||"";if(J!==J)throw Error("SafeHtml is not meant to be built directly");this.h=a}toString(){return this.h.toString()}}new K;function L(){return G("iPhone")&&!G("iPod")&&!G("iPad")};var M=H(),N=L()||G("iPod"),O=G("iPad"),P=G("Android")&&!(I()||H()||G("Opera")||G("Silk")),Q=I(),aa=G("Safari")&&!(I()||G("Coast")||G("Opera")||G("Edge")||G("Edg/")||G("OPR")||H()||G("Silk")||G("Android"))&&!(L()||G("iPad")||G("iPod"));function R(a){return(a=a.exec(F()))?a[1]:""}(function(){if(M)return R(/Firefox\/([0-9.]+)/);if(Q){if(L()||G("iPad")||G("iPod")||G("Macintosh")){var a=R(/CriOS\/([0-9.]+)/);if(a)return a}return R(/Chrome\/([0-9.]+)/)}if(aa&&!(L()||G("iPad")||G("iPod")))return R(/Version\/([0-9.]+)/);if(N||O){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(F()))return a[1]+"."+a[2]}else if(P)return(a=R(/Android\s+([0-9.]+)/))?a:R(/Version\/([0-9.]+)/);return""})();function ba(){return document.activeElement||document.body};var ca=JSON.stringify;function da(a){function b(c,d){switch(l(c)){case "string":case "number":case "boolean":return c;case "function":return c.toString();case "array":return u(c,function(h){return b(h,d)});case "object":if(d.indexOf(c)>=0)throw new n(17,"Recursive object cannot be transferred");if(B(c,"nodeType")&&(c.nodeType==1||c.nodeType==9)){var g={};g.ELEMENT=S(c);return g}if(B(c,"document"))return g={},g.WINDOW=S(c),g;d.push(c);if(m(c))return u(c,function(h){return b(h,d)});c=z(c,function(h,r){return typeof r===
"number"||typeof r==="string"});return A(c,function(h){return b(h,d)});default:return null}}return b(a,[])}function T(a,b){return Array.isArray(a)?u(a,function(c){return T(c,b)}):k(a)?typeof a=="function"?a:B(a,"ELEMENT")?U(a.ELEMENT,b):B(a,"WINDOW")?U(a.WINDOW,b):A(a,function(c){return T(c,b)}):a}function V(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.g=Date.now());b.g||(b.g=Date.now());return b}
function S(a){var b=V(a.ownerDocument),c=C(b,function(d){return d==a});c||(c=":wdc:"+b.g++,b[c]=a);return c}
function U(a,b){a=decodeURIComponent(a);b=b||document;var c=V(b);if(!B(c,a))throw new n(10,"Element does not exist in cache");var d=c[a];if(B(d,"setInterval")){if(d.closed)throw delete c[a],new n(23,"Window has been closed.");return d}for(var g=d;g;){if(g==b.documentElement)return d;g.host&&g.nodeType===11&&(g=g.host);g=g.parentNode}delete c[a];throw new n(10,"Element is no longer attached to the DOM");};function W(){var a=ba,b=[],c=window||f;try{a:{var d=a;if(typeof d==="string")try{a=new c.Function(d);break a}catch(t){throw t;}a=c==window?d:new c.Function("return ("+d+").apply(null,arguments);")}var g=T(b,c.document),h=a.apply(null,g);var r={status:0,value:da(h)}}catch(t){r={status:B(t,"code")?t.code:13,value:{message:t.message}}}return ca(r)}var X=["se_exportedFunctionSymbol"],Y=e;X[0]in Y||typeof Y.execScript=="undefined"||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||W===void 0?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=W;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
