function(){return function(){var h,aa=this;function m(a){return void 0!==a}function n(a){return"string"==typeof a}function ba(a){return"number"==typeof a}function ca(a,b){a=a.split(".");var c=aa;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function fa(a){return"function"==da(a)}function ga(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var ha="closure_uid_"+(1E9*Math.random()>>>0),ia=0;function ja(a,b,c){return a.call.apply(a.bind,arguments)}
function ka(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function la(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?la=ja:la=ka;return la.apply(null,arguments)}
function ma(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var na=Date.now||function(){return+new Date};function p(a,b){function c(){}c.prototype=b.prototype;a.aa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Z=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var oa=window;var pa;function qa(a){var b=a.length-1;return 0<=b&&a.indexOf(" ",b)==b}var ra=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function sa(a,b){var c=0;a=ra(String(a)).split(".");b=ra(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;!c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=ta(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||ta(0==f[2].length,0==g[2].length)||ta(f[2],g[2]);f=f[3];g=g[3]}while(!c)}return c}function ta(a,b){return a<b?-1:a>b?1:0}
function ua(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};function va(a,b){if(n(a))return n(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function r(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)}function wa(a,b){for(var c=a.length,d=[],e=0,f=n(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d}function xa(a,b){for(var c=a.length,d=Array(c),e=n(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}
function ya(a,b,c){var d=c;r(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function za(a,b){for(var c=a.length,d=n(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Aa(a,b){for(var c=a.length,d=n(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}function Ba(a,b){a:{for(var c=a.length,d=n(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:n(a)?a.charAt(b):a[b]}
function Ca(a){return Array.prototype.concat.apply([],arguments)}function Da(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Ea={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Fa="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Ga=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Ha=/^#(?:[0-9a-f]{3}){1,2}$/i,Ja=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Ka=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function t(a,b){this.code=a;this.a=v[a]||La;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}p(t,Error);var La="unknown error",v={15:"element not selectable",11:"element not visible"};v[31]=La;v[30]=La;v[24]="invalid cookie domain";v[29]="invalid element coordinates";v[12]="invalid element state";
v[32]="invalid selector";v[51]="invalid selector";v[52]="invalid selector";v[17]="javascript error";v[405]="unsupported operation";v[34]="move target out of bounds";v[27]="no such alert";v[7]="no such element";v[8]="no such frame";v[23]="no such window";v[28]="script timeout";v[33]="session not created";v[10]="stale element reference";v[21]="timeout";v[25]="unable to set cookie";v[26]="unexpected alert open";v[13]=La;v[9]="unknown command";t.prototype.toString=function(){return this.name+": "+this.message};var Ma;a:{var Na=aa.navigator;if(Na){var Oa=Na.userAgent;if(Oa){Ma=Oa;break a}}Ma=""}function w(a){return-1!=Ma.indexOf(a)};function Pa(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function Qa(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function Ra(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Sa(a,b){return null!==a&&b in a}function Ta(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function Ua(){return(w("Chrome")||w("CriOS"))&&!w("Edge")};function Va(){return w("iPhone")&&!w("iPod")&&!w("iPad")};function Wa(a,b){var c=Xa;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Ya=w("Opera"),x=w("Trident")||w("MSIE"),Za=w("Edge"),y=w("Gecko")&&!(-1!=Ma.toLowerCase().indexOf("webkit")&&!w("Edge"))&&!(w("Trident")||w("MSIE"))&&!w("Edge"),A=-1!=Ma.toLowerCase().indexOf("webkit")&&!w("Edge"),$a=A&&w("Mobile"),ab=w("Macintosh"),bb=w("Windows");function cb(){var a=aa.document;return a?a.documentMode:void 0}var db;
a:{var eb="",fb=function(){var a=Ma;if(y)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Za)return/Edge\/([\d\.]+)/.exec(a);if(x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(A)return/WebKit\/(\S+)/.exec(a);if(Ya)return/(?:Version)[ \/]?(\S+)/.exec(a)}();fb&&(eb=fb?fb[1]:"");if(x){var gb=cb();if(null!=gb&&gb>parseFloat(eb)){db=String(gb);break a}}db=eb}var Xa={};function hb(a){return Wa(a,function(){return 0<=sa(db,a)})}function ib(a){return Number(jb)>=a}var kb;var lb=aa.document;
kb=lb&&x?cb()||("CSS1Compat"==lb.compatMode?parseInt(db,10):5):void 0;var jb=kb;var mb=w("Firefox"),nb=Va()||w("iPod"),ob=w("iPad"),pb=w("Android")&&!(Ua()||w("Firefox")||w("Opera")||w("Silk")),qb=Ua(),rb=w("Safari")&&!(Ua()||w("Coast")||w("Opera")||w("Edge")||w("Silk")||w("Android"))&&!(Va()||w("iPad")||w("iPod"));function sb(a){return(a=a.exec(Ma))?a[1]:""}var tb=function(){if(mb)return sb(/Firefox\/([0-9.]+)/);if(x||Za||Ya)return db;if(qb)return Va()||w("iPad")||w("iPod")?sb(/CriOS\/([0-9.]+)/):sb(/Chrome\/([0-9.]+)/);if(rb&&!(Va()||w("iPad")||w("iPod")))return sb(/Version\/([0-9.]+)/);if(nb||ob){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Ma);if(a)return a[1]+"."+a[2]}else if(pb)return(a=sb(/Android\s+([0-9.]+)/))?a:sb(/Version\/([0-9.]+)/);return""}();var ub,vb;function wb(a){return xb?ub(a):x?0<=sa(jb,a):hb(a)}function yb(a){return xb?vb(a):pb?0<=sa(zb,a):0<=sa(tb,a)}
var xb=function(){if(!y)return!1;var a=aa.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;ub=function(a){return 0<=c.compare(d,""+a)};vb=function(a){return 0<=c.compare(e,""+a)};return!0}(),Ab;try{Ab=!!(aa.chrome||aa.$).extension}catch(a){Ab=!1}var Bb=Ab,Cb=ob||nb,Db;
if(pb){var Eb=/Android\s+([0-9\.]+)/.exec(Ma);Db=Eb?Eb[1]:"0"}else Db="0";var zb=Db,Fb=x&&!ib(8),Gb=ib(9),Hb=x&&!ib(9),Ib=ib(10);pb&&yb(2.3);pb&&yb(4);rb&&yb(6);var Jb=x&&-1!=Ma.indexOf("IEMobile");function Kb(a,b){this.x=m(a)?a:0;this.y=m(b)?b:0}h=Kb.prototype;h.toString=function(){return"("+this.x+", "+this.y+")"};h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};h.scale=function(a,b){b=ba(b)?b:a;this.x*=a;this.y*=b;return this};function Lb(a,b){this.width=a;this.height=b}h=Lb.prototype;h.toString=function(){return"("+this.width+" x "+this.height+")"};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};h.scale=function(a,b){b=ba(b)?b:a;this.width*=a;this.height*=b;return this};function Mb(a){return a?new Nb(B(a)):pa||(pa=new Nb)}function Ob(a){return a.scrollingElement?a.scrollingElement:A||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function Pb(a){return a?a.parentWindow||a.defaultView:window}function Qb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}
function Rb(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Sb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(x&&!ib(9)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Tb(a,b):!c&&Rb(e,b)?-1*Ub(a,b):!d&&Rb(f,a)?Ub(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=B(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(aa.Range.START_TO_END,a)}function Ub(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Tb(b,a)}function Tb(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function B(a){return 9==a.nodeType?a:a.ownerDocument||a.document}var Vb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Wb={IMG:" ",BR:"\n"};
function Xb(a,b,c){if(!(a.nodeName in Vb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Wb)b.push(Wb[a.nodeName]);else for(a=a.firstChild;a;)Xb(a,b,c),a=a.nextSibling}function Yb(a,b,c){a&&!c&&(a=a.parentNode);for(c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function Nb(a){this.a=a||aa.document||document}Nb.prototype.getElementsByTagName=function(a,b){return(b||this.a).getElementsByTagName(String(a))};
function Zb(a,b,c,d){a=d||a.a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))c=a.querySelectorAll(e+(c?"."+c:""));else if(c&&a.getElementsByClassName)if(d=a.getElementsByClassName(c),e){a={};for(var f=b=0,g;g=d[f];f++)e==g.nodeName&&(a[b++]=g);a.length=b;c=a}else c=d;else if(d=a.getElementsByTagName(e||"*"),c){a={};for(f=b=0;g=d[f];f++){var e=g.className,k;if(k="function"==typeof e.split)k=0<=va(e.split(/\s+/),c);k&&(a[b++]=g)}a.length=b;c=a}else c=d;return c}
Nb.prototype.contains=Rb;function $b(a,b){b=b.toLowerCase();return"style"==b?ac(a.style.cssText):Fb&&"value"==b&&C(a,"INPUT")?a.value:Hb&&!0===a[b]?String(a.getAttribute(b)):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var bc=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function ac(a){var b=[];r(a.split(bc),function(a){var c=a.indexOf(":");0<c&&(a=[a.slice(0,c),a.slice(c+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function cc(a,b){Fb&&"value"==b&&C(a,"OPTION")&&null===$b(a,"value")?(b=[],Xb(a,b,!1),a=b.join("")):a=a[b];return a}function C(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)}
function dc(a){return C(a,"OPTION")?!0:C(a,"INPUT")?(a=a.type.toLowerCase(),"checkbox"==a||"radio"==a):!1}function ec(a){if(!dc(a))throw new t(15,"Element is not selectable");var b="selected",c=a.type&&a.type.toLowerCase();if("checkbox"==c||"radio"==c)b="checked";return!!cc(a,b)};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function fc(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var gc=x&&!ib(9),hc=x&&!ib(8);function ic(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function jc(a,b){var c=hc&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new ic(b,a,b.nodeName,c)};function kc(a){this.b=a;this.a=0}function lc(a){a=a.match(mc);for(var b=0;b<a.length;b++)nc.test(a[b])&&a.splice(b,1);return new kc(a)}var mc=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,nc=/^\s/;function D(a,b){return a.b[a.a+(b||0)]}kc.prototype.next=function(){return this.b[this.a++]};function oc(a){return a.b.length<=a.a};function pc(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(gc&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),gc&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function qc(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}hc&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function rc(a,b,c,d,e){return(gc?sc:tc).call(null,a,b,n(c)?c:null,n(d)?d:null,e||new E)}
function sc(a,b,c,d,e){if(a instanceof uc||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;var g=vc(a);if("*"!=g&&(f=b.getElementsByTagName(g),!f))return e;if(c){var k=[];for(a=0;b=f[a++];)qc(b,c,d)&&k.push(b);f=k}for(a=0;b=f[a++];)"*"==g&&"!"==b.tagName||F(e,b);return e}wc(a,b,c,d,e);return e}
function tc(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!x?(b=b.getElementsByName(d),r(b,function(b){a.a(b)&&F(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),r(b,function(b){b.className==d&&a.a(b)&&F(e,b)})):a instanceof xc?wc(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),r(b,function(a){qc(a,c,d)&&F(e,a)}));return e}
function yc(a,b,c,d,e){var f;if((a instanceof uc||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=vc(a);if("*"!=g&&(f=wa(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=wa(f,function(a){return qc(a,c,d)}));r(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||F(e,a)});return e}return zc(a,b,c,d,e)}function zc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)qc(b,c,d)&&a.a(b)&&F(e,b);return e}
function wc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)qc(b,c,d)&&a.a(b)&&F(e,b),wc(a,b,c,d,e)}function vc(a){if(a instanceof xc){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function E(){this.b=this.a=null;this.s=0}function Ac(a){this.node=a;this.next=this.a=null}function Bc(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;){e=c.node;var g=b.node;e==g||e instanceof ic&&g instanceof ic&&e.a==g.a?(e=c,c=c.next,b=b.next):0<Sb(c.node,b.node)?(e=b,b=b.next):(e=c,c=c.next);(e.a=d)?d.next=e:a.a=e;d=e;f++}for(e=c||b;e;)e.a=d,d=d.next=e,f++,e=e.next;a.b=d;a.s=f;return a}function Cc(a,b){b=new Ac(b);b.next=a.a;a.b?a.a.a=b:a.a=a.b=b;a.a=b;a.s++}
function F(a,b){b=new Ac(b);b.a=a.b;a.a?a.b.next=b:a.a=a.b=b;a.b=b;a.s++}function Dc(a){return(a=a.a)?a.node:null}function Ec(a){return(a=Dc(a))?pc(a):""}E.prototype.iterator=function(a){return new Fc(this,!!a)};function Fc(a,b){this.f=a;this.b=(this.C=b)?a.b:a.a;this.a=null}Fc.prototype.next=function(){var a=this.b;if(a){var b=this.a=a;this.b=this.C?a.a:a.next;return b.node}return null};function G(a){this.l=a;this.b=this.j=!1;this.f=null}function H(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Gc(a,b){a.j=b}function Hc(a,b){a.b=b}function I(a,b){a=a.a(b);return a instanceof E?+Ec(a):+a}function J(a,b){a=a.a(b);return a instanceof E?Ec(a):""+a}function Ic(a,b){a=a.a(b);return a instanceof E?!!a.s:!!a};function Jc(a,b,c){G.call(this,a.l);this.c=a;this.g=b;this.m=c;this.j=b.j||c.j;this.b=b.b||c.b;this.c==Kc&&(c.b||c.j||4==c.l||0==c.l||!b.f?b.b||b.j||4==b.l||0==b.l||!c.f||(this.f={name:c.f.name,D:b}):this.f={name:b.f.name,D:c})}p(Jc,G);
function Lc(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof E&&c instanceof E){b=b.iterator();for(d=b.next();d;d=b.next())for(e=c.iterator(),f=e.next();f;f=e.next())if(a(pc(d),pc(f)))return!0;return!1}if(b instanceof E||c instanceof E){b instanceof E?(e=b,d=c):(e=c,d=b);f=e.iterator();for(var g=typeof d,k=f.next();k;k=f.next()){switch(g){case "number":k=+pc(k);break;case "boolean":k=!!pc(k);break;case "string":k=pc(k);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&
a(k,d)||e==c&&a(d,k))return!0}return!1}return e?"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Jc.prototype.a=function(a){return this.c.v(this.g,this.m,a)};Jc.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+H(this.g);return a+=H(this.m)};function Mc(a,b,c,d){this.X=a;this.R=b;this.l=c;this.v=d}Mc.prototype.toString=function(){return this.X};var Nc={};
function K(a,b,c,d){if(Nc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Mc(a,b,c,d);return Nc[a.toString()]=a}K("div",6,1,function(a,b,c){return I(a,c)/I(b,c)});K("mod",6,1,function(a,b,c){return I(a,c)%I(b,c)});K("*",6,1,function(a,b,c){return I(a,c)*I(b,c)});K("+",5,1,function(a,b,c){return I(a,c)+I(b,c)});K("-",5,1,function(a,b,c){return I(a,c)-I(b,c)});K("<",4,2,function(a,b,c){return Lc(function(a,b){return a<b},a,b,c)});
K(">",4,2,function(a,b,c){return Lc(function(a,b){return a>b},a,b,c)});K("<=",4,2,function(a,b,c){return Lc(function(a,b){return a<=b},a,b,c)});K(">=",4,2,function(a,b,c){return Lc(function(a,b){return a>=b},a,b,c)});var Kc=K("=",3,2,function(a,b,c){return Lc(function(a,b){return a==b},a,b,c,!0)});K("!=",3,2,function(a,b,c){return Lc(function(a,b){return a!=b},a,b,c,!0)});K("and",2,2,function(a,b,c){return Ic(a,c)&&Ic(b,c)});K("or",1,2,function(a,b,c){return Ic(a,c)||Ic(b,c)});function Oc(a,b){if(b.a.length&&4!=a.l)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");G.call(this,a.l);this.c=a;this.g=b;this.j=a.j;this.b=a.b}p(Oc,G);Oc.prototype.a=function(a){a=this.c.a(a);return Pc(this.g,a)};Oc.prototype.toString=function(){var a="Filter:"+H(this.c);return a+=H(this.g)};function Qc(a,b){if(b.length<a.O)throw Error("Function "+a.o+" expects at least"+a.O+" arguments, "+b.length+" given");if(null!==a.I&&b.length>a.I)throw Error("Function "+a.o+" expects at most "+a.I+" arguments, "+b.length+" given");a.W&&r(b,function(b,d){if(4!=b.l)throw Error("Argument "+d+" to function "+a.o+" is not of type Nodeset: "+b);});G.call(this,a.l);this.G=a;this.c=b;Gc(this,a.j||za(b,function(a){return a.j}));Hc(this,a.V&&!b.length||a.U&&!!b.length||za(b,function(a){return a.b}))}
p(Qc,G);Qc.prototype.a=function(a){return this.G.v.apply(null,Ca(a,this.c))};Qc.prototype.toString=function(){var a="Function: "+this.G;if(this.c.length)var b=ya(this.c,function(a,b){return a+H(b)},"Arguments:"),a=a+H(b);return a};function Rc(a,b,c,d,e,f,g,k,l){this.o=a;this.l=b;this.j=c;this.V=d;this.U=e;this.v=f;this.O=g;this.I=m(k)?k:g;this.W=!!l}Rc.prototype.toString=function(){return this.o};var Sc={};
function L(a,b,c,d,e,f,g,k){if(Sc.hasOwnProperty(a))throw Error("Function already created: "+a+".");Sc[a]=new Rc(a,b,c,d,!1,e,f,g,k)}L("boolean",2,!1,!1,function(a,b){return Ic(b,a)},1);L("ceiling",1,!1,!1,function(a,b){return Math.ceil(I(b,a))},1);L("concat",3,!1,!1,function(a,b){return ya(Da(arguments,1),function(b,d){return b+J(d,a)},"")},2,null);L("contains",2,!1,!1,function(a,b,c){b=J(b,a);a=J(c,a);return-1!=b.indexOf(a)},2);L("count",1,!1,!1,function(a,b){return b.a(a).s},1,1,!0);
L("false",2,!1,!1,function(){return!1},0);L("floor",1,!1,!1,function(a,b){return Math.floor(I(b,a))},1);L("id",4,!1,!1,function(a,b){function c(a){if(gc){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Ba(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument;a=J(b,a).split(/\s+/);var f=[];r(a,function(a){a=c(a);!a||0<=va(f,a)||f.push(a)});f.sort(Sb);var g=new E;r(f,function(a){F(g,a)});return g},1);
L("lang",2,!1,!1,function(){return!1},1);L("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);L("local-name",3,!1,!0,function(a,b){return(a=b?Dc(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);L("name",3,!1,!0,function(a,b){return(a=b?Dc(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);L("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
L("normalize-space",3,!1,!0,function(a,b){return(b?J(b,a):pc(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);L("not",2,!1,!1,function(a,b){return!Ic(b,a)},1);L("number",1,!1,!0,function(a,b){return b?I(b,a):+pc(a.a)},0,1);L("position",1,!0,!1,function(a){return a.b},0);L("round",1,!1,!1,function(a,b){return Math.round(I(b,a))},1);L("starts-with",2,!1,!1,function(a,b,c){b=J(b,a);a=J(c,a);return!b.lastIndexOf(a,0)},2);L("string",3,!1,!0,function(a,b){return b?J(b,a):pc(a.a)},0,1);
L("string-length",1,!1,!0,function(a,b){return(b?J(b,a):pc(a.a)).length},0,1);L("substring",3,!1,!1,function(a,b,c,d){c=I(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?I(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=J(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);L("substring-after",3,!1,!1,function(a,b,c){b=J(b,a);a=J(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
L("substring-before",3,!1,!1,function(a,b,c){b=J(b,a);a=J(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);L("sum",1,!1,!1,function(a,b){a=b.a(a).iterator();b=0;for(var c=a.next();c;c=a.next())b+=+pc(c);return b},1,1,!0);L("translate",3,!1,!1,function(a,b,c,d){b=J(b,a);c=J(c,a);var e=J(d,a);d={};for(var f=0;f<c.length;f++)a=c.charAt(f),a in d||(d[a]=e.charAt(f));c="";for(f=0;f<b.length;f++)a=b.charAt(f),c+=a in d?d[a]:a;return c},3);L("true",2,!1,!1,function(){return!0},0);function xc(a,b){this.g=a;this.c=m(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Tc(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}xc.prototype.a=function(a){return null===this.b||this.b==a.nodeType};xc.prototype.f=function(){return this.g};
xc.prototype.toString=function(){var a="Kind Test: "+this.g;null===this.c||(a+=H(this.c));return a};function Uc(a){G.call(this,3);this.c=a.substring(1,a.length-1)}p(Uc,G);Uc.prototype.a=function(){return this.c};Uc.prototype.toString=function(){return"Literal: "+this.c};function uc(a,b){this.o=a.toLowerCase();a="*"==this.o?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():a}uc.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=m(a.localName)?a.localName:a.nodeName;return"*"!=this.o&&this.o!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};uc.prototype.f=function(){return this.o};
uc.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.o};function Vc(a){G.call(this,1);this.c=a}p(Vc,G);Vc.prototype.a=function(){return this.c};Vc.prototype.toString=function(){return"Number: "+this.c};function Wc(a,b){G.call(this,a.l);this.g=a;this.c=b;this.j=a.j;this.b=a.b;1==this.c.length&&(a=this.c[0],a.w||a.c!=Xc||(a=a.m,"*"!=a.f()&&(this.f={name:a.f(),D:null})))}p(Wc,G);function Yc(){G.call(this,4)}p(Yc,G);Yc.prototype.a=function(a){var b=new E;a=a.a;9==a.nodeType?F(b,a):F(b,a.ownerDocument);return b};Yc.prototype.toString=function(){return"Root Helper Expression"};function Zc(){G.call(this,4)}p(Zc,G);Zc.prototype.a=function(a){var b=new E;F(b,a.a);return b};Zc.prototype.toString=function(){return"Context Helper Expression"};
function $c(a){return"/"==a||"//"==a}Wc.prototype.a=function(a){var b=this.g.a(a);if(!(b instanceof E))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.s;c++){var e=a[c],f=b.iterator(e.c.C);if(e.j||e.c!=ad)if(e.j||e.c!=bd){var g=f.next();for(b=e.a(new fc(g));g=f.next();)g=e.a(new fc(g)),b=Bc(b,g)}else g=f.next(),b=e.a(new fc(g));else{for(g=f.next();(b=f.next())&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new fc(g))}}return b};
Wc.prototype.toString=function(){var a="Path Expression:"+H(this.g);if(this.c.length){var b=ya(this.c,function(a,b){return a+H(b)},"Steps:");a+=H(b)}return a};function cd(a,b){this.a=a;this.C=!!b}
function Pc(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=b.iterator(),f=b.s,g,k=0;g=e.next();k++){var l=a.C?f-k:k+1;g=d.a(new fc(g,l,f));if("number"==typeof g)l=l==g;else if("string"==typeof g||"boolean"==typeof g)l=!!g;else if(g instanceof E)l=0<g.s;else throw Error("Predicate.evaluate returned an unexpected type.");if(!l){l=e;g=l.f;var q=l.a;if(!q)throw Error("Next must be called at least once before remove.");var u=q.a,q=q.next;u?u.next=q:g.a=q;q?q.a=u:g.b=u;g.s--;l.a=null}}return b}
cd.prototype.toString=function(){return ya(this.a,function(a,b){return a+H(b)},"Predicates:")};function dd(a,b,c,d){G.call(this,4);this.c=a;this.m=b;this.g=c||new cd([]);this.w=!!d;b=this.g;b=0<b.a.length?b.a[0].f:null;a.Y&&b&&(a=b.name,a=gc?a.toLowerCase():a,this.f={name:a,D:b.D});a:{a=this.g;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.j||1==c.l||0==c.l){a=!0;break a}a=!1}this.j=a}p(dd,G);
dd.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.D?J(c.D,a):null,f=1);if(this.w)if(this.j||this.c!=ed)if(b=(new dd(fd,new xc("node"))).a(a).iterator(),c=b.next())for(a=this.v(c,d,e,f);c=b.next();)a=Bc(a,this.v(c,d,e,f));else a=new E;else a=rc(this.m,b,d,e),a=Pc(this.g,a,f);else a=this.v(a.a,d,e,f);return a};dd.prototype.v=function(a,b,c,d){a=this.c.G(this.m,a,b,c);return a=Pc(this.g,a,d)};
dd.prototype.toString=function(){var a="Step:"+H("Operator: "+(this.w?"//":"/"));this.c.o&&(a+=H("Axis: "+this.c));a+=H(this.m);if(this.g.a.length){var b=ya(this.g.a,function(a,b){return a+H(b)},"Predicates:");a+=H(b)}return a};function gd(a,b,c,d){this.o=a;this.G=b;this.C=c;this.Y=d}gd.prototype.toString=function(){return this.o};var hd={};function M(a,b,c,d){if(hd.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new gd(a,b,c,!!d);return hd[a]=b}
M("ancestor",function(a,b){for(var c=new E;b=b.parentNode;)a.a(b)&&Cc(c,b);return c},!0);M("ancestor-or-self",function(a,b){var c=new E;do a.a(b)&&Cc(c,b);while(b=b.parentNode);return c},!0);
var Xc=M("attribute",function(a,b){var c=new E,d=a.f();if("style"==d&&gc&&b.style)return F(c,new ic(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof xc&&null===a.b||"*"==d)for(d=0;a=e[d];d++)gc?a.nodeValue&&F(c,jc(b,a)):F(c,a);else(a=e.getNamedItem(d))&&(gc?a.nodeValue&&F(c,jc(b,a)):F(c,a));return c},!1),ed=M("child",function(a,b,c,d,e){return(gc?yc:zc).call(null,a,b,n(c)?c:null,n(d)?d:null,e||new E)},!1,!0);M("descendant",rc,!1,!0);
var fd=M("descendant-or-self",function(a,b,c,d){var e=new E;qc(b,c,d)&&a.a(b)&&F(e,b);return rc(a,b,c,d,e)},!1,!0),ad=M("following",function(a,b,c,d){var e=new E;do for(var f=b;f=f.nextSibling;)qc(f,c,d)&&a.a(f)&&F(e,f),e=rc(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);M("following-sibling",function(a,b){for(var c=new E;b=b.nextSibling;)a.a(b)&&F(c,b);return c},!1);M("namespace",function(){return new E},!1);
var id=M("parent",function(a,b){var c=new E;if(9==b.nodeType)return c;if(2==b.nodeType)return F(c,b.ownerElement),c;b=b.parentNode;a.a(b)&&F(c,b);return c},!1),bd=M("preceding",function(a,b,c,d){var e=new E,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,k=f.length;g<k;g++){var l=[];for(b=f[g];b=b.previousSibling;)l.unshift(b);for(var q=0,u=l.length;q<u;q++)b=l[q],qc(b,c,d)&&a.a(b)&&F(e,b),e=rc(a,b,c,d,e)}return e},!0,!0);
M("preceding-sibling",function(a,b){for(var c=new E;b=b.previousSibling;)a.a(b)&&Cc(c,b);return c},!0);var jd=M("self",function(a,b){var c=new E;a.a(b)&&F(c,b);return c},!1);function kd(a){G.call(this,1);this.c=a;this.j=a.j;this.b=a.b}p(kd,G);kd.prototype.a=function(a){return-I(this.c,a)};kd.prototype.toString=function(){return"Unary Expression: -"+H(this.c)};function ld(a){G.call(this,4);this.c=a;Gc(this,za(this.c,function(a){return a.j}));Hc(this,za(this.c,function(a){return a.b}))}p(ld,G);ld.prototype.a=function(a){var b=new E;r(this.c,function(c){c=c.a(a);if(!(c instanceof E))throw Error("Path expression must evaluate to NodeSet.");b=Bc(b,c)});return b};ld.prototype.toString=function(){return ya(this.c,function(a,b){return a+H(b)},"Union Expression:")};function md(a,b){this.a=a;this.b=b}function nd(a){for(var b,c=[];;){N(a,"Missing right hand side of binary expression.");b=od(a);var d=a.a.next();if(!d)break;var e=(d=Nc[d]||null)&&d.R;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].R;)b=new Jc(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Jc(c.pop(),c.pop(),b);return b}function N(a,b){if(oc(a.a))throw Error(b);}function pd(a,b){a=a.a.next();if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function qd(a){a=a.a.next();if(")"!=a)throw Error("Bad token: "+a);}function rd(a){a=a.a.next();if(2>a.length)throw Error("Unclosed literal string");return new Uc(a)}
function sd(a){var b=[];if($c(D(a.a))){var c=a.a.next();var d=D(a.a);if("/"==c&&(oc(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new Yc;d=new Yc;N(a,"Missing next location step.");c=td(a,c);b.push(c)}else{a:{c=D(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":a.a.next();c=nd(a);N(a,'unclosed "("');pd(a,")");break;case '"':case "'":c=rd(a);break;default:if(isNaN(+c))if(!Tc(c)&&/(?![0-9])[\w]/.test(d)&&"("==D(a.a,
1)){c=a.a.next();c=Sc[c]||null;a.a.next();for(d=[];")"!=D(a.a);){N(a,"Missing function argument list.");d.push(nd(a));if(","!=D(a.a))break;a.a.next()}N(a,"Unclosed function argument list.");qd(a);c=new Qc(c,d)}else{c=null;break a}else c=new Vc(+a.a.next())}"["==D(a.a)&&(d=new cd(ud(a)),c=new Oc(c,d))}if(c)if($c(D(a.a)))d=c;else return c;else c=td(a,"/"),d=new Zc,b.push(c)}for(;$c(D(a.a));)c=a.a.next(),N(a,"Missing next location step."),c=td(a,c),b.push(c);return new Wc(d,b)}
function td(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==D(a.a)){var c=new dd(jd,new xc("node"));a.a.next();return c}if(".."==D(a.a))return c=new dd(id,new xc("node")),a.a.next(),c;if("@"==D(a.a)){var d=Xc;a.a.next();N(a,"Missing attribute name")}else if("::"==D(a.a,1)){if(!/(?![0-9])[\w]/.test(D(a.a).charAt(0)))throw Error("Bad token: "+a.a.next());var e=a.a.next();d=hd[e]||null;if(!d)throw Error("No axis with name: "+e);a.a.next();N(a,"Missing node name")}else d=
ed;e=D(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==D(a.a,1)){if(!Tc(e))throw Error("Invalid node type: "+e);e=a.a.next();if(!Tc(e))throw Error("Invalid type name: "+e);pd(a,"(");N(a,"Bad nodetype");var f=D(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=rd(a);N(a,"Bad nodetype");qd(a);e=new xc(e,g)}else if(e=a.a.next(),f=e.indexOf(":"),-1==f)e=new uc(e);else{var g=e.substring(0,f);if("*"==g)var k="*";else if(k=a.b(g),!k)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new uc(e,
k)}else throw Error("Bad token: "+a.a.next());a=new cd(ud(a),d.C);return c||new dd(d,e,a,"//"==b)}function ud(a){for(var b=[];"["==D(a.a);){a.a.next();N(a,"Missing predicate expression.");var c=nd(a);b.push(c);N(a,"Unclosed predicate expression.");pd(a,"]")}return b}function od(a){if("-"==D(a.a))return a.a.next(),new kd(od(a));var b=sd(a);if("|"!=D(a.a))a=b;else{for(b=[b];"|"==a.a.next();)N(a,"Missing next union location path."),b.push(sd(a));a.a.a--;a=new ld(b)}return a};function vd(a){switch(a.nodeType){case 1:return ma(wd,a);case 9:return vd(a.documentElement);case 11:case 10:case 6:case 12:return xd;default:return a.parentNode?vd(a.parentNode):xd}}function xd(){return null}function wd(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?wd(a.parentNode,b):null};function yd(a,b){if(!a.length)throw Error("Empty XPath expression.");a=lc(a);if(oc(a))throw Error("Invalid XPath expression.");b?fa(b)||(b=la(b.lookupNamespaceURI,b)):b=function(){return null};var c=nd(new md(a,b));if(!oc(a))throw Error("Bad token: "+a.next());this.evaluate=function(a,b){a=c.a(new fc(a));return new P(a,b)}}
function P(a,b){if(!b)if(a instanceof E)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof E))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof E?Ec(a):""+a;break;case 1:this.numberValue=a instanceof E?+Ec(a):+a;break;case 3:this.booleanValue=a instanceof E?0<a.s:!!a;break;case 4:case 5:case 6:case 7:var c=
a.iterator();var d=[];for(var e=c.next();e;e=c.next())d.push(e instanceof ic?e.a:e);this.snapshotLength=a.s;this.invalidIteratorState=!1;break;case 8:case 9:a=Dc(a);this.singleNodeValue=a instanceof ic?a.a:a;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");
return a>=d.length||0>a?null:d[a]}}P.ANY_TYPE=0;P.NUMBER_TYPE=1;P.STRING_TYPE=2;P.BOOLEAN_TYPE=3;P.UNORDERED_NODE_ITERATOR_TYPE=4;P.ORDERED_NODE_ITERATOR_TYPE=5;P.UNORDERED_NODE_SNAPSHOT_TYPE=6;P.ORDERED_NODE_SNAPSHOT_TYPE=7;P.ANY_UNORDERED_NODE_TYPE=8;P.FIRST_ORDERED_NODE_TYPE=9;function zd(a){this.lookupNamespaceURI=vd(a)}
function Ad(a,b){a=a||aa;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=P,c.evaluate=function(a,b,c,g){return(new yd(a,c)).evaluate(b,g)},c.createExpression=function(a,b){return new yd(a,b)},c.createNSResolver=function(a){return new zd(a)}}ca("wgxpath.install",Ad);var Q={};Q.K=function(){var a={ba:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
Q.v=function(a,b,c){var d=B(a);if(!d.documentElement)return null;(x||pb)&&Ad(Pb(d));try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):Q.K;if(x&&!hb(7))return d.evaluate.call(d,b,a,e,c,null);if(!x||ib(9)){for(var f={},g=d.getElementsByTagName("*"),k=0;k<g.length;++k){var l=g[k],q=l.namespaceURI;if(q&&!f[q]){var u=l.lookupPrefix(q);if(!u)var z=q.match(".*/(\\w+)/?$"),u=z?z[1]:"xhtml";f[q]=u}}var O={},Z;for(Z in f)O[f[Z]]=Z;e=function(a){return O[a]||null}}try{return d.evaluate(b,a,
e,c,null)}catch(Ia){if("TypeError"===Ia.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):Q.K,d.evaluate(b,a,e,c,null);throw Ia;}}catch(Ia){if(!y||"NS_ERROR_ILLEGAL_VALUE"!=Ia.name)throw new t(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Ia);}};Q.L=function(a,b){if(!a||1!=a.nodeType)throw new t(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
Q.A=function(a,b){var c=function(){var c=Q.v(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||Q.L(c,a);return c};
Q.u=function(a,b){var c=function(){var c=Q.v(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();r(c,function(b){Q.L(b,a)});return c};function Bd(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}h=Bd.prototype;h.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};h.contains=function(a){return this&&a?a instanceof Bd?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
h.scale=function(a,b){b=ba(b)?b:a;this.left*=a;this.right*=a;this.top*=b;this.bottom*=b;return this};function Cd(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}h=Cd.prototype;h.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};h.contains=function(a){return a instanceof Kb?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};
h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.scale=function(a,b){b=ba(b)?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};function Dd(a,b){var c=B(a);return c.defaultView&&c.defaultView.getComputedStyle&&(a=c.defaultView.getComputedStyle(a,null))?a[b]||a.getPropertyValue(b)||"":""}function Ed(a){a=a?B(a):document;return!x||ib(9)||"CSS1Compat"==Mb(a).a.compatMode?a.documentElement:a.body}
function Fd(a){var b=a.offsetWidth,c=a.offsetHeight,d=A&&!b&&!c;if((!m(b)||d)&&a.getBoundingClientRect){a:{try{var e=a.getBoundingClientRect()}catch(f){e={left:0,top:0,right:0,bottom:0};break a}x&&a.ownerDocument.body&&(a=a.ownerDocument,e.left-=a.documentElement.clientLeft+a.body.clientLeft,e.top-=a.documentElement.clientTop+a.body.clientTop)}return new Lb(e.right-e.left,e.bottom-e.top)}return new Lb(b,c)}var Gd={thin:2,medium:4,thick:6};
function Hd(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:null;if(c in Gd)a=Gd[c];else if(/^\d+px?$/.test(c))a=parseInt(c,10);else{b=a.style.left;var d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=b;a.runtimeStyle.left=d;a=+c}return a};var Id="function"===typeof ShadowRoot;function Jd(a){a:{a=B(a);try{var b=a&&a.activeElement;break a}catch(c){}b=null}return x&&b&&"undefined"===typeof b.nodeType?null:b}function Kd(a){var b;if(b=Ld(a,!0)&&Md(a))b=!(x||y&&!wb("1.9.2")?0:"none"==R(a,"pointer-events"));return b}var Nd="A AREA BUTTON INPUT LABEL SELECT TEXTAREA".split(" ");function Od(a){return za(Nd,function(b){return C(a,b)})||null!=$b(a,"tabindex")&&0<=Number(cc(a,"tabIndex"))||Pd(a)}var Qd="BUTTON INPUT OPTGROUP OPTION SELECT TEXTAREA".split(" ");
function Md(a){return za(Qd,function(b){return C(a,b)})?cc(a,"disabled")?!1:a.parentNode&&1==a.parentNode.nodeType&&C(a,"OPTGROUP")||C(a,"OPTION")?Md(a.parentNode):!Yb(a,function(a){var b=a.parentNode;if(b&&C(b,"FIELDSET")&&cc(b,"disabled")){if(!C(a,"LEGEND"))return!0;for(;a=m(a.previousElementSibling)?a.previousElementSibling:Qb(a.previousSibling);)if(C(a,"LEGEND"))return!0}return!1},!0):!0}var Rd="text search tel url email password number".split(" ");
function Sd(a,b){return C(a,"INPUT")?a.type.toLowerCase()==b:!1}function Td(a){function b(a){return"inherit"==a.contentEditable?(a=Ud(a))?b(a):!1:"true"==a.contentEditable}return m(a.contentEditable)?!x&&m(a.isContentEditable)?a.isContentEditable:b(a):!1}
function Pd(a){return((C(a,"TEXTAREA")?!0:C(a,"INPUT")?0<=va(Rd,a.type.toLowerCase()):Td(a)?!0:!1)||(C(a,"INPUT")?"file"==a.type.toLowerCase():!1)||Sd(a,"range")||Sd(a,"date")||Sd(a,"month")||Sd(a,"week")||Sd(a,"time")||Sd(a,"datetime-local")||Sd(a,"color"))&&!cc(a,"readOnly")}function Ud(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return C(a)?a:null}
function R(a,b){b=ua(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b=Hb?"styleFloat":"cssFloat";a=Dd(a,b)||Vd(a,b);if(null===a)a=null;else if(0<=va(Fa,b)){b:{var c=a.match(Ja);if(c){b=Number(c[1]);var d=Number(c[2]),e=Number(c[3]),c=Number(c[4]);if(0<=b&&255>=b&&0<=d&&255>=d&&0<=e&&255>=e&&0<=c&&1>=c){b=[b,d,e,c];break b}}b=null}if(!b)b:{if(e=a.match(Ka))if(b=Number(e[1]),d=Number(e[2]),e=Number(e[3]),0<=b&&255>=b&&0<=d&&255>=d&&0<=e&&255>=e){b=[b,d,e,1];break b}b=null}if(!b)b:{b=a.toLowerCase();
d=Ea[b.toLowerCase()];if(!d&&(d="#"==b.charAt(0)?b:"#"+b,4==d.length&&(d=d.replace(Ga,"#$1$1$2$2$3$3")),!Ha.test(d))){b=null;break b}b=[parseInt(d.substr(1,2),16),parseInt(d.substr(3,2),16),parseInt(d.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}function Vd(a,b){var c=a.currentStyle||a.style,d=c[b];!m(d)&&fa(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?m(d)?d:null:(a=Ud(a))?Vd(a,b):null}
function Wd(a,b,c){function d(a){var b=Xd(a);return 0<b.height&&0<b.width?!0:C(a,"PATH")&&(0<b.height||0<b.width)?(a=R(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=R(a,"overflow")&&za(a.childNodes,function(a){return 3==a.nodeType||C(a)&&d(a)})}function e(a){return Yd(a)==Zd&&Aa(a.childNodes,function(a){return!C(a)||e(a)||!d(a)})}if(!C(a))throw Error("Argument to isShown must be of type Element");if(C(a,"BODY"))return!0;if(C(a,"OPTION")||C(a,"OPTGROUP"))return a=Yb(a,function(a){return C(a,"SELECT")}),
!!a&&Wd(a,!0,c);var f=$d(a);if(f)return!!f.M&&0<f.rect.width&&0<f.rect.height&&Wd(f.M,b,c);if(C(a,"INPUT")&&"hidden"==a.type.toLowerCase()||C(a,"NOSCRIPT"))return!1;f=R(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||ae(a))&&d(a)?!e(a):!1}
function Ld(a,b){function c(a){if(C(a)&&"none"==R(a,"display"))return!1;var b;(b=a.parentNode)&&b.shadowRoot&&void 0!==a.assignedSlot?b=a.assignedSlot?a.assignedSlot.parentNode:null:a.getDestinationInsertionPoints&&(a=a.getDestinationInsertionPoints(),0<a.length&&(b=a[a.length-1]));if(Id&&b instanceof ShadowRoot){if(b.host.shadowRoot!==b)return!1;b=b.host}return!b||9!=b.nodeType&&11!=b.nodeType?b&&c(b):!0}return Wd(a,!!b,c)}var Zd="hidden";
function Yd(a,b){function c(a){function b(a){return a==g?!0:!R(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==R(a,"position")?!1:!0}var c=R(a,"position");if("fixed"==c)return q=!0,a==g?null:g;for(a=Ud(a);a&&!b(a);)a=Ud(a);return a}function d(a){var b=a;if("visible"==l)if(a==g&&k)b=k;else if(a==k)return{x:"visible",y:"visible"};b={x:R(b,"overflow-x"),y:R(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function e(a){if(a==g){var b=(new Nb(f)).a;
a=Ob(b);b=b.parentWindow||b.defaultView;a=x&&hb("10")&&b.pageYOffset!=a.scrollTop?new Kb(a.scrollLeft,a.scrollTop):new Kb(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new Kb(a.scrollLeft,a.scrollTop);return a}b=be(a,b);var f=B(a),g=f.documentElement,k=f.body,l=R(g,"overflow"),q;for(a=c(a);a;a=c(a)){var u=d(a);if("visible"!=u.x||"visible"!=u.y){var z=Xd(a);if(!z.width||!z.height)return Zd;var O=b.right<z.left,Z=b.bottom<z.top;if(O&&"hidden"==u.x||Z&&"hidden"==u.y)return Zd;if(O&&
"visible"!=u.x||Z&&"visible"!=u.y){O=e(a);Z=b.bottom<z.top-O.y;if(b.right<z.left-O.x&&"visible"!=u.x||Z&&"visible"!=u.x)return Zd;b=Yd(a);return b==Zd?Zd:"scroll"}O=b.left>=z.left+z.width;z=b.top>=z.top+z.height;if(O&&"hidden"==u.x||z&&"hidden"==u.y)return Zd;if(O&&"visible"!=u.x||z&&"visible"!=u.y){if(q&&(u=e(a),b.left>=g.scrollWidth-u.x||b.right>=g.scrollHeight-u.y))return Zd;b=Yd(a);return b==Zd?Zd:"scroll"}}}return"none"}
function Xd(a){var b=$d(a);if(b)return b.rect;if(C(a,"HTML"))return a=B(a),a=(Pb(a)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new Lb(a.clientWidth,a.clientHeight),new Cd(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new Cd(0,0,0,0)}b=new Cd(c.left,c.top,c.right-c.left,c.bottom-c.top);x&&a.ownerDocument.body&&(a=B(a),b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function $d(a){var b=C(a,"MAP");if(!b&&!C(a,"AREA"))return null;var c=b?a:C(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=Q.A('/descendant::*[@usemap = "#'+c.name+'"]',B(c)))&&(e=Xd(d),b||"default"==a.shape.toLowerCase()||(a=ce(a),b=Math.min(Math.max(a.left,0),e.width),c=Math.min(Math.max(a.top,0),e.height),e=new Cd(b+e.left,c+e.top,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{M:d,rect:e||new Cd(0,0,0,0)}}
function ce(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new Cd(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new Cd(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new Cd(b,c,d-b,e-c)}return new Cd(0,0,0,0)}
function be(a,b){a=Xd(a);a=new Bd(a.top,a.left+a.width,a.top+a.height,a.left);b&&(b=b instanceof Cd?b:new Cd(b.x,b.y,1,1),a.left=Math.min(Math.max(a.left+b.left,a.left),a.right),a.top=Math.min(Math.max(a.top+b.top,a.top),a.bottom),a.right=Math.min(Math.max(a.left+b.width,a.left),a.right),a.bottom=Math.min(Math.max(a.top+b.height,a.top),a.bottom));return a}function de(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}
function ee(a){var b=[];Id?fe(a,b):ge(a,b);a=xa(b,de);return de(a.join("\n")).replace(/\xa0/g," ")}
function he(a,b,c){var d=Ld;if(C(a,"BR"))b.push("");else{var e=C(a,"TD"),f=R(a,"display"),g=!e&&!(0<=va(ie,f)),k=m(a.previousElementSibling)?a.previousElementSibling:Qb(a.previousSibling),k=k?R(k,"display"):"",l=R(a,"float")||R(a,"cssFloat")||R(a,"styleFloat");!g||"run-in"==k&&"none"==l||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var q=d(a),u=null,z=null;q&&(u=R(a,"white-space"),z=R(a,"text-transform"));r(a.childNodes,function(a){c(a,b,q,u,z)});a=b[b.length-1]||"";!e&&"table-cell"!=f||!a||
qa(a)||(b[b.length-1]+=" ");g&&"run-in"!=f&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function ge(a,b){he(a,b,function(a,b,e,f,g){3==a.nodeType&&e?je(a,b,f,g):C(a)&&ge(a,b)})}var ie="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function je(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";qa(c)&&!a.lastIndexOf(" ",0)&&(a=a.substr(1));b.push(c+a)}
function ae(a){if(Hb){if("relative"==R(a,"position"))return 1;a=R(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return ke(a)}function ke(a){var b=1,c=R(a,"opacity");c&&(b=Number(c));(a=Ud(a))&&(b*=ke(a));return b}
function le(a,b,c,d,e){var f;if(3==a.nodeType&&c)je(a,b,d,e);else if(C(a))if(C(a,"CONTENT")||C(a,"SLOT")){for(f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?(a=C(a,"CONTENT")?a.getDistributedNodes():a.assignedNodes(),r(a,function(a){le(a,b,c,d,e)})):fe(a,b)}else if(C(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)r(a.childNodes,function(a){le(a,b,c,d,e)}),a=a.olderShadowRoot}else fe(a,b)}
function fe(a,b){a.shadowRoot&&r(a.shadowRoot.childNodes,function(a){le(a,b,!0,null,null)});he(a,b,function(a,b,e,f,g){var c=null;1==a.nodeType?c=a:3==a.nodeType&&(c=a);c&&(c.assignedSlot||c.getDestinationInsertionPoints&&0<c.getDestinationInsertionPoints().length)||le(a,b,e,f,g)})};var me={F:function(a){return!(!a.querySelectorAll||!a.querySelector)},A:function(a,b){if(!a)throw new t(32,"No class name specified");a=ra(a);if(-1!==a.indexOf(" "))throw new t(32,"Compound class names not permitted");if(me.F(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new t(32,"An invalid or illegal class name was specified");}a=Zb(Mb(b),"*",a,b);return a.length?a[0]:null},u:function(a,b){if(!a)throw new t(32,"No class name specified");a=ra(a);if(-1!==a.indexOf(" "))throw new t(32,
"Compound class names not permitted");if(me.F(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new t(32,"An invalid or illegal class name was specified");}return Zb(Mb(b),"*",a,b)}};var ne={A:function(a,b){if(!fa(b.querySelector)&&x&&wb(8)&&!ga(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new t(32,"No selector specified");a=ra(a);try{var c=b.querySelector(a)}catch(d){throw new t(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},u:function(a,b){if(!fa(b.querySelectorAll)&&x&&wb(8)&&!ga(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new t(32,"No selector specified");a=ra(a);try{return b.querySelectorAll(a)}catch(c){throw new t(32,
"An invalid or illegal selector was specified");}}};var oe={F:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},A:function(a,b){var c=Mb(b),d=n(a)?c.a.getElementById(a):a;return d?$b(d,"id")==a&&b!=d&&Rb(b,d)?d:Ba(Zb(c,"*"),function(c){return $b(c,"id")==a&&b!=c&&Rb(b,c)}):null},u:function(a,b){if(!a)return[];if(oe.F(b,a))try{return b.querySelectorAll("#"+oe.T(a))}catch(c){return[]}b=Zb(Mb(b),"*",null,b);return wa(b,function(b){return $b(b,"id")==a})},T:function(a){return a.replace(/([\s'"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var pe={},qe={};pe.S=function(a,b,c){try{var d=ne.u("a",b)}catch(e){d=Zb(Mb(b),"A",null,b)}return Ba(d,function(b){b=ee(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};pe.N=function(a,b,c){try{var d=ne.u("a",b)}catch(e){d=Zb(Mb(b),"A",null,b)}return wa(d,function(b){b=ee(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};pe.A=function(a,b){return pe.S(a,b,!1)};pe.u=function(a,b){return pe.N(a,b,!1)};qe.A=function(a,b){return pe.S(a,b,!0)};
qe.u=function(a,b){return pe.N(a,b,!0)};var re={A:function(a,b){if(""===a)throw new t(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},u:function(a,b){if(""===a)throw new t(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var se={className:me,"class name":me,css:ne,"css selector":ne,id:oe,linkText:pe,"link text":pe,name:{A:function(a,b){b=Zb(Mb(b),"*",null,b);return Ba(b,function(b){return $b(b,"name")==a})},u:function(a,b){b=Zb(Mb(b),"*",null,b);return wa(b,function(b){return $b(b,"name")==a})}},partialLinkText:qe,"partial link text":qe,tagName:re,"tag name":re,xpath:Q};
function te(a,b){a:{for(c in a)if(a.hasOwnProperty(c))break a;var c=null}if(c){var d=se[c];if(d&&fa(d.u))return d.u(a[c],b||oa.document)}throw Error("Unsupported locator strategy: "+c);};function ue(a){this.a=oa.document.documentElement;this.f=null;var b=Jd(this.a);b&&ve(this,b);this.m=a||new we}function ve(a,b){a.a=b;C(b,"OPTION")?a.f=Yb(b,function(a){return C(a,"SELECT")}):a.f=null}
function xe(a,b,c,d,e,f,g,k,l){if(!g&&!Kd(a.a))return!1;if(e&&ye!=b&&ze!=b)throw new t(12,"Event type does not allow related target: "+b);c={clientX:c.x,clientY:c.y,button:d,altKey:!!(a.m.a&4),ctrlKey:!!(a.m.a&2),shiftKey:!!(a.m.a&1),metaKey:!!(a.m.a&8),wheelDelta:f||0,relatedTarget:e||null,count:l||1};k=k||1;d=a.a;b!=Ae&&b!=Be&&k in Ce?d=Ce[k]:a.f&&(d=De(a,b));return d?S(d,b,c):!0}
function Ee(a,b,c,d,e,f,g){var k=MSPointerEvent.MSPOINTER_TYPE_MOUSE;if(!g&&!Kd(a.a))return!1;if(f&&Fe!=b&&Ge!=b)throw new t(12,"Event type does not allow related target: "+b);c={clientX:c.x,clientY:c.y,button:d,altKey:!1,ctrlKey:!1,shiftKey:!1,metaKey:!1,relatedTarget:f||null,width:0,height:0,pressure:0,rotation:0,pointerId:1,tiltX:0,tiltY:0,pointerType:k,isPrimary:e};d=a.f?De(a,b):a.a;Ce[1]&&(d=Ce[1]);a=Pb(B(a.a));if(a&&b==He){var l=a.Element.prototype.msSetPointerCapture;a.Element.prototype.msSetPointerCapture=
function(a){Ce[a]=this}}b=d?S(d,b,c):!0;l&&(a.Element.prototype.msSetPointerCapture=l);return b}function De(a,b){if(x)switch(b){case ye:case Fe:return null;case Ie:case Je:case Ke:return a.f.multiple?a.f:null;default:return a.f}if(A)switch(b){case Ae:case Le:return a.f.multiple?a.a:a.f;default:return a.f.multiple?a.a:null}return a.a}
function Me(a){var b=Yb(a.a,function(a){return!!a&&C(a)&&Od(a)},!0),b=b||a.a;a=Jd(b);if(b==a)return!1;if(a&&(fa(a.blur)||x&&ga(a.blur))){if(!C(a,"BODY"))try{a.blur()}catch(c){if(!x||"Unspecified error."!=c.message)throw c;}x&&!wb(8)&&Pb(B(b)).focus()}return fa(b.focus)||x&&ga(b.focus)?(b.focus(),!0):!1}var Ne=A||xb&&yb(3.6);function Oe(a){if(C(a,"INPUT")){var b=a.type.toLowerCase();if("submit"==b||"image"==b)return!0}return C(a,"BUTTON")&&(b=a.type.toLowerCase(),"submit"==b)?!0:!1}
function Pe(a){if(Ne||!a.href)return!1;if(!xb&&!Bb)return!0;if(a.target||0==a.href.toLowerCase().indexOf("javascript"))return!1;var b=Pb(B(a)),c=b.location.href;a=Qe(b.location,a.href);return c.split("#")[0]!==a.split("#")[0]}function Re(a){return C(a,"FORM")}
function Se(a){if(!Re(a))throw new t(12,"Element is not a form, so could not submit.");if(S(a,Te))if(C(a.submit))if(!x||wb(8))a.constructor.prototype.submit.call(a);else{var b=te({id:"submit"},a),c=te({name:"submit"},a);r(b,function(a){a.removeAttribute("id")});r(c,function(a){a.removeAttribute("name")});a=a.submit;r(b,function(a){a.setAttribute("id","submit")});r(c,function(a){a.setAttribute("name","submit")});a()}else a.submit()}var Ue=/^([^:/?#.]+:)?(?:\/\/([^/]*))?([^?#]+)?(\?[^#]*)?(#.*)?$/;
function Qe(a,b){var c=b.match(Ue);if(!c)return"";b=c[1]||"";var d=c[2]||"",e=c[3]||"",f=c[4]||"",c=c[5]||"";if(!b&&(b=a.protocol,!d))if(d=a.host,!e)e=a.pathname,f=f||a.search;else if("/"!=e.charAt(0)){var g=a.pathname.lastIndexOf("/");-1!=g&&(e=a.pathname.substr(0,g+1)+e)}return b+"//"+d+e+f+c}function we(){this.a=0}var Ce={};var Ve=!(x&&!wb(10)),We=pb?!yb(4):!Cb,Xe=x&&oa.navigator.msPointerEnabled;function T(a,b,c){this.a=a;this.b=b;this.f=c}T.prototype.create=function(a){a=B(a);Hb&&a.createEventObject?a=a.createEventObject():(a=a.createEvent("HTMLEvents"),a.initEvent(this.a,this.b,this.f));return a};T.prototype.toString=function(){return this.a};function Ye(a,b,c){T.call(this,a,b,c)}p(Ye,T);
Ye.prototype.create=function(a,b){if(!y&&this==Ze)throw new t(9,"Browser does not support a mouse pixel scroll event.");var c=B(a);if(Hb){var d=c.createEventObject();d.altKey=b.altKey;d.ctrlKey=b.ctrlKey;d.metaKey=b.metaKey;d.shiftKey=b.shiftKey;d.button=b.button;d.clientX=b.clientX;d.clientY=b.clientY;c=function(a,b){Object.defineProperty(d,a,{get:function(){return b}})};if(this==ze||this==ye)if(Object.defineProperty){var e=this==ze;c("fromElement",e?a:b.relatedTarget);c("toElement",e?b.relatedTarget:
a)}else d.relatedTarget=b.relatedTarget;this==$e&&(Object.defineProperty?c("wheelDelta",b.wheelDelta):d.detail=b.wheelDelta)}else{e=Pb(c);d=c.createEvent("MouseEvents");var f=1;this==$e&&(y||(d.wheelDelta=b.wheelDelta),y&&(f=b.wheelDelta/-40));y&&this==Ze&&(f=b.wheelDelta);d.initMouseEvent(this.a,this.b,this.f,e,f,b.clientX,b.clientY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);if(x&&!d.pageX&&!d.pageY&&Object.defineProperty){a=Ob(Mb(a).a);var c=Ed(c),g=b.clientX+
a.scrollLeft-c.clientLeft,k=b.clientY+a.scrollTop-c.clientTop;Object.defineProperty(d,"pageX",{get:function(){return g}});Object.defineProperty(d,"pageY",{get:function(){return k}})}}return d};function af(a,b,c){T.call(this,a,b,c)}p(af,T);
af.prototype.create=function(a,b){var c=B(a);if(y){a=Pb(c);var d=b.charCode?0:b.keyCode,c=c.createEvent("KeyboardEvent");c.initKeyEvent(this.a,this.b,this.f,a,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,d,b.charCode);this.a==bf&&b.preventDefault&&c.preventDefault()}else if(Hb?c=c.createEventObject():(c=c.createEvent("Events"),c.initEvent(this.a,this.b,this.f)),c.altKey=b.altKey,c.ctrlKey=b.ctrlKey,c.metaKey=b.metaKey,c.shiftKey=b.shiftKey,c.keyCode=b.charCode||b.keyCode,A||Za)c.charCode=this==bf?c.keyCode:
0;return c};function cf(a,b,c){T.call(this,a,b,c)}p(cf,T);
cf.prototype.create=function(a,b){function c(b){b=xa(b,function(b){return g.createTouch(k,a,b.identifier,b.pageX,b.pageY,b.screenX,b.screenY)});return g.createTouchList.apply(g,b)}function d(b){var c=xa(b,function(b){return{identifier:b.identifier,screenX:b.screenX,screenY:b.screenY,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,target:a}});c.item=function(a){return c[a]};return c}function e(b){return xa(b,function(b){return new Touch({identifier:b.identifier,screenX:b.screenX,screenY:b.screenY,
clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,target:a})})}function f(a,b){switch(a){case 1:return d(b);case 2:return c(b);case 3:return e(b)}return null}if(!Ve)throw new t(9,"Browser does not support firing touch events.");var g=B(a),k=Pb(g);if(We)var l=1;else if(TouchEvent.prototype.initTouchEvent)l=2;else if(TouchEvent&&0<TouchEvent.length)l=3;else throw new t(9,"Not able to create touch events in this browser");var q=f(l,b.changedTouches),u=b.touches==b.changedTouches?q:f(l,
b.touches),z=b.targetTouches==b.changedTouches?q:f(l,b.targetTouches);if(1==l)l=g.createEvent("MouseEvents"),l.initMouseEvent(this.a,this.b,this.f,k,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,b.relatedTarget),l.touches=u,l.targetTouches=z,l.changedTouches=q,l.scale=b.scale,l.rotation=b.rotation;else if(2==l)l=g.createEvent("TouchEvent"),0==l.initTouchEvent.length?l.initTouchEvent(u,z,q,this.a,k,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey):l.initTouchEvent(this.a,
this.b,this.f,k,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,u,z,q,b.scale,b.rotation),l.relatedTarget=b.relatedTarget;else if(3==l)l=new TouchEvent(this.a,{touches:u,targetTouches:z,changedTouches:q,bubbles:this.b,cancelable:this.f,ctrlKey:b.ctrlKey,shiftKey:b.shiftKey,altKey:b.altKey,metaKey:b.metaKey});else throw new t(9,"Illegal TouchEventStrategy_ value (this is a bug)");return l};function df(a,b,c){T.call(this,a,b,c)}p(df,T);
df.prototype.create=function(a,b){if(!Xe)throw new t(9,"Browser does not support MSPointer events.");var c=B(a);a=Pb(c);c=c.createEvent("MSPointerEvent");c.initPointerEvent(this.a,this.b,this.f,a,0,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget,0,0,b.width,b.height,b.pressure,b.rotation,b.tiltX,b.tiltY,b.pointerId,b.pointerType,0,b.isPrimary);return c};
var ef=new T("blur",!1,!1),ff=new T("change",!0,!1),gf=new T("focus",!1,!1),hf=new T("input",!0,!1),Te=new T("submit",!0,!0),jf=new T("textInput",!0,!0),Ae=new Ye("click",!0,!0),Ie=new Ye("contextmenu",!0,!0),kf=new Ye("dblclick",!0,!0),Be=new Ye("mousedown",!0,!0),Je=new Ye("mousemove",!0,!1),ze=new Ye("mouseout",!0,!0),ye=new Ye("mouseover",!0,!0),Le=new Ye("mouseup",!0,!0),$e=new Ye(y?"DOMMouseScroll":"mousewheel",!0,!0),Ze=new Ye("MozMousePixelScroll",!0,!0),lf=new af("keydown",!0,!0),bf=new af("keypress",
!0,!0),mf=new af("keyup",!0,!0),nf=new cf("touchend",!0,!0),of=new cf("touchstart",!0,!0),pf=new df("MSGotPointerCapture",!0,!1),qf=new df("MSLostPointerCapture",!0,!1),He=new df("MSPointerDown",!0,!0),Ke=new df("MSPointerMove",!0,!0),Fe=new df("MSPointerOver",!0,!0),Ge=new df("MSPointerOut",!0,!0),rf=new df("MSPointerUp",!0,!0);function S(a,b,c){c=b.create(a,c);"isTrusted"in c||(c.isTrusted=!1);return Hb&&a.fireEvent?a.fireEvent("on"+b.a,c):a.dispatchEvent(c)};function sf(a,b){if(tf(a))a.selectionStart=b;else if(uf()){var c=vf(a),d=c[0];d.inRange(c[1])&&(b=wf(a,b),d.collapse(!0),d.move("character",b),d.select())}}
function xf(a,b){var c=0,d=0;if(tf(a))c=a.selectionStart,d=b?-1:a.selectionEnd;else if(uf()){var e=vf(a),f=e[0],e=e[1];if(f.inRange(e)){f.setEndPoint("EndToStart",e);if("textarea"==a.type){a=e.duplicate();for(var g=f.text,c=g,e=d=a.text,k=!1;!k;)0==f.compareEndPoints("StartToEnd",f)?k=!0:(f.moveEnd("character",-1),f.text==g?c+="\r\n":k=!0);if(b)b=[c.length,-1];else{for(b=!1;!b;)0==a.compareEndPoints("StartToEnd",a)?b=!0:(a.moveEnd("character",-1),a.text==d?e+="\r\n":b=!0);b=[c.length,c.length+e.length]}return b}c=
f.text.length;d=b?-1:f.text.length+e.text.length}}return[c,d]}function yf(a,b){if(tf(a))a.selectionEnd=b;else if(uf()){var c=vf(a),d=c[1];c[0].inRange(d)&&(b=wf(a,b),a=wf(a,xf(a,!0)[0]),d.collapse(!0),d.moveEnd("character",b-a),d.select())}}function zf(a,b){tf(a)?(a.selectionStart=b,a.selectionEnd=b):uf()&&(b=wf(a,b),a=a.createTextRange(),a.collapse(!0),a.move("character",b),a.select())}
function Af(a,b){if(tf(a)){var c=a.value,d=a.selectionStart;a.value=c.substr(0,d)+b+c.substr(a.selectionEnd);a.selectionStart=d;a.selectionEnd=d+b.length}else if(uf())c=vf(a),a=c[1],c[0].inRange(a)&&(c=a.duplicate(),a.text=b,a.setEndPoint("StartToStart",c),a.select());else throw Error("Cannot set the selection end");}
function vf(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();"textarea"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]}function wf(a,b){"textarea"==a.type&&(b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length);return b}function tf(a){try{return"number"==typeof a.selectionStart}catch(b){return!1}}function uf(){return x&&!hb("9")};function Bf(a,b){this.b={};this.a=[];this.f=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof Bf)d=Cf(a),c=a.B();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=Ra(a)}for(e=0;e<d.length;e++)this.set(d[e],c[e])}}Bf.prototype.B=function(){Df(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};function Cf(a){Df(a);return a.a.concat()}
function Df(a){var b,c;if(a.f!=a.a.length){for(b=c=0;c<a.a.length;){var d=a.a[c];Ef(a.b,d)&&(a.a[b++]=d);c++}a.a.length=b}if(a.f!=a.a.length){var e={};for(b=c=0;c<a.a.length;)d=a.a[c],Ef(e,d)||(a.a[b++]=d,e[d]=1),c++;a.a.length=b}}Bf.prototype.get=function(a,b){return Ef(this.b,a)?this.b[a]:b};Bf.prototype.set=function(a,b){Ef(this.b,a)||(this.f++,this.a.push(a));this.b[a]=b};function Ef(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Ff(a){if(a.B&&"function"==typeof a.B)return a.B();if(n(a))return a.split("");if(ea(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ra(a)};function Gf(a){this.a=new Bf;if(a){a=Ff(a);for(var b=a.length,c=0;c<b;c++){var d=a[c];this.a.set(Hf(d),d)}}}function Hf(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ha]||(a[ha]=++ia)):b.charAt(0)+a}Gf.prototype.contains=function(a){a=Hf(a);return Ef(this.a.b,a)};Gf.prototype.B=function(){return this.a.B()};function If(a){ue.call(this);this.c=Pd(this.a);this.b=0;this.g=new Gf;a&&(r(a.pressed,function(a){Jf(this,a,!0)},this),this.b=a.currentPos||0)}p(If,ue);var Kf={};function U(a,b,c){ga(a)&&(a=y?a.h:a.i);a=new Lf(a,b,c);!b||b in Kf&&!c||(Kf[b]={key:a,shift:!1},c&&(Kf[c]={key:a,shift:!0}));return a}function Lf(a,b,c){this.code=a;this.a=b||null;this.b=c||this.a}var Mf=U(8),Nf=U(9),Of=U(13),V=U(16),Pf=U(17),Qf=U(18),Rf=U(19);U(20);
var Sf=U(27),Tf=U(32," "),Uf=U(33),Vf=U(34),Wf=U(35),Xf=U(36),Yf=U(37),Zf=U(38),$f=U(39),ag=U(40);U(44);var bg=U(45),cg=U(46);U(48,"0",")");U(49,"1","!");U(50,"2","@");U(51,"3","#");U(52,"4","$");U(53,"5","%");U(54,"6","^");U(55,"7","&");U(56,"8","*");U(57,"9","(");U(65,"a","A");U(66,"b","B");U(67,"c","C");U(68,"d","D");U(69,"e","E");U(70,"f","F");U(71,"g","G");U(72,"h","H");U(73,"i","I");U(74,"j","J");U(75,"k","K");U(76,"l","L");U(77,"m","M");U(78,"n","N");U(79,"o","O");U(80,"p","P");U(81,"q","Q");
U(82,"r","R");U(83,"s","S");U(84,"t","T");U(85,"u","U");U(86,"v","V");U(87,"w","W");U(88,"x","X");U(89,"y","Y");U(90,"z","Z");
var dg=U(bb?{h:91,i:91}:ab?{h:224,i:91}:{h:0,i:91}),eg=U(bb?{h:92,i:92}:ab?{h:224,i:93}:{h:0,i:92}),fg=U(bb?{h:93,i:93}:ab?{h:0,i:0}:{h:93,i:null}),gg=U({h:96,i:96},"0"),hg=U({h:97,i:97},"1"),ig=U({h:98,i:98},"2"),jg=U({h:99,i:99},"3"),kg=U({h:100,i:100},"4"),lg=U({h:101,i:101},"5"),mg=U({h:102,i:102},"6"),ng=U({h:103,i:103},"7"),og=U({h:104,i:104},"8"),pg=U({h:105,i:105},"9"),qg=U({h:106,i:106},"*"),rg=U({h:107,i:107},"+"),sg=U({h:109,i:109},"-"),tg=U({h:110,i:110},"."),ug=U({h:111,i:111},"/");U(144);
var vg=U(112),wg=U(113),xg=U(114),yg=U(115),zg=U(116),Ag=U(117),Bg=U(118),Cg=U(119),Dg=U(120),Eg=U(121),Fg=U(122),Gg=U(123),Hg=U({h:107,i:187},"=","+"),Ig=U(108,",");U({h:109,i:189},"-","_");U(188,",","<");U(190,".",">");U(191,"/","?");U(192,"`","~");U(219,"[","{");U(220,"\\","|");U(221,"]","}");var Jg=U({h:59,i:186},";",":");U(222,"'",'"');var Kg=[Qf,Pf,dg,V],Lg=new Bf;Lg.set(1,V);Lg.set(2,Pf);Lg.set(4,Qf);Lg.set(8,dg);
var Mg=function(a){var b=new Bf;r(Cf(a),function(c){b.set(a.get(c).code,c)});return b}(Lg);function Jf(a,b,c){if(0<=va(Kg,b)){var d=Mg.get(b.code),e=a.m;e.a=c?e.a|d:e.a&~d}c?a.g.a.set(Hf(b),b):(a=a.g.a,b=Hf(b),Ef(a.b,b)&&(delete a.b[b],a.f--,a.a.length>2*a.f&&Df(a)))}var Ng=x?"\r\n":"\n";function W(a,b){return a.g.contains(b)}
function Og(a,b){if(0<=va(Kg,b)&&W(a,b))throw new t(13,"Cannot press a modifier key that is already pressed.");var c=null!==b.code&&Pg(a,lf,b);if((c||y)&&(!Qg(b)||Pg(a,bf,b,!c))&&c&&(Rg(a,b),a.c))if(b.a){if(!Sg){var c=Tg(a,b),d=xf(a.a,!0)[0]+1;if(a.a instanceof window.HTMLInputElement){var e=Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype,"value"),f=e.get.call(a.a);e.set.call(a.a,f+c)}else Ug(a.a)?Af(a.a,c):a.a.value+=c;Ug(a.a)&&sf(a.a,d);A&&S(a.a,jf);Hb||S(a.a,hf);a.b=d}}else switch(b){case Of:Sg||
(A&&S(a.a,jf),C(a.a,"TEXTAREA")&&(c=xf(a.a,!0)[0]+Ng.length,Ug(a.a)?(Af(a.a,Ng),sf(a.a,c)):a.a.value+=Ng,x||S(a.a,hf),a.b=c));break;case Mf:case cg:Sg||(Vg(a.a),c=xf(a.a,!1),c[0]==c[1]&&(b==Mf?(sf(a.a,c[1]-1),yf(a.a,c[1])):yf(a.a,c[1]+1)),c=xf(a.a,!1),c=!(c[0]==a.a.value.length||!c[1]),Af(a.a,""),(!x&&c||y&&b==Mf)&&S(a.a,hf),c=xf(a.a,!1),a.b=c[1]);break;case Yf:case $f:Vg(a.a);var c=a.a,f=xf(c,!0)[0],g=xf(c,!1)[1],e=d=0;b==Yf?W(a,V)?a.b==f?(d=Math.max(f-1,0),e=g,f=d):(d=f,f=e=g-1):f=f==g?Math.max(f-
1,0):f:W(a,V)?a.b==g?(d=f,f=e=Math.min(g+1,c.value.length)):(d=f+1,e=g,f=d):f=f==g?Math.min(g+1,c.value.length):g;W(a,V)?(sf(c,d),yf(c,e)):zf(c,f);a.b=f;break;case Xf:case Wf:Vg(a.a),c=a.a,d=xf(c,!0)[0],e=xf(c,!1)[1],b==Xf?(W(a,V)?(sf(c,0),yf(c,a.b==d?e:d)):zf(c,0),a.b=0):(W(a,V)?(a.b==d&&sf(c,e),yf(c,c.value.length)):zf(c,c.value.length),a.b=c.value.length)}Jf(a,b,!0)}
function Qg(a){if(a.a||a==Of)return!0;if(A||Za)return!1;if(x)return a==Sf;switch(a){case V:case Pf:case Qf:return!1;case dg:case eg:case fg:return y;default:return!0}}function Rg(a,b){b==Of&&!y&&C(a.a,"INPUT")&&(a=Yb(a.a,Re,!0))&&(b=a.getElementsByTagName("input"),(za(b,function(a){return Oe(a)})||1==b.length||A&&!wb(534))&&Se(a))}function Wg(a,b){if(!W(a,b))throw new t(13,"Cannot release a key that is not pressed. ("+b.code+")");null===b.code||Pg(a,mf,b);Jf(a,b,!1)}
function Tg(a,b){if(!b.a)throw new t(13,"not a character key");return W(a,V)?b.b:b.a}var Sg=y&&!wb(12);function Vg(a){try{if("number"==typeof a.selectionStart)return}catch(b){if(-1!=b.message.indexOf("does not support selection."))throw Error(b.message+" (For more information, see https://code.google.com/p/chromium/issues/detail?id=330456)");throw b;}throw Error("Element does not support selection");}function Ug(a){try{Vg(a)}catch(b){return!1}return!0}
function Pg(a,b,c,d){if(null===c.code)throw new t(13,"Key must have a keycode to be fired.");c={altKey:W(a,Qf),ctrlKey:W(a,Pf),metaKey:W(a,dg),shiftKey:W(a,V),keyCode:c.code,charCode:c.a&&b==bf?Tg(a,c).charCodeAt(0):0,preventDefault:!!d};return S(a.a,b,c)}function Xg(a,b){ve(a,b);a.c=Pd(b);var c=Me(a);a.c&&c&&(zf(b,b.value.length),a.b=b.value.length)};function Yg(a,b){ue.call(this,b);this.g=this.b=null;this.c=new Kb(0,0);this.H=this.w=!1;if(a){ba(a.buttonPressed)&&(this.b=a.buttonPressed);try{C(a.elementPressed)&&(this.g=a.elementPressed)}catch(c){this.b=null}this.c=new Kb(a.clientXY.x,a.clientXY.y);this.w=!!a.nextClickIsDoubleClick;this.H=!!a.hasEverInteracted;try{a.element&&C(a.element)&&ve(this,a.element)}catch(c){this.b=null}}}p(Yg,ue);var X={};
Hb?(X[Ae]=[0,0,0,null],X[Ie]=[null,null,0,null],X[Le]=[1,4,2,null],X[ze]=[0,0,0,0],X[Je]=[1,4,2,0]):A||Gb?(X[Ae]=[0,1,2,null],X[Ie]=[null,null,2,null],X[Le]=[0,1,2,null],X[ze]=[0,1,2,0],X[Je]=[0,1,2,0]):(X[Ae]=[0,1,2,null],X[Ie]=[null,null,2,null],X[Le]=[0,1,2,null],X[ze]=[0,0,0,0],X[Je]=[0,0,0,0]);Ib&&(X[He]=X[Le],X[rf]=X[Le],X[Ke]=[-1,-1,-1,-1],X[Ge]=X[Ke],X[Fe]=X[Ke]);X[kf]=X[Ae];X[Be]=X[Le];X[ye]=X[ze];var Zg={};Zg[Be]=He;Zg[Je]=Ke;Zg[ze]=Ge;Zg[ye]=Fe;Zg[Le]=rf;
function $g(a,b,c,d,e,f){a.H=!0;if(Ib){var g=Zg[b];if(g&&!Ee(a,g,a.c,ah(a,g),!0,c,e))return!1}return xe(a,b,a.c,ah(a,b),c,d,e,null,f)}function ah(a,b){if(!(b in X))return 0;a=X[b][null===a.b?3:a.b];if(null===a)throw new t(13,"Event does not permit the specified mouse button.");return a};function bh(a,b){this.x=a;this.y=b}p(bh,Kb);bh.prototype.scale=Kb.prototype.scale;function ch(a,b,c,d){function e(a){n(a)?r(a.split(""),function(a){if(1!=a.length)throw new t(13,"Argument not a single character: "+a);var b=Kf[a];b||(b=a.toUpperCase(),b=U(b.charCodeAt(0),a.toLowerCase(),b),b={key:b,shift:a!=b.a});a=b;b=W(f,V);a.shift&&!b&&Og(f,V);Og(f,a.key);Wg(f,a.key);a.shift&&!b&&Wg(f,V)}):0<=va(Kg,a)?W(f,a)?Wg(f,a):Og(f,a):(Og(f,a),Wg(f,a))}if(a!=Jd(a)){if(!Kd(a))throw new t(12,"Element is not currently interactable and may not be manipulated");dh(a)}var f=c||new If;Xg(f,a);
if((!rb||$a)&&A&&"date"==a.type){c="array"==da(b)?b=b.join(""):b;var g=/\d{4}-\d{2}-\d{2}/;if(c.match(g)){$a&&rb&&(S(a,of),S(a,nf));S(a,gf);a.value=c.match(g)[0];S(a,ff);S(a,ef);return}}"array"==da(b)?r(b,e):e(b);d||r(Kg,function(a){W(f,a)&&Wg(f,a)})}
function eh(a,b,c,d){if(!Ld(a,!0))throw new t(11,"Element is not currently visible and may not be manipulated");dh(a,b||void 0);b?b=new bh(b.x,b.y):(b=fh(a),b=new bh(b.width/2,b.height/2));c=c||new Yg;var e=b;b=Kd(a);var f=Xd(a);c.c.x=e.x+f.left;c.c.y=e.y+f.top;e=c.a;if(a!=e){try{Pb(B(e)).closed&&(e=null)}catch(Ia){e=null}e&&(f=e===oa.document.documentElement||e===oa.document.body,e=!c.H&&f?null:e,$g(c,ze,a));ve(c,a);x||$g(c,ye,e,null,b)}$g(c,Je,null,null,b);x&&a!=e&&$g(c,ye,e,null,b);c.w=!1;if(null!==
c.b)throw new t(13,"Cannot press more than one button or an already pressed button.");c.b=0;c.g=c.a;a=y&&!yb(4);if((A||a)&&(C(c.a,"OPTION")||C(c.a,"SELECT")))var g=!0;else(a=y||x)&&(g=Jd(c.a)),g=(b=$g(c,Be,null,null,!1,void 0))&&a&&g!=Jd(c.a)?!1:b;g&&(Ib&&0==c.b&&C(c.g,"OPTION")&&Ee(c,pf,c.c,0,!0),Me(c));if(null===c.b)throw new t(13,"Cannot release a button when no button is pressed.");c.f&&Kd(c.a)&&(g=c.f,a=ec(c.a),!a||g.multiple)&&(c.a.selected=!a,(!A||!g.multiple||qb&&yb(28)||pb&&yb(4))&&S(g,ff));
g=Kd(c.a);$g(c,Le,null,null,d,void 0);try{if(0==c.b&&c.a==c.g){if(!Jb||!C(c.g,"OPTION")){var k=c.c,l=ah(c,Ae);if(g||Kd(c.a)){a=d=null;if(!Ne)for(var q=c.a;q;q=q.parentNode)if(C(q,"A")){d=q;break}else if(Oe(q)){a=q;break}var u=!c.f&&dc(c.a),z=u&&ec(c.a);if(x&&a)a.click();else if(xe(c,Ae,k,l,null,0,g,void 0))if(d&&Pe(d)){var k=d,O=k.href,Z=Pb(B(k));x&&!wb(8)&&(O=Qe(Z.location,O));k.target?Z.open(O,k.target):Z.location.href=O}else!u||y||A||z&&"radio"==c.a.type.toLowerCase()||(c.a.checked=!z)}}c.w&&$g(c,
kf);c.w=!c.w;Ib&&0==c.b&&C(c.g,"OPTION")&&Ee(c,qf,new Kb(0,0),0,!1)}else 2==c.b&&$g(c,Ie)}catch(Ia){}Ce={};c.b=null;c.g=null}function fh(a){if("none"!=(Dd(a,"display")||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display))var b=Fd(a);else{b=a.style;var c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";var f=Fd(a);b.display=c;b.position=e;b.visibility=d;b=f}return 0<b.width&&0<b.height||!a.offsetParent?b:fh(a.offsetParent)}
function dh(a,b){if("scroll"==Yd(a,b)){if(a.scrollIntoView&&(a.scrollIntoView(),"none"==Yd(a,b)))return;for(var c=be(a,b),d=Ud(a);d;d=Ud(d)){var e=d,f=Xd(e);var g=e;if(x&&!ib(9)){var k=Hd(g,"borderLeft");var l=Hd(g,"borderRight");var q=Hd(g,"borderTop");g=Hd(g,"borderBottom");l=new Bd(q,l,g,k)}else k=Dd(g,"borderLeftWidth"),l=Dd(g,"borderRightWidth"),q=Dd(g,"borderTopWidth"),g=Dd(g,"borderBottomWidth"),l=new Bd(parseFloat(q),parseFloat(l),parseFloat(g),parseFloat(k));k=c.left-f.left-l.left;f=c.top-
f.top-l.top;l=e.clientHeight+c.top-c.bottom;e.scrollLeft+=Math.min(k,Math.max(k-(e.clientWidth+c.left-c.right),0));e.scrollTop+=Math.min(f,Math.max(f-l,0))}Yd(a,b)}};function Y(a,b,c,d){function e(){return{P:f,keys:[]}}var f=!!d,g=[],k=e();g.push(k);r(b,function(a){r(a.split(""),function(a){if("\ue000"<=a&&"\ue03d">=a){var b=Y.a[a];if(null===b)g.push(k=e()),f&&(k.P=!1,g.push(k=e()));else if(m(b))k.keys.push(b);else throw Error("Unsupported WebDriver key: \\u"+a.charCodeAt(0).toString(16));}else switch(a){case "\n":k.keys.push(Of);break;case "\t":k.keys.push(Nf);break;case "\b":k.keys.push(Mf);break;default:k.keys.push(a)}})});r(g,function(b){ch(a,b.keys,c,b.P)})}
Y.a={};Y.a["\ue000"]=null;Y.a["\ue003"]=Mf;Y.a["\ue004"]=Nf;Y.a["\ue006"]=Of;Y.a["\ue007"]=Of;Y.a["\ue008"]=V;Y.a["\ue009"]=Pf;Y.a["\ue00a"]=Qf;Y.a["\ue00b"]=Rf;Y.a["\ue00c"]=Sf;Y.a["\ue00d"]=Tf;Y.a["\ue00e"]=Uf;Y.a["\ue00f"]=Vf;Y.a["\ue010"]=Wf;Y.a["\ue011"]=Xf;Y.a["\ue012"]=Yf;Y.a["\ue013"]=Zf;Y.a["\ue014"]=$f;Y.a["\ue015"]=ag;Y.a["\ue016"]=bg;Y.a["\ue017"]=cg;Y.a["\ue018"]=Jg;Y.a["\ue019"]=Hg;Y.a["\ue01a"]=gg;Y.a["\ue01b"]=hg;Y.a["\ue01c"]=ig;Y.a["\ue01d"]=jg;Y.a["\ue01e"]=kg;Y.a["\ue01f"]=lg;
Y.a["\ue020"]=mg;Y.a["\ue021"]=ng;Y.a["\ue022"]=og;Y.a["\ue023"]=pg;Y.a["\ue024"]=qg;Y.a["\ue025"]=rg;Y.a["\ue027"]=sg;Y.a["\ue028"]=tg;Y.a["\ue029"]=ug;Y.a["\ue026"]=Ig;Y.a["\ue031"]=vg;Y.a["\ue032"]=wg;Y.a["\ue033"]=xg;Y.a["\ue034"]=yg;Y.a["\ue035"]=zg;Y.a["\ue036"]=Ag;Y.a["\ue037"]=Bg;Y.a["\ue038"]=Cg;Y.a["\ue039"]=Dg;Y.a["\ue03a"]=Eg;Y.a["\ue03b"]=Fg;Y.a["\ue03c"]=Gg;Y.a["\ue03d"]=dg;function gh(){}
function hh(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if("array"==da(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),hh(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),ih(d,c),c.push(":"),hh(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":ih(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var jh={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},kh=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function ih(a,b){b.push('"',a.replace(kh,function(a){var b=jh[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),jh[a]=b);return b}),'"')};A||y&&wb(3.5)||x&&wb(8);function lh(a){function b(a,e){switch(da(a)){case "string":case "number":case "boolean":return a;case "function":return a.toString();case "array":return xa(a,function(a){return b(a,e)});case "object":if(0<=e.indexOf(a)){if(c)return null;throw new t(17,"Recursive object cannot be transferred");}if(Sa(a,"nodeType")&&(1==a.nodeType||9==a.nodeType)){var d={};d.ELEMENT=mh(a);return d}if(Sa(a,"document"))return d={},d.WINDOW=mh(a),d;e.push(a);if(ea(a))return xa(a,function(a){return b(a,e)});a=Pa(a,function(a,
b){return ba(b)||n(b)});return Qa(a,function(a){return b(a,e)});default:return null}}var c=a instanceof ShadowRoot;return b(a,[])}function nh(a,b){return"array"==da(a)?xa(a,function(a){return nh(a,b)}):ga(a)?"function"==typeof a?a:Sa(a,"ELEMENT")?oh(a.ELEMENT,b):Sa(a,"WINDOW")?oh(a.WINDOW,b):Qa(a,function(a){return nh(a,b)}):a}function ph(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.J=na());b.J||(b.J=na());return b}
function mh(a){var b=ph(a.ownerDocument),c=Ta(b,function(b){return b==a});c||(c=":wdc:"+b.J++,b[c]=a);return c}
function oh(a,b){a=decodeURIComponent(a);b=b||document;var c=ph(b);if(!Sa(c,a))throw new t(10,"Element does not exist in cache");var d=c[a];if(Sa(d,"setInterval")){if(d.closed)throw delete c[a],new t(23,"Window has been closed.");return d}for(var e=d;e;){if(e==b.documentElement)return d;e.host&&11===e.nodeType&&(e=e.host);e=e.parentNode}delete c[a];throw new t(10,"Element is no longer attached to the DOM");};ca("_",function(a,b){a=[a];try{var c;b?c=oh(b.WINDOW):c=window;var d=nh(a,c.document),e=eh.apply(null,d);var f={status:0,value:lh(e)}}catch(g){f={status:Sa(g,"code")?g.code:13,value:{message:g.message}}}b=[];hh(new gh,f,b);return b.join("")});; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
