function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var e=this||self;try{var f=window}catch(a){f=e};function k(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function l(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function m(a){var b=l(a);return b=="array"||b=="object"&&typeof a.length=="number"};function n(a,b){this.code=a;this.state=p[a]||q;this.message=b||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(b<0||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}(function(){function a(){}a.prototype=Error.prototype;n.prototype=new a;n.prototype.constructor=n})();var q="unknown error",p={15:"element not selectable",11:"element not visible"};p[31]=q;p[30]=q;
p[24]="invalid cookie domain";p[29]="invalid element coordinates";p[12]="invalid element state";p[32]="invalid selector";p[51]="invalid selector";p[52]="invalid selector";p[17]="javascript error";p[405]="unsupported operation";p[34]="move target out of bounds";p[27]="no such alert";p[7]="no such element";p[8]="no such frame";p[23]="no such window";p[28]="script timeout";p[33]="session not created";p[10]="stale element reference";p[21]="timeout";p[25]="unable to set cookie";p[26]="unexpected alert open";
p[13]=q;p[9]="unknown command";n.prototype.toString=function(){return this.name+": "+this.message};var u=class{constructor(a){if(r!==r)throw Error("SafeUrl is not meant to be built directly");this.l=a}toString(){return this.l.toString()}},r={};new u("about:invalid#zClosurez");new u("about:blank");const v={};class x{constructor(){if(v!==v)throw Error("SafeStyle is not meant to be built directly");this.j=""}toString(){return this.j.toString()}}new x;function y(a,b){var c={};for(let d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function z(a,b){var c={};for(let d in a)c[d]=b.call(void 0,a[d],d,a);return c}function A(a){var b=0;for(let c in a)b++;return b}function B(a,b){return a!==null&&b in a}function C(a,b){for(let c in a)if(b.call(void 0,a[c],c,a))return c};const D={};class F{constructor(){if(D!==D)throw Error("SafeStyleSheet is not meant to be built directly");this.i=""}toString(){return this.i.toString()}}new F;function G(){var a=e.navigator;return a&&(a=a.userAgent)?a:""}function H(a){return G().indexOf(a)!=-1};function I(){return H("Firefox")||H("FxiOS")}function J(){return(H("Chrome")||H("CriOS"))&&!H("Edge")||H("Silk")};const K=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){var c=a.length,d=Array(c),g=typeof a==="string"?a.split(""):a;for(let h=0;h<c;h++)h in g&&(d[h]=b.call(void 0,g[h],h,a));return d};const L={};class M{constructor(){var a=e.trustedTypes&&e.trustedTypes.emptyHTML||"";if(L!==L)throw Error("SafeHtml is not meant to be built directly");this.h=a}toString(){return this.h.toString()}}new M;function N(){return H("iPhone")&&!H("iPod")&&!H("iPad")};var O=I(),P=N()||H("iPod"),aa=H("iPad"),ba=H("Android")&&!(J()||I()||H("Opera")||H("Silk")),ca=J(),da=H("Safari")&&!(J()||H("Coast")||H("Opera")||H("Edge")||H("Edg/")||H("OPR")||I()||H("Silk")||H("Android"))&&!(N()||H("iPad")||H("iPod"));function Q(a){return(a=a.exec(G()))?a[1]:""}(function(){if(O)return Q(/Firefox\/([0-9.]+)/);if(ca){if(N()||H("iPad")||H("iPod")||H("Macintosh")){var a=Q(/CriOS\/([0-9.]+)/);if(a)return a}return Q(/Chrome\/([0-9.]+)/)}if(da&&!(N()||H("iPad")||H("iPod")))return Q(/Version\/([0-9.]+)/);if(P||aa){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(G()))return a[1]+"."+a[2]}else if(ba)return(a=Q(/Android\s+([0-9.]+)/))?a:Q(/Version\/([0-9.]+)/);return""})();var ea=JSON.stringify;function fa(a){function b(c,d){switch(l(c)){case "string":case "number":case "boolean":return c;case "function":return c.toString();case "array":return K(c,function(h){return b(h,d)});case "object":if(d.indexOf(c)>=0)throw new n(17,"Recursive object cannot be transferred");if(B(c,"nodeType")&&(c.nodeType==1||c.nodeType==9)){var g={};c=R(c);g.ELEMENT=c;g["element-6066-11e4-a52e-4f735466cecf"]=c;return g}if(B(c,"document"))return g={},g.WINDOW=R(c),g;d.push(c);if(m(c))return K(c,function(h){return b(h,
d)});g=y(c,function(h,w){return typeof w==="number"||typeof w==="string"});return z(g,function(h){return b(h,d)});default:return null}}return b(a,[])}function S(a,b){return Array.isArray(a)?K(a,function(c){return S(c,b)}):k(a)?typeof a=="function"?a:B(a,"ELEMENT")?T(a.ELEMENT,b):B(a,"element-6066-11e4-a52e-4f735466cecf")?T(a["element-6066-11e4-a52e-4f735466cecf"],b):B(a,"WINDOW")?T(a.WINDOW,b):z(a,function(c){return S(c,b)}):a}
function U(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.g=Date.now());b.g||(b.g=Date.now());return b}function V(a,b){if(B(b,"setInterval"))return!!b.closed;for(;b;){if(b==a.documentElement)return!1;b.host&&b.nodeType===11&&(b=b.host);b=b.parentNode}return!0}function ha(a){var b=U(a),c;for(c in b){var d=b[c];d&&typeof d==="object"&&V(a,d)&&delete b[c]}}
function R(a){var b=U(a.ownerDocument);A(b)-1>=200&&ha(a.ownerDocument);var c=C(b,function(d){return d==a});c||(c=":wdc:"+b.g++,b[c]=a);return c}function T(a,b){a=decodeURIComponent(a);b=b||document;var c=U(b);if(!B(c,a))throw new n(10,"Element does not exist in cache");var d=c[a];if(!V(b,d))return d;delete c[a];if(B(d,"setInterval"))throw new n(23,"Window has been closed.");throw new n(10,"Element is no longer attached to the DOM");};function W(a,b,c,d){d=d||f;try{a:{var g=a;if(typeof g==="string")try{a=new d.Function(g);break a}catch(t){throw t;}a=d==window?g:new d.Function("return ("+g+").apply(null,arguments);")}var h=S(b,d.document),w=a.apply(null,h);var E={status:0,value:fa(w)}}catch(t){a=B(t,"code")?t.code:13,E={status:a,value:{message:t.message,error:p[a]||q}}}return c?ea(E):E}var X=["se_exportedFunctionSymbol"],Y=e;X[0]in Y||typeof Y.execScript=="undefined"||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||W===void 0?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=W;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
