function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var e=this||self;try{var f=window}catch(a){f=e};function k(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function l(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function m(a){var b=l(a);return b=="array"||b=="object"&&typeof a.length=="number"};var q=class extends Error{constructor(a,b){super(b||"");this.code=a;this.state=n[a]||p;this.message=b||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(b<0||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}},p="unknown error",n={15:"element not selectable",11:"element not visible"};n[31]=p;n[30]=p;n[24]="invalid cookie domain";n[29]="invalid element coordinates";
n[12]="invalid element state";n[32]="invalid selector";n[51]="invalid selector";n[52]="invalid selector";n[17]="javascript error";n[405]="unsupported operation";n[34]="move target out of bounds";n[27]="no such alert";n[7]="no such element";n[8]="no such frame";n[23]="no such window";n[28]="script timeout";n[33]="session not created";n[10]="stale element reference";n[21]="timeout";n[25]="unable to set cookie";n[26]="unexpected alert open";n[13]=p;n[9]="unknown command";
q.prototype.toString=function(){return this.name+": "+this.message};(class{constructor(a,b){this.m=a===r&&b||""}}).prototype.toString=function(){return"Const{"+this.m+"}"};var r={};var v=class{constructor(a){if(u!==u)throw Error("SafeUrl is not meant to be built directly");this.l=a}toString(){return this.l.toString()}},u={};new v("about:invalid#zClosurez");new v("about:blank");var x={};class y{constructor(){if(x!==x)throw Error("SafeStyle is not meant to be built directly");this.j=""}toString(){return this.j.toString()}}new y;function z(a,b){var c={};for(let d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function A(a,b){var c={};for(let d in a)c[d]=b.call(void 0,a[d],d,a);return c}function B(a){var b=0;for(let c in a)b++;return b}function C(a,b){return a!==null&&b in a}function D(a,b){for(let c in a)if(b.call(void 0,a[c],c,a))return c};var F={};class G{constructor(){if(F!==F)throw Error("SafeStyleSheet is not meant to be built directly");this.i=""}toString(){return this.i.toString()}}new G;function H(){var a=e.navigator;return a&&(a=a.userAgent)?a:""}function I(a){return H().indexOf(a)!=-1};function J(){return I("Firefox")||I("FxiOS")}function K(){return(I("Chrome")||I("CriOS"))&&!I("Edge")||I("Silk")};const L=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){var c=a.length,d=Array(c),g=typeof a==="string"?a.split(""):a;for(let h=0;h<c;h++)h in g&&(d[h]=b.call(void 0,g[h],h,a));return d};var M={};class N{constructor(){var a=e.trustedTypes&&e.trustedTypes.emptyHTML||"";if(M!==M)throw Error("SafeHtml is not meant to be built directly");this.h=a}toString(){return this.h.toString()}}new N;function O(){return I("iPhone")&&!I("iPod")&&!I("iPad")};var P=J(),aa=O()||I("iPod"),ba=I("iPad"),ca=I("Android")&&!(K()||J()||I("Opera")||I("Silk")),da=K(),ea=I("Safari")&&!(K()||I("Coast")||I("Opera")||I("Edge")||I("Edg/")||I("OPR")||J()||I("Silk")||I("Android"))&&!(O()||I("iPad")||I("iPod"));function Q(a){return(a=a.exec(H()))?a[1]:""}(function(){if(P)return Q(/Firefox\/([0-9.]+)/);if(da){if(O()||I("iPad")||I("iPod")||I("Macintosh")){var a=Q(/CriOS\/([0-9.]+)/);if(a)return a}return Q(/Chrome\/([0-9.]+)/)}if(ea&&!(O()||I("iPad")||I("iPod")))return Q(/Version\/([0-9.]+)/);if(aa||ba){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(H()))return a[1]+"."+a[2]}else if(ca)return(a=Q(/Android\s+([0-9.]+)/))?a:Q(/Version\/([0-9.]+)/);return""})();var fa=JSON.stringify;function ha(a){function b(c,d){switch(l(c)){case "string":case "number":case "boolean":return c;case "function":return c.toString();case "array":return L(c,function(h){return b(h,d)});case "object":if(d.indexOf(c)>=0)throw new q(17,"Recursive object cannot be transferred");if(C(c,"nodeType")&&(c.nodeType==1||c.nodeType==9)){var g={};c=R(c);g.ELEMENT=c;g["element-6066-11e4-a52e-4f735466cecf"]=c;return g}if(C(c,"document"))return g={},g.WINDOW=R(c),g;d.push(c);if(m(c))return L(c,function(h){return b(h,
d)});g=z(c,function(h,w){return typeof w==="number"||typeof w==="string"});return A(g,function(h){return b(h,d)});default:return null}}return b(a,[])}function S(a,b){return Array.isArray(a)?L(a,function(c){return S(c,b)}):k(a)?typeof a=="function"?a:C(a,"ELEMENT")?T(a.ELEMENT,b):C(a,"element-6066-11e4-a52e-4f735466cecf")?T(a["element-6066-11e4-a52e-4f735466cecf"],b):C(a,"WINDOW")?T(a.WINDOW,b):A(a,function(c){return S(c,b)}):a}
function U(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.g=Date.now());b.g||(b.g=Date.now());return b}function V(a,b){if(C(b,"setInterval"))return!!b.closed;for(;b;){if(b==a.documentElement)return!1;b.host&&b.nodeType===11&&(b=b.host);b=b.parentNode}return!0}function ia(a){var b=U(a),c;for(c in b){var d=b[c];d&&typeof d==="object"&&V(a,d)&&delete b[c]}}
function R(a){var b=U(a.ownerDocument);B(b)-1>=200&&ia(a.ownerDocument);var c=D(b,function(d){return d==a});c||(c=":wdc:"+b.g++,b[c]=a);return c}function T(a,b){a=decodeURIComponent(a);b=b||document;var c=U(b);if(!C(c,a))throw new q(10,"Element does not exist in cache");var d=c[a];if(!V(b,d))return d;delete c[a];if(C(d,"setInterval"))throw new q(23,"Window has been closed.");throw new q(10,"Element is no longer attached to the DOM");};function W(a,b,c,d){d=d||f;try{a:{var g=a;if(typeof g==="string")try{a=new d.Function(g);break a}catch(t){throw t;}a=d==window?g:new d.Function("return ("+g+").apply(null,arguments);")}var h=S(b,d.document),w=a.apply(null,h);var E={status:0,value:ha(w)}}catch(t){a=C(t,"code")?t.code:13,E={status:a,value:{message:t.message,error:n[a]||p}}}return c?fa(E):E}var X=["se_exportedFunctionSymbol"],Y=e;X[0]in Y||typeof Y.execScript=="undefined"||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||W===void 0?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=W;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
