function(){return function(){var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ca(a,b){if(b){for(var c=ba,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&aa(c,d,{configurable:!0,writable:!0,value:f})}}
ca("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=c),a>>>=1)c+=c;return d}});ca("Math.sign",function(a){return a?a:function(a){a=Number(a);return!a||isNaN(a)?a:0<a?1:-1}});var l=this;function m(a){return void 0!==a}
function da(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&m(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function fa(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function q(a){return"string"==typeof a}function ga(a){return"function"==ea(a)}function ha(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ia(a,b,c){return a.call.apply(a.bind,arguments)}
function ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ka(a,b,c){ka=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return ka.apply(null,arguments)}
function la(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ma=Date.now||function(){return+new Date};function t(a,b){function c(){}c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.P=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var na=window;function u(a,b){this.code=a;this.a=v[a]||oa;this.message=b||"";var c=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=c.length-5;if(0>d||c.indexOf("Error",d)!=d)c+="Error";this.name=c;c=Error(this.message);c.name=this.name;this.stack=c.stack||""}t(u,Error);var oa="unknown error",v={15:"element not selectable",11:"element not visible"};v[31]=oa;v[30]=oa;v[24]="invalid cookie domain";v[29]="invalid element coordinates";v[12]="invalid element state";
v[32]="invalid selector";v[51]="invalid selector";v[52]="invalid selector";v[17]="javascript error";v[405]="unsupported operation";v[34]="move target out of bounds";v[27]="no such alert";v[7]="no such element";v[8]="no such frame";v[23]="no such window";v[28]="script timeout";v[33]="session not created";v[10]="stale element reference";v[21]="timeout";v[25]="unable to set cookie";v[26]="unexpected alert open";v[13]=oa;v[9]="unknown command";u.prototype.toString=function(){return this.name+": "+this.message};var pa;function qa(a){var b=a.length-1;return 0<=b&&a.indexOf(" ",b)==b}var ra=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function sa(a,b){for(var c=0,d=ra(String(a)).split("."),e=ra(String(b)).split("."),f=Math.max(d.length,e.length),g=0;!c&&g<f;g++){var h=d[g]||"",n=e[g]||"",p=RegExp("(\\d*)(\\D*)","g"),k=RegExp("(\\d*)(\\D*)","g");do{var r=p.exec(h)||["","",""],y=k.exec(n)||["","",""];if(0==r[0].length&&0==y[0].length)break;c=ta(0==r[1].length?0:parseInt(r[1],10),0==y[1].length?0:parseInt(y[1],10))||ta(0==r[2].length,0==y[2].length)||ta(r[2],y[2])}while(!c)}return c}function ta(a,b){return a<b?-1:a>b?1:0}
function ua(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};function va(a,b){if(q(a))return q(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function w(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function wa(a,b){for(var c=a.length,d=[],e=0,f=q(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}
function xa(a,b){for(var c=a.length,d=Array(c),e=q(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function ya(a,b,c){var d=c;w(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function za(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function Aa(a,b){for(var c=a.length,d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}
function Ca(a,b){var c;a:{c=a.length;for(var d=q(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:q(a)?a.charAt(c):a[c]}function Da(a){return Array.prototype.concat.apply(Array.prototype,arguments)}function Ea(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var x;a:{var Fa=l.navigator;if(Fa){var Ga=Fa.userAgent;if(Ga){x=Ga;break a}}x=""}function z(a){return-1!=x.indexOf(a)};function Ha(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function Ia(a){var b=Ja,c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function Ka(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function La(){return z("Opera")||z("OPR")}function Ma(){return(z("Chrome")||z("CriOS"))&&!La()&&!z("Edge")};function Na(){return z("iPhone")&&!z("iPod")&&!z("iPad")};var Oa=La(),A=z("Trident")||z("MSIE"),Pa=z("Edge"),Qa=z("Gecko")&&!(-1!=x.toLowerCase().indexOf("webkit")&&!z("Edge"))&&!(z("Trident")||z("MSIE"))&&!z("Edge"),Ra=-1!=x.toLowerCase().indexOf("webkit")&&!z("Edge");function Sa(){var a=x;if(Qa)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Pa)return/Edge\/([\d\.]+)/.exec(a);if(A)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ra)return/WebKit\/(\S+)/.exec(a)}function Ta(){var a=l.document;return a?a.documentMode:void 0}
var Ua=function(){if(Oa&&l.opera){var a;var b=l.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Sa())&&(a=b?b[1]:"");return A&&(b=Ta(),null!=b&&b>parseFloat(a))?String(b):a}(),Va={};function Wa(a){return Va[a]||(Va[a]=0<=sa(Ua,a))}var Xa=l.document,Ya=Xa&&A?Ta()||("CSS1Compat"==Xa.compatMode?parseInt(Ua,10):5):void 0;!Qa&&!A||A&&9<=Number(Ya)||Qa&&Wa("1.9.1");A&&Wa("9");function B(a,b){this.x=m(a)?a:0;this.y=m(b)?b:0}B.prototype.clone=function(){return new B(this.x,this.y)};B.prototype.toString=function(){return"("+this.x+", "+this.y+")"};B.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};B.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};B.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function Za(a,b){this.width=a;this.height=b}Za.prototype.clone=function(){return new Za(this.width,this.height)};Za.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};Za.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};Za.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
Za.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function $a(a){return a?new ab(C(a)):pa||(pa=new ab)}function bb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function cb(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function db(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(A&&!(9<=Number(Ya))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?eb(a,b):!c&&cb(e,b)?-1*fb(a,b):!d&&cb(f,a)?fb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=C(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(l.Range.START_TO_END,d)}function fb(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return eb(d,a)}function eb(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}function C(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function gb(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}
function ab(a){this.a=a||l.document||document}
function hb(a,b,c,d){a=d||a.a;var e=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))c=a.querySelectorAll(e+(c?"."+c:""));else if(c&&a.getElementsByClassName)if(b=a.getElementsByClassName(c),e){a={};for(var f=d=0,g;g=b[f];f++)e==g.nodeName&&(a[d++]=g);a.length=d;c=a}else c=b;else if(b=a.getElementsByTagName(e||"*"),c){a={};for(f=d=0;g=b[f];f++){var e=g.className,h;if(h="function"==typeof e.split)h=0<=va(e.split(/\s+/),c);h&&(a[d++]=g)}a.length=d;c=a}else c=b;return c};var ib={w:function(a){return!(!a.querySelectorAll||!a.querySelector)},o:function(a,b){if(!a)throw new u(32,"No class name specified");a=ra(a);if(-1!==a.indexOf(" "))throw new u(32,"Compound class names not permitted");if(ib.w(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(d){throw new u(32,"An invalid or illegal class name was specified");}var c=hb($a(b),"*",a,b);return c.length?c[0]:null},s:function(a,b){if(!a)throw new u(32,"No class name specified");a=ra(a);if(-1!==a.indexOf(" "))throw new u(32,
"Compound class names not permitted");if(ib.w(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new u(32,"An invalid or illegal class name was specified");}return hb($a(b),"*",a,b)}};var jb=z("Firefox"),kb=Na()||z("iPod"),lb=z("iPad"),mb=z("Android")&&!(Ma()||z("Firefox")||La()||z("Silk")),nb=Ma(),ob=z("Safari")&&!(Ma()||z("Coast")||La()||z("Edge")||z("Silk")||z("Android"))&&!(Na()||z("iPad")||z("iPod"));function pb(a){return(a=a.exec(x))?a[1]:""}var qb=function(){if(jb)return pb(/Firefox\/([0-9.]+)/);if(A||Pa||Oa)return Ua;if(nb)return pb(/Chrome\/([0-9.]+)/);if(ob&&!(Na()||z("iPad")||z("iPod")))return pb(/Version\/([0-9.]+)/);if(kb||lb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(x);if(a)return a[1]+"."+a[2]}else if(mb)return(a=pb(/Android\s+([0-9.]+)/))?a:pb(/Version\/([0-9.]+)/);return""}();var rb,sb;function tb(a){return ub?rb(a):A?0<=sa(Ya,a):Wa(a)}function vb(a){ub?sb(a):mb?sa(wb,a):sa(qb,a)}
var ub=function(){if(!Qa)return!1;var a=l.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;rb=function(a){return 0<=c.compare(d,""+a)};sb=function(a){c.compare(e,""+a)};return!0}(),xb;if(mb){var yb=/Android\s+([0-9\.]+)/.exec(x);xb=yb?yb[1]:"0"}else xb="0";
var wb=xb,zb=A&&!(8<=Number(Ya)),Ab=A&&!(9<=Number(Ya));mb&&vb(2.3);mb&&vb(4);ob&&vb(6);var Bb={o:function(a,b){if(!ga(b.querySelector)&&A&&tb(8)&&!ha(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new u(32,"No selector specified");a=ra(a);var c;try{c=b.querySelector(a)}catch(d){throw new u(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},s:function(a,b){if(!ga(b.querySelectorAll)&&A&&tb(8)&&!ha(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new u(32,"No selector specified");a=ra(a);try{return b.querySelectorAll(a)}catch(c){throw new u(32,
"An invalid or illegal selector was specified");}}};var Cb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Db="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Eb=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Fb=/^#(?:[0-9a-f]{3}){1,2}$/i,Gb=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Hb=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function Ib(a,b){b=b.toLowerCase();if("style"==b)return Jb(a.style.cssText);if(zb&&"value"==b&&D(a,"INPUT"))return a.value;if(Ab&&!0===a[b])return String(a.getAttribute(b));var c=a.getAttributeNode(b);return c&&c.specified?c.value:null}var Kb=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function Jb(a){var b=[];w(a.split(Kb),function(a){var d=a.indexOf(":");0<d&&(a=[a.slice(0,d),a.slice(d+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function D(a,b){return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function Lb(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var Mb=A&&!(9<=Number(Ya)),Nb=A&&!(8<=Number(Ya));function Ob(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Pb(a,b){var c=Nb&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Ob(b,a,b.nodeName,c)};function Qb(a){this.b=a;this.a=0}function Rb(a){a=a.match(Sb);for(var b=0;b<a.length;b++)Tb.test(a[b])&&a.splice(b,1);return new Qb(a)}var Sb=RegExp("\\$?(?:(?![0-9-\\.])(?:\\*|[\\w-\\.]+):)?(?![0-9-\\.])(?:\\*|[\\w-\\.]+)|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),Tb=/^\s/;function E(a,b){return a.b[a.a+(b||0)]}function F(a){return a.b[a.a++]}function Ub(a){return a.b.length<=a.a};function G(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(Mb&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),Mb&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function Vb(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Nb&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Wb(a,b,c,d,e){return(Mb?Xb:Yb).call(null,a,b,q(c)?c:null,q(d)?d:null,e||new H)}
function Xb(a,b,c,d,e){if(a instanceof Zb||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;a=$b(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var g=[],h=0;b=f[h++];)Vb(b,c,d)&&g.push(b);f=g}for(h=0;b=f[h++];)"*"==a&&"!"==b.tagName||I(e,b);return e}ac(a,b,c,d,e);return e}
function Yb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!A?(b=b.getElementsByName(d),w(b,function(b){a.a(b)&&I(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),w(b,function(b){b.className==d&&a.a(b)&&I(e,b)})):a instanceof J?ac(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),w(b,function(a){Vb(a,c,d)&&I(e,a)}));return e}
function bc(a,b,c,d,e){var f;if((a instanceof Zb||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=$b(a);if("*"!=g&&(f=wa(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=wa(f,function(a){return Vb(a,c,d)}));w(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||I(e,a)});return e}return cc(a,b,c,d,e)}function cc(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Vb(b,c,d)&&a.a(b)&&I(e,b);return e}
function ac(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Vb(b,c,d)&&a.a(b)&&I(e,b),ac(a,b,c,d,e)}function $b(a){if(a instanceof J){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function H(){this.b=this.a=null;this.l=0}function dc(a){this.node=a;this.a=this.b=null}function ec(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f,g=0;c&&d;){f=c.node;var h=d.node;f==h||f instanceof Ob&&h instanceof Ob&&f.a==h.a?(f=c,c=c.a,d=d.a):0<db(c.node,d.node)?(f=d,d=d.a):(f=c,c=c.a);(f.b=e)?e.a=f:a.a=f;e=f;g++}for(f=c||d;f;)f.b=e,e=e.a=f,g++,f=f.a;a.b=e;a.l=g;return a}H.prototype.unshift=function(a){a=new dc(a);a.a=this.a;this.b?this.a.b=a:this.a=this.b=a;this.a=a;this.l++};
function I(a,b){var c=new dc(b);c.b=a.b;a.a?a.b.a=c:a.a=a.b=c;a.b=c;a.l++}function fc(a){return(a=a.a)?a.node:null}function gc(a){return(a=fc(a))?G(a):""}function hc(a,b){return new ic(a,!!b)}function ic(a,b){this.f=a;this.b=(this.c=b)?a.b:a.a;this.a=null}function K(a){var b=a.b;if(b){var c=a.a=b;a.b=a.c?b.b:b.a;return c.node}return null};function L(a){this.i=a;this.b=this.g=!1;this.f=null}function M(a){return"\n  "+a.toString().split("\n").join("\n  ")}function jc(a,b){a.g=b}function kc(a,b){a.b=b}function O(a,b){var c=a.a(b);return c instanceof H?+gc(c):+c}function P(a,b){var c=a.a(b);return c instanceof H?gc(c):""+c}function lc(a,b){var c=a.a(b);return c instanceof H?!!c.l:!!c};function mc(a,b,c){L.call(this,a.i);this.c=a;this.h=b;this.u=c;this.g=b.g||c.g;this.b=b.b||c.b;this.c==nc&&(c.b||c.g||4==c.i||0==c.i||!b.f?b.b||b.g||4==b.i||0==b.i||!c.f||(this.f={name:c.f.name,v:b}):this.f={name:b.f.name,v:c})}t(mc,L);
function oc(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof H&&c instanceof H){b=hc(b);for(d=K(b);d;d=K(b))for(e=hc(c),f=K(e);f;f=K(e))if(a(G(d),G(f)))return!0;return!1}if(b instanceof H||c instanceof H){b instanceof H?(e=b,d=c):(e=c,d=b);f=hc(e);for(var g=typeof d,h=K(f);h;h=K(f)){switch(g){case "number":h=+G(h);break;case "boolean":h=!!G(h);break;case "string":h=G(h);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(h,d)||e==c&&a(d,h))return!0}return!1}return e?
"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}mc.prototype.a=function(a){return this.c.m(this.h,this.u,a)};mc.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+M(this.h);return a+=M(this.u)};function pc(a,b,c,d){this.a=a;this.I=b;this.i=c;this.m=d}pc.prototype.toString=function(){return this.a};var qc={};
function Q(a,b,c,d){if(qc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new pc(a,b,c,d);return qc[a.toString()]=a}Q("div",6,1,function(a,b,c){return O(a,c)/O(b,c)});Q("mod",6,1,function(a,b,c){return O(a,c)%O(b,c)});Q("*",6,1,function(a,b,c){return O(a,c)*O(b,c)});Q("+",5,1,function(a,b,c){return O(a,c)+O(b,c)});Q("-",5,1,function(a,b,c){return O(a,c)-O(b,c)});Q("<",4,2,function(a,b,c){return oc(function(a,b){return a<b},a,b,c)});
Q(">",4,2,function(a,b,c){return oc(function(a,b){return a>b},a,b,c)});Q("<=",4,2,function(a,b,c){return oc(function(a,b){return a<=b},a,b,c)});Q(">=",4,2,function(a,b,c){return oc(function(a,b){return a>=b},a,b,c)});var nc=Q("=",3,2,function(a,b,c){return oc(function(a,b){return a==b},a,b,c,!0)});Q("!=",3,2,function(a,b,c){return oc(function(a,b){return a!=b},a,b,c,!0)});Q("and",2,2,function(a,b,c){return lc(a,c)&&lc(b,c)});Q("or",1,2,function(a,b,c){return lc(a,c)||lc(b,c)});function rc(a,b){if(b.a.length&&4!=a.i)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");L.call(this,a.i);this.c=a;this.h=b;this.g=a.g;this.b=a.b}t(rc,L);rc.prototype.a=function(a){a=this.c.a(a);return sc(this.h,a)};rc.prototype.toString=function(){var a;a="Filter:"+M(this.c);return a+=M(this.h)};function tc(a,b){if(b.length<a.J)throw Error("Function "+a.j+" expects at least"+a.J+" arguments, "+b.length+" given");if(null!==a.C&&b.length>a.C)throw Error("Function "+a.j+" expects at most "+a.C+" arguments, "+b.length+" given");a.O&&w(b,function(b,d){if(4!=b.i)throw Error("Argument "+d+" to function "+a.j+" is not of type Nodeset: "+b);});L.call(this,a.i);this.h=a;this.c=b;jc(this,a.g||za(b,function(a){return a.g}));kc(this,a.N&&!b.length||a.M&&!!b.length||za(b,function(a){return a.b}))}
t(tc,L);tc.prototype.a=function(a){return this.h.m.apply(null,Da(a,this.c))};tc.prototype.toString=function(){var a="Function: "+this.h;if(this.c.length)var b=ya(this.c,function(a,b){return a+M(b)},"Arguments:"),a=a+M(b);return a};function uc(a,b,c,d,e,f,g,h,n){this.j=a;this.i=b;this.g=c;this.N=d;this.M=e;this.m=f;this.J=g;this.C=m(h)?h:g;this.O=!!n}uc.prototype.toString=function(){return this.j};var vc={};
function R(a,b,c,d,e,f,g,h){if(vc.hasOwnProperty(a))throw Error("Function already created: "+a+".");vc[a]=new uc(a,b,c,d,!1,e,f,g,h)}R("boolean",2,!1,!1,function(a,b){return lc(b,a)},1);R("ceiling",1,!1,!1,function(a,b){return Math.ceil(O(b,a))},1);R("concat",3,!1,!1,function(a,b){return ya(Ea(arguments,1),function(b,d){return b+P(d,a)},"")},2,null);R("contains",2,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);return-1!=b.indexOf(a)},2);R("count",1,!1,!1,function(a,b){return b.a(a).l},1,1,!0);
R("false",2,!1,!1,function(){return!1},0);R("floor",1,!1,!1,function(a,b){return Math.floor(O(b,a))},1);R("id",4,!1,!1,function(a,b){function c(a){if(Mb){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return Ca(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=P(b,a).split(/\s+/),f=[];w(d,function(a){a=c(a);!a||0<=va(f,a)||f.push(a)});f.sort(db);var g=new H;w(f,function(a){I(g,a)});return g},1);
R("lang",2,!1,!1,function(){return!1},1);R("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);R("local-name",3,!1,!0,function(a,b){var c=b?fc(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);R("name",3,!1,!0,function(a,b){var c=b?fc(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);R("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
R("normalize-space",3,!1,!0,function(a,b){return(b?P(b,a):G(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);R("not",2,!1,!1,function(a,b){return!lc(b,a)},1);R("number",1,!1,!0,function(a,b){return b?O(b,a):+G(a.a)},0,1);R("position",1,!0,!1,function(a){return a.b},0);R("round",1,!1,!1,function(a,b){return Math.round(O(b,a))},1);R("starts-with",2,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);return!b.lastIndexOf(a,0)},2);R("string",3,!1,!0,function(a,b){return b?P(b,a):G(a.a)},0,1);
R("string-length",1,!1,!0,function(a,b){return(b?P(b,a):G(a.a)).length},0,1);R("substring",3,!1,!1,function(a,b,c,d){c=O(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?O(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=P(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);R("substring-after",3,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
R("substring-before",3,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);R("sum",1,!1,!1,function(a,b){for(var c=hc(b.a(a)),d=0,e=K(c);e;e=K(c))d+=+G(e);return d},1,1,!0);R("translate",3,!1,!1,function(a,b,c,d){b=P(b,a);c=P(c,a);var e=P(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);R("true",2,!1,!1,function(){return!0},0);function J(a,b){this.h=a;this.c=m(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function wc(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}J.prototype.a=function(a){return null===this.b||this.b==a.nodeType};J.prototype.f=function(){return this.h};
J.prototype.toString=function(){var a="Kind Test: "+this.h;!this.c||(a+=M(this.c));return a};function xc(a){L.call(this,3);this.c=a.substring(1,a.length-1)}t(xc,L);xc.prototype.a=function(){return this.c};xc.prototype.toString=function(){return"Literal: "+this.c};function Zb(a,b){this.j=a.toLowerCase();var c;c="*"==this.j?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():c}Zb.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=m(a.localName)?a.localName:a.nodeName;return"*"!=this.j&&this.j!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Zb.prototype.f=function(){return this.j};
Zb.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.j};function yc(a){L.call(this,1);this.c=a}t(yc,L);yc.prototype.a=function(){return this.c};yc.prototype.toString=function(){return"Number: "+this.c};function zc(a,b){L.call(this,a.i);this.h=a;this.c=b;this.g=a.g;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.A||c.c!=Ac||(c=c.u,"*"!=c.f()&&(this.f={name:c.f(),v:null}))}}t(zc,L);function Bc(){L.call(this,4)}t(Bc,L);Bc.prototype.a=function(a){var b=new H;a=a.a;9==a.nodeType?I(b,a):I(b,a.ownerDocument);return b};Bc.prototype.toString=function(){return"Root Helper Expression"};function Cc(){L.call(this,4)}t(Cc,L);Cc.prototype.a=function(a){var b=new H;I(b,a.a);return b};Cc.prototype.toString=function(){return"Context Helper Expression"};
function Dc(a){return"/"==a||"//"==a}zc.prototype.a=function(a){var b=this.h.a(a);if(!(b instanceof H))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.l;c++){var e=a[c],f=hc(b,e.c.a),g;if(e.g||e.c!=Ec)if(e.g||e.c!=Fc)for(g=K(f),b=e.a(new Lb(g));g=K(f);)g=e.a(new Lb(g)),b=ec(b,g);else g=K(f),b=e.a(new Lb(g));else{for(g=K(f);(b=K(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new Lb(g))}}return b};
zc.prototype.toString=function(){var a;a="Path Expression:"+M(this.h);if(this.c.length){var b=ya(this.c,function(a,b){return a+M(b)},"Steps:");a+=M(b)}return a};function Gc(a,b){this.a=a;this.b=!!b}
function sc(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=hc(b),f=b.l,g,h=0;g=K(e);h++){var n=a.b?f-h:h+1;g=d.a(new Lb(g,n,f));if("number"==typeof g)n=n==g;else if("string"==typeof g||"boolean"==typeof g)n=!!g;else if(g instanceof H)n=0<g.l;else throw Error("Predicate.evaluate returned an unexpected type.");if(!n){n=e;g=n.f;var p=n.a;if(!p)throw Error("Next must be called at least once before remove.");var k=p.b,p=p.a;k?k.a=p:g.a=p;p?p.b=k:g.b=k;g.l--;n.a=null}}return b}
Gc.prototype.toString=function(){return ya(this.a,function(a,b){return a+M(b)},"Predicates:")};function Hc(a,b,c,d){L.call(this,4);this.c=a;this.u=b;this.h=c||new Gc([]);this.A=!!d;b=this.h;b=0<b.a.length?b.a[0].f:null;a.b&&b&&(a=b.name,a=Mb?a.toLowerCase():a,this.f={name:a,v:b.v});a:{a=this.h;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.g||1==c.i||0==c.i){a=!0;break a}a=!1}this.g=a}t(Hc,L);
Hc.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.v?P(c.v,a):null,f=1);if(this.A)if(this.g||this.c!=Ic)if(b=hc((new Hc(Jc,new J("node"))).a(a)),c=K(b))for(a=this.m(c,d,e,f);c=K(b);)a=ec(a,this.m(c,d,e,f));else a=new H;else a=Wb(this.u,b,d,e),a=sc(this.h,a,f);else a=this.m(a.a,d,e,f);return a};Hc.prototype.m=function(a,b,c,d){a=this.c.f(this.u,a,b,c);return a=sc(this.h,a,d)};
Hc.prototype.toString=function(){var a;a="Step:"+M("Operator: "+(this.A?"//":"/"));this.c.j&&(a+=M("Axis: "+this.c));a+=M(this.u);if(this.h.a.length){var b=ya(this.h.a,function(a,b){return a+M(b)},"Predicates:");a+=M(b)}return a};function Kc(a,b,c,d){this.j=a;this.f=b;this.a=c;this.b=d}Kc.prototype.toString=function(){return this.j};var Lc={};function S(a,b,c,d){if(Lc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new Kc(a,b,c,!!d);return Lc[a]=b}
S("ancestor",function(a,b){for(var c=new H,d=b;d=d.parentNode;)a.a(d)&&c.unshift(d);return c},!0);S("ancestor-or-self",function(a,b){var c=new H,d=b;do a.a(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var Ac=S("attribute",function(a,b){var c=new H,d=a.f();if("style"==d&&Mb&&b.style)return I(c,new Ob(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof J&&null===a.b||"*"==d)for(var d=0,f;f=e[d];d++)Mb?f.nodeValue&&I(c,Pb(b,f)):I(c,f);else(f=e.getNamedItem(d))&&(Mb?f.nodeValue&&I(c,Pb(b,f)):I(c,f));return c},!1),Ic=S("child",function(a,b,c,d,e){return(Mb?bc:cc).call(null,a,b,q(c)?c:null,q(d)?d:null,e||new H)},!1,!0);S("descendant",Wb,!1,!0);
var Jc=S("descendant-or-self",function(a,b,c,d){var e=new H;Vb(b,c,d)&&a.a(b)&&I(e,b);return Wb(a,b,c,d,e)},!1,!0),Ec=S("following",function(a,b,c,d){var e=new H;do for(var f=b;f=f.nextSibling;)Vb(f,c,d)&&a.a(f)&&I(e,f),e=Wb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);S("following-sibling",function(a,b){for(var c=new H,d=b;d=d.nextSibling;)a.a(d)&&I(c,d);return c},!1);S("namespace",function(){return new H},!1);
var Mc=S("parent",function(a,b){var c=new H;if(9==b.nodeType)return c;if(2==b.nodeType)return I(c,b.ownerElement),c;var d=b.parentNode;a.a(d)&&I(c,d);return c},!1),Fc=S("preceding",function(a,b,c,d){var e=new H,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var n=[];for(b=f[g];b=b.previousSibling;)n.unshift(b);for(var p=0,k=n.length;p<k;p++)b=n[p],Vb(b,c,d)&&a.a(b)&&I(e,b),e=Wb(a,b,c,d,e)}return e},!0,!0);
S("preceding-sibling",function(a,b){for(var c=new H,d=b;d=d.previousSibling;)a.a(d)&&c.unshift(d);return c},!0);var Nc=S("self",function(a,b){var c=new H;a.a(b)&&I(c,b);return c},!1);function Oc(a){L.call(this,1);this.c=a;this.g=a.g;this.b=a.b}t(Oc,L);Oc.prototype.a=function(a){return-O(this.c,a)};Oc.prototype.toString=function(){return"Unary Expression: -"+M(this.c)};function Pc(a){L.call(this,4);this.c=a;jc(this,za(this.c,function(a){return a.g}));kc(this,za(this.c,function(a){return a.b}))}t(Pc,L);Pc.prototype.a=function(a){var b=new H;w(this.c,function(c){c=c.a(a);if(!(c instanceof H))throw Error("Path expression must evaluate to NodeSet.");b=ec(b,c)});return b};Pc.prototype.toString=function(){return ya(this.c,function(a,b){return a+M(b)},"Union Expression:")};function Qc(a,b){this.a=a;this.b=b}function Rc(a){for(var b,c=[];;){T(a,"Missing right hand side of binary expression.");b=Sc(a);var d=F(a.a);if(!d)break;var e=(d=qc[d]||null)&&d.I;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].I;)b=new mc(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new mc(c.pop(),c.pop(),b);return b}function T(a,b){if(Ub(a.a))throw Error(b);}function Tc(a,b){var c=F(a.a);if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function Uc(a){a=F(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Vc(a){a=F(a.a);if(2>a.length)throw Error("Unclosed literal string");return new xc(a)}
function Wc(a){var b,c=[],d;if(Dc(E(a.a))){b=F(a.a);d=E(a.a);if("/"==b&&(Ub(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new Bc;d=new Bc;T(a,"Missing next location step.");b=Xc(a,b);c.push(b)}else{a:{b=E(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":F(a.a);b=Rc(a);T(a,'unclosed "("');Tc(a,")");break;case '"':case "'":b=Vc(a);break;default:if(isNaN(+b))if(!wc(b)&&/(?![0-9])[\w]/.test(d)&&"("==E(a.a,1)){b=F(a.a);
b=vc[b]||null;F(a.a);for(d=[];")"!=E(a.a);){T(a,"Missing function argument list.");d.push(Rc(a));if(","!=E(a.a))break;F(a.a)}T(a,"Unclosed function argument list.");Uc(a);b=new tc(b,d)}else{b=null;break a}else b=new yc(+F(a.a))}"["==E(a.a)&&(d=new Gc(Yc(a)),b=new rc(b,d))}if(b)if(Dc(E(a.a)))d=b;else return b;else b=Xc(a,"/"),d=new Cc,c.push(b)}for(;Dc(E(a.a));)b=F(a.a),T(a,"Missing next location step."),b=Xc(a,b),c.push(b);return new zc(d,c)}
function Xc(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==E(a.a))return d=new Hc(Nc,new J("node")),F(a.a),d;if(".."==E(a.a))return d=new Hc(Mc,new J("node")),F(a.a),d;var f;if("@"==E(a.a))f=Ac,F(a.a),T(a,"Missing attribute name");else if("::"==E(a.a,1)){if(!/(?![0-9])[\w]/.test(E(a.a).charAt(0)))throw Error("Bad token: "+F(a.a));c=F(a.a);f=Lc[c]||null;if(!f)throw Error("No axis with name: "+c);F(a.a);T(a,"Missing node name")}else f=Ic;c=E(a.a);if(/(?![0-9])[\w\*]/.test(c.charAt(0)))if("("==
E(a.a,1)){if(!wc(c))throw Error("Invalid node type: "+c);c=F(a.a);if(!wc(c))throw Error("Invalid type name: "+c);Tc(a,"(");T(a,"Bad nodetype");e=E(a.a).charAt(0);var g=null;if('"'==e||"'"==e)g=Vc(a);T(a,"Bad nodetype");Uc(a);c=new J(c,g)}else if(c=F(a.a),e=c.indexOf(":"),-1==e)c=new Zb(c);else{var g=c.substring(0,e),h;if("*"==g)h="*";else if(h=a.b(g),!h)throw Error("Namespace prefix not declared: "+g);c=c.substr(e+1);c=new Zb(c,h)}else throw Error("Bad token: "+F(a.a));e=new Gc(Yc(a),f.a);return d||
new Hc(f,c,e,"//"==b)}function Yc(a){for(var b=[];"["==E(a.a);){F(a.a);T(a,"Missing predicate expression.");var c=Rc(a);b.push(c);T(a,"Unclosed predicate expression.");Tc(a,"]")}return b}function Sc(a){if("-"==E(a.a))return F(a.a),new Oc(Sc(a));var b=Wc(a);if("|"!=E(a.a))a=b;else{for(b=[b];"|"==F(a.a);)T(a,"Missing next union location path."),b.push(Wc(a));a.a.a--;a=new Pc(b)}return a};function Zc(a){switch(a.nodeType){case 1:return la($c,a);case 9:return Zc(a.documentElement);case 11:case 10:case 6:case 12:return ad;default:return a.parentNode?Zc(a.parentNode):ad}}function ad(){return null}function $c(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?$c(a.parentNode,b):null};function bd(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=Rb(a);if(Ub(c))throw Error("Invalid XPath expression.");b?ga(b)||(b=ka(b.lookupNamespaceURI,b)):b=function(){return null};var d=Rc(new Qc(c,b));if(!Ub(c))throw Error("Bad token: "+F(c));this.evaluate=function(a,b){var c=d.a(new Lb(a));return new U(c,b)}}
function U(a,b){if(!b)if(a instanceof H)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof H))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof H?gc(a):""+a;break;case 1:this.numberValue=a instanceof H?+gc(a):+a;break;case 3:this.booleanValue=a instanceof H?0<a.l:!!a;break;case 4:case 5:case 6:case 7:var d=
hc(a);c=[];for(var e=K(d);e;e=K(d))c.push(e instanceof Ob?e.a:e);this.snapshotLength=a.l;this.invalidIteratorState=!1;break;case 8:case 9:d=fc(a);this.singleNodeValue=d instanceof Ob?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=c.length||
0>a?null:c[a]}}U.ANY_TYPE=0;U.NUMBER_TYPE=1;U.STRING_TYPE=2;U.BOOLEAN_TYPE=3;U.UNORDERED_NODE_ITERATOR_TYPE=4;U.ORDERED_NODE_ITERATOR_TYPE=5;U.UNORDERED_NODE_SNAPSHOT_TYPE=6;U.ORDERED_NODE_SNAPSHOT_TYPE=7;U.ANY_UNORDERED_NODE_TYPE=8;U.FIRST_ORDERED_NODE_TYPE=9;function cd(a){this.lookupNamespaceURI=Zc(a)}
function dd(a,b){var c=a||l,d=c.Document&&c.Document.prototype||c.document;if(!d.evaluate||b)c.XPathResult=U,d.evaluate=function(a,b,c,d){return(new bd(a,c)).evaluate(b,d)},d.createExpression=function(a,b){return new bd(a,b)},d.createNSResolver=function(a){return new cd(a)}}da("wgxpath.install",dd);var V={};V.D=function(){var a={S:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
V.m=function(a,b,c){var d=C(a);if(!d.documentElement)return null;(A||mb)&&dd(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):V.D;if(A&&!Wa(7))return d.evaluate.call(d,b,a,e,c,null);if(!A||9<=Number(Ya)){for(var f={},g=d.getElementsByTagName("*"),h=0;h<g.length;++h){var n=g[h],p=n.namespaceURI;if(p&&!f[p]){var k=n.lookupPrefix(p);if(!k)var r=p.match(".*/(\\w+)/?$"),k=r?r[1]:"xhtml";f[p]=k}}var y={},N;for(N in f)y[f[N]]=N;e=function(a){return y[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(Ba){if("TypeError"===Ba.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):V.D,d.evaluate(b,a,e,c,null);throw Ba;}}catch(Ba){if(!Qa||"NS_ERROR_ILLEGAL_VALUE"!=Ba.name)throw new u(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Ba);}};V.F=function(a,b){if(!a||1!=a.nodeType)throw new u(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
V.o=function(a,b){var c=function(){var c=V.m(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=C(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||V.F(c,a);return c};
V.s=function(a,b){var c=function(){var c=V.m(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=C(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();w(c,function(b){V.F(b,a)});return c};function ed(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}ed.prototype.clone=function(){return new ed(this.top,this.right,this.bottom,this.left)};ed.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};ed.prototype.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
ed.prototype.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};ed.prototype.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function W(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}W.prototype.clone=function(){return new W(this.left,this.top,this.width,this.height)};W.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};W.prototype.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
W.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};W.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function fd(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return D(a)?a:null}
function X(a,b){var c=ua(b);if("float"==c||"cssFloat"==c||"styleFloat"==c)c=Ab?"styleFloat":"cssFloat";var d;a:{d=c;var e=C(a);if(e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))){d=e[d]||e.getPropertyValue(d)||"";break a}d=""}d=d||gd(a,c);if(null===d)d=null;else if(0<=va(Db,c)){b:{var f=d.match(Gb);if(f){var c=Number(f[1]),e=Number(f[2]),g=Number(f[3]),f=Number(f[4]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g&&0<=f&&1>=f){c=[c,e,g,f];break b}}c=null}if(!c)b:{if(g=
d.match(Hb))if(c=Number(g[1]),e=Number(g[2]),g=Number(g[3]),0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g){c=[c,e,g,1];break b}c=null}if(!c)b:{c=d.toLowerCase();e=Cb[c.toLowerCase()];if(!e&&(e="#"==c.charAt(0)?c:"#"+c,4==e.length&&(e=e.replace(Eb,"#$1$1$2$2$3$3")),!Fb.test(e))){c=null;break b}c=[parseInt(e.substr(1,2),16),parseInt(e.substr(3,2),16),parseInt(e.substr(5,2),16),1]}d=c?"rgba("+c.join(", ")+")":d}return d}
function gd(a,b){var c=a.currentStyle||a.style,d=c[b];!m(d)&&ga(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?m(d)?d:null:(c=fd(a))?gd(c,b):null}
function hd(a,b,c){function d(a){var b=id(a);return 0<b.height&&0<b.width?!0:D(a,"PATH")&&(0<b.height||0<b.width)?(a=X(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=X(a,"overflow")&&za(a.childNodes,function(a){return 3==a.nodeType||D(a)&&d(a)})}function e(a){return jd(a)==Y&&Aa(a.childNodes,function(a){return!D(a)||e(a)||!d(a)})}if(!D(a))throw Error("Argument to isShown must be of type Element");if(D(a,"BODY"))return!0;if(D(a,"OPTION")||D(a,"OPTGROUP"))return a=gb(a,function(a){return D(a,"SELECT")}),
!!a&&hd(a,!0,c);var f=kd(a);if(f)return!!f.G&&0<f.rect.width&&0<f.rect.height&&hd(f.G,b,c);if(D(a,"INPUT")&&"hidden"==a.type.toLowerCase()||D(a,"NOSCRIPT"))return!1;f=X(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||ld(a))&&d(a)?!e(a):!1}function md(a){function b(a){if("none"==X(a,"display"))return!1;a=fd(a);return!a||b(a)}return hd(a,!1,b)}var Y="hidden";
function jd(a){function b(a){function b(a){return a==g?!0:!X(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==X(a,"position")?!1:!0}var c=X(a,"position");if("fixed"==c)return p=!0,a==g?null:g;for(a=fd(a);a&&!b(a);)a=fd(a);return a}function c(a){var b=a;if("visible"==n)if(a==g&&h)b=h;else if(a==h)return{x:"visible",y:"visible"};b={x:X(b,"overflow-x"),y:X(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new ab(f)).a;
a=b.scrollingElement?b.scrollingElement:Ra||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=A&&Wa("10")&&b.pageYOffset!=a.scrollTop?new B(a.scrollLeft,a.scrollTop):new B(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new B(a.scrollLeft,a.scrollTop);return a}var e=nd(a),f=C(a),g=f.documentElement,h=f.body,n=X(g,"overflow"),p;for(a=b(a);a;a=b(a)){var k=c(a);if("visible"!=k.x||"visible"!=k.y){var r=id(a);if(!r.width||!r.height)return Y;
var y=e.right<r.left,N=e.bottom<r.top;if(y&&"hidden"==k.x||N&&"hidden"==k.y)return Y;if(y&&"visible"!=k.x||N&&"visible"!=k.y){y=d(a);N=e.bottom<r.top-y.y;if(e.right<r.left-y.x&&"visible"!=k.x||N&&"visible"!=k.x)return Y;e=jd(a);return e==Y?Y:"scroll"}y=e.left>=r.left+r.width;r=e.top>=r.top+r.height;if(y&&"hidden"==k.x||r&&"hidden"==k.y)return Y;if(y&&"visible"!=k.x||r&&"visible"!=k.y){if(p&&(k=d(a),e.left>=g.scrollWidth-k.x||e.right>=g.scrollHeight-k.y))return Y;e=jd(a);return e==Y?Y:"scroll"}}}return"none"}
function id(a){var b=kd(a);if(b)return b.rect;if(D(a,"HTML"))return a=C(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new Za(a.clientWidth,a.clientHeight),new W(0,0,a.width,a.height);var c;try{c=a.getBoundingClientRect()}catch(d){return new W(0,0,0,0)}b=new W(c.left,c.top,c.right-c.left,c.bottom-c.top);A&&a.ownerDocument.body&&(a=C(a),b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+
a.body.clientTop);return b}function kd(a){var b=D(a,"MAP");if(!b&&!D(a,"AREA"))return null;var c=b?a:D(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=V.o('/descendant::*[@usemap = "#'+c.name+'"]',C(c)))&&(e=id(d),b||"default"==a.shape.toLowerCase()||(a=od(a),b=Math.min(Math.max(a.left,0),e.width),c=Math.min(Math.max(a.top,0),e.height),e=new W(b+e.left,c+e.top,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{G:d,rect:e||new W(0,0,0,0)}}
function od(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new W(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new W(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new W(b,c,d-b,e-c)}return new W(0,0,0,0)}function nd(a){a=id(a);return new ed(a.top,a.left+a.width,a.top+a.height,a.left)}
function pd(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function qd(a){var b=[];rd(a,b);a=xa(b,pd);return pd(a.join("\n")).replace(/\xa0/g," ")}
function sd(a,b,c){if(D(a,"BR"))b.push("");else{var d=D(a,"TD"),e=X(a,"display"),f=!d&&!(0<=va(td,e)),g=m(a.previousElementSibling)?a.previousElementSibling:bb(a.previousSibling),g=g?X(g,"display"):"",h=X(a,"float")||X(a,"cssFloat")||X(a,"styleFloat");!f||"run-in"==g&&"none"==h||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var n=md(a),p=null,k=null;n&&(p=X(a,"white-space"),k=X(a,"text-transform"));w(a.childNodes,function(a){c(a,b,n,p,k)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||qa(a)||(b[b.length-
1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function rd(a,b){sd(a,b,function(a,b,e,f,g){3==a.nodeType&&e?ud(a,b,f,g):D(a)&&rd(a,b)})}var td="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function ud(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";qa(c)&&!a.lastIndexOf(" ",0)&&(a=a.substr(1));b.push(c+a)}
function ld(a){if(Ab){if("relative"==X(a,"position"))return 1;a=X(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return vd(a)}function vd(a){var b=1,c=X(a,"opacity");c&&(b=Number(c));(a=fd(a))&&(b*=vd(a));return b};var wd={w:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},o:function(a,b){var c=$a(b),d=q(a)?c.a.getElementById(a):a;return d?Ib(d,"id")==a&&cb(b,d)?d:Ca(hb(c,"*"),function(c){return Ib(c,"id")==a&&cb(b,c)}):null},s:function(a,b){if(!a)return[];if(wd.w(b,a))try{return b.querySelectorAll("#"+wd.L(a))}catch(d){return[]}var c=hb($a(b),"*",null,b);return wa(c,function(b){return Ib(b,"id")==a})},L:function(a){return a.replace(/(['"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var Z={},xd={};Z.K=function(a,b,c){var d;try{d=Bb.s("a",b)}catch(e){d=hb($a(b),"A",null,b)}return Ca(d,function(b){b=qd(b);return c&&-1!=b.indexOf(a)||b==a})};Z.H=function(a,b,c){var d;try{d=Bb.s("a",b)}catch(e){d=hb($a(b),"A",null,b)}return wa(d,function(b){b=qd(b);return c&&-1!=b.indexOf(a)||b==a})};Z.o=function(a,b){return Z.K(a,b,!1)};Z.s=function(a,b){return Z.H(a,b,!1)};xd.o=function(a,b){return Z.K(a,b,!0)};xd.s=function(a,b){return Z.H(a,b,!0)};var yd={o:function(a,b){if(""===a)throw new u(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},s:function(a,b){if(""===a)throw new u(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var zd={className:ib,"class name":ib,css:Bb,"css selector":Bb,id:wd,linkText:Z,"link text":Z,name:{o:function(a,b){var c=hb($a(b),"*",null,b);return Ca(c,function(b){return Ib(b,"name")==a})},s:function(a,b){var c=hb($a(b),"*",null,b);return wa(c,function(b){return Ib(b,"name")==a})}},partialLinkText:xd,"partial link text":xd,tagName:yd,"tag name":yd,xpath:V};function Ad(){}
function Bd(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if("array"==ea(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Bd(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Cd(d,c),c.push(":"),Bd(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Cd(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var Dd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Ed=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Cd(a,b){b.push('"',a.replace(Ed,function(a){var b=Dd[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Dd[a]=b);return b}),'"')};Ra||Qa&&tb(3.5)||A&&tb(8);function Ja(a){switch(ea(a)){case "string":case "number":case "boolean":return a;case "function":return a.toString();case "array":return xa(a,Ja);case "object":if(a&&"nodeType"in a&&(1==a.nodeType||9==a.nodeType)){var b={};b.ELEMENT=Fd(a);return b}if(a&&"document"in a)return b={},b.WINDOW=Fd(a),b;if(fa(a))return xa(a,Ja);a=Ha(a,function(a,b){return"number"==typeof b||q(b)});return Ia(a);default:return null}}
function Gd(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.B=ma());b.B||(b.B=ma());return b}function Fd(a){var b=Gd(a.ownerDocument),c=Ka(b,function(b){return b==a});c||(c=":wdc:"+b.B++,b[c]=a);return c}
function Hd(a,b){a=decodeURIComponent(a);var c=b||document,d=Gd(c);if(!(d&&a in d))throw new u(10,"Element does not exist in cache");var e=d[a];if(e&&"setInterval"in e){if(e.closed)throw delete d[a],new u(23,"Window has been closed.");return e}for(var f=e;f;){if(f==c.documentElement)return e;f=f.parentNode}delete d[a];throw new u(10,"Element is no longer attached to the DOM");};da("_",function(a,b,c,d){var e={};e[a]=b;var f;try{var g,h;d?h=Hd(d.WINDOW):h=window;g=h;var n;c?n=Hd(c.ELEMENT,g.document):n=g.document;var p;a:{a=n;var k;b:{for(var r in e)if(e.hasOwnProperty(r)){k=r;break b}k=null}if(k){var y=zd[k];if(y&&ga(y.o)){p=y.o(e[k],a||na.document);break a}}throw Error("Unsupported locator strategy: "+k);}f={status:0,value:Ja(p)}}catch(N){f={status:N&&"code"in N?N.code:13,value:{message:N.message}}}e=[];Bd(new Ad,f,e);return e.join("")});; return this._.apply(null,arguments);}.apply({navigator:typeof window!=undefined?window.navigator:null,document:typeof window!=undefined?window.document:null}, arguments);}
