function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var h,l=this||self;try{var aa=window}catch(a){aa=l};function n(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function ba(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ca(a){var b=ba(a);return b=="array"||b=="object"&&typeof a.length=="number"};function p(a,b){this.code=a;this.state=q[a]||t;this.message=b||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(b<0||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}(function(){function a(){}a.prototype=Error.prototype;p.prototype=new a;p.prototype.constructor=p})();var t="unknown error",q={15:"element not selectable",11:"element not visible"};q[31]=t;q[30]=t;
q[24]="invalid cookie domain";q[29]="invalid element coordinates";q[12]="invalid element state";q[32]="invalid selector";q[51]="invalid selector";q[52]="invalid selector";q[17]="javascript error";q[405]="unsupported operation";q[34]="move target out of bounds";q[27]="no such alert";q[7]="no such element";q[8]="no such frame";q[23]="no such window";q[28]="script timeout";q[33]="session not created";q[10]="stale element reference";q[21]="timeout";q[25]="unable to set cookie";q[26]="unexpected alert open";
q[13]=t;q[9]="unknown command";p.prototype.toString=function(){return this.name+": "+this.message};var da;function ea(a){var b=a.length-1;return b>=0&&a.indexOf(" ",b)==b}var v=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var ha=class{constructor(a){if(fa!==fa)throw Error("SafeUrl is not meant to be built directly");this.R=a}toString(){return this.R.toString()}},fa={};new ha("about:invalid#zClosurez");new ha("about:blank");const ia={};class ja{constructor(){if(ia!==ia)throw Error("SafeStyle is not meant to be built directly");this.P=""}toString(){return this.P.toString()}}new ja;function ka(a,b){var c={};for(let d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function la(a,b){var c={};for(let d in a)c[d]=b.call(void 0,a[d],d,a);return c}function ma(a,b){for(let c in a)if(b.call(void 0,a[c],c,a))return c};const na={};class oa{constructor(){if(na!==na)throw Error("SafeStyleSheet is not meant to be built directly");this.O=""}toString(){return this.O.toString()}}new oa;function pa(){var a=l.navigator;return a&&(a=a.userAgent)?a:""}function z(a){return pa().indexOf(a)!=-1};function qa(){return z("Firefox")||z("FxiOS")}function sa(){return(z("Chrome")||z("CriOS"))&&!z("Edge")||z("Silk")};const ta=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(let c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},A=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){var d=a.length,e=typeof a==="string"?a.split(""):a;for(let f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ua=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){var c=a.length,d=[],e=0,f=typeof a==="string"?a.split(""):a;for(let g=0;g<c;g++)if(g in f){let k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d},va=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){var c=a.length,d=Array(c),e=typeof a==="string"?a.split(""):a;for(let f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},wa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){var c=
a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},xa=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){var d=a.length,e=typeof a==="string"?a.split(""):a;for(let f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};
function ya(a,b){a:{let c=a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return b<0?null:typeof a==="string"?a.charAt(b):a[b]}function za(a){var b=a.length;if(b>0){let c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]}function Aa(a,b){a.sort(b||Ba)}function Ba(a,b){return a>b?1:a<b?-1:0};const Ca={};class Da{constructor(){var a=l.trustedTypes&&l.trustedTypes.emptyHTML||"";if(Ca!==Ca)throw Error("SafeHtml is not meant to be built directly");this.N=a}toString(){return this.N.toString()}}new Da;function Ea(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};function C(){return z("iPhone")&&!z("iPod")&&!z("iPad")};var Fa=qa(),Ga=C()||z("iPod"),Ha=z("iPad"),Ia=z("Android")&&!(sa()||qa()||z("Opera")||z("Silk")),Ja=sa(),Ka=z("Safari")&&!(sa()||z("Coast")||z("Opera")||z("Edge")||z("Edg/")||z("OPR")||qa()||z("Silk")||z("Android"))&&!(C()||z("iPad")||z("iPod"));function D(a){return(a=a.exec(pa()))?a[1]:""}(function(){if(Fa)return D(/Firefox\/([0-9.]+)/);if(Ja){if(C()||z("iPad")||z("iPod")||z("Macintosh")){var a=D(/CriOS\/([0-9.]+)/);if(a)return a}return D(/Chrome\/([0-9.]+)/)}if(Ka&&!(C()||z("iPad")||z("iPod")))return D(/Version\/([0-9.]+)/);if(Ga||Ha){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(pa()))return a[1]+"."+a[2]}else if(Ia)return(a=D(/Android\s+([0-9.]+)/))?a:D(/Version\/([0-9.]+)/);return""})();function Na(){this.o=void 0}
function Oa(a,b,c){if(b==null)c.push("null");else{if(typeof b=="object"){if(Array.isArray(b)){var d=b;b=d.length;c.push("[");var e="";for(var f=0;f<b;f++)c.push(e),e=d[f],Oa(a,a.o?a.o.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],typeof e!="function"&&(c.push(f),Pa(d,c),c.push(":"),Oa(a,a.o?a.o.call(b,d,e):e,c),f=","));c.push("}");
return}}switch(typeof b){case "string":Pa(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var Qa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\v":"\\u000b"},Ra=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;
function Pa(a,b){b.push('"',a.replace(Ra,function(c){var d=Qa[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).slice(1),Qa[c]=d);return d}),'"')};function Sa(a){function b(c,d){switch(ba(c)){case "string":case "number":case "boolean":return c;case "function":return c.toString();case "array":return va(c,function(f){return b(f,d)});case "object":if(d.indexOf(c)>=0)throw new p(17,"Recursive object cannot be transferred");if(c!==null&&"nodeType"in c&&(c.nodeType==1||c.nodeType==9)){var e={};e.ELEMENT=Ta(c);return e}if(c!==null&&"document"in c)return e={},e.WINDOW=Ta(c),e;d.push(c);if(ca(c))return va(c,function(f){return b(f,d)});c=ka(c,function(f,
g){return typeof g==="number"||typeof g==="string"});return la(c,function(f){return b(f,d)});default:return null}}return b(a,[])}function Ua(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.u=Date.now());b.u||(b.u=Date.now());return b}function Ta(a){var b=Ua(a.ownerDocument),c=ma(b,function(d){return d==a});c||(c=":wdc:"+b.u++,b[c]=a);return c}
function Va(a,b){a=decodeURIComponent(a);b=b||document;var c=Ua(b);if(!(c!==null&&a in c))throw new p(10,"Element does not exist in cache");var d=c[a];if(d!==null&&"setInterval"in d){if(d.closed)throw delete c[a],new p(23,"Window has been closed.");return d}for(var e=d;e;){if(e==b.documentElement)return d;e.host&&e.nodeType===11&&(e=e.host);e=e.parentNode}delete c[a];throw new p(10,"Element is no longer attached to the DOM");};function E(a,b){this.x=a!==void 0?a:0;this.y=b!==void 0?b:0}h=E.prototype;h.clone=function(){return new E(this.x,this.y)};h.toString=function(){return"("+this.x+", "+this.y+")"};h.equals=function(a){return a instanceof E&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};h.translate=function(a,b){a instanceof E?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),typeof b==="number"&&(this.y+=b));return this};h.scale=function(a,b){this.x*=a;this.y*=typeof b==="number"?b:a;return this};function F(a,b){this.width=a;this.height=b}h=F.prototype;h.clone=function(){return new F(this.width,this.height)};h.toString=function(){return"("+this.width+" x "+this.height+")"};h.aspectRatio=function(){return this.width/this.height};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};h.scale=function(a,b){this.width*=a;this.height*=typeof b==="number"?b:a;return this};function G(a){return a?new H(I(a)):da||=new H}function Wa(a,b){return typeof b==="string"?a.getElementById(b):b}function Xa(a,b,c){function d(k){k&&b.appendChild(typeof k==="string"?a.createTextNode(k):k)}for(var e=1;e<c.length;e++){var f=c[e];if(!ca(f)||n(f)&&f.nodeType>0)d(f);else{a:{if(f&&typeof f.length=="number"){if(n(f)){var g=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){g=typeof f.item=="function";break a}}g=!1}A(g?za(f):f,d)}}}
function Ya(a){for(;a&&a.nodeType!=1;)a=a.previousSibling;return a}function Za(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function I(a){return a.nodeType==9?a:a.ownerDocument||a.document}function $a(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}
function H(a){this.l=a||l.document||document}h=H.prototype;h.getElementsByTagName=function(a,b){return(b||this.l).getElementsByTagName(String(a))};
function J(a,b,c,d){a=a.l;d=d||a;var e=b&&b!="*"?String(b).toUpperCase():"";if(d.querySelectorAll&&d.querySelector&&(e||c))c=d.querySelectorAll(e+(c?"."+c:""));else if(c&&d.getElementsByClassName)if(b=d.getElementsByClassName(c),e){d={};for(var f=a=0,g;g=b[f];f++)e==g.nodeName&&(d[a++]=g);d.length=a;c=d}else c=b;else if(b=d.getElementsByTagName(e||"*"),c){d={};for(f=a=0;g=b[f];f++){e=g.className;var k;if(k=typeof e.split=="function")k=ta(e.split(/\s+/),c)>=0;k&&(d[a++]=g)}d.length=a;c=d}else c=b;
return c}h.createElement=function(a){var b=this.l;a=String(a);b.contentType==="application/xhtml+xml"&&(a=a.toLowerCase());return b.createElement(a)};h.createTextNode=function(a){return this.l.createTextNode(String(a))};h.appendChild=function(a,b){a.appendChild(b)};h.append=function(a,b){Xa(I(a),a,arguments)};h.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
h.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};h.contains=Za;var K={m:function(a){return!(!a.querySelectorAll||!a.querySelector)},i:function(a,b){if(!a)throw new p(32,"No class name specified");a=v(a);if(a.indexOf(" ")!==-1)throw new p(32,"Compound class names not permitted");if(K.m(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new p(32,"An invalid or illegal class name was specified");}a=J(G(b),"*",a,b);return a.length?a[0]:null},g:function(a,b){if(!a)throw new p(32,"No class name specified");a=v(a);if(a.indexOf(" ")!==-1)throw new p(32,
"Compound class names not permitted");if(K.m(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new p(32,"An invalid or illegal class name was specified");}return J(G(b),"*",a,b)}};var M={i:function(a,b){if(!a)throw new p(32,"No selector specified");a=v(a);try{var c=b.querySelector(a)}catch(d){throw new p(32,"An invalid or illegal selector was specified");}return c&&c.nodeType==1?c:null},g:function(a,b){if(!a)throw new p(32,"No selector specified");a=v(a);try{return b.querySelectorAll(a)}catch(c){throw new p(32,"An invalid or illegal selector was specified");}}};var ab={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var bb="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),cb=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,db=/^#(?:[0-9a-f]{3}){1,2}$/i,eb=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,fb=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function N(a,b){b=b.toLowerCase();return b=="style"?gb(a.style.cssText):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var hb=RegExp("[;]+(?=(?:(?:[^\"]*\"){2})*[^\"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\\([^()]*\\))*[^()]*$)");function gb(a){var b=[];A(a.split(hb),function(c){var d=c.indexOf(":");d>0&&(c=[c.slice(0,d),c.slice(d+1)],c.length==2&&b.push(c[0].toLowerCase(),":",c[1],";"))});b=b.join("");return b=b.charAt(b.length-1)==";"?b:b+";"}
function O(a,b){b&&typeof b!=="string"&&(b=b.toString());return a instanceof HTMLFormElement?!!a&&a.nodeType==1&&(!b||"FORM"==b):!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)};function P(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}h=P.prototype;h.clone=function(){return new P(this.top,this.right,this.bottom,this.left)};h.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};h.contains=function(a){return this&&a?a instanceof P?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
h.expand=function(a,b,c,d){n(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=Number(b),this.bottom+=Number(c),this.left-=Number(d));return this};h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
h.translate=function(a,b){a instanceof E?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,typeof b==="number"&&(this.top+=b,this.bottom+=b));return this};h.scale=function(a,b){b=typeof b==="number"?b:a;this.left*=a;this.right*=a;this.top*=b;this.bottom*=b;return this};function Q(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}h=Q.prototype;h.clone=function(){return new Q(this.left,this.top,this.width,this.height)};h.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
h.intersection=function(a){var b=Math.max(this.left,a.left),c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top);a=Math.min(this.top+this.height,a.top+a.height);if(d<=a)return this.left=b,this.top=d,this.width=c-b,this.height=a-d,!0}return!1};
h.difference=function(a){b:{var b=Math.max(this.left,a.left);var c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top),e=Math.min(this.top+this.height,a.top+a.height);if(d<=e){b=new Q(b,d,c-b,e-d);break b}}b=null}if(b&&b.height&&b.width){b=[];c=this.top;d=this.height;e=this.left+this.width;var f=this.top+this.height,g=a.left+a.width,k=a.top+a.height;a.top>this.top&&(b.push(new Q(this.left,this.top,this.width,a.top-this.top)),c=a.top,d-=a.top-this.top);k<f&&(b.push(new Q(this.left,
k,this.width,f-k)),d=k-c);a.left>this.left&&b.push(new Q(this.left,c,a.left-this.left,d));g<e&&b.push(new Q(g,c,e-g,d));a=b}else a=[this.clone()];return a};h.contains=function(a){return a instanceof E?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};h.getSize=function(){return new F(this.width,this.height)};
h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.translate=function(a,b){a instanceof E?(this.left+=a.x,this.top+=a.y):(this.left+=a,typeof b==="number"&&(this.top+=b));return this};h.scale=function(a,b){b=typeof b==="number"?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};var ib=typeof ShadowRoot==="function";function jb(a){for(a=a.parentNode;a&&a.nodeType!=1&&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode;return O(a)?a:null}
function R(a,b){b=Ea(b);if(b=="float"||b=="cssFloat"||b=="styleFloat")b="cssFloat";a:{var c=b;var d=I(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||kb(a,b);if(a===null)a=null;else if(ta(bb,b)>=0){b:{var e=a.match(eb);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),b>=0&&b<=255&&c>=0&&c<=255&&d>=0&&d<=255&&e>=0&&e<=1)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(fb))if(b=Number(d[1]),
c=Number(d[2]),d=Number(d[3]),b>=0&&b<=255&&c>=0&&c<=255&&d>=0&&d<=255){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=ab[b.toLowerCase()];if(!c&&(c=b.charAt(0)=="#"?b:"#"+b,c.length==4&&(c=c.replace(cb,"#$1$1$2$2$3$3")),!db.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function kb(a,b){var c=a.currentStyle||a.style,d=c[b];d===void 0&&typeof c.getPropertyValue==="function"&&(d=c.getPropertyValue(b));return d!="inherit"?d!==void 0?d:null:(a=jb(a))?kb(a,b):null}
function lb(a,b,c){function d(g){var k=S(g);if(k.height>0&&k.width>0)return!0;if(O(g,"PATH")&&(k.height>0||k.width>0))return g=R(g,"stroke-width"),!!g&&parseInt(g,10)>0;k=R(g,"visibility");return k!="collapse"&&k!="hidden"&&c(g)?R(g,"overflow")!="hidden"&&wa(g.childNodes,function(x){return x.nodeType==3?(x=x.nodeValue,/^[\s]*$/.test(x)&&/[\n\r\t]/.test(x)?!1:!0):O(x)&&d(x)}):!1}function e(g){return mb(g)==T&&xa(g.childNodes,function(k){return!O(k)||e(k)||!d(k)})}if(!O(a))throw Error("Argument to isShown must be of type Element");
if(O(a,"BODY"))return!0;if(O(a,"OPTION")||O(a,"OPTGROUP"))return a=$a(a,function(g){return O(g,"SELECT")}),!!a&&lb(a,!0,c);var f=nb(a);if(f)return!!f.image&&f.rect.width>0&&f.rect.height>0&&lb(f.image,b,c);if(O(a,"INPUT")&&a.type.toLowerCase()=="hidden"||O(a,"NOSCRIPT"))return!1;f=R(a,"visibility");return f!="collapse"&&f!="hidden"&&c(a)&&(b||ob(a)!=0)&&d(a)?!e(a):!1}
function pb(a){function b(c){if(O(c)&&(R(c,"display")=="none"||R(c,"content-visibility")=="hidden"))return!1;var d;a:if((d=c.parentNode)&&d.shadowRoot&&c.assignedSlot!==void 0)d=c.assignedSlot?c.assignedSlot.parentNode:null;else if(c.getDestinationInsertionPoints){var e=c.getDestinationInsertionPoints();if(e.length>0){d=e[e.length-1];break a}}if(ib&&d instanceof ShadowRoot){if(d.host.shadowRoot&&d.host.shadowRoot!==d)return!1;d=d.host}return!d||d.nodeType!=9&&d.nodeType!=11?d&&O(d,"DETAILS")&&!d.open&&
!O(c,"SUMMARY")?!1:!!d&&b(d):!0}return lb(a,!1,b)}var T="hidden";
function mb(a){function b(m){function u(ra){if(ra==g)return!0;var La=R(ra,"display");return La.lastIndexOf("inline",0)==0||La=="contents"||Ma=="absolute"&&R(ra,"position")=="static"?!1:!0}var Ma=R(m,"position");if(Ma=="fixed")return w=!0,m==g?null:g;for(m=jb(m);m&&!u(m);)m=jb(m);return m}function c(m){var u=m;if(x=="visible")if(m==g&&k)u=k;else if(m==k)return{x:"visible",y:"visible"};u={x:R(u,"overflow-x"),y:R(u,"overflow-y")};m==g&&(u.x=u.x=="visible"?"auto":u.x,u.y=u.y=="visible"?"auto":u.y);return u}
function d(m){if(m==g){var u=(new H(f)).l;m=u.scrollingElement?u.scrollingElement:u.body||u.documentElement;u=u.parentWindow||u.defaultView;m=new E(u.pageXOffset||m.scrollLeft,u.pageYOffset||m.scrollTop)}else m=new E(m.scrollLeft,m.scrollTop);return m}var e=qb(a),f=I(a),g=f.documentElement,k=f.body,x=R(g,"overflow"),w;for(a=b(a);a;a=b(a)){var r=c(a);if(r.x!="visible"||r.y!="visible"){var y=S(a);if(y.width==0||y.height==0)return T;var B=e.right<y.left,L=e.bottom<y.top;if(B&&r.x=="hidden"||L&&r.y==
"hidden")return T;if(B&&r.x!="visible"||L&&r.y!="visible"){B=d(a);L=e.bottom<y.top-B.y;if(e.right<y.left-B.x&&r.x!="visible"||L&&r.x!="visible")return T;e=mb(a);return e==T?T:"scroll"}B=e.left>=y.left+y.width;y=e.top>=y.top+y.height;if(B&&r.x=="hidden"||y&&r.y=="hidden")return T;if(B&&r.x!="visible"||y&&r.y!="visible"){if(w&&(r=d(a),e.left>=g.scrollWidth-r.x||e.right>=g.scrollHeight-r.y))return T;e=mb(a);return e==T?T:"scroll"}}}return"none"}
function S(a){var b=nb(a);if(b)return b.rect;if(O(a,"HTML"))return a=I(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a=a.compatMode=="CSS1Compat"?a.documentElement:a.body,a=new F(a.clientWidth,a.clientHeight),new Q(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new Q(0,0,0,0)}return new Q(c.left,c.top,c.right-c.left,c.bottom-c.top)}
function nb(a){var b=O(a,"MAP");if(!b&&!O(a,"AREA"))return null;var c=b?a:O(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=M.i('*[usemap="#'+c.name+'"]',I(c)))&&(e=S(d),b||a.shape.toLowerCase()=="default"||(a=rb(a),b=Math.min(Math.max(a.left,0),e.width),c=Math.min(Math.max(a.top,0),e.height),e=new Q(b+e.left,c+e.top,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{image:d,rect:e||new Q(0,0,0,0)}}
function rb(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if(b=="rect"&&a.length==4){b=a[0];var c=a[1];return new Q(b,c,a[2]-b,a[3]-c)}if(b=="circle"&&a.length==3)return b=a[2],new Q(a[0]-b,a[1]-b,2*b,2*b);if(b=="poly"&&a.length>2){b=a[0];c=a[1];for(var d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new Q(b,c,d-b,e-c)}return new Q(0,0,0,0)}function qb(a){a=S(a);return new P(a.top,a.left+a.width,a.top+a.height,a.left)}
function sb(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function tb(a){var b=[];ib?ub(a,b):vb(a,b);a=va(b,sb);return sb(a.join("\n")).replace(/\xa0/g," ")}
function wb(a,b,c){if(O(a,"BR"))b.push("");else{var d=O(a,"TD"),e=R(a,"display"),f=!d&&!(ta(xb,e)>=0),g=a.previousElementSibling!==void 0?a.previousElementSibling:Ya(a.previousSibling);g=g?R(g,"display"):"";var k=R(a,"float")||R(a,"cssFloat")||R(a,"styleFloat");!f||g=="run-in"&&k=="none"||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var x=pb(a),w=null,r=null;x&&(w=R(a,"white-space"),r=R(a,"text-transform"));A(a.childNodes,function(y){c(y,b,x,w,r)});a=b[b.length-1]||"";!d&&e!="table-cell"||!a||
ea(a)||(b[b.length-1]+=" ");f&&e!="run-in"&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function vb(a,b){wb(a,b,function(c,d,e,f,g){c.nodeType==3&&e?yb(c,d,f,g):O(c)&&vb(c,d)})}var xb="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function yb(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if(c=="normal"||c=="nowrap")a=a.replace(/\n/g," ");a=c=="pre"||c=="pre-wrap"?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[ \f\t\v\u2028\u2029]+/g," ");d=="capitalize"?(c=/(^|[^'_0-9A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24B6-\u24E9\u0300-\u036F\u1AB0-\u1AFF\u1DC0-\u1DFF])([A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24B6-\u24E9])/g,a=a.replace(c,function(){return arguments[1]+arguments[2].toUpperCase()}),
c=/(^|[^'_0-9A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24B6-\u24E9])([_*])([A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24D0-\u24E9])/g,a=a.replace(c,function(){return arguments[1]+arguments[2]+arguments[3].toUpperCase()})):d=="uppercase"?a=a.toUpperCase():d=="lowercase"&&(a=a.toLowerCase());c=b.pop()||"";ea(c)&&a.lastIndexOf(" ",0)==0&&(a=a.substr(1));b.push(c+a)}function ob(a){var b=1,c=R(a,"opacity");c&&(b=Number(c));(a=jb(a))&&(b*=ob(a));return b}
function zb(a,b,c,d,e){if(a.nodeType==3&&c)yb(a,b,d,e);else if(O(a))if(O(a,"CONTENT")||O(a,"SLOT")){for(var f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?(f=O(a,"CONTENT")?a.getDistributedNodes():a.assignedNodes(),A(f.length>0?f:a.childNodes,function(g){zb(g,b,c,d,e)})):ub(a,b)}else if(O(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)A(a.childNodes,function(g){zb(g,b,c,d,e)}),a=a.olderShadowRoot}else ub(a,b)}
function ub(a,b){if(a.shadowRoot){var c=R(a,"white-space"),d=R(a,"text-transform");A(a.shadowRoot.childNodes,function(e){zb(e,b,!0,c,d)})}wb(a,b,function(e,f,g,k,x){var w=null;e.nodeType==1?w=e:e.nodeType==3&&(w=e);w!=null&&(w.assignedSlot!=null||w.getDestinationInsertionPoints&&w.getDestinationInsertionPoints().length>0)||zb(e,f,g,k,x)})};var Ab={m:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},i:function(a,b){var c=G(b),d=Wa(c.l,a);return d?N(d,"id")==a&&b!=d&&Za(b,d)?d:ya(J(c,"*"),function(e){return N(e,"id")==a&&b!=e&&Za(b,e)}):null},g:function(a,b){if(!a)return[];if(Ab.m(b,a))try{return b.querySelectorAll("#"+Ab.J(a))}catch(c){return[]}b=J(G(b),"*",null,b);return ua(b,function(c){return N(c,"id")==a})},J:function(a){return a.replace(/([\s'"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,"\\$1")}};var U={},Bb={};U.D=function(a,b,c){try{var d=M.g("a",b)}catch(e){d=J(G(b),"A",null,b)}return ya(d,function(e){e=tb(e);e=e.replace(/^[\s]+|[\s]+$/g,"");return c&&e.indexOf(a)!=-1||e==a})};U.C=function(a,b,c){try{var d=M.g("a",b)}catch(e){d=J(G(b),"A",null,b)}return ua(d,function(e){e=tb(e);e=e.replace(/^[\s]+|[\s]+$/g,"");return c&&e.indexOf(a)!=-1||e==a})};U.i=function(a,b){return U.D(a,b,!1)};U.g=function(a,b){return U.C(a,b,!1)};Bb.i=function(a,b){return U.D(a,b,!0)};
Bb.g=function(a,b){return U.C(a,b,!0)};var V={j:function(a,b){return function(c){var d=V.h(a);d=S(d);c=S(c);return b.call(null,d,c)}},H:function(a){return V.j(a,function(b,c){return c.top+c.height<=b.top})},I:function(a){return V.j(a,function(b,c){return c.top>=b.top+b.height})},L:function(a){return V.j(a,function(b,c){return c.left+c.width<=b.left})},S:function(a){return V.j(a,function(b,c){return c.left>=b.left+b.width})},U:function(a){return V.j(a,function(b,c){return c.left<b.left+b.width&&c.left+c.width>b.left&&c.top+c.height<=b.top})},
V:function(a){return V.j(a,function(b,c){return c.left<b.left+b.width&&c.left+c.width>b.left&&c.top>=b.top+b.height})},W:function(a){return V.j(a,function(b,c){return c.top<b.top+b.height&&c.top+c.height>b.top&&c.left+c.width<=b.left})},X:function(a){return V.j(a,function(b,c){return c.top<b.top+b.height&&c.top+c.height>b.top&&c.left>=b.left+b.width})},M:function(a,b){var c;b?c=b:typeof a.distance==="number"&&(c=a.distance);c||=50;return function(d){var e=V.h(a);if(e===d)return!1;e=S(e);d=S(d);e=
new Q(e.left-c,e.top-c,e.width+c*2,e.height+c*2);return e.left<=d.left+d.width&&d.left<=e.left+e.width&&e.top<=d.top+d.height&&d.top<=e.top+e.height}},h:function(a){if(n(a)&&a.nodeType==1)return a;if(typeof a==="function")return V.h(a.call(null));if(n(a)){var b=Cb(a);if(!b)throw new p(7,"No element has been found by "+JSON.stringify(a));return b}throw new p(61,"Selector is of wrong type: "+JSON.stringify(a));}};
V.G={above:V.H,below:V.I,left:V.L,near:V.M,right:V.S,straightAbove:V.U,straightBelow:V.V,straightLeft:V.W,straightRight:V.X};V.F={above:V.h,below:V.h,left:V.h,near:V.h,right:V.h,straightAbove:V.h,straightBelow:V.h,straightLeft:V.h,straightRight:V.h};
V.K=function(a,b){var c=[];A(a,function(e){e&&xa(b,function(f){var g=f.kind,k=V.G[g];if(!k)throw new p(61,"Cannot find filter suitable for "+g);return k.apply(null,f.args)(e)},null)&&c.push(e)},null);a=b[b.length-1];var d=V.F[a?a.kind:"unknown"];return d?(a=d.apply(null,a.args))?V.T(a,c):c:c};
V.T=function(a,b){function c(f){f=S(f);return Math.sqrt(Math.pow(d-(f.left+Math.max(1,f.width)/2),2)+Math.pow(e-(f.top+Math.max(1,f.height)/2),2))}a=S(a);var d=a.left+Math.max(1,a.width)/2,e=a.top+Math.max(1,a.height)/2;Aa(b,function(f,g){return c(f)-c(g)});return b};V.i=function(a,b){a=V.g(a,b);return a.length==0?null:a[0]};
V.g=function(a,b){if(!a.hasOwnProperty("root")||!a.hasOwnProperty("filters"))throw new p(61,"Locator not suitable for relative locators: "+JSON.stringify(a));if(!ca(a.filters))throw new p(61,"Targets should be an array: "+JSON.stringify(a));if(O(a.root))b=[a.root];else a:{var c=a.root,d=Db(c);if(d){var e=Eb[d];if(e&&typeof e.g==="function"){b=e.g(c[d],b||aa.document);break a}}throw new p(61,"Unsupported locator strategy: "+d);}return b.length==0?[]:V.K(b,a.filters)};var Fb={i:function(a,b){if(a==="")throw new p(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},g:function(a,b){if(a==="")throw new p(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var W={};W.v=function(){var a={Y:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
W.B=function(a,b,c){var d=I(a);if(!d.documentElement)return null;try{for(var e=d.createNSResolver?d.createNSResolver(d.documentElement):W.v,f={},g=d.getElementsByTagName("*"),k=0;k<g.length;++k){var x=g[k],w=x.namespaceURI;if(w&&!f[w]){var r=x.lookupPrefix(w);if(!r){var y=w.match(".*/(\\w+)/?$");r=y?y[1]:"xhtml"}f[w]=r}}var B={},L;for(L in f)B[f[L]]=L;e=function(m){return B[m]||null};try{return d.evaluate(b,a,e,c,null)}catch(m){if(m.name==="TypeError")return e=d.createNSResolver?d.createNSResolver(d.documentElement):
W.v,d.evaluate(b,a,e,c,null);throw m;}}catch(m){throw new p(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+m);}};W.A=function(a,b){if(!a||a.nodeType!=1)throw new p(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
W.i=function(a,b){var c=function(){var d=W.B(b,a,9);return d?d.singleNodeValue||null:b.selectSingleNode?(d=I(b),d.setProperty&&d.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();c!==null&&W.A(c,a);return c};
W.g=function(a,b){var c=function(){var d=W.B(b,a,7);if(d){for(var e=d.snapshotLength,f=[],g=0;g<e;++g)f.push(d.snapshotItem(g));return f}return b.selectNodes?(d=I(b),d.setProperty&&d.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();A(c,function(d){W.A(d,a)});return c};var Eb={className:K,"class name":K,css:M,"css selector":M,relative:V,id:Ab,linkText:U,"link text":U,name:{i:function(a,b){b=J(G(b),"*",null,b);return ya(b,function(c){return N(c,"name")==a})},g:function(a,b){b=J(G(b),"*",null,b);return ua(b,function(c){return N(c,"name")==a})}},partialLinkText:Bb,"partial link text":Bb,tagName:Fb,"tag name":Fb,xpath:W};function Db(a){for(var b in a)if(a.hasOwnProperty(b))return b;return null}
function Cb(a,b){var c=Db(a);if(c){var d=Eb[c];if(d&&typeof d.i==="function")return d.i(a[c],b||aa.document)}throw new p(61,"Unsupported locator strategy: "+c);};function Gb(a,b,c,d){var e=Cb,f={};f[a]=b;try{var g=d?Va(d.WINDOW):window;var k=c?Va(c.ELEMENT,g.document):g.document;var x=e(f,k);var w={status:0,value:Sa(x)}}catch(r){w={status:r!==null&&"code"in r?r.code:13,value:{message:r.message}}}a=[];Oa(new Na,w,a);return a.join("")}var X=["se_exportedFunctionSymbol"],Y=l;X[0]in Y||typeof Y.execScript=="undefined"||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||Gb===void 0?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=Gb;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
