function(){return (function(){var ba=this||self;function ca(a){return"string"==typeof a}function da(a,b){a=a.split(".");var c=ba;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function fa(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function ha(a){return"function"==ea(a)}function ia(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ja(a,b,c){return a.call.apply(a.bind,arguments)}
function ka(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function la(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?la=ja:la=ka;return la.apply(null,arguments)}
function ma(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var na=Date.now||function(){return+new Date};function k(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function oa(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var pa;var qa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},p=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ra=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d},sa=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},ta=Array.prototype.reduce?function(a,b,c){return Array.prototype.reduce.call(a,b,c)}:function(a,b,c){var d=c;p(a,
function(e,f){d=b.call(void 0,d,e,f,a)});return d},ua=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},va=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};
function wa(a,b){a:{for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:"string"===typeof a?a.charAt(b):a[b]}function xa(a){return Array.prototype.concat.apply([],arguments)}function ya(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)}function za(a,b){a.sort(b||Aa)}function Aa(a,b){return a>b?1:a<b?-1:0};function Ba(a){var b=a.length-1;return 0<=b&&a.indexOf(" ",b)==b}var Ca=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var Da;a:{var Ea=ba.navigator;if(Ea){var Fa=Ea.userAgent;if(Fa){Da=Fa;break a}}Da=""}function q(a){return-1!=Da.indexOf(a)};function Ga(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function Ha(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function Ia(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function Ja(){return q("Firefox")||q("FxiOS")}function Ka(){return(q("Chrome")||q("CriOS"))&&!q("Edge")};function La(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};function Ma(){return q("iPhone")&&!q("iPod")&&!q("iPad")};function Na(a){this.b=a;this.a=0}function Oa(a){a=a.match(Pa);for(var b=0;b<a.length;b++)Qa.test(a[b])&&a.splice(b,1);return new Na(a)}var Pa=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,Qa=/^\s/;function r(a,b){return a.b[a.a+(b||0)]}function t(a){return a.b[a.a++]}function Ra(a){return a.b.length<=a.a};function Sa(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0}Sa.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};Sa.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};Sa.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function Ta(a,b){this.width=a;this.height=b}Ta.prototype.aspectRatio=function(){return this.width/this.height};Ta.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};Ta.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};Ta.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function v(a){return a?new Ua(w(a)):pa||(pa=new Ua)}function Va(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function Wa(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Xa(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Ya(a,b):!c&&Wa(e,b)?-1*Za(a,b):!d&&Wa(f,a)?Za(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=w(a);c=d.createRange();c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);
a.collapse(!0);return c.compareBoundaryPoints(ba.Range.START_TO_END,a)}function Za(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Ya(b,a)}function Ya(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function w(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function $a(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function Ua(a){this.a=a||ba.document||document}
Ua.prototype.getElementsByTagName=function(a,b){return(b||this.a).getElementsByTagName(String(a))};
function x(a,b,c,d){a=d||a.a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))c=a.querySelectorAll(e+(c?"."+c:""));else if(c&&a.getElementsByClassName)if(b=a.getElementsByClassName(c),e){a={};for(var f=d=0,g;g=b[f];f++)e==g.nodeName&&(a[d++]=g);a.length=d;c=a}else c=b;else if(b=a.getElementsByTagName(e||"*"),c){a={};for(f=d=0;g=b[f];f++){e=g.className;var h;if(h="function"==typeof e.split)h=0<=qa(e.split(/\s+/),c);h&&(a[d++]=g)}a.length=d;c=a}else c=b;return c}
;function A(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;c=0;var d=[];for(b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return b}
function ab(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function bb(a,b,c,d,e){return cb.call(null,a,b,ca(c)?c:null,ca(d)?d:null,e||new B)}
function cb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c?(b=b.getElementsByName(d),p(b,function(f){a.a(f)&&e.add(f)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),p(b,function(f){f.className==d&&a.a(f)&&e.add(f)})):a instanceof C?db(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),p(b,function(f){ab(f,c,d)&&e.add(f)}));return e}function db(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)ab(b,c,d)&&a.a(b)&&e.add(b),db(a,b,c,d,e)};function B(){this.b=this.a=null;this.m=0}function eb(a){this.f=a;this.a=this.b=null}function fb(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;)c.f==b.f?(e=c,c=c.a,b=b.a):0<Xa(c.f,b.f)?(e=b,b=b.a):(e=c,c=c.a),(e.b=d)?d.a=e:a.a=e,d=e,f++;for(e=c||b;e;)e.b=d,d=d.a=e,f++,e=e.a;a.b=d;a.m=f;return a}function gb(a,b){b=new eb(b);b.a=a.a;a.b?a.a.b=b:a.a=a.b=b;a.a=b;a.m++}B.prototype.add=function(a){a=new eb(a);a.b=this.b;this.a?this.b.a=a:this.a=this.b=a;this.b=a;this.m++};
function hb(a){return(a=a.a)?a.f:null}function ib(a){return(a=hb(a))?A(a):""}function D(a,b){return new jb(a,!!b)}function jb(a,b){this.f=a;this.b=(this.A=b)?a.b:a.a;this.a=null}function E(a){var b=a.b;if(null==b)return null;var c=a.a=b;a.b=a.A?b.b:b.a;return c.f};function F(a){this.i=a;this.b=this.g=!1;this.f=null}function G(a){return"\n  "+a.toString().split("\n").join("\n  ")}function kb(a,b){a.g=b}function lb(a,b){a.b=b}function H(a,b){a=a.a(b);return a instanceof B?+ib(a):+a}function I(a,b){a=a.a(b);return a instanceof B?ib(a):""+a}function mb(a,b){a=a.a(b);return a instanceof B?!!a.m:!!a};function nb(a,b,c){F.call(this,a.i);this.c=a;this.h=b;this.v=c;this.g=b.g||c.g;this.b=b.b||c.b;this.c==pb&&(c.b||c.g||4==c.i||0==c.i||!b.f?b.b||b.g||4==b.i||0==b.i||!c.f||(this.f={name:c.f.name,B:b}):this.f={name:b.f.name,B:c})}k(nb,F);
function qb(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof B&&c instanceof B){b=D(b);for(d=E(b);d;d=E(b))for(e=D(c),f=E(e);f;f=E(e))if(a(A(d),A(f)))return!0;return!1}if(b instanceof B||c instanceof B){b instanceof B?(e=b,d=c):(e=c,d=b);f=D(e);for(var g=typeof d,h=E(f);h;h=E(f)){switch(g){case "number":h=+A(h);break;case "boolean":h=!!A(h);break;case "string":h=A(h);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(h,d)||e==c&&a(d,h))return!0}return!1}return e?"boolean"==
typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}nb.prototype.a=function(a){return this.c.s(this.h,this.v,a)};nb.prototype.toString=function(){var a="Binary Expression: "+this.c;a+=G(this.h);return a+=G(this.v)};function rb(a,b,c,d){this.aa=a;this.N=b;this.i=c;this.s=d}rb.prototype.toString=function(){return this.aa};var sb={};
function J(a,b,c,d){if(sb.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new rb(a,b,c,d);return sb[a.toString()]=a}J("div",6,1,function(a,b,c){return H(a,c)/H(b,c)});J("mod",6,1,function(a,b,c){return H(a,c)%H(b,c)});J("*",6,1,function(a,b,c){return H(a,c)*H(b,c)});J("+",5,1,function(a,b,c){return H(a,c)+H(b,c)});J("-",5,1,function(a,b,c){return H(a,c)-H(b,c)});J("<",4,2,function(a,b,c){return qb(function(d,e){return d<e},a,b,c)});
J(">",4,2,function(a,b,c){return qb(function(d,e){return d>e},a,b,c)});J("<=",4,2,function(a,b,c){return qb(function(d,e){return d<=e},a,b,c)});J(">=",4,2,function(a,b,c){return qb(function(d,e){return d>=e},a,b,c)});var pb=J("=",3,2,function(a,b,c){return qb(function(d,e){return d==e},a,b,c,!0)});J("!=",3,2,function(a,b,c){return qb(function(d,e){return d!=e},a,b,c,!0)});J("and",2,2,function(a,b,c){return mb(a,c)&&mb(b,c)});J("or",1,2,function(a,b,c){return mb(a,c)||mb(b,c)});function tb(a,b){if(b.a.length&&4!=a.i)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");F.call(this,a.i);this.c=a;this.h=b;this.g=a.g;this.b=a.b}k(tb,F);tb.prototype.a=function(a){a=this.c.a(a);return ub(this.h,a)};tb.prototype.toString=function(){var a="Filter:"+G(this.c);return a+=G(this.h)};function vb(a,b){if(b.length<a.M)throw Error("Function "+a.l+" expects at least"+a.M+" arguments, "+b.length+" given");if(null!==a.H&&b.length>a.H)throw Error("Function "+a.l+" expects at most "+a.H+" arguments, "+b.length+" given");a.$&&p(b,function(c,d){if(4!=c.i)throw Error("Argument "+d+" to function "+a.l+" is not of type Nodeset: "+c);});F.call(this,a.i);this.D=a;this.c=b;kb(this,a.g||ua(b,function(c){return c.g}));lb(this,a.Z&&!b.length||a.Y&&!!b.length||ua(b,function(c){return c.b}))}
k(vb,F);vb.prototype.a=function(a){return this.D.s.apply(null,xa(a,this.c))};vb.prototype.toString=function(){var a="Function: "+this.D;if(this.c.length){var b=ta(this.c,function(c,d){return c+G(d)},"Arguments:");a+=G(b)}return a};function wb(a,b,c,d,e,f,g,h){this.l=a;this.i=b;this.g=c;this.Z=d;this.Y=!1;this.s=e;this.M=f;this.H=void 0!==g?g:f;this.$=!!h}wb.prototype.toString=function(){return this.l};var xb={};
function K(a,b,c,d,e,f,g,h){if(xb.hasOwnProperty(a))throw Error("Function already created: "+a+".");xb[a]=new wb(a,b,c,d,e,f,g,h)}K("boolean",2,!1,!1,function(a,b){return mb(b,a)},1);K("ceiling",1,!1,!1,function(a,b){return Math.ceil(H(b,a))},1);K("concat",3,!1,!1,function(a,b){return ta(ya(arguments,1),function(c,d){return c+I(d,a)},"")},2,null);K("contains",2,!1,!1,function(a,b,c){b=I(b,a);a=I(c,a);return-1!=b.indexOf(a)},2);K("count",1,!1,!1,function(a,b){return b.a(a).m},1,1,!0);
K("false",2,!1,!1,function(){return!1},0);K("floor",1,!1,!1,function(a,b){return Math.floor(H(b,a))},1);K("id",4,!1,!1,function(a,b){var c=a.a,d=9==c.nodeType?c:c.ownerDocument;a=I(b,a).split(/\s+/);var e=[];p(a,function(g){g=d.getElementById(g);!g||0<=qa(e,g)||e.push(g)});e.sort(Xa);var f=new B;p(e,function(g){f.add(g)});return f},1);K("lang",2,!1,!1,function(){return!1},1);K("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);
K("local-name",3,!1,!0,function(a,b){return(a=b?hb(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);K("name",3,!1,!0,function(a,b){return(a=b?hb(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);K("namespace-uri",3,!0,!1,function(){return""},0,1,!0);K("normalize-space",3,!1,!0,function(a,b){return(b?I(b,a):A(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);K("not",2,!1,!1,function(a,b){return!mb(b,a)},1);K("number",1,!1,!0,function(a,b){return b?H(b,a):+A(a.a)},0,1);
K("position",1,!0,!1,function(a){return a.b},0);K("round",1,!1,!1,function(a,b){return Math.round(H(b,a))},1);K("starts-with",2,!1,!1,function(a,b,c){b=I(b,a);a=I(c,a);return 0==b.lastIndexOf(a,0)},2);K("string",3,!1,!0,function(a,b){return b?I(b,a):A(a.a)},0,1);K("string-length",1,!1,!0,function(a,b){return(b?I(b,a):A(a.a)).length},0,1);
K("substring",3,!1,!1,function(a,b,c,d){c=H(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?H(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=I(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);K("substring-after",3,!1,!1,function(a,b,c){b=I(b,a);a=I(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
K("substring-before",3,!1,!1,function(a,b,c){b=I(b,a);a=I(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);K("sum",1,!1,!1,function(a,b){a=D(b.a(a));b=0;for(var c=E(a);c;c=E(a))b+=+A(c);return b},1,1,!0);K("translate",3,!1,!1,function(a,b,c,d){b=I(b,a);c=I(c,a);var e=I(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);K("true",2,!1,!1,function(){return!0},0);function C(a,b){this.h=a;this.c=void 0!==b?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function yb(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}C.prototype.a=function(a){return null===this.b||this.b==a.nodeType};C.prototype.f=function(){return this.h};
C.prototype.toString=function(){var a="Kind Test: "+this.h;null===this.c||(a+=G(this.c));return a};function zb(a){F.call(this,3);this.c=a.substring(1,a.length-1)}k(zb,F);zb.prototype.a=function(){return this.c};zb.prototype.toString=function(){return"Literal: "+this.c};function Ab(a,b){this.l=a.toLowerCase();a="*"==this.l?"*":"http://www.w3.org/1999/xhtml";this.b=b?b.toLowerCase():a}Ab.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=void 0!==a.localName?a.localName:a.nodeName;return"*"!=this.l&&this.l!=b.toLowerCase()?!1:"*"==this.b?!0:this.b==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Ab.prototype.f=function(){return this.l};
Ab.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.b?"":this.b+":")+this.l};function Bb(a){F.call(this,1);this.c=a}k(Bb,F);Bb.prototype.a=function(){return this.c};Bb.prototype.toString=function(){return"Number: "+this.c};function Cb(a,b){F.call(this,a.i);this.h=a;this.c=b;this.g=a.g;this.b=a.b;1==this.c.length&&(a=this.c[0],a.G||a.c!=Db||(a=a.v,"*"!=a.f()&&(this.f={name:a.f(),B:null})))}k(Cb,F);function Eb(){F.call(this,4)}k(Eb,F);Eb.prototype.a=function(a){var b=new B;a=a.a;9==a.nodeType?b.add(a):b.add(a.ownerDocument);return b};Eb.prototype.toString=function(){return"Root Helper Expression"};function Fb(){F.call(this,4)}k(Fb,F);Fb.prototype.a=function(a){var b=new B;b.add(a.a);return b};Fb.prototype.toString=function(){return"Context Helper Expression"};
function Gb(a){return"/"==a||"//"==a}Cb.prototype.a=function(a){var b=this.h.a(a);if(!(b instanceof B))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.m;c++){var e=a[c],f=D(b,e.c.A);if(e.g||e.c!=Hb)if(e.g||e.c!=Ib){var g=E(f);for(b=e.a(new oa(g));null!=(g=E(f));)g=e.a(new oa(g)),b=fb(b,g)}else g=E(f),b=e.a(new oa(g));else{for(g=E(f);(b=E(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new oa(g))}}return b};
Cb.prototype.toString=function(){var a="Path Expression:"+G(this.h);if(this.c.length){var b=ta(this.c,function(c,d){return c+G(d)},"Steps:");a+=G(b)}return a};function Jb(a,b){this.a=a;this.A=!!b}
function ub(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=D(b),f=b.m,g,h=0;g=E(e);h++){var n=a.A?f-h:h+1;g=d.a(new oa(g,n,f));if("number"==typeof g)n=n==g;else if("string"==typeof g||"boolean"==typeof g)n=!!g;else if(g instanceof B)n=0<g.m;else throw Error("Predicate.evaluate returned an unexpected type.");if(!n){n=e;g=n.f;var u=n.a;if(!u)throw Error("Next must be called at least once before remove.");var l=u.b;u=u.a;l?l.a=u:g.a=u;u?u.b=l:g.b=l;g.m--;n.a=null}}return b}
Jb.prototype.toString=function(){return ta(this.a,function(a,b){return a+G(b)},"Predicates:")};function L(a,b,c,d){F.call(this,4);this.c=a;this.v=b;this.h=c||new Jb([]);this.G=!!d;b=this.h;b=0<b.a.length?b.a[0].f:null;a.da&&b&&(this.f={name:b.name,B:b.B});a:{a=this.h;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.g||1==c.i||0==c.i){a=!0;break a}a=!1}this.g=a}k(L,F);
L.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.B?I(c.B,a):null,f=1);if(this.G)if(this.g||this.c!=Kb)if(b=D((new L(Lb,new C("node"))).a(a)),c=E(b))for(a=this.s(c,d,e,f);null!=(c=E(b));)a=fb(a,this.s(c,d,e,f));else a=new B;else a=bb(this.v,b,d,e),a=ub(this.h,a,f);else a=this.s(a.a,d,e,f);return a};L.prototype.s=function(a,b,c,d){a=this.c.D(this.v,a,b,c);return a=ub(this.h,a,d)};
L.prototype.toString=function(){var a="Step:"+G("Operator: "+(this.G?"//":"/"));this.c.l&&(a+=G("Axis: "+this.c));a+=G(this.v);if(this.h.a.length){var b=ta(this.h.a,function(c,d){return c+G(d)},"Predicates:");a+=G(b)}return a};function Mb(a,b,c,d){this.l=a;this.D=b;this.A=c;this.da=d}Mb.prototype.toString=function(){return this.l};var Nb={};function M(a,b,c,d){if(Nb.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new Mb(a,b,c,!!d);return Nb[a]=b}
M("ancestor",function(a,b){for(var c=new B;b=b.parentNode;)a.a(b)&&gb(c,b);return c},!0);M("ancestor-or-self",function(a,b){var c=new B;do a.a(b)&&gb(c,b);while(b=b.parentNode);return c},!0);
var Db=M("attribute",function(a,b){var c=new B,d=a.f();if(b=b.attributes)if(a instanceof C&&null===a.b||"*"==d)for(a=0;d=b[a];a++)c.add(d);else(d=b.getNamedItem(d))&&c.add(d);return c},!1),Kb=M("child",function(a,b,c,d,e){c=ca(c)?c:null;d=ca(d)?d:null;e=e||new B;for(b=b.firstChild;b;b=b.nextSibling)ab(b,c,d)&&a.a(b)&&e.add(b);return e},!1,!0);M("descendant",bb,!1,!0);
var Lb=M("descendant-or-self",function(a,b,c,d){var e=new B;ab(b,c,d)&&a.a(b)&&e.add(b);return bb(a,b,c,d,e)},!1,!0),Hb=M("following",function(a,b,c,d){var e=new B;do for(var f=b;f=f.nextSibling;)ab(f,c,d)&&a.a(f)&&e.add(f),e=bb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);M("following-sibling",function(a,b){for(var c=new B;b=b.nextSibling;)a.a(b)&&c.add(b);return c},!1);M("namespace",function(){return new B},!1);
var Ob=M("parent",function(a,b){var c=new B;if(9==b.nodeType)return c;if(2==b.nodeType)return c.add(b.ownerElement),c;b=b.parentNode;a.a(b)&&c.add(b);return c},!1),Ib=M("preceding",function(a,b,c,d){var e=new B,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var n=[];for(b=f[g];b=b.previousSibling;)n.unshift(b);for(var u=0,l=n.length;u<l;u++)b=n[u],ab(b,c,d)&&a.a(b)&&e.add(b),e=bb(a,b,c,d,e)}return e},!0,!0);
M("preceding-sibling",function(a,b){for(var c=new B;b=b.previousSibling;)a.a(b)&&gb(c,b);return c},!0);var Pb=M("self",function(a,b){var c=new B;a.a(b)&&c.add(b);return c},!1);function Qb(a){F.call(this,1);this.c=a;this.g=a.g;this.b=a.b}k(Qb,F);Qb.prototype.a=function(a){return-H(this.c,a)};Qb.prototype.toString=function(){return"Unary Expression: -"+G(this.c)};function Rb(a){F.call(this,4);this.c=a;kb(this,ua(this.c,function(b){return b.g}));lb(this,ua(this.c,function(b){return b.b}))}k(Rb,F);Rb.prototype.a=function(a){var b=new B;p(this.c,function(c){c=c.a(a);if(!(c instanceof B))throw Error("Path expression must evaluate to NodeSet.");b=fb(b,c)});return b};Rb.prototype.toString=function(){return ta(this.c,function(a,b){return a+G(b)},"Union Expression:")};function Sb(a,b){this.a=a;this.b=b}function Tb(a){for(var b,c=[];;){N(a,"Missing right hand side of binary expression.");b=Ub(a);var d=t(a.a);if(!d)break;var e=(d=sb[d]||null)&&d.N;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].N;)b=new nb(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new nb(c.pop(),c.pop(),b);return b}function N(a,b){if(Ra(a.a))throw Error(b);}function Vb(a,b){a=t(a.a);if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function Wb(a){a=t(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Xb(a){a=t(a.a);if(2>a.length)throw Error("Unclosed literal string");return new zb(a)}
function Yb(a){var b=[];if(Gb(r(a.a))){var c=t(a.a);var d=r(a.a);if("/"==c&&(Ra(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new Eb;d=new Eb;N(a,"Missing next location step.");c=Zb(a,c);b.push(c)}else{a:{c=r(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":t(a.a);c=Tb(a);N(a,'unclosed "("');Vb(a,")");break;case '"':case "'":c=Xb(a);break;default:if(isNaN(+c))if(!yb(c)&&/(?![0-9])[\w]/.test(d)&&"("==r(a.a,1)){c=t(a.a);
c=xb[c]||null;t(a.a);for(d=[];")"!=r(a.a);){N(a,"Missing function argument list.");d.push(Tb(a));if(","!=r(a.a))break;t(a.a)}N(a,"Unclosed function argument list.");Wb(a);c=new vb(c,d)}else{c=null;break a}else c=new Bb(+t(a.a))}"["==r(a.a)&&(d=new Jb($b(a)),c=new tb(c,d))}if(c)if(Gb(r(a.a)))d=c;else return c;else c=Zb(a,"/"),d=new Fb,b.push(c)}for(;Gb(r(a.a));)c=t(a.a),N(a,"Missing next location step."),c=Zb(a,c),b.push(c);return new Cb(d,b)}
function Zb(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==r(a.a)){var c=new L(Pb,new C("node"));t(a.a);return c}if(".."==r(a.a))return c=new L(Ob,new C("node")),t(a.a),c;if("@"==r(a.a)){var d=Db;t(a.a);N(a,"Missing attribute name")}else if("::"==r(a.a,1)){if(!/(?![0-9])[\w]/.test(r(a.a).charAt(0)))throw Error("Bad token: "+t(a.a));var e=t(a.a);d=Nb[e]||null;if(!d)throw Error("No axis with name: "+e);t(a.a);N(a,"Missing node name")}else d=Kb;e=r(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==
r(a.a,1)){if(!yb(e))throw Error("Invalid node type: "+e);e=t(a.a);if(!yb(e))throw Error("Invalid type name: "+e);Vb(a,"(");N(a,"Bad nodetype");var f=r(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=Xb(a);N(a,"Bad nodetype");Wb(a);e=new C(e,g)}else if(e=t(a.a),f=e.indexOf(":"),-1==f)e=new Ab(e);else{g=e.substring(0,f);if("*"==g)var h="*";else if(h=a.b(g),!h)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new Ab(e,h)}else throw Error("Bad token: "+t(a.a));a=new Jb($b(a),d.A);return c||
new L(d,e,a,"//"==b)}function $b(a){for(var b=[];"["==r(a.a);){t(a.a);N(a,"Missing predicate expression.");var c=Tb(a);b.push(c);N(a,"Unclosed predicate expression.");Vb(a,"]")}return b}function Ub(a){if("-"==r(a.a))return t(a.a),new Qb(Ub(a));var b=Yb(a);if("|"!=r(a.a))a=b;else{for(b=[b];"|"==t(a.a);)N(a,"Missing next union location path."),b.push(Yb(a));a.a.a--;a=new Rb(b)}return a};function ac(a){switch(a.nodeType){case 1:return ma(dc,a);case 9:return ac(a.documentElement);case 11:case 10:case 6:case 12:return ec;default:return a.parentNode?ac(a.parentNode):ec}}function ec(){return null}function dc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?dc(a.parentNode,b):null};function fc(a,b){if(!a.length)throw Error("Empty XPath expression.");a=Oa(a);if(Ra(a))throw Error("Invalid XPath expression.");b?ha(b)||(b=la(b.lookupNamespaceURI,b)):b=function(){return null};var c=Tb(new Sb(a,b));if(!Ra(a))throw Error("Bad token: "+t(a));this.evaluate=function(d,e){d=c.a(new oa(d));return new O(d,e)}}
function O(a,b){if(0==b)if(a instanceof B)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof B))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof B?ib(a):""+a;break;case 1:this.numberValue=a instanceof B?+ib(a):+a;break;case 3:this.booleanValue=a instanceof B?0<a.m:!!a;break;case 4:case 5:case 6:case 7:var c=
D(a);var d=[];for(var e=E(c);e;e=E(c))d.push(e);this.snapshotLength=a.m;this.invalidIteratorState=!1;break;case 8:case 9:this.singleNodeValue=hb(a);break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(g){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return g>=d.length||0>g?null:d[g]}}O.ANY_TYPE=0;
O.NUMBER_TYPE=1;O.STRING_TYPE=2;O.BOOLEAN_TYPE=3;O.UNORDERED_NODE_ITERATOR_TYPE=4;O.ORDERED_NODE_ITERATOR_TYPE=5;O.UNORDERED_NODE_SNAPSHOT_TYPE=6;O.ORDERED_NODE_SNAPSHOT_TYPE=7;O.ANY_UNORDERED_NODE_TYPE=8;O.FIRST_ORDERED_NODE_TYPE=9;function gc(a){this.lookupNamespaceURI=ac(a)}
function hc(a,b){a=a||ba;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=O,c.evaluate=function(d,e,f,g){return(new fc(d,f)).evaluate(e,g)},c.createExpression=function(d,e){return new fc(d,e)},c.createNSResolver=function(d){return new gc(d)}}da("wgxpath.install",hc);da("wgxpath.install",hc);var ic=window;function P(a,b){this.code=a;this.a=R[a]||jc;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}k(P,Error);var jc="unknown error",R={15:"element not selectable",11:"element not visible"};R[31]=jc;R[30]=jc;R[24]="invalid cookie domain";R[29]="invalid element coordinates";R[12]="invalid element state";
R[32]="invalid selector";R[51]="invalid selector";R[52]="invalid selector";R[17]="javascript error";R[405]="unsupported operation";R[34]="move target out of bounds";R[27]="no such alert";R[7]="no such element";R[8]="no such frame";R[23]="no such window";R[28]="script timeout";R[33]="session not created";R[10]="stale element reference";R[21]="timeout";R[25]="unable to set cookie";R[26]="unexpected alert open";R[13]=jc;R[9]="unknown command";var kc=Ja(),lc=Ma()||q("iPod"),mc=q("iPad"),nc=q("Android")&&!(Ka()||Ja()||q("Opera")||q("Silk")),oc=Ka(),pc=q("Safari")&&!(Ka()||q("Coast")||q("Opera")||q("Edge")||q("Edg/")||q("OPR")||Ja()||q("Silk")||q("Android"))&&!(Ma()||q("iPad")||q("iPod"));function qc(a){return(a=a.exec(Da))?a[1]:""}(function(){if(kc)return qc(/Firefox\/([0-9.]+)/);if(oc)return Ma()||q("iPad")||q("iPod")?qc(/CriOS\/([0-9.]+)/):qc(/Chrome\/([0-9.]+)/);if(pc&&!(Ma()||q("iPad")||q("iPod")))return qc(/Version\/([0-9.]+)/);if(lc||mc){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Da);if(a)return a[1]+"."+a[2]}else if(nc)return(a=qc(/Android\s+([0-9.]+)/))?a:qc(/Version\/([0-9.]+)/);return""})();var rc=ba.JSON.stringify;function sc(a){function b(c,d){switch(ea(c)){case "string":case "number":case "boolean":return c;case "function":return c.toString();case "array":return sa(c,function(f){return b(f,d)});case "object":if(0<=d.indexOf(c))throw new P(17,"Recursive object cannot be transferred");if(null!==c&&"nodeType"in c&&(1==c.nodeType||9==c.nodeType)){var e={};e.ELEMENT=tc(c);return e}if(null!==c&&"document"in c)return e={},e.WINDOW=tc(c),e;d.push(c);if(fa(c))return sa(c,function(f){return b(f,d)});c=Ga(c,function(f,
g){return"number"==typeof g||ca(g)});return Ha(c,function(f){return b(f,d)});default:return null}}return b(a,[])}function uc(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.I=na());b.I||(b.I=na());return b}function tc(a){var b=uc(a.ownerDocument),c=Ia(b,function(d){return d==a});c||(c=":wdc:"+b.I++,b[c]=a);return c}
function vc(a,b){a=decodeURIComponent(a);b=b||document;var c=uc(b);if(!(null!==c&&a in c))throw new P(10,"Element does not exist in cache");var d=c[a];if(null!==d&&"setInterval"in d){if(d.closed)throw delete c[a],new P(23,"Window has been closed.");return d}for(var e=d;e;){if(e==b.documentElement)return d;e.host&&11===e.nodeType&&(e=e.host);e=e.parentNode}delete c[a];throw new P(10,"Element is no longer attached to the DOM");};var wc={C:function(a){return!(!a.querySelectorAll||!a.querySelector)},o:function(a,b){if(!a)throw new P(32,"No class name specified");a=Ca(a);if(-1!==a.indexOf(" "))throw new P(32,"Compound class names not permitted");if(wc.C(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new P(32,"An invalid or illegal class name was specified");}a=x(v(b),"*",a,b);return a.length?a[0]:null},j:function(a,b){if(!a)throw new P(32,"No class name specified");a=Ca(a);if(-1!==a.indexOf(" "))throw new P(32,
"Compound class names not permitted");if(wc.C(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new P(32,"An invalid or illegal class name was specified");}return x(v(b),"*",a,b)}};var xc={o:function(a,b){ha(b.querySelector);if(!a)throw new P(32,"No selector specified");a=Ca(a);try{var c=b.querySelector(a)}catch(d){throw new P(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},j:function(a,b){ha(b.querySelectorAll);if(!a)throw new P(32,"No selector specified");a=Ca(a);try{return b.querySelectorAll(a)}catch(c){throw new P(32,"An invalid or illegal selector was specified");}}};var yc={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var zc="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Ac=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Bc=/^#(?:[0-9a-f]{3}){1,2}$/i,Cc=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Dc=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function Ec(a,b){b=b.toLowerCase();return"style"==b?Fc(a.style.cssText):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var Gc=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;function Fc(a){var b=[];p(a.split(Gc),function(c){var d=c.indexOf(":");0<d&&(c=[c.slice(0,d),c.slice(d+1)],2==c.length&&b.push(c[0].toLowerCase(),":",c[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}
function S(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};function Hc(a,b,c,d){this.c=a;this.a=b;this.b=c;this.f=d}Hc.prototype.ceil=function(){this.c=Math.ceil(this.c);this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.f=Math.ceil(this.f);return this};Hc.prototype.floor=function(){this.c=Math.floor(this.c);this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.f=Math.floor(this.f);return this};Hc.prototype.round=function(){this.c=Math.round(this.c);this.a=Math.round(this.a);this.b=Math.round(this.b);this.f=Math.round(this.f);return this};function T(a,b,c,d){this.a=a;this.b=b;this.width=c;this.height=d}T.prototype.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};T.prototype.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
T.prototype.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Ic="function"===typeof ShadowRoot;function Jc(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return S(a)?a:null}
function U(a,b){b=La(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b="cssFloat";a:{var c=b;var d=w(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||Kc(a,b);if(null===a)a=null;else if(0<=qa(zc,b)){b:{var e=a.match(Cc);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d&&0<=e&&1>=e)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(Dc))if(b=Number(d[1]),
c=Number(d[2]),d=Number(d[3]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=yc[b.toLowerCase()];if(!c&&(c="#"==b.charAt(0)?b:"#"+b,4==c.length&&(c=c.replace(Ac,"#$1$1$2$2$3$3")),!Bc.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function Kc(a,b){var c=a.currentStyle||a.style,d=c[b];void 0===d&&ha(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?void 0!==d?d:null:(a=Jc(a))?Kc(a,b):null}
function Lc(a,b,c){function d(g){var h=V(g);return 0<h.height&&0<h.width?!0:S(g,"PATH")&&(0<h.height||0<h.width)?(g=U(g,"stroke-width"),!!g&&0<parseInt(g,10)):"hidden"!=U(g,"overflow")&&ua(g.childNodes,function(n){return 3==n.nodeType||S(n)&&d(n)})}function e(g){return Mc(g)==W&&va(g.childNodes,function(h){return!S(h)||e(h)||!d(h)})}if(!S(a))throw Error("Argument to isShown must be of type Element");if(S(a,"BODY"))return!0;if(S(a,"OPTION")||S(a,"OPTGROUP"))return a=$a(a,function(g){return S(g,"SELECT")}),
!!a&&Lc(a,!0,c);var f=Nc(a);if(f)return!!f.image&&0<f.rect.width&&0<f.rect.height&&Lc(f.image,b,c);if(S(a,"INPUT")&&"hidden"==a.type.toLowerCase()||S(a,"NOSCRIPT"))return!1;f=U(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||0!=Oc(a))&&d(a)?!e(a):!1}
function Pc(a){function b(c){if(S(c)&&"none"==U(c,"display"))return!1;var d;if((d=c.parentNode)&&d.shadowRoot&&void 0!==c.assignedSlot)d=c.assignedSlot?c.assignedSlot.parentNode:null;else if(c.getDestinationInsertionPoints){var e=c.getDestinationInsertionPoints();0<e.length&&(d=e[e.length-1])}if(Ic&&d instanceof ShadowRoot){if(d.host.shadowRoot&&d.host.shadowRoot!==d)return!1;d=d.host}return!d||9!=d.nodeType&&11!=d.nodeType?d&&S(d,"DETAILS")&&!d.open&&!S(c,"SUMMARY")?!1:!!d&&b(d):!0}return Lc(a,!1,
b)}var W="hidden";
function Mc(a){function b(m){function y(ob){if(ob==g)return!0;var bc=U(ob,"display");return 0==bc.lastIndexOf("inline",0)||"contents"==bc||"absolute"==cc&&"static"==U(ob,"position")?!1:!0}var cc=U(m,"position");if("fixed"==cc)return u=!0,m==g?null:g;for(m=Jc(m);m&&!y(m);)m=Jc(m);return m}function c(m){var y=m;if("visible"==n)if(m==g&&h)y=h;else if(m==h)return{x:"visible",y:"visible"};y={x:U(y,"overflow-x"),y:U(y,"overflow-y")};m==g&&(y.x="visible"==y.x?"auto":y.x,y.y="visible"==y.y?"auto":y.y);return y}
function d(m){if(m==g){var y=(new Ua(f)).a;m=y.scrollingElement?y.scrollingElement:y.body||y.documentElement;y=y.parentWindow||y.defaultView;m=new Sa(y.pageXOffset||m.scrollLeft,y.pageYOffset||m.scrollTop)}else m=new Sa(m.scrollLeft,m.scrollTop);return m}var e=Qc(a),f=w(a),g=f.documentElement,h=f.body,n=U(g,"overflow"),u;for(a=b(a);a;a=b(a)){var l=c(a);if("visible"!=l.x||"visible"!=l.y){var z=V(a);if(0==z.width||0==z.height)return W;var Q=e.a<z.a,aa=e.b<z.b;if(Q&&"hidden"==l.x||aa&&"hidden"==l.y)return W;
if(Q&&"visible"!=l.x||aa&&"visible"!=l.y){Q=d(a);aa=e.b<z.b-Q.y;if(e.a<z.a-Q.x&&"visible"!=l.x||aa&&"visible"!=l.x)return W;e=Mc(a);return e==W?W:"scroll"}Q=e.f>=z.a+z.width;z=e.c>=z.b+z.height;if(Q&&"hidden"==l.x||z&&"hidden"==l.y)return W;if(Q&&"visible"!=l.x||z&&"visible"!=l.y){if(u&&(l=d(a),e.f>=g.scrollWidth-l.x||e.a>=g.scrollHeight-l.y))return W;e=Mc(a);return e==W?W:"scroll"}}}return"none"}
function V(a){var b=Nc(a);if(b)return b.rect;if(S(a,"HTML"))return a=w(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new Ta(a.clientWidth,a.clientHeight),new T(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new T(0,0,0,0)}return new T(c.left,c.top,c.right-c.left,c.bottom-c.top)}
function Nc(a){var b=S(a,"MAP");if(!b&&!S(a,"AREA"))return null;var c=b?a:S(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=xc.o('*[usemap="#'+c.name+'"]',w(c)))&&(e=V(d),b||"default"==a.shape.toLowerCase()||(a=Rc(a),b=Math.min(Math.max(a.a,0),e.width),c=Math.min(Math.max(a.b,0),e.height),e=new T(b+e.a,c+e.b,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{image:d,rect:e||new T(0,0,0,0)}}
function Rc(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){b=a[0];var c=a[1];return new T(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new T(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){b=a[0];c=a[1];for(var d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new T(b,c,d-b,e-c)}return new T(0,0,0,0)}function Qc(a){a=V(a);return new Hc(a.b,a.a+a.width,a.b+a.height,a.a)}
function Sc(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function Tc(a){var b=[];Ic?Uc(a,b):Vc(a,b);a=sa(b,Sc);return Sc(a.join("\n")).replace(/\xa0/g," ")}
function Wc(a,b,c){if(S(a,"BR"))b.push("");else{var d=S(a,"TD"),e=U(a,"display"),f=!d&&!(0<=qa(Xc,e)),g=void 0!==a.previousElementSibling?a.previousElementSibling:Va(a.previousSibling);g=g?U(g,"display"):"";var h=U(a,"float")||U(a,"cssFloat")||U(a,"styleFloat");!f||"run-in"==g&&"none"==h||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var n=Pc(a),u=null,l=null;n&&(u=U(a,"white-space"),l=U(a,"text-transform"));p(a.childNodes,function(z){c(z,b,n,u,l)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||
Ba(a)||(b[b.length-1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function Vc(a,b){Wc(a,b,function(c,d,e,f,g){3==c.nodeType&&e?Yc(c,d,f,g):S(c)&&Vc(c,d)})}var Xc="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function Yc(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|[^\d\p{L}\p{S}])([\p{Ll}|\p{S}])/gu,function(e,f,g){return f+g.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";Ba(c)&&0==a.lastIndexOf(" ",0)&&(a=a.substr(1));
b.push(c+a)}function Oc(a){var b=1,c=U(a,"opacity");c&&(b=Number(c));(a=Jc(a))&&(b*=Oc(a));return b}
function Zc(a,b,c,d,e){if(3==a.nodeType&&c)Yc(a,b,d,e);else if(S(a))if(S(a,"CONTENT")||S(a,"SLOT")){for(var f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?(f=S(a,"CONTENT")?a.getDistributedNodes():a.assignedNodes(),p(0<f.length?f:a.childNodes,function(g){Zc(g,b,c,d,e)})):Uc(a,b)}else if(S(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)p(a.childNodes,function(g){Zc(g,b,c,d,e)}),a=a.olderShadowRoot}else Uc(a,b)}
function Uc(a,b){a.shadowRoot&&p(a.shadowRoot.childNodes,function(c){Zc(c,b,!0,null,null)});Wc(a,b,function(c,d,e,f,g){var h=null;1==c.nodeType?h=c:3==c.nodeType&&(h=c);null!=h&&(null!=h.assignedSlot||h.getDestinationInsertionPoints&&0<h.getDestinationInsertionPoints().length)||Zc(c,d,e,f,g)})};var $c={C:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},o:function(a,b){var c=v(b),d="string"===typeof a?c.a.getElementById(a):a;return d?Ec(d,"id")==a&&b!=d&&Wa(b,d)?d:wa(x(c,"*"),function(e){return Ec(e,"id")==a&&b!=e&&Wa(b,e)}):null},j:function(a,b){if(!a)return[];if($c.C(b,a))try{return b.querySelectorAll("#"+$c.U(a))}catch(c){return[]}b=x(v(b),"*",null,b);return ra(b,function(c){return Ec(c,"id")==a})},U:function(a){return a.replace(/([\s'"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var X={},ad={};X.O=function(a,b,c){try{var d=xc.j("a",b)}catch(e){d=x(v(b),"A",null,b)}return wa(d,function(e){e=Tc(e);e=e.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=e.indexOf(a)||e==a})};X.L=function(a,b,c){try{var d=xc.j("a",b)}catch(e){d=x(v(b),"A",null,b)}return ra(d,function(e){e=Tc(e);e=e.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=e.indexOf(a)||e==a})};X.o=function(a,b){return X.O(a,b,!1)};X.j=function(a,b){return X.L(a,b,!1)};ad.o=function(a,b){return X.O(a,b,!0)};
ad.j=function(a,b){return X.L(a,b,!0)};var Y={F:function(a,b){return function(c){var d=Y.u(a);d=V(d);c=V(c);return b.call(null,d,c)}},S:function(a){return Y.F(a,function(b,c){return c.b+c.height<b.b})},T:function(a){return Y.F(a,function(b,c){return b.b+b.height<c.b})},W:function(a){return Y.F(a,function(b,c){return c.a+c.width<b.a})},ba:function(a){return Y.F(a,function(b,c){return b.a+b.width<c.a})},X:function(a,b){var c;b?c=b:"number"==typeof a.distance&&(c=a.distance);c||(c=50);return function(d){var e=Y.u(a);if(e===d)return!1;e=V(e);
d=V(d);e=new T(e.a-c,e.b-c,e.width+2*c,e.height+2*c);return e.a<=d.a+d.width&&d.a<=e.a+e.width&&e.b<=d.b+d.height&&d.b<=e.b+e.height}},u:function(a){if(ia(a)&&1==a.nodeType)return a;if(ha(a))return Y.u(a.call(null));if(ia(a)){var b=bd(a);if(!b)throw new P(7,"No element has been found by "+JSON.stringify(a));return b}throw new P(61,"Selector is of wrong type: "+JSON.stringify(a));}};Y.R={left:Y.W,right:Y.ba,above:Y.S,below:Y.T,near:Y.X};Y.P={left:Y.u,right:Y.u,above:Y.u,below:Y.u,near:Y.u};
Y.V=function(a,b){var c=[];p(a,function(e){e&&va(b,function(f){var g=f.kind,h=Y.R[g];if(!h)throw new P(61,"Cannot find filter suitable for "+g);return h.apply(null,f.args)(e)},null)&&c.push(e)},null);a=b[b.length-1];var d=Y.P[a?a.kind:"unknown"];return d?(a=d.apply(null,a.args))?Y.ca(a,c):c:c};
Y.ca=function(a,b){function c(f){f=V(f);return Math.sqrt(Math.pow(d-(f.a+Math.max(1,f.width)/2),2)+Math.pow(e-(f.b+Math.max(1,f.height)/2),2))}a=V(a);var d=a.a+Math.max(1,a.width)/2,e=a.b+Math.max(1,a.height)/2;za(b,function(f,g){return c(f)-c(g)});return b};Y.o=function(a,b){a=Y.j(a,b);return 0==a.length?null:a[0]};
Y.j=function(a,b){if(!a.hasOwnProperty("root")||!a.hasOwnProperty("filters"))throw new P(61,"Locator not suitable for relative locators: "+JSON.stringify(a));if(!fa(a.filters))throw new P(61,"Targets should be an array: "+JSON.stringify(a));if(S(a.root))b=[a.root];else a:{var c=a.root,d=cd(c);if(d){var e=dd[d];if(e&&ha(e.j)){b=e.j(c[d],b||ic.document);break a}}throw new P(61,"Unsupported locator strategy: "+d);}return 0==b.length?[]:Y.V(b,a.filters)};var ed={o:function(a,b){if(""===a)throw new P(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},j:function(a,b){if(""===a)throw new P(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var Z={};Z.J=function(){var a={ea:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
Z.s=function(a,b,c){var d=w(a);if(!d.documentElement)return null;nc&&hc(d?d.parentWindow||d.defaultView:window);try{for(var e=d.createNSResolver?d.createNSResolver(d.documentElement):Z.J,f={},g=d.getElementsByTagName("*"),h=0;h<g.length;++h){var n=g[h],u=n.namespaceURI;if(u&&!f[u]){var l=n.lookupPrefix(u);if(!l){var z=u.match(".*/(\\w+)/?$");l=z?z[1]:"xhtml"}f[u]=l}}var Q={},aa;for(aa in f)Q[f[aa]]=aa;e=function(m){return Q[m]||null};try{return d.evaluate(b,a,e,c,null)}catch(m){if("TypeError"===m.name)return e=
d.createNSResolver?d.createNSResolver(d.documentElement):Z.J,d.evaluate(b,a,e,c,null);throw m;}}catch(m){throw new P(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+m);}};Z.K=function(a,b){if(!a||1!=a.nodeType)throw new P(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
Z.o=function(a,b){var c=function(){var d=Z.s(b,a,9);return d?d.singleNodeValue||null:b.selectSingleNode?(d=w(b),d.setProperty&&d.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||Z.K(c,a);return c};
Z.j=function(a,b){var c=function(){var d=Z.s(b,a,7);if(d){for(var e=d.snapshotLength,f=[],g=0;g<e;++g)f.push(d.snapshotItem(g));return f}return b.selectNodes?(d=w(b),d.setProperty&&d.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();p(c,function(d){Z.K(d,a)});return c};var dd={className:wc,"class name":wc,css:xc,"css selector":xc,relative:Y,id:$c,linkText:X,"link text":X,name:{o:function(a,b){b=x(v(b),"*",null,b);return wa(b,function(c){return Ec(c,"name")==a})},j:function(a,b){b=x(v(b),"*",null,b);return ra(b,function(c){return Ec(c,"name")==a})}},partialLinkText:ad,"partial link text":ad,tagName:ed,"tag name":ed,xpath:Z};function cd(a){for(var b in a)if(a.hasOwnProperty(b))return b;return null}
function bd(a,b){var c=cd(a);if(c){var d=dd[c];if(d&&ha(d.o))return d.o(a[c],b||ic.document)}throw new P(61,"Unsupported locator strategy: "+c);};da("_",function(a,b,c,d){var e=bd,f={};f[a]=b;try{var g;d?g=vc(d.WINDOW):g=window;var h=g;var n;c?n=vc(c.ELEMENT,h.document):n=h.document;var u=e(f,n);var l={status:0,value:sc(u)}}catch(z){l={status:null!==z&&"code"in z?z.code:13,value:{message:z.message}}}return rc(l)});; return this._.apply(null,arguments);}).apply(window, arguments);}
