function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var h,l=this||self;var n=void 0;try{n=window}catch(a){n=l};function p(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a){var b=aa(a);return b=="array"||b=="object"&&typeof a.length=="number"};var w=class extends Error{constructor(a,b){super(b||"");this.code=a;this.state=q[a]||t;this.message=b||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(b<0||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}},t="unknown error",q={15:"element not selectable",11:"element not visible"};q[31]=t;q[30]=t;q[24]="invalid cookie domain";q[29]="invalid element coordinates";
q[12]="invalid element state";q[32]="invalid selector";q[51]="invalid selector";q[52]="invalid selector";q[17]="javascript error";q[405]="unsupported operation";q[34]="move target out of bounds";q[27]="no such alert";q[7]="no such element";q[8]="no such frame";q[23]="no such window";q[28]="script timeout";q[33]="session not created";q[10]="stale element reference";q[21]="timeout";q[25]="unable to set cookie";q[26]="unexpected alert open";q[13]=t;q[9]="unknown command";
w.prototype.toString=function(){return this.name+": "+this.message};var ca;(class{constructor(a,b){this.Y=a===da&&b||""}}).prototype.toString=function(){return"Const{"+this.Y+"}"};var da={};function ea(a){var b=a.length-1;return b>=0&&a.indexOf(" ",b)==b}var z=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var ha=class{constructor(a){if(fa!==fa)throw Error("SafeUrl is not meant to be built directly");this.R=a}toString(){return this.R.toString()}},fa={};new ha("about:invalid#zClosurez");new ha("about:blank");var ia={};class ja{constructor(){if(ia!==ia)throw Error("SafeStyle is not meant to be built directly");this.P=""}toString(){return this.P.toString()}}new ja;function ka(a,b){var c={};for(let d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function la(a,b){var c={};for(let d in a)c[d]=b.call(void 0,a[d],d,a);return c}function ma(a){var b=0;for(let c in a)b++;return b}function A(a,b){return a!==null&&b in a}function na(a,b){for(let c in a)if(b.call(void 0,a[c],c,a))return c};var oa={};class pa{constructor(){if(oa!==oa)throw Error("SafeStyleSheet is not meant to be built directly");this.O=""}toString(){return this.O.toString()}}new pa;function qa(){var a=l.navigator;return a&&(a=a.userAgent)?a:""}function C(a){return qa().indexOf(a)!=-1};function ra(){return C("Firefox")||C("FxiOS")}function sa(){return(C("Chrome")||C("CriOS"))&&!C("Edge")||C("Silk")};const ta=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(let c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},D=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){var d=a.length,e=typeof a==="string"?a.split(""):a;for(let f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ua=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,
b,void 0)}:function(a,b){var c=a.length,d=[],e=0,f=typeof a==="string"?a.split(""):a;for(let g=0;g<c;g++)if(g in f){let k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d},E=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){var c=a.length,d=Array(c),e=typeof a==="string"?a.split(""):a;for(let f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},wa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){var c=a.length,
d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},xa=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){var d=a.length,e=typeof a==="string"?a.split(""):a;for(let f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};
function ya(a,b){a:{let c=a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return b<0?null:typeof a==="string"?a.charAt(b):a[b]}function za(a){var b=a.length;if(b>0){let c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]}function Aa(a,b){a.sort(b||Ba)}function Ba(a,b){return a>b?1:a<b?-1:0};var Ca={};class Da{constructor(){var a=l.trustedTypes&&l.trustedTypes.emptyHTML||"";if(Ca!==Ca)throw Error("SafeHtml is not meant to be built directly");this.N=a}toString(){return this.N.toString()}}new Da;function Ea(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};function F(){return C("iPhone")&&!C("iPod")&&!C("iPad")};var Fa=ra(),Ga=F()||C("iPod"),Ha=C("iPad"),Ia=C("Android")&&!(sa()||ra()||C("Opera")||C("Silk")),Ja=sa(),Ka=C("Safari")&&!(sa()||C("Coast")||C("Opera")||C("Edge")||C("Edg/")||C("OPR")||ra()||C("Silk")||C("Android"))&&!(F()||C("iPad")||C("iPod"));function G(a){return(a=a.exec(qa()))?a[1]:""}(function(){if(Fa)return G(/Firefox\/([0-9.]+)/);if(Ja){if(F()||C("iPad")||C("iPod")||C("Macintosh")){var a=G(/CriOS\/([0-9.]+)/);if(a)return a}return G(/Chrome\/([0-9.]+)/)}if(Ka&&!(F()||C("iPad")||C("iPod")))return G(/Version\/([0-9.]+)/);if(Ga||Ha){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(qa()))return a[1]+"."+a[2]}else if(Ia)return(a=G(/Android\s+([0-9.]+)/))?a:G(/Version\/([0-9.]+)/);return""})();function La(){this.o=void 0}
function Ma(a,b,c){if(b==null)c.push("null");else{if(typeof b=="object"){if(Array.isArray(b)){var d=b;b=d.length;c.push("[");var e="";for(var f=0;f<b;f++)c.push(e),e=d[f],Ma(a,a.o?a.o.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],typeof e!="function"&&(c.push(f),Na(d,c),c.push(":"),Ma(a,a.o?a.o.call(b,d,e):e,c),f=","));c.push("}");
return}}switch(typeof b){case "string":Na(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var Oa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\v":"\\u000b"},Ra=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;
function Na(a,b){b.push('"',a.replace(Ra,function(c){var d=Oa[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).slice(1),Oa[c]=d);return d}),'"')};function Sa(a){function b(c,d){switch(aa(c)){case "string":case "number":case "boolean":return c;case "function":return c.toString();case "array":return E(c,function(f){return b(f,d)});case "object":if(d.indexOf(c)>=0)throw new w(17,"Recursive object cannot be transferred");if(A(c,"nodeType")&&(c.nodeType==1||c.nodeType==9)){var e={};c=Ta(c);e.ELEMENT=c;e["element-6066-11e4-a52e-4f735466cecf"]=c;return e}if(A(c,"document"))return e={},e.WINDOW=Ta(c),e;d.push(c);if(ba(c))return E(c,function(f){return b(f,
d)});e=ka(c,function(f,g){return typeof g==="number"||typeof g==="string"});return la(e,function(f){return b(f,d)});default:return null}}return b(a,[])}function Ua(a,b){return Array.isArray(a)?E(a,function(c){return Ua(c,b)}):p(a)?typeof a=="function"?a:A(a,"ELEMENT")?H(a.ELEMENT,b):A(a,"element-6066-11e4-a52e-4f735466cecf")?H(a["element-6066-11e4-a52e-4f735466cecf"],b):A(a,"WINDOW")?H(a.WINDOW,b):la(a,function(c){return Ua(c,b)}):a}
function Va(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.u=Date.now());b.u||(b.u=Date.now());return b}function Wa(a,b){if(A(b,"setInterval"))return!!b.closed;for(;b;){if(b==a.documentElement)return!1;b.host&&b.nodeType===11&&(b=b.host);b=b.parentNode}return!0}function Xa(a){var b=Va(a),c;for(c in b){var d=b[c];d&&typeof d==="object"&&Wa(a,d)&&delete b[c]}}function Ta(a){var b=a.ownerDocument,c=Va(b);ma(c)-1>=200&&Xa(b);b=na(c,function(d){return d==a});b||(b=":wdc:"+c.u++,c[b]=a);return b}
function H(a,b){a=decodeURIComponent(a);b=b||document;var c=Va(b);if(!A(c,a))throw new w(10,"Element does not exist in cache");var d=c[a];if(!Wa(b,d))return d;delete c[a];if(A(d,"setInterval"))throw new w(23,"Window has been closed.");throw new w(10,"Element is no longer attached to the DOM");};function I(a,b){this.x=a!==void 0?a:0;this.y=b!==void 0?b:0}h=I.prototype;h.clone=function(){return new I(this.x,this.y)};h.toString=function(){return"("+this.x+", "+this.y+")"};h.equals=function(a){return a instanceof I&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};h.translate=function(a,b){a instanceof I?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),typeof b==="number"&&(this.y+=b));return this};h.scale=function(a,b){this.x*=a;this.y*=typeof b==="number"?b:a;return this};function Ya(a,b){this.width=a;this.height=b}h=Ya.prototype;h.clone=function(){return new Ya(this.width,this.height)};h.toString=function(){return"("+this.width+" x "+this.height+")"};h.aspectRatio=function(){return this.width/this.height};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};h.scale=function(a,b){this.width*=a;this.height*=typeof b==="number"?b:a;return this};function J(a){return a?new Za(K(a)):ca||=new Za}function $a(a,b){return typeof b==="string"?a.getElementById(b):b}function ab(a,b,c){function d(k){k&&b.appendChild(typeof k==="string"?a.createTextNode(k):k)}for(var e=1;e<c.length;e++){var f=c[e];if(!ba(f)||p(f)&&f.nodeType>0)d(f);else{a:{if(f&&typeof f.length=="number"){if(p(f)){var g=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){g=typeof f.item=="function";break a}}g=!1}D(g?za(f):f,d)}}}
function bb(a){for(;a&&a.nodeType!=1;)a=a.previousSibling;return a}function cb(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function K(a){return a.nodeType==9?a:a.ownerDocument||a.document}function db(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}
function Za(a){this.l=a||l.document||document}h=Za.prototype;h.getElementsByTagName=function(a,b){return(b||this.l).getElementsByTagName(String(a))};
function L(a,b,c,d){a=a.l;d=d||a;var e=b&&b!="*"?String(b).toUpperCase():"";if(d.querySelectorAll&&d.querySelector&&(e||c))c=d.querySelectorAll(e+(c?"."+c:""));else if(c&&d.getElementsByClassName)if(b=d.getElementsByClassName(c),e){d={};for(var f=a=0,g;g=b[f];f++)e==g.nodeName&&(d[a++]=g);d.length=a;c=d}else c=b;else if(b=d.getElementsByTagName(e||"*"),c){d={};for(f=a=0;g=b[f];f++){e=g.className;var k;if(k=typeof e.split=="function")k=ta(e.split(/\s+/),c)>=0;k&&(d[a++]=g)}d.length=a;c=d}else c=b;
return c}h.createElement=function(a){var b=this.l;a=String(a);b.contentType==="application/xhtml+xml"&&(a=a.toLowerCase());return b.createElement(a)};h.createTextNode=function(a){return this.l.createTextNode(String(a))};h.appendChild=function(a,b){a.appendChild(b)};h.append=function(a,b){ab(K(a),a,arguments)};h.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
h.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};h.contains=cb;var eb={m:function(a){return!(!a.querySelectorAll||!a.querySelector)},i:function(a,b){if(!a)throw new w(32,"No class name specified");a=z(a);if(a.indexOf(" ")!==-1)throw new w(32,"Compound class names not permitted");if(eb.m(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new w(32,"An invalid or illegal class name was specified");}a=L(J(b),"*",a,b);return a.length?a[0]:null},g:function(a,b){if(!a)throw new w(32,"No class name specified");a=z(a);if(a.indexOf(" ")!==-1)throw new w(32,
"Compound class names not permitted");if(eb.m(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new w(32,"An invalid or illegal class name was specified");}return L(J(b),"*",a,b)}};var N={i:function(a,b){if(!a)throw new w(32,"No selector specified");a=z(a);try{var c=b.querySelector(a)}catch(d){throw new w(32,"An invalid or illegal selector was specified");}return c&&c.nodeType==1?c:null},g:function(a,b){if(!a)throw new w(32,"No selector specified");a=z(a);try{return b.querySelectorAll(a)}catch(c){throw new w(32,"An invalid or illegal selector was specified");}}};var fb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var gb="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),hb=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,ib=/^#(?:[0-9a-f]{3}){1,2}$/i,jb=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,kb=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function O(a,b){b=b.toLowerCase();return b=="style"?lb(a.style.cssText):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var mb=RegExp("[;]+(?=(?:(?:[^\"]*\"){2})*[^\"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\\([^()]*\\))*[^()]*$)");function lb(a){var b=[];D(a.split(mb),function(c){var d=c.indexOf(":");d>0&&(c=[c.slice(0,d),c.slice(d+1)],c.length==2&&b.push(c[0].toLowerCase(),":",c[1],";"))});a=b.join("");return a.charAt(a.length-1)==";"?a:a+";"}
function P(a,b){b&&typeof b!=="string"&&(b=b.toString());return a instanceof HTMLFormElement?!!a&&a.nodeType==1&&(!b||"FORM"==b):!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)};function nb(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}h=nb.prototype;h.clone=function(){return new nb(this.top,this.right,this.bottom,this.left)};h.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};h.contains=function(a){return this&&a?a instanceof nb?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
h.expand=function(a,b,c,d){p(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=Number(b),this.bottom+=Number(c),this.left-=Number(d));return this};h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
h.translate=function(a,b){a instanceof I?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,typeof b==="number"&&(this.top+=b,this.bottom+=b));return this};h.scale=function(a,b){b=typeof b==="number"?b:a;this.left*=a;this.right*=a;this.top*=b;this.bottom*=b;return this};var Q=class{constructor(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}};h=Q.prototype;h.clone=function(){return new Q(this.left,this.top,this.width,this.height)};h.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
h.intersection=function(a){var b=Math.max(this.left,a.left),c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top);a=Math.min(this.top+this.height,a.top+a.height);if(d<=a)return this.left=b,this.top=d,this.width=c-b,this.height=a-d,!0}return!1};
h.difference=function(a){b:{var b=Math.max(this.left,a.left);var c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top),e=Math.min(this.top+this.height,a.top+a.height);if(d<=e){b=new Q(b,d,c-b,e-d);break b}}b=null}if(b&&b.height&&b.width){b=[];c=this.top;d=this.height;e=this.left+this.width;var f=this.top+this.height,g=a.left+a.width,k=a.top+a.height;a.top>this.top&&(b.push(new Q(this.left,this.top,this.width,a.top-this.top)),c=a.top,d-=a.top-this.top);k<f&&(b.push(new Q(this.left,
k,this.width,f-k)),d=k-c);a.left>this.left&&b.push(new Q(this.left,c,a.left-this.left,d));g<e&&b.push(new Q(g,c,e-g,d));a=b}else a=[this.clone()];return a};h.contains=function(a){return a instanceof I?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};h.getSize=function(){return new Ya(this.width,this.height)};
h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.translate=function(a,b){a instanceof I?(this.left+=a.x,this.top+=a.y):(this.left+=a,typeof b==="number"&&(this.top+=b));return this};h.scale=function(a,b){b=typeof b==="number"?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};var ob=typeof ShadowRoot==="function";function pb(a){for(a=a.parentNode;a&&a.nodeType!=1&&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode;return P(a)?a:null}
function R(a,b){b=Ea(b);if(b=="float"||b=="cssFloat"||b=="styleFloat")b="cssFloat";a:{var c=b;var d=K(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||qb(a,b);if(a===null)a=null;else if(ta(gb,b)>=0){b:{var e=a.match(jb);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),b>=0&&b<=255&&c>=0&&c<=255&&d>=0&&d<=255&&e>=0&&e<=1)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(kb))if(b=Number(d[1]),
c=Number(d[2]),d=Number(d[3]),b>=0&&b<=255&&c>=0&&c<=255&&d>=0&&d<=255){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=fb[b.toLowerCase()];if(!c&&(c=b.charAt(0)=="#"?b:"#"+b,c.length==4&&(c=c.replace(hb,"#$1$1$2$2$3$3")),!ib.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function qb(a,b){var c=a.currentStyle||a.style,d=c[b];d===void 0&&typeof c.getPropertyValue==="function"&&(d=c.getPropertyValue(b));return d!="inherit"?d!==void 0?d:null:(a=pb(a))?qb(a,b):null}
function rb(a,b,c){function d(g){var k=S(g);if(k.height>0&&k.width>0)return!0;if(P(g,"PATH")&&(k.height>0||k.width>0))return g=R(g,"stroke-width"),!!g&&parseInt(g,10)>0;k=R(g,"visibility");return k!="collapse"&&k!="hidden"&&c(g)?R(g,"overflow")!="hidden"&&wa(g.childNodes,function(x){return x.nodeType==3?(x=x.nodeValue,/^[\s]*$/.test(x)&&/[\n\r\t]/.test(x)?!1:!0):P(x)&&d(x)}):!1}function e(g){return sb(g)==T&&xa(g.childNodes,function(k){return!P(k)||e(k)||!d(k)})}if(!P(a))throw Error("Argument to isShown must be of type Element");
if(P(a,"BODY"))return!0;if(P(a,"OPTION")||P(a,"OPTGROUP"))return a=db(a,function(g){return P(g,"SELECT")}),!!a&&rb(a,!0,c);var f=tb(a);if(f)return!!f.image&&f.rect.width>0&&f.rect.height>0&&rb(f.image,b,c);if(P(a,"INPUT")&&a.type.toLowerCase()=="hidden"||P(a,"NOSCRIPT"))return!1;f=R(a,"visibility");return f!="collapse"&&f!="hidden"&&c(a)&&(b||ub(a)!=0)&&d(a)?!e(a):!1}
function vb(a){function b(c){if(P(c)&&(R(c,"display")=="none"||R(c,"content-visibility")=="hidden"))return!1;var d;a:if((d=c.parentNode)&&d.shadowRoot&&c.assignedSlot!==void 0)d=c.assignedSlot?c.assignedSlot.parentNode:null;else if(c.getDestinationInsertionPoints){var e=c.getDestinationInsertionPoints();if(e.length>0){d=e[e.length-1];break a}}if(ob&&d instanceof ShadowRoot){if(d.host.shadowRoot&&d.host.shadowRoot!==d)return!1;d=d.host}return!d||d.nodeType!=9&&d.nodeType!=11?d&&P(d,"DETAILS")&&!d.open&&
!P(c,"SUMMARY")?!1:!!d&&b(d):!0}return rb(a,!1,b)}var T="hidden";
function sb(a){function b(m){function v(va){if(va==g)return!0;var Pa=R(va,"display");return Pa.lastIndexOf("inline",0)==0||Pa=="contents"||Qa=="absolute"&&R(va,"position")=="static"?!1:!0}var Qa=R(m,"position");if(Qa=="fixed")return u=!0,m==g?null:g;for(m=pb(m);m&&!v(m);)m=pb(m);return m}function c(m){var v=m;if(x=="visible")if(m==g&&k)v=k;else if(m==k)return{x:"visible",y:"visible"};v={x:R(v,"overflow-x"),y:R(v,"overflow-y")};m==g&&(v.x=v.x=="visible"?"auto":v.x,v.y=v.y=="visible"?"auto":v.y);return v}
function d(m){if(m==g){var v=(new Za(f)).l;m=v.scrollingElement?v.scrollingElement:v.body||v.documentElement;v=v.parentWindow||v.defaultView;m=new I(v.pageXOffset||m.scrollLeft,v.pageYOffset||m.scrollTop)}else m=new I(m.scrollLeft,m.scrollTop);return m}var e=wb(a),f=K(a),g=f.documentElement,k=f.body,x=R(g,"overflow"),u;for(a=b(a);a;a=b(a)){var r=c(a);if(r.x!="visible"||r.y!="visible"){var y=S(a);if(y.width==0||y.height==0)return T;var B=e.right<y.left,M=e.bottom<y.top;if(B&&r.x=="hidden"||M&&r.y==
"hidden")return T;if(B&&r.x!="visible"||M&&r.y!="visible"){B=d(a);M=e.bottom<y.top-B.y;if(e.right<y.left-B.x&&r.x!="visible"||M&&r.x!="visible")return T;e=sb(a);return e==T?T:"scroll"}B=e.left>=y.left+y.width;y=e.top>=y.top+y.height;if(B&&r.x=="hidden"||y&&r.y=="hidden")return T;if(B&&r.x!="visible"||y&&r.y!="visible"){if(u&&(r=d(a),e.left>=g.scrollWidth-r.x||e.right>=g.scrollHeight-r.y))return T;e=sb(a);return e==T?T:"scroll"}}}return"none"}
function S(a){var b=tb(a);if(b)return b.rect;if(P(a,"HTML"))return a=K(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a=a.compatMode=="CSS1Compat"?a.documentElement:a.body,a=new Ya(a.clientWidth,a.clientHeight),new Q(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new Q(0,0,0,0)}return new Q(c.left,c.top,c.right-c.left,c.bottom-c.top)}
function tb(a){var b=P(a,"MAP");if(!b&&!P(a,"AREA"))return null;var c=b?a:P(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=N.i('*[usemap="#'+c.name+'"]',K(c)))&&(e=S(d),b||a.shape.toLowerCase()=="default"||(a=xb(a),b=Math.min(Math.max(a.left,0),e.width),c=Math.min(Math.max(a.top,0),e.height),e=new Q(b+e.left,c+e.top,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{image:d,rect:e||new Q(0,0,0,0)}}
function xb(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if(b=="rect"&&a.length==4){b=Number(a[0]);var c=Number(a[1]);return new Q(b,c,Number(a[2])-b,Number(a[3])-c)}if(b=="circle"&&a.length==3)return b=Number(a[2]),new Q(Number(a[0])-b,Number(a[1])-b,2*b,2*b);if(b=="poly"&&a.length>2){b=Number(a[0]);c=Number(a[1]);for(var d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,Number(a[f])),d=Math.max(d,Number(a[f])),c=Math.min(c,Number(a[f+1])),e=Math.max(e,Number(a[f+1]));return new Q(b,c,d-b,e-c)}return new Q(0,
0,0,0)}function wb(a){a=S(a);return new nb(a.top,a.left+a.width,a.top+a.height,a.left)}function yb(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function zb(a){var b=[];ob?Ab(a,b):Bb(a,b);a=E(b,yb);return yb(a.join("\n")).replace(/\xa0/g," ")}
function Cb(a,b,c){if(P(a,"BR"))b.push("");else{var d=P(a,"TD"),e=R(a,"display"),f=!d&&!(ta(Db,e)>=0),g=a.previousElementSibling!==void 0?a.previousElementSibling:bb(a.previousSibling);g=g?R(g,"display"):"";var k=R(a,"float")||R(a,"cssFloat")||R(a,"styleFloat");!f||g=="run-in"&&k=="none"||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var x=vb(a),u=null,r=null;x&&(u=R(a,"white-space"),r=R(a,"text-transform"));D(a.childNodes,function(y){c(y,b,x,u,r)});a=b[b.length-1]||"";!d&&e!="table-cell"||!a||
ea(a)||(b[b.length-1]+=" ");f&&e!="run-in"&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function Bb(a,b){Cb(a,b,function(c,d,e,f,g){c.nodeType==3&&e?Eb(c,d,f,g):P(c)&&Bb(c,d)})}var Db="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function Eb(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if(c=="normal"||c=="nowrap")a=a.replace(/\n/g," ");a=c=="pre"||c=="pre-wrap"?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[ \f\t\v\u2028\u2029]+/g," ");d=="capitalize"?(c=/(^|[^'_0-9A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24B6-\u24E9\u0300-\u036F\u1AB0-\u1AFF\u1DC0-\u1DFF])([A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24B6-\u24E9])/g,a=a.replace(c,function(){return arguments[1]+arguments[2].toUpperCase()}),
c=/(^|[^'_0-9A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24B6-\u24E9])([_*])([A-Za-z\u00C0-\u02AF\u1E00-\u1EFF\u24D0-\u24E9])/g,a=a.replace(c,function(){return arguments[1]+arguments[2]+arguments[3].toUpperCase()})):d=="uppercase"?a=a.toUpperCase():d=="lowercase"&&(a=a.toLowerCase());c=b.pop()||"";ea(c)&&a.lastIndexOf(" ",0)==0&&(a=a.substr(1));b.push(c+a)}function ub(a){var b=1,c=R(a,"opacity");c&&(b=Number(c));(a=pb(a))&&(b*=ub(a));return b}
function Fb(a,b,c,d,e){if(a.nodeType==3&&c)Eb(a,b,d,e);else if(P(a))if(P(a,"CONTENT")||P(a,"SLOT")){for(var f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?(f=P(a,"CONTENT")?a.getDistributedNodes():a.assignedNodes(),D(f.length>0?f:a.childNodes,function(g){Fb(g,b,c,d,e)})):Ab(a,b)}else if(P(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)D(a.childNodes,function(g){Fb(g,b,c,d,e)}),a=a.olderShadowRoot}else Ab(a,b)}
function Ab(a,b){if(a.shadowRoot){var c=R(a,"white-space"),d=R(a,"text-transform");D(a.shadowRoot.childNodes,function(e){Fb(e,b,!0,c,d)})}Cb(a,b,function(e,f,g,k,x){var u=null;e.nodeType==1?u=e:e.nodeType==3&&(u=e);u!=null&&(u.assignedSlot!=null||u.getDestinationInsertionPoints&&u.getDestinationInsertionPoints().length>0)||Fb(e,f,g,k,x)})};var Gb={m:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},i:function(a,b){var c=J(b),d=$a(c.l,a);return d?O(d,"id")==a&&b!=d&&cb(b,d)?d:ya(L(c,"*"),function(e){return O(e,"id")==a&&b!=e&&cb(b,e)}):null},g:function(a,b){if(!a)return[];if(Gb.m(b,a))try{return b.querySelectorAll("#"+Gb.J(a))}catch(c){return[]}b=L(J(b),"*",null,b);return ua(b,function(c){return O(c,"id")==a})},J:function(a){return a.replace(/([\s'"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,"\\$1")}};var U={},Hb={};U.D=function(a,b,c){try{var d=N.g("a",b)}catch(e){d=L(J(b),"A",null,b)}return ya(d,function(e){e=zb(e);e=e.replace(/^[\s]+|[\s]+$/g,"");return c&&e.indexOf(a)!=-1||e==a})};U.C=function(a,b,c){try{var d=N.g("a",b)}catch(e){d=L(J(b),"A",null,b)}return ua(d,function(e){e=zb(e);e=e.replace(/^[\s]+|[\s]+$/g,"");return c&&e.indexOf(a)!=-1||e==a})};U.i=function(a,b){return U.D(a,b,!1)};U.g=function(a,b){return U.C(a,b,!1)};Hb.i=function(a,b){return U.D(a,b,!0)};
Hb.g=function(a,b){return U.C(a,b,!0)};var V={j:function(a,b){return function(c){var d=V.h(a);d=S(d);c=S(c);return b.call(null,d,c)}},H:function(a){return V.j(a,function(b,c){return c.top+c.height<=b.top})},I:function(a){return V.j(a,function(b,c){return c.top>=b.top+b.height})},L:function(a){return V.j(a,function(b,c){return c.left+c.width<=b.left})},S:function(a){return V.j(a,function(b,c){return c.left>=b.left+b.width})},U:function(a){return V.j(a,function(b,c){return c.left<b.left+b.width&&c.left+c.width>b.left&&c.top+c.height<=b.top})},
V:function(a){return V.j(a,function(b,c){return c.left<b.left+b.width&&c.left+c.width>b.left&&c.top>=b.top+b.height})},W:function(a){return V.j(a,function(b,c){return c.top<b.top+b.height&&c.top+c.height>b.top&&c.left+c.width<=b.left})},X:function(a){return V.j(a,function(b,c){return c.top<b.top+b.height&&c.top+c.height>b.top&&c.left>=b.left+b.width})},M:function(a,b){var c;b?c=b:typeof a.distance==="number"&&(c=a.distance);c||=50;return function(d){var e=V.h(a);if(e===d)return!1;e=S(e);d=S(d);e=
new Q(e.left-c,e.top-c,e.width+c*2,e.height+c*2);return e.left<=d.left+d.width&&d.left<=e.left+e.width&&e.top<=d.top+d.height&&d.top<=e.top+e.height}},h:function(a){if(p(a)&&a.nodeType==1)return a;if(typeof a==="function")return V.h(a.call(null));if(p(a)){var b=Ib(a);if(!b)throw new w(7,"No element has been found by "+JSON.stringify(a));return b}throw new w(61,"Selector is of wrong type: "+JSON.stringify(a));}};
V.G={above:V.H,below:V.I,left:V.L,near:V.M,right:V.S,straightAbove:V.U,straightBelow:V.V,straightLeft:V.W,straightRight:V.X};V.F={above:V.h,below:V.h,left:V.h,near:V.h,right:V.h,straightAbove:V.h,straightBelow:V.h,straightLeft:V.h,straightRight:V.h};
V.K=function(a,b){var c=[];D(a,function(e){e&&xa(b,function(f){var g=f.kind,k=V.G[g];if(!k)throw new w(61,"Cannot find filter suitable for "+g);return k.apply(null,f.args)(e)},null)&&c.push(e)},null);a=b[b.length-1];var d=V.F[a?a.kind:"unknown"];return d?(a=d.apply(null,a.args))?V.T(a,c):c:c};
V.T=function(a,b){function c(f){f=S(f);return Math.sqrt(Math.pow(d-(f.left+Math.max(1,f.width)/2),2)+Math.pow(e-(f.top+Math.max(1,f.height)/2),2))}a=S(a);var d=a.left+Math.max(1,a.width)/2,e=a.top+Math.max(1,a.height)/2;Aa(b,function(f,g){return c(f)-c(g)});return b};V.i=function(a,b){a=V.g(a,b);return a.length==0?null:a[0]};
V.g=function(a,b){if(!a.hasOwnProperty("root")||!a.hasOwnProperty("filters"))throw new w(61,"Locator not suitable for relative locators: "+JSON.stringify(a));if(!ba(a.filters))throw new w(61,"Targets should be an array: "+JSON.stringify(a));if(P(a.root))b=[a.root];else a:{var c=a.root,d=Jb(c);if(d){var e=Kb[d];if(e&&typeof e.g==="function"){b=e.g(c[d],b||n.document);break a}}throw new w(61,"Unsupported locator strategy: "+d);}return b.length==0?[]:V.K(b,a.filters)};var Lb={i:function(a,b){if(a==="")throw new w(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},g:function(a,b){if(a==="")throw new w(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var W={};W.v=function(){var a={Z:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
W.B=function(a,b,c){var d=K(a);if(!d.documentElement)return null;try{for(var e=d.createNSResolver?d.createNSResolver(d.documentElement):W.v,f={},g=d.getElementsByTagName("*"),k=0;k<g.length;++k){var x=g[k],u=x.namespaceURI;if(u&&!f[u]){var r=x.lookupPrefix(u);if(!r){var y=u.match(".*/(\\w+)/?$");r=y?y[1]:"xhtml"}f[u]=r}}var B={},M;for(M in f)B[f[M]]=M;e=function(m){return B[m]||null};try{return d.evaluate(b,a,e,c,null)}catch(m){if(m.name==="TypeError")return e=d.createNSResolver?d.createNSResolver(d.documentElement):
W.v,d.evaluate(b,a,e,c,null);throw m;}}catch(m){throw new w(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+m);}};W.A=function(a,b){if(!a||a.nodeType!=1)throw new w(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
W.i=function(a,b){var c=function(){var d=W.B(b,a,9);return d?d.singleNodeValue||null:b.selectSingleNode?(d=K(b),d.setProperty&&d.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();c!==null&&W.A(c,a);return c};
W.g=function(a,b){var c=function(){var d=W.B(b,a,7);if(d){for(var e=d.snapshotLength,f=[],g=0;g<e;++g)f.push(d.snapshotItem(g));return f}return b.selectNodes?(d=K(b),d.setProperty&&d.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();D(c,function(d){W.A(d,a)});return c};var Kb={className:eb,"class name":eb,css:N,"css selector":N,relative:V,id:Gb,linkText:U,"link text":U,name:{i:function(a,b){b=L(J(b),"*",null,b);return ya(b,function(c){return O(c,"name")==a})},g:function(a,b){b=L(J(b),"*",null,b);return ua(b,function(c){return O(c,"name")==a})}},partialLinkText:Hb,"partial link text":Hb,tagName:Lb,"tag name":Lb,xpath:W};function Jb(a){for(var b in a)if(a.hasOwnProperty(b))return b;return null}
function Ib(a,b){var c=Jb(a);if(c){var d=Kb[c];if(d&&typeof d.i==="function")return d.i(a[c],b||n.document)}throw new w(61,"Unsupported locator strategy: "+c);};function Mb(a,b,c,d){var e=Ib,f={};f[a]=b;try{var g=d?H(d.WINDOW):window;var k=c?Ua(c,g.document):g.document;var x=e(f,k);var u={status:0,value:Sa(x)}}catch(r){u=A(r,"code")?r.code:13,u={status:u,value:{message:r.message,error:q[u]||t}}}a=[];Ma(new La,u,a);return a.join("")}var X=["se_exportedFunctionSymbol"],Y=l;X[0]in Y||typeof Y.execScript=="undefined"||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||Mb===void 0?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=Mb;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
