function(){return function(){var k=this;function l(a){return void 0!==a}function n(a){return"string"==typeof a}function aa(a,b){a=a.split(".");var c=k;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&l(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function da(a){return"function"==ba(a)}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ia(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia=ga:ia=ha;return ia.apply(null,arguments)}
function ja(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ka=Date.now||function(){return+new Date};function p(a,b){function c(){}c.prototype=b.prototype;a.V=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.U=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};function q(a,b){this.code=a;this.a=r[a]||la;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}p(q,Error);var la="unknown error",r={15:"element not selectable",11:"element not visible"};r[31]=la;r[30]=la;r[24]="invalid cookie domain";r[29]="invalid element coordinates";r[12]="invalid element state";
r[32]="invalid selector";r[51]="invalid selector";r[52]="invalid selector";r[17]="javascript error";r[405]="unsupported operation";r[34]="move target out of bounds";r[27]="no such alert";r[7]="no such element";r[8]="no such frame";r[23]="no such window";r[28]="script timeout";r[33]="session not created";r[10]="stale element reference";r[21]="timeout";r[25]="unable to set cookie";r[26]="unexpected alert open";r[13]=la;r[9]="unknown command";q.prototype.toString=function(){return this.name+": "+this.message};var ma=window;var na;function oa(a){var b=a.length-1;return 0<=b&&a.indexOf(" ",b)==b}var pa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function qa(a,b){var c=0;a=pa(String(a)).split(".");b=pa(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;!c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=ra(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||ra(0==f[2].length,0==g[2].length)||ra(f[2],g[2]);f=f[3];g=g[3]}while(!c)}return c}function ra(a,b){return a<b?-1:a>b?1:0}
function sa(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};function ta(a,b){if(n(a))return n(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function v(a,b){for(var c=a.length,d=n(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function ua(a,b){for(var c=a.length,d=[],e=0,f=n(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}
function va(a,b){for(var c=a.length,d=Array(c),e=n(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function wa(a,b,c){var d=c;v(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function xa(a,b){for(var c=a.length,d=n(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function ya(a,b){for(var c=a.length,d=n(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}
function za(a,b){a:{for(var c=a.length,d=n(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:n(a)?a.charAt(b):a[b]}function Ba(a){return Array.prototype.concat.apply([],arguments)}function Ca(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var w;a:{var Da=k.navigator;if(Da){var Ea=Da.userAgent;if(Ea){w=Ea;break a}}w=""}function x(a){return-1!=w.indexOf(a)};function Fa(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function Ga(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function Ha(a,b){return null!==a&&b in a}function Ia(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function Ja(){return(x("Chrome")||x("CriOS"))&&!x("Edge")};function Ka(){return x("iPhone")&&!x("iPod")&&!x("iPad")};function La(a,b){var c=Ma;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Na=x("Opera"),y=x("Trident")||x("MSIE"),Oa=x("Edge"),Pa=x("Gecko")&&!(-1!=w.toLowerCase().indexOf("webkit")&&!x("Edge"))&&!(x("Trident")||x("MSIE"))&&!x("Edge"),Qa=-1!=w.toLowerCase().indexOf("webkit")&&!x("Edge");function Ra(){var a=k.document;return a?a.documentMode:void 0}var Sa;
a:{var Ta="",Ua=function(){var a=w;if(Pa)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Oa)return/Edge\/([\d\.]+)/.exec(a);if(y)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Qa)return/WebKit\/(\S+)/.exec(a);if(Na)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ua&&(Ta=Ua?Ua[1]:"");if(y){var Va=Ra();if(null!=Va&&Va>parseFloat(Ta)){Sa=String(Va);break a}}Sa=Ta}var Ma={};function Wa(a){return La(a,function(){return 0<=qa(Sa,a)})}var z;var Xa=k.document;
z=Xa&&y?Ra()||("CSS1Compat"==Xa.compatMode?parseInt(Sa,10):5):void 0;function Ya(a,b){this.x=l(a)?a:0;this.y=l(b)?b:0}Ya.prototype.toString=function(){return"("+this.x+", "+this.y+")"};Ya.prototype.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};Ya.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};Ya.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function Za(a,b){this.width=a;this.height=b}Za.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};Za.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};Za.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};Za.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function $a(a){return a?new ab(A(a)):na||(na=new ab)}function bb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function cb(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function db(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(y&&!(9<=Number(z))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?eb(a,b):!c&&cb(e,b)?-1*fb(a,b):!d&&cb(f,a)?fb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=A(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(k.Range.START_TO_END,a)}function fb(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return eb(b,a)}function eb(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function A(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function gb(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?c.parentWindow||c.defaultView:window}else d=null;b=d}return b}catch(e){}return null}function hb(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function ab(a){this.a=a||k.document||document}ab.prototype.getElementsByTagName=function(a,b){return(b||this.a).getElementsByTagName(String(a))};
function ib(a,b,c,d){a=d||a.a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))c=a.querySelectorAll(e+(c?"."+c:""));else if(c&&a.getElementsByClassName)if(d=a.getElementsByClassName(c),e){a={};for(var f=b=0,g;g=d[f];f++)e==g.nodeName&&(a[b++]=g);a.length=b;c=a}else c=d;else if(d=a.getElementsByTagName(e||"*"),c){a={};for(f=b=0;g=d[f];f++){var e=g.className,h;if(h="function"==typeof e.split)h=0<=ta(e.split(/\s+/),c);h&&(a[b++]=g)}a.length=b;c=a}else c=d;return c}
;var jb={A:function(a){return!(!a.querySelectorAll||!a.querySelector)},s:function(a,b){if(!a)throw new q(32,"No class name specified");a=pa(a);if(-1!==a.indexOf(" "))throw new q(32,"Compound class names not permitted");if(jb.A(b))try{return b.querySelector("."+a.replace(/\./g,"\\."))||null}catch(c){throw new q(32,"An invalid or illegal class name was specified");}a=ib($a(b),"*",a,b);return a.length?a[0]:null},m:function(a,b){if(!a)throw new q(32,"No class name specified");a=pa(a);if(-1!==a.indexOf(" "))throw new q(32,
"Compound class names not permitted");if(jb.A(b))try{return b.querySelectorAll("."+a.replace(/\./g,"\\."))}catch(c){throw new q(32,"An invalid or illegal class name was specified");}return ib($a(b),"*",a,b)}};var kb=x("Firefox"),lb=Ka()||x("iPod"),mb=x("iPad"),nb=x("Android")&&!(Ja()||x("Firefox")||x("Opera")||x("Silk")),ob=Ja(),pb=x("Safari")&&!(Ja()||x("Coast")||x("Opera")||x("Edge")||x("Silk")||x("Android"))&&!(Ka()||x("iPad")||x("iPod"));function qb(a){return(a=a.exec(w))?a[1]:""}(function(){if(kb)return qb(/Firefox\/([0-9.]+)/);if(y||Oa||Na)return Sa;if(ob)return Ka()||x("iPad")||x("iPod")?qb(/CriOS\/([0-9.]+)/):qb(/Chrome\/([0-9.]+)/);if(pb&&!(Ka()||x("iPad")||x("iPod")))return qb(/Version\/([0-9.]+)/);if(lb||mb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(w);if(a)return a[1]+"."+a[2]}else if(nb)return(a=qb(/Android\s+([0-9.]+)/))?a:qb(/Version\/([0-9.]+)/);return""})();var rb,sb;function tb(a){return ub?rb(a):y?0<=qa(z,a):Wa(a)}
var ub=function(){if(!Pa)return!1;var a=k.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;rb=function(a){return 0<=c.compare(d,""+a)};sb=function(a){c.compare(e,""+a)};return!0}(),vb=y&&!(8<=Number(z)),wb=y&&!(9<=Number(z));nb&&ub&&sb(2.3);nb&&ub&&sb(4);pb&&ub&&sb(6);var xb={s:function(a,b){if(!da(b.querySelector)&&y&&tb(8)&&!ea(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new q(32,"No selector specified");a=pa(a);try{var c=b.querySelector(a)}catch(d){throw new q(32,"An invalid or illegal selector was specified");}return c&&1==c.nodeType?c:null},m:function(a,b){if(!da(b.querySelectorAll)&&y&&tb(8)&&!ea(b.querySelector))throw Error("CSS selection is not supported");if(!a)throw new q(32,"No selector specified");a=pa(a);try{return b.querySelectorAll(a)}catch(c){throw new q(32,
"An invalid or illegal selector was specified");}}};var yb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var zb="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Ab=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Bb=/^#(?:[0-9a-f]{3}){1,2}$/i,Cb=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Db=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function Eb(a,b){b=b.toLowerCase();return"style"==b?Fb(a.style.cssText):vb&&"value"==b&&B(a,"INPUT")?a.value:wb&&!0===a[b]?String(a.getAttribute(b)):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var Gb=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;
function Fb(a){var b=[];v(a.split(Gb),function(a){var c=a.indexOf(":");0<c&&(a=[a.slice(0,c),a.slice(c+1)],2==a.length&&b.push(a[0].toLowerCase(),":",a[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}function B(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function Hb(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var C=y&&!(9<=Number(z)),Ib=y&&!(8<=Number(z));function Jb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Kb(a,b){var c=Ib&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Jb(b,a,b.nodeName,c)};function Lb(a){this.b=a;this.a=0}function Mb(a){a=a.match(Nb);for(var b=0;b<a.length;b++)Ob.test(a[b])&&a.splice(b,1);return new Lb(a)}var Nb=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,Ob=/^\s/;function D(a,b){return a.b[a.a+(b||0)]}function E(a){return a.b[a.a++]}function Pb(a){return a.b.length<=a.a};function F(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(C&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),C&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function Qb(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Ib&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Rb(a,b,c,d,e){return(C?Sb:Tb).call(null,a,b,n(c)?c:null,n(d)?d:null,e||new H)}
function Sb(a,b,c,d,e){if(a instanceof Ub||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;var g=Vb(a);if("*"!=g&&(f=b.getElementsByTagName(g),!f))return e;if(c){var h=[];for(a=0;b=f[a++];)Qb(b,c,d)&&h.push(b);f=h}for(a=0;b=f[a++];)"*"==g&&"!"==b.tagName||I(e,b);return e}Wb(a,b,c,d,e);return e}
function Tb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!y?(b=b.getElementsByName(d),v(b,function(b){a.a(b)&&I(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),v(b,function(b){b.className==d&&a.a(b)&&I(e,b)})):a instanceof J?Wb(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),v(b,function(a){Qb(a,c,d)&&I(e,a)}));return e}
function Xb(a,b,c,d,e){var f;if((a instanceof Ub||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=Vb(a);if("*"!=g&&(f=ua(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=ua(f,function(a){return Qb(a,c,d)}));v(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||I(e,a)});return e}return Yb(a,b,c,d,e)}function Yb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Qb(b,c,d)&&a.a(b)&&I(e,b);return e}
function Wb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Qb(b,c,d)&&a.a(b)&&I(e,b),Wb(a,b,c,d,e)}function Vb(a){if(a instanceof J){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function H(){this.b=this.a=null;this.l=0}function Zb(a){this.node=a;this.a=this.b=null}function $b(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;){e=c.node;var g=b.node;e==g||e instanceof Jb&&g instanceof Jb&&e.a==g.a?(e=c,c=c.a,b=b.a):0<db(c.node,b.node)?(e=b,b=b.a):(e=c,c=c.a);(e.b=d)?d.a=e:a.a=e;d=e;f++}for(e=c||b;e;)e.b=d,d=d.a=e,f++,e=e.a;a.b=d;a.l=f;return a}function ac(a,b){b=new Zb(b);b.a=a.a;a.b?a.a.b=b:a.a=a.b=b;a.a=b;a.l++}
function I(a,b){b=new Zb(b);b.b=a.b;a.a?a.b.a=b:a.a=a.b=b;a.b=b;a.l++}function bc(a){return(a=a.a)?a.node:null}function cc(a){return(a=bc(a))?F(a):""}function dc(a,b){return new ec(a,!!b)}function ec(a,b){this.f=a;this.b=(this.v=b)?a.b:a.a;this.a=null}function K(a){var b=a.b;if(b){var c=a.a=b;a.b=a.v?b.b:b.a;return c.node}return null};function L(a){this.i=a;this.b=this.g=!1;this.f=null}function M(a){return"\n  "+a.toString().split("\n").join("\n  ")}function fc(a,b){a.g=b}function gc(a,b){a.b=b}function N(a,b){a=a.a(b);return a instanceof H?+cc(a):+a}function O(a,b){a=a.a(b);return a instanceof H?cc(a):""+a}function hc(a,b){a=a.a(b);return a instanceof H?!!a.l:!!a};function ic(a,b,c){L.call(this,a.i);this.c=a;this.h=b;this.u=c;this.g=b.g||c.g;this.b=b.b||c.b;this.c==jc&&(c.b||c.g||4==c.i||0==c.i||!b.f?b.b||b.g||4==b.i||0==b.i||!c.f||(this.f={name:c.f.name,w:b}):this.f={name:b.f.name,w:c})}p(ic,L);
function kc(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof H&&c instanceof H){b=dc(b);for(d=K(b);d;d=K(b))for(e=dc(c),f=K(e);f;f=K(e))if(a(F(d),F(f)))return!0;return!1}if(b instanceof H||c instanceof H){b instanceof H?(e=b,d=c):(e=c,d=b);f=dc(e);for(var g=typeof d,h=K(f);h;h=K(f)){switch(g){case "number":h=+F(h);break;case "boolean":h=!!F(h);break;case "string":h=F(h);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(h,d)||e==c&&a(d,h))return!0}return!1}return e?
"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}ic.prototype.a=function(a){return this.c.o(this.h,this.u,a)};ic.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+M(this.h);return a+=M(this.u)};function lc(a,b,c,d){this.S=a;this.L=b;this.i=c;this.o=d}lc.prototype.toString=function(){return this.S};var mc={};
function P(a,b,c,d){if(mc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new lc(a,b,c,d);return mc[a.toString()]=a}P("div",6,1,function(a,b,c){return N(a,c)/N(b,c)});P("mod",6,1,function(a,b,c){return N(a,c)%N(b,c)});P("*",6,1,function(a,b,c){return N(a,c)*N(b,c)});P("+",5,1,function(a,b,c){return N(a,c)+N(b,c)});P("-",5,1,function(a,b,c){return N(a,c)-N(b,c)});P("<",4,2,function(a,b,c){return kc(function(a,b){return a<b},a,b,c)});
P(">",4,2,function(a,b,c){return kc(function(a,b){return a>b},a,b,c)});P("<=",4,2,function(a,b,c){return kc(function(a,b){return a<=b},a,b,c)});P(">=",4,2,function(a,b,c){return kc(function(a,b){return a>=b},a,b,c)});var jc=P("=",3,2,function(a,b,c){return kc(function(a,b){return a==b},a,b,c,!0)});P("!=",3,2,function(a,b,c){return kc(function(a,b){return a!=b},a,b,c,!0)});P("and",2,2,function(a,b,c){return hc(a,c)&&hc(b,c)});P("or",1,2,function(a,b,c){return hc(a,c)||hc(b,c)});function nc(a,b){if(b.a.length&&4!=a.i)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");L.call(this,a.i);this.c=a;this.h=b;this.g=a.g;this.b=a.b}p(nc,L);nc.prototype.a=function(a){a=this.c.a(a);return oc(this.h,a)};nc.prototype.toString=function(){var a="Filter:"+M(this.c);return a+=M(this.h)};function pc(a,b){if(b.length<a.K)throw Error("Function "+a.j+" expects at least"+a.K+" arguments, "+b.length+" given");if(null!==a.D&&b.length>a.D)throw Error("Function "+a.j+" expects at most "+a.D+" arguments, "+b.length+" given");a.R&&v(b,function(b,d){if(4!=b.i)throw Error("Argument "+d+" to function "+a.j+" is not of type Nodeset: "+b);});L.call(this,a.i);this.B=a;this.c=b;fc(this,a.g||xa(b,function(a){return a.g}));gc(this,a.P&&!b.length||a.O&&!!b.length||xa(b,function(a){return a.b}))}
p(pc,L);pc.prototype.a=function(a){return this.B.o.apply(null,Ba(a,this.c))};pc.prototype.toString=function(){var a="Function: "+this.B;if(this.c.length)var b=wa(this.c,function(a,b){return a+M(b)},"Arguments:"),a=a+M(b);return a};function qc(a,b,c,d,e,f,g,h,t){this.j=a;this.i=b;this.g=c;this.P=d;this.O=e;this.o=f;this.K=g;this.D=l(h)?h:g;this.R=!!t}qc.prototype.toString=function(){return this.j};var rc={};
function R(a,b,c,d,e,f,g,h){if(rc.hasOwnProperty(a))throw Error("Function already created: "+a+".");rc[a]=new qc(a,b,c,d,!1,e,f,g,h)}R("boolean",2,!1,!1,function(a,b){return hc(b,a)},1);R("ceiling",1,!1,!1,function(a,b){return Math.ceil(N(b,a))},1);R("concat",3,!1,!1,function(a,b){return wa(Ca(arguments,1),function(b,d){return b+O(d,a)},"")},2,null);R("contains",2,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);return-1!=b.indexOf(a)},2);R("count",1,!1,!1,function(a,b){return b.a(a).l},1,1,!0);
R("false",2,!1,!1,function(){return!1},0);R("floor",1,!1,!1,function(a,b){return Math.floor(N(b,a))},1);R("id",4,!1,!1,function(a,b){function c(a){if(C){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return za(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument;a=O(b,a).split(/\s+/);var f=[];v(a,function(a){a=c(a);!a||0<=ta(f,a)||f.push(a)});f.sort(db);var g=new H;v(f,function(a){I(g,a)});return g},1);
R("lang",2,!1,!1,function(){return!1},1);R("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);R("local-name",3,!1,!0,function(a,b){return(a=b?bc(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);R("name",3,!1,!0,function(a,b){return(a=b?bc(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);R("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
R("normalize-space",3,!1,!0,function(a,b){return(b?O(b,a):F(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);R("not",2,!1,!1,function(a,b){return!hc(b,a)},1);R("number",1,!1,!0,function(a,b){return b?N(b,a):+F(a.a)},0,1);R("position",1,!0,!1,function(a){return a.b},0);R("round",1,!1,!1,function(a,b){return Math.round(N(b,a))},1);R("starts-with",2,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);return!b.lastIndexOf(a,0)},2);R("string",3,!1,!0,function(a,b){return b?O(b,a):F(a.a)},0,1);
R("string-length",1,!1,!0,function(a,b){return(b?O(b,a):F(a.a)).length},0,1);R("substring",3,!1,!1,function(a,b,c,d){c=N(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?N(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=O(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);R("substring-after",3,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
R("substring-before",3,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);R("sum",1,!1,!1,function(a,b){a=dc(b.a(a));b=0;for(var c=K(a);c;c=K(a))b+=+F(c);return b},1,1,!0);R("translate",3,!1,!1,function(a,b,c,d){b=O(b,a);c=O(c,a);var e=O(d,a);d={};for(var f=0;f<c.length;f++)a=c.charAt(f),a in d||(d[a]=e.charAt(f));c="";for(f=0;f<b.length;f++)a=b.charAt(f),c+=a in d?d[a]:a;return c},3);R("true",2,!1,!1,function(){return!0},0);function J(a,b){this.h=a;this.c=l(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function sc(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}J.prototype.a=function(a){return null===this.b||this.b==a.nodeType};J.prototype.f=function(){return this.h};
J.prototype.toString=function(){var a="Kind Test: "+this.h;null===this.c||(a+=M(this.c));return a};function tc(a){L.call(this,3);this.c=a.substring(1,a.length-1)}p(tc,L);tc.prototype.a=function(){return this.c};tc.prototype.toString=function(){return"Literal: "+this.c};function Ub(a,b){this.j=a.toLowerCase();a="*"==this.j?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():a}Ub.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=l(a.localName)?a.localName:a.nodeName;return"*"!=this.j&&this.j!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Ub.prototype.f=function(){return this.j};
Ub.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.j};function uc(a){L.call(this,1);this.c=a}p(uc,L);uc.prototype.a=function(){return this.c};uc.prototype.toString=function(){return"Number: "+this.c};function vc(a,b){L.call(this,a.i);this.h=a;this.c=b;this.g=a.g;this.b=a.b;1==this.c.length&&(a=this.c[0],a.C||a.c!=wc||(a=a.u,"*"!=a.f()&&(this.f={name:a.f(),w:null})))}p(vc,L);function xc(){L.call(this,4)}p(xc,L);xc.prototype.a=function(a){var b=new H;a=a.a;9==a.nodeType?I(b,a):I(b,a.ownerDocument);return b};xc.prototype.toString=function(){return"Root Helper Expression"};function yc(){L.call(this,4)}p(yc,L);yc.prototype.a=function(a){var b=new H;I(b,a.a);return b};yc.prototype.toString=function(){return"Context Helper Expression"};
function zc(a){return"/"==a||"//"==a}vc.prototype.a=function(a){var b=this.h.a(a);if(!(b instanceof H))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.l;c++){var e=a[c],f=dc(b,e.c.v);if(e.g||e.c!=Ac)if(e.g||e.c!=Bc){var g=K(f);for(b=e.a(new Hb(g));g=K(f);)g=e.a(new Hb(g)),b=$b(b,g)}else g=K(f),b=e.a(new Hb(g));else{for(g=K(f);(b=K(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new Hb(g))}}return b};
vc.prototype.toString=function(){var a="Path Expression:"+M(this.h);if(this.c.length){var b=wa(this.c,function(a,b){return a+M(b)},"Steps:");a+=M(b)}return a};function Cc(a,b){this.a=a;this.v=!!b}
function oc(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=dc(b),f=b.l,g,h=0;g=K(e);h++){var t=a.v?f-h:h+1;g=d.a(new Hb(g,t,f));if("number"==typeof g)t=t==g;else if("string"==typeof g||"boolean"==typeof g)t=!!g;else if(g instanceof H)t=0<g.l;else throw Error("Predicate.evaluate returned an unexpected type.");if(!t){t=e;g=t.f;var u=t.a;if(!u)throw Error("Next must be called at least once before remove.");var m=u.b,u=u.a;m?m.a=u:g.a=u;u?u.b=m:g.b=m;g.l--;t.a=null}}return b}
Cc.prototype.toString=function(){return wa(this.a,function(a,b){return a+M(b)},"Predicates:")};function Dc(a,b,c,d){L.call(this,4);this.c=a;this.u=b;this.h=c||new Cc([]);this.C=!!d;b=this.h;b=0<b.a.length?b.a[0].f:null;a.T&&b&&(a=b.name,a=C?a.toLowerCase():a,this.f={name:a,w:b.w});a:{a=this.h;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.g||1==c.i||0==c.i){a=!0;break a}a=!1}this.g=a}p(Dc,L);
Dc.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.w?O(c.w,a):null,f=1);if(this.C)if(this.g||this.c!=Ec)if(b=dc((new Dc(Fc,new J("node"))).a(a)),c=K(b))for(a=this.o(c,d,e,f);c=K(b);)a=$b(a,this.o(c,d,e,f));else a=new H;else a=Rb(this.u,b,d,e),a=oc(this.h,a,f);else a=this.o(a.a,d,e,f);return a};Dc.prototype.o=function(a,b,c,d){a=this.c.B(this.u,a,b,c);return a=oc(this.h,a,d)};
Dc.prototype.toString=function(){var a="Step:"+M("Operator: "+(this.C?"//":"/"));this.c.j&&(a+=M("Axis: "+this.c));a+=M(this.u);if(this.h.a.length){var b=wa(this.h.a,function(a,b){return a+M(b)},"Predicates:");a+=M(b)}return a};function Gc(a,b,c,d){this.j=a;this.B=b;this.v=c;this.T=d}Gc.prototype.toString=function(){return this.j};var Hc={};function S(a,b,c,d){if(Hc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new Gc(a,b,c,!!d);return Hc[a]=b}
S("ancestor",function(a,b){for(var c=new H;b=b.parentNode;)a.a(b)&&ac(c,b);return c},!0);S("ancestor-or-self",function(a,b){var c=new H;do a.a(b)&&ac(c,b);while(b=b.parentNode);return c},!0);
var wc=S("attribute",function(a,b){var c=new H,d=a.f();if("style"==d&&C&&b.style)return I(c,new Jb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof J&&null===a.b||"*"==d)for(d=0;a=e[d];d++)C?a.nodeValue&&I(c,Kb(b,a)):I(c,a);else(a=e.getNamedItem(d))&&(C?a.nodeValue&&I(c,Kb(b,a)):I(c,a));return c},!1),Ec=S("child",function(a,b,c,d,e){return(C?Xb:Yb).call(null,a,b,n(c)?c:null,n(d)?d:null,e||new H)},!1,!0);S("descendant",Rb,!1,!0);
var Fc=S("descendant-or-self",function(a,b,c,d){var e=new H;Qb(b,c,d)&&a.a(b)&&I(e,b);return Rb(a,b,c,d,e)},!1,!0),Ac=S("following",function(a,b,c,d){var e=new H;do for(var f=b;f=f.nextSibling;)Qb(f,c,d)&&a.a(f)&&I(e,f),e=Rb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);S("following-sibling",function(a,b){for(var c=new H;b=b.nextSibling;)a.a(b)&&I(c,b);return c},!1);S("namespace",function(){return new H},!1);
var Ic=S("parent",function(a,b){var c=new H;if(9==b.nodeType)return c;if(2==b.nodeType)return I(c,b.ownerElement),c;b=b.parentNode;a.a(b)&&I(c,b);return c},!1),Bc=S("preceding",function(a,b,c,d){var e=new H,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var t=[];for(b=f[g];b=b.previousSibling;)t.unshift(b);for(var u=0,m=t.length;u<m;u++)b=t[u],Qb(b,c,d)&&a.a(b)&&I(e,b),e=Rb(a,b,c,d,e)}return e},!0,!0);
S("preceding-sibling",function(a,b){for(var c=new H;b=b.previousSibling;)a.a(b)&&ac(c,b);return c},!0);var Jc=S("self",function(a,b){var c=new H;a.a(b)&&I(c,b);return c},!1);function Kc(a){L.call(this,1);this.c=a;this.g=a.g;this.b=a.b}p(Kc,L);Kc.prototype.a=function(a){return-N(this.c,a)};Kc.prototype.toString=function(){return"Unary Expression: -"+M(this.c)};function Lc(a){L.call(this,4);this.c=a;fc(this,xa(this.c,function(a){return a.g}));gc(this,xa(this.c,function(a){return a.b}))}p(Lc,L);Lc.prototype.a=function(a){var b=new H;v(this.c,function(c){c=c.a(a);if(!(c instanceof H))throw Error("Path expression must evaluate to NodeSet.");b=$b(b,c)});return b};Lc.prototype.toString=function(){return wa(this.c,function(a,b){return a+M(b)},"Union Expression:")};function Mc(a,b){this.a=a;this.b=b}function Nc(a){for(var b,c=[];;){T(a,"Missing right hand side of binary expression.");b=Oc(a);var d=E(a.a);if(!d)break;var e=(d=mc[d]||null)&&d.L;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].L;)b=new ic(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new ic(c.pop(),c.pop(),b);return b}function T(a,b){if(Pb(a.a))throw Error(b);}function Pc(a,b){a=E(a.a);if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function Qc(a){a=E(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Rc(a){a=E(a.a);if(2>a.length)throw Error("Unclosed literal string");return new tc(a)}
function Sc(a){var b=[];if(zc(D(a.a))){var c=E(a.a);var d=D(a.a);if("/"==c&&(Pb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new xc;d=new xc;T(a,"Missing next location step.");c=Tc(a,c);b.push(c)}else{a:{c=D(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":E(a.a);c=Nc(a);T(a,'unclosed "("');Pc(a,")");break;case '"':case "'":c=Rc(a);break;default:if(isNaN(+c))if(!sc(c)&&/(?![0-9])[\w]/.test(d)&&"("==D(a.a,1)){c=E(a.a);
c=rc[c]||null;E(a.a);for(d=[];")"!=D(a.a);){T(a,"Missing function argument list.");d.push(Nc(a));if(","!=D(a.a))break;E(a.a)}T(a,"Unclosed function argument list.");Qc(a);c=new pc(c,d)}else{c=null;break a}else c=new uc(+E(a.a))}"["==D(a.a)&&(d=new Cc(Uc(a)),c=new nc(c,d))}if(c)if(zc(D(a.a)))d=c;else return c;else c=Tc(a,"/"),d=new yc,b.push(c)}for(;zc(D(a.a));)c=E(a.a),T(a,"Missing next location step."),c=Tc(a,c),b.push(c);return new vc(d,b)}
function Tc(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==D(a.a)){var c=new Dc(Jc,new J("node"));E(a.a);return c}if(".."==D(a.a))return c=new Dc(Ic,new J("node")),E(a.a),c;if("@"==D(a.a)){var d=wc;E(a.a);T(a,"Missing attribute name")}else if("::"==D(a.a,1)){if(!/(?![0-9])[\w]/.test(D(a.a).charAt(0)))throw Error("Bad token: "+E(a.a));var e=E(a.a);d=Hc[e]||null;if(!d)throw Error("No axis with name: "+e);E(a.a);T(a,"Missing node name")}else d=Ec;e=D(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==
D(a.a,1)){if(!sc(e))throw Error("Invalid node type: "+e);e=E(a.a);if(!sc(e))throw Error("Invalid type name: "+e);Pc(a,"(");T(a,"Bad nodetype");var f=D(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=Rc(a);T(a,"Bad nodetype");Qc(a);e=new J(e,g)}else if(e=E(a.a),f=e.indexOf(":"),-1==f)e=new Ub(e);else{var g=e.substring(0,f);if("*"==g)var h="*";else if(h=a.b(g),!h)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new Ub(e,h)}else throw Error("Bad token: "+E(a.a));a=new Cc(Uc(a),d.v);return c||
new Dc(d,e,a,"//"==b)}function Uc(a){for(var b=[];"["==D(a.a);){E(a.a);T(a,"Missing predicate expression.");var c=Nc(a);b.push(c);T(a,"Unclosed predicate expression.");Pc(a,"]")}return b}function Oc(a){if("-"==D(a.a))return E(a.a),new Kc(Oc(a));var b=Sc(a);if("|"!=D(a.a))a=b;else{for(b=[b];"|"==E(a.a);)T(a,"Missing next union location path."),b.push(Sc(a));a.a.a--;a=new Lc(b)}return a};function Vc(a){switch(a.nodeType){case 1:return ja(Wc,a);case 9:return Vc(a.documentElement);case 11:case 10:case 6:case 12:return Xc;default:return a.parentNode?Vc(a.parentNode):Xc}}function Xc(){return null}function Wc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Wc(a.parentNode,b):null};function Yc(a,b){if(!a.length)throw Error("Empty XPath expression.");a=Mb(a);if(Pb(a))throw Error("Invalid XPath expression.");b?da(b)||(b=ia(b.lookupNamespaceURI,b)):b=function(){return null};var c=Nc(new Mc(a,b));if(!Pb(a))throw Error("Bad token: "+E(a));this.evaluate=function(a,b){a=c.a(new Hb(a));return new U(a,b)}}
function U(a,b){if(!b)if(a instanceof H)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof H))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof H?cc(a):""+a;break;case 1:this.numberValue=a instanceof H?+cc(a):+a;break;case 3:this.booleanValue=a instanceof H?0<a.l:!!a;break;case 4:case 5:case 6:case 7:var c=
dc(a);var d=[];for(var e=K(c);e;e=K(c))d.push(e instanceof Jb?e.a:e);this.snapshotLength=a.l;this.invalidIteratorState=!1;break;case 8:case 9:a=bc(a);this.singleNodeValue=a instanceof Jb?a.a:a;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=d.length||
0>a?null:d[a]}}U.ANY_TYPE=0;U.NUMBER_TYPE=1;U.STRING_TYPE=2;U.BOOLEAN_TYPE=3;U.UNORDERED_NODE_ITERATOR_TYPE=4;U.ORDERED_NODE_ITERATOR_TYPE=5;U.UNORDERED_NODE_SNAPSHOT_TYPE=6;U.ORDERED_NODE_SNAPSHOT_TYPE=7;U.ANY_UNORDERED_NODE_TYPE=8;U.FIRST_ORDERED_NODE_TYPE=9;function Zc(a){this.lookupNamespaceURI=Vc(a)}
function $c(a,b){a=a||k;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=U,c.evaluate=function(a,b,c,g){return(new Yc(a,c)).evaluate(b,g)},c.createExpression=function(a,b){return new Yc(a,b)},c.createNSResolver=function(a){return new Zc(a)}}aa("wgxpath.install",$c);var V={};V.G=function(){var a={W:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
V.o=function(a,b,c){var d=A(a);if(!d.documentElement)return null;(y||nb)&&$c(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):V.G;if(y&&!Wa(7))return d.evaluate.call(d,b,a,e,c,null);if(!y||9<=Number(z)){for(var f={},g=d.getElementsByTagName("*"),h=0;h<g.length;++h){var t=g[h],u=t.namespaceURI;if(u&&!f[u]){var m=t.lookupPrefix(u);if(!m)var G=u.match(".*/(\\w+)/?$"),m=G?G[1]:"xhtml";f[u]=m}}var Q={},fa;for(fa in f)Q[f[fa]]=fa;e=function(a){return Q[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(Aa){if("TypeError"===Aa.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):V.G,d.evaluate(b,a,e,c,null);throw Aa;}}catch(Aa){if(!Pa||"NS_ERROR_ILLEGAL_VALUE"!=Aa.name)throw new q(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+Aa);}};V.H=function(a,b){if(!a||1!=a.nodeType)throw new q(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
V.s=function(a,b){var c=function(){var c=V.o(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=A(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||V.H(c,a);return c};
V.m=function(a,b){var c=function(){var c=V.o(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=A(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();v(c,function(b){V.H(b,a)});return c};function ad(a,b,c,d){this.c=a;this.a=b;this.b=c;this.f=d}ad.prototype.toString=function(){return"("+this.c+"t, "+this.a+"r, "+this.b+"b, "+this.f+"l)"};ad.prototype.ceil=function(){this.c=Math.ceil(this.c);this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.f=Math.ceil(this.f);return this};ad.prototype.floor=function(){this.c=Math.floor(this.c);this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.f=Math.floor(this.f);return this};
ad.prototype.round=function(){this.c=Math.round(this.c);this.a=Math.round(this.a);this.b=Math.round(this.b);this.f=Math.round(this.f);return this};function W(a,b,c,d){this.a=a;this.b=b;this.width=c;this.height=d}W.prototype.toString=function(){return"("+this.a+", "+this.b+" - "+this.width+"w x "+this.height+"h)"};W.prototype.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};W.prototype.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
W.prototype.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var bd="function"===typeof ShadowRoot;function cd(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return B(a)?a:null}
function X(a,b){b=sa(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b=wb?"styleFloat":"cssFloat";a:{var c=b;var d=A(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||dd(a,b);if(null===a)a=null;else if(0<=ta(zb,b)){b:{var e=a.match(Cb);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d&&0<=e&&1>=e)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(Db))if(b=
Number(d[1]),c=Number(d[2]),d=Number(d[3]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=yb[b.toLowerCase()];if(!c&&(c="#"==b.charAt(0)?b:"#"+b,4==c.length&&(c=c.replace(Ab,"#$1$1$2$2$3$3")),!Bb.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function dd(a,b){var c=a.currentStyle||a.style,d=c[b];!l(d)&&da(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?l(d)?d:null:(a=cd(a))?dd(a,b):null}
function ed(a,b,c){function d(a){var b=fd(a);return 0<b.height&&0<b.width?!0:B(a,"PATH")&&(0<b.height||0<b.width)?(a=X(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=X(a,"overflow")&&xa(a.childNodes,function(a){return 3==a.nodeType||B(a)&&d(a)})}function e(a){return gd(a)==Y&&ya(a.childNodes,function(a){return!B(a)||e(a)||!d(a)})}if(!B(a))throw Error("Argument to isShown must be of type Element");if(B(a,"BODY"))return!0;if(B(a,"OPTION")||B(a,"OPTGROUP"))return a=hb(a,function(a){return B(a,"SELECT")}),
!!a&&ed(a,!0,c);var f=hd(a);if(f)return!!f.I&&0<f.rect.width&&0<f.rect.height&&ed(f.I,b,c);if(B(a,"INPUT")&&"hidden"==a.type.toLowerCase()||B(a,"NOSCRIPT"))return!1;f=X(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||id(a))&&d(a)?!e(a):!1}
function jd(a){function b(a){if(B(a)&&"none"==X(a,"display"))return!1;var c;(c=a.parentNode)&&c.shadowRoot&&void 0!==a.assignedSlot?c=a.assignedSlot?a.assignedSlot.parentNode:null:a.getDestinationInsertionPoints&&(a=a.getDestinationInsertionPoints(),0<a.length&&(c=a[a.length-1]));if(bd&&c instanceof ShadowRoot){if(c.host.shadowRoot!==c)return!1;c=c.host}return!c||9!=c.nodeType&&11!=c.nodeType?c&&b(c):!0}return ed(a,!1,b)}var Y="hidden";
function gd(a){function b(a){function b(a){return a==g?!0:!X(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==X(a,"position")?!1:!0}var c=X(a,"position");if("fixed"==c)return u=!0,a==g?null:g;for(a=cd(a);a&&!b(a);)a=cd(a);return a}function c(a){var b=a;if("visible"==t)if(a==g&&h)b=h;else if(a==h)return{x:"visible",y:"visible"};b={x:X(b,"overflow-x"),y:X(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new ab(f)).a;
a=b.scrollingElement?b.scrollingElement:Qa||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=y&&Wa("10")&&b.pageYOffset!=a.scrollTop?new Ya(a.scrollLeft,a.scrollTop):new Ya(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new Ya(a.scrollLeft,a.scrollTop);return a}var e=kd(a);var f=A(a),g=f.documentElement,h=f.body,t=X(g,"overflow"),u;for(a=b(a);a;a=b(a)){var m=c(a);if("visible"!=m.x||"visible"!=m.y){var G=fd(a);if(!G.width||!G.height)return Y;
var Q=e.a<G.a,fa=e.b<G.b;if(Q&&"hidden"==m.x||fa&&"hidden"==m.y)return Y;if(Q&&"visible"!=m.x||fa&&"visible"!=m.y){Q=d(a);fa=e.b<G.b-Q.y;if(e.a<G.a-Q.x&&"visible"!=m.x||fa&&"visible"!=m.x)return Y;e=gd(a);return e==Y?Y:"scroll"}Q=e.f>=G.a+G.width;G=e.c>=G.b+G.height;if(Q&&"hidden"==m.x||G&&"hidden"==m.y)return Y;if(Q&&"visible"!=m.x||G&&"visible"!=m.y){if(u&&(m=d(a),e.f>=g.scrollWidth-m.x||e.a>=g.scrollHeight-m.y))return Y;e=gd(a);return e==Y?Y:"scroll"}}}return"none"}
function fd(a){var b=hd(a);if(b)return b.rect;if(B(a,"HTML"))return a=A(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new Za(a.clientWidth,a.clientHeight),new W(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new W(0,0,0,0)}b=new W(c.left,c.top,c.right-c.left,c.bottom-c.top);y&&a.ownerDocument.body&&(a=A(a),b.a-=a.documentElement.clientLeft+a.body.clientLeft,b.b-=a.documentElement.clientTop+a.body.clientTop);
return b}function hd(a){var b=B(a,"MAP");if(!b&&!B(a,"AREA"))return null;var c=b?a:B(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=V.s('/descendant::*[@usemap = "#'+c.name+'"]',A(c)))&&(e=fd(d),b||"default"==a.shape.toLowerCase()||(a=ld(a),b=Math.min(Math.max(a.a,0),e.width),c=Math.min(Math.max(a.b,0),e.height),e=new W(b+e.a,c+e.b,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{I:d,rect:e||new W(0,0,0,0)}}
function ld(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new W(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new W(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new W(b,c,d-b,e-c)}return new W(0,0,0,0)}function kd(a){a=fd(a);return new ad(a.b,a.a+a.width,a.b+a.height,a.a)}
function md(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function nd(a){var b=[];bd?od(a,b):pd(a,b);a=va(b,md);return md(a.join("\n")).replace(/\xa0/g," ")}
function qd(a,b,c){if(B(a,"BR"))b.push("");else{var d=B(a,"TD"),e=X(a,"display"),f=!d&&!(0<=ta(rd,e)),g=l(a.previousElementSibling)?a.previousElementSibling:bb(a.previousSibling),g=g?X(g,"display"):"",h=X(a,"float")||X(a,"cssFloat")||X(a,"styleFloat");!f||"run-in"==g&&"none"==h||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var t=jd(a),u=null,m=null;t&&(u=X(a,"white-space"),m=X(a,"text-transform"));v(a.childNodes,function(a){c(a,b,t,u,m)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||oa(a)||(b[b.length-
1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function pd(a,b){qd(a,b,function(a,b,e,f,g){3==a.nodeType&&e?sd(a,b,f,g):B(a)&&pd(a,b)})}var rd="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function sd(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";oa(c)&&!a.lastIndexOf(" ",0)&&(a=a.substr(1));b.push(c+a)}
function id(a){if(wb){if("relative"==X(a,"position"))return 1;a=X(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return td(a)}function td(a){var b=1,c=X(a,"opacity");c&&(b=Number(c));(a=cd(a))&&(b*=td(a));return b}
function ud(a,b,c,d,e){var f;if(3==a.nodeType&&c)sd(a,b,d,e);else if(B(a))if(B(a,"CONTENT")||B(a,"SLOT")){for(f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?(a=B(a,"CONTENT")?a.getDistributedNodes():a.assignedNodes(),v(a,function(a){ud(a,b,c,d,e)})):od(a,b)}else if(B(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)v(a.childNodes,function(a){ud(a,b,c,d,e)}),a=a.olderShadowRoot}else od(a,b)}
function od(a,b){a.shadowRoot&&v(a.shadowRoot.childNodes,function(a){ud(a,b,!0,null,null)});qd(a,b,function(a,b,e,f,g){var c=null;1==a.nodeType?c=a:3==a.nodeType&&(c=a);c&&(c.assignedSlot||c.getDestinationInsertionPoints&&0<c.getDestinationInsertionPoints().length)||ud(a,b,e,f,g)})};var vd={A:function(a,b){return!(!a.querySelectorAll||!a.querySelector)&&!/^\d.*/.test(b)},s:function(a,b){var c=$a(b),d=n(a)?c.a.getElementById(a):a;return d?Eb(d,"id")==a&&b!=d&&cb(b,d)?d:za(ib(c,"*"),function(c){return Eb(c,"id")==a&&b!=c&&cb(b,c)}):null},m:function(a,b){if(!a)return[];if(vd.A(b,a))try{return b.querySelectorAll("#"+vd.N(a))}catch(c){return[]}b=ib($a(b),"*",null,b);return ua(b,function(b){return Eb(b,"id")==a})},N:function(a){return a.replace(/([\s'"\\#.:;,!?+<>=~*^$|%&@`{}\-\/\[\]\(\)])/g,
"\\$1")}};var Z={},wd={};Z.M=function(a,b,c){try{var d=xb.m("a",b)}catch(e){d=ib($a(b),"A",null,b)}return za(d,function(b){b=nd(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};Z.J=function(a,b,c){try{var d=xb.m("a",b)}catch(e){d=ib($a(b),"A",null,b)}return ua(d,function(b){b=nd(b);b=b.replace(/^[\s]+|[\s]+$/g,"");return c&&-1!=b.indexOf(a)||b==a})};Z.s=function(a,b){return Z.M(a,b,!1)};Z.m=function(a,b){return Z.J(a,b,!1)};wd.s=function(a,b){return Z.M(a,b,!0)};
wd.m=function(a,b){return Z.J(a,b,!0)};var xd={s:function(a,b){if(""===a)throw new q(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)[0]||null},m:function(a,b){if(""===a)throw new q(32,'Unable to locate an element with the tagName ""');return b.getElementsByTagName(a)}};var yd={className:jb,"class name":jb,css:xb,"css selector":xb,id:vd,linkText:Z,"link text":Z,name:{s:function(a,b){b=ib($a(b),"*",null,b);return za(b,function(b){return Eb(b,"name")==a})},m:function(a,b){b=ib($a(b),"*",null,b);return ua(b,function(b){return Eb(b,"name")==a})}},partialLinkText:wd,"partial link text":wd,tagName:xd,"tag name":xd,xpath:V};function zd(a,b){for(var c=b||ma,d=c.frames.length,e=0;e<d;e++){var f=c.frames[e];b=f.frameElement||f;if(b.name==a)return f.document?f:gb(f)}a:{a={id:a};b=c.document;b:{for(g in a)if(a.hasOwnProperty(g))break b;var g=null}if(g&&(c=yd[g])&&da(c.m)){g=c.m(a[g],b||ma.document);break a}throw Error("Unsupported locator strategy: "+g);}for(e=0;e<g.length;e++)if((b=g[e])&&(B(b,"FRAME")||B(b,"IFRAME")))return gb(b);return null};function Ad(){}
function Bd(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if("array"==ba(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Bd(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Cd(d,c),c.push(":"),Bd(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Cd(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var Dd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Ed=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Cd(a,b){b.push('"',a.replace(Ed,function(a){var b=Dd[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Dd[a]=b);return b}),'"')};Qa||Pa&&tb(3.5)||y&&tb(8);function Fd(a){function b(a,d){switch(ba(a)){case "string":case "number":case "boolean":return a;case "function":return a.toString();case "array":return va(a,function(a){return b(a,d)});case "object":if(0<=d.indexOf(a))throw new q(17,"Recursive object cannot be transferred");if(Ha(a,"nodeType")&&(1==a.nodeType||9==a.nodeType)){var c={};c.ELEMENT=Gd(a);return c}if(Ha(a,"document"))return c={},c.WINDOW=Gd(a),c;d.push(a);if(ca(a))return va(a,function(a){return b(a,d)});a=Fa(a,function(a,b){return"number"==
typeof b||n(b)});return Ga(a,function(a){return b(a,d)});default:return null}}return b(a,[])}function Hd(a,b){return"array"==ba(a)?va(a,function(a){return Hd(a,b)}):ea(a)?"function"==typeof a?a:Ha(a,"ELEMENT")?Id(a.ELEMENT,b):Ha(a,"WINDOW")?Id(a.WINDOW,b):Ga(a,function(a){return Hd(a,b)}):a}function Jd(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.F=ka());b.F||(b.F=ka());return b}function Gd(a){var b=Jd(a.ownerDocument),c=Ia(b,function(b){return b==a});c||(c=":wdc:"+b.F++,b[c]=a);return c}
function Id(a,b){a=decodeURIComponent(a);b=b||document;var c=Jd(b);if(!Ha(c,a))throw new q(10,"Element does not exist in cache");var d=c[a];if(Ha(d,"setInterval")){if(d.closed)throw delete c[a],new q(23,"Window has been closed.");return d}for(var e=d;e;){if(e==b.documentElement)return d;e=e.parentNode}delete c[a];throw new q(10,"Element is no longer attached to the DOM");};aa("_",function(a,b){a=[a,b];b=zd;var c=window||ma;try{a:{var d=b;if(n(d))try{b=new c.Function(d);break a}catch(g){if(y&&c.execScript){c.execScript(";");b=new c.Function(d);break a}throw g;}b=c==window?d:new c.Function("return ("+d+").apply(null,arguments);")}var e=Hd(a,c.document);var f={status:0,value:Fd(b.apply(null,e))}}catch(g){f={status:Ha(g,"code")?g.code:13,value:{message:g.message}}}e=[];Bd(new Ad,f,e);return e.join("")});; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
