function(){return function(){var g=this;function k(a){return"string"==typeof a}function aa(a,b){a=a.split(".");var c=g;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function m(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ca(a){var b=m(a);return"array"==b||"object"==b&&"number"==typeof a.length}function da(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ga(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ga=ea:ga=fa;return ga.apply(null,arguments)}
function ha(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ia=Date.now||function(){return+new Date};function n(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.O=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};var ja=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function ka(a,b){var c=0;a=ja(String(a)).split(".");b=ja(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;!c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=la(0==f[1].length?0:parseInt(f[1],10),0==h[1].length?0:parseInt(h[1],10))||la(0==f[2].length,0==h[2].length)||la(f[2],h[2]);f=f[3];h=h[3]}while(!c)}return c}function la(a,b){return a<b?-1:a>b?1:0}
function ma(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};function na(a,b){if(k(a))return k(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function p(a,b){for(var c=a.length,d=k(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function oa(a,b){for(var c=a.length,d=[],e=0,f=k(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var l=f[h];b.call(void 0,l,h,a)&&(d[e++]=l)}return d}
function pa(a,b){for(var c=a.length,d=Array(c),e=k(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function q(a,b,c){var d=c;p(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function qa(a,b){for(var c=a.length,d=k(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function ra(a,b){a:{for(var c=a.length,d=k(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:k(a)?a.charAt(b):a[b]}
function sa(a){return Array.prototype.concat.apply([],arguments)}function ta(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var ua={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var va="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),wa=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,xa=/^#(?:[0-9a-f]{3}){1,2}$/i,ya=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,za=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function r(a,b){this.code=a;this.a=t[a]||Aa;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}n(r,Error);var Aa="unknown error",t={15:"element not selectable",11:"element not visible"};t[31]=Aa;t[30]=Aa;t[24]="invalid cookie domain";t[29]="invalid element coordinates";t[12]="invalid element state";
t[32]="invalid selector";t[51]="invalid selector";t[52]="invalid selector";t[17]="javascript error";t[405]="unsupported operation";t[34]="move target out of bounds";t[27]="no such alert";t[7]="no such element";t[8]="no such frame";t[23]="no such window";t[28]="script timeout";t[33]="session not created";t[10]="stale element reference";t[21]="timeout";t[25]="unable to set cookie";t[26]="unexpected alert open";t[13]=Aa;t[9]="unknown command";r.prototype.toString=function(){return this.name+": "+this.message};var u;a:{var Ba=g.navigator;if(Ba){var Ca=Ba.userAgent;if(Ca){u=Ca;break a}}u=""}function v(a){return-1!=u.indexOf(a)};function Da(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function Ea(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function w(a,b){return null!==a&&b in a}function Fa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function Ga(){return(v("Chrome")||v("CriOS"))&&!v("Edge")};function Ha(){return v("iPhone")&&!v("iPod")&&!v("iPad")};function Ia(a,b){var c=Ja;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Ka=v("Opera"),y=v("Trident")||v("MSIE"),La=v("Edge"),Ma=v("Gecko")&&!(-1!=u.toLowerCase().indexOf("webkit")&&!v("Edge"))&&!(v("Trident")||v("MSIE"))&&!v("Edge"),Na=-1!=u.toLowerCase().indexOf("webkit")&&!v("Edge"),Oa=v("Macintosh"),Pa=v("Windows");function Qa(){var a=g.document;return a?a.documentMode:void 0}var Ra;
a:{var Sa="",Ta=function(){var a=u;if(Ma)return/rv\:([^\);]+)(\)|;)/.exec(a);if(La)return/Edge\/([\d\.]+)/.exec(a);if(y)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Na)return/WebKit\/(\S+)/.exec(a);if(Ka)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ta&&(Sa=Ta?Ta[1]:"");if(y){var Ua=Qa();if(null!=Ua&&Ua>parseFloat(Sa)){Ra=String(Ua);break a}}Ra=Sa}var Ja={};function Va(a){return Ia(a,function(){return 0<=ka(Ra,a)})}var z;var Wa=g.document;
z=Wa&&y?Qa()||("CSS1Compat"==Wa.compatMode?parseInt(Ra,10):5):void 0;var Xa=v("Firefox"),Ya=Ha()||v("iPod"),Za=v("iPad"),$a=v("Android")&&!(Ga()||v("Firefox")||v("Opera")||v("Silk")),ab=Ga(),bb=v("Safari")&&!(Ga()||v("Coast")||v("Opera")||v("Edge")||v("Silk")||v("Android"))&&!(Ha()||v("iPad")||v("iPod"));function A(a){return(a=a.exec(u))?a[1]:""}(function(){if(Xa)return A(/Firefox\/([0-9.]+)/);if(y||La||Ka)return Ra;if(ab)return Ha()||v("iPad")||v("iPod")?A(/CriOS\/([0-9.]+)/):A(/Chrome\/([0-9.]+)/);if(bb&&!(Ha()||v("iPad")||v("iPod")))return A(/Version\/([0-9.]+)/);if(Ya||Za){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(u);if(a)return a[1]+"."+a[2]}else if($a)return(a=A(/Android\s+([0-9.]+)/))?a:A(/Version\/([0-9.]+)/);return""})();var cb,B;function db(a){return C?cb(a):y?0<=ka(z,a):Va(a)}var C=function(){if(!Ma)return!1;var a=g.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;cb=function(a){return 0<=c.compare(d,""+a)};B=function(a){c.compare(e,""+a)};return!0}(),eb=y&&!(9<=Number(z));$a&&C&&B(2.3);
$a&&C&&B(4);bb&&C&&B(6);function fb(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function gb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(y&&!(9<=Number(z))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?hb(a,b):!c&&fb(e,b)?-1*ib(a,b):!d&&fb(f,a)?ib(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=9==a.nodeType?
a:a.ownerDocument||a.document;c=d.createRange();c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(g.Range.START_TO_END,a)}function ib(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return hb(b,a)}function hb(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function D(a,b,c){this.a=a;this.b=b||1;this.h=c||1};var F=y&&!(9<=Number(z)),jb=y&&!(8<=Number(z));function G(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function kb(a,b){var c=jb&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new G(b,a,b.nodeName,c)};function lb(a){this.b=a;this.a=0}function mb(a){a=a.match(nb);for(var b=0;b<a.length;b++)ob.test(a[b])&&a.splice(b,1);return new lb(a)}var nb=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,ob=/^\s/;function H(a,b){return a.b[a.a+(b||0)]}lb.prototype.next=function(){return this.b[this.a++]};function pb(a){return a.b.length<=a.a};function I(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(F&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),F&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function J(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}jb&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function qb(a,b,c,d,e){return(F?rb:sb).call(null,a,b,k(c)?c:null,k(d)?d:null,e||new K)}
function rb(a,b,c,d,e){if(a instanceof L||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;var h=tb(a);if("*"!=h&&(f=b.getElementsByTagName(h),!f))return e;if(c){var l=[];for(a=0;b=f[a++];)J(b,c,d)&&l.push(b);f=l}for(a=0;b=f[a++];)"*"==h&&"!"==b.tagName||M(e,b);return e}ub(a,b,c,d,e);return e}
function sb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!y?(b=b.getElementsByName(d),p(b,function(b){a.a(b)&&M(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),p(b,function(b){b.className==d&&a.a(b)&&M(e,b)})):a instanceof N?ub(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.h()),p(b,function(a){J(a,c,d)&&M(e,a)}));return e}
function vb(a,b,c,d,e){var f;if((a instanceof L||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var h=tb(a);if("*"!=h&&(f=oa(f,function(a){return a.tagName&&a.tagName.toLowerCase()==h}),!f))return e;c&&(f=oa(f,function(a){return J(a,c,d)}));p(f,function(a){"*"==h&&("!"==a.tagName||"*"==h&&1!=a.nodeType)||M(e,a)});return e}return wb(a,b,c,d,e)}function wb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)J(b,c,d)&&a.a(b)&&M(e,b);return e}
function ub(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)J(b,c,d)&&a.a(b)&&M(e,b),ub(a,b,c,d,e)}function tb(a){if(a instanceof N){if(8==a.b)return"!";if(null===a.b)return"*"}return a.h()};function K(){this.b=this.a=null;this.s=0}function xb(a){this.node=a;this.next=this.a=null}function yb(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;){e=c.node;var h=b.node;e==h||e instanceof G&&h instanceof G&&e.a==h.a?(e=c,c=c.next,b=b.next):0<gb(c.node,b.node)?(e=b,b=b.next):(e=c,c=c.next);(e.a=d)?d.next=e:a.a=e;d=e;f++}for(e=c||b;e;)e.a=d,d=d.next=e,f++,e=e.next;a.b=d;a.s=f;return a}function zb(a,b){b=new xb(b);b.next=a.a;a.b?a.a.a=b:a.a=a.b=b;a.a=b;a.s++}
function M(a,b){b=new xb(b);b.a=a.b;a.a?a.b.next=b:a.a=a.b=b;a.b=b;a.s++}function Ab(a){return(a=a.a)?a.node:null}function Bb(a){return(a=Ab(a))?I(a):""}K.prototype.iterator=function(a){return new Cb(this,!!a)};function Cb(a,b){this.h=a;this.b=(this.A=b)?a.b:a.a;this.a=null}Cb.prototype.next=function(){var a=this.b;if(a){var b=this.a=a;this.b=this.A?a.a:a.next;return b.node}return null};function O(a){this.l=a;this.b=this.i=!1;this.h=null}function P(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Db(a,b){a.i=b}function Eb(a,b){a.b=b}function Q(a,b){a=a.a(b);return a instanceof K?+Bb(a):+a}function R(a,b){a=a.a(b);return a instanceof K?Bb(a):""+a}function S(a,b){a=a.a(b);return a instanceof K?!!a.s:!!a};function Fb(a,b,c){O.call(this,a.l);this.c=a;this.j=b;this.v=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==Gb&&(c.b||c.i||4==c.l||0==c.l||!b.h?b.b||b.i||4==b.l||0==b.l||!c.h||(this.h={name:c.h.name,B:b}):this.h={name:b.h.name,B:c})}n(Fb,O);
function Hb(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof K&&c instanceof K){b=b.iterator();for(d=b.next();d;d=b.next())for(e=c.iterator(),f=e.next();f;f=e.next())if(a(I(d),I(f)))return!0;return!1}if(b instanceof K||c instanceof K){b instanceof K?(e=b,d=c):(e=c,d=b);f=e.iterator();for(var h=typeof d,l=f.next();l;l=f.next()){switch(h){case "number":l=+I(l);break;case "boolean":l=!!I(l);break;case "string":l=I(l);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(l,
d)||e==c&&a(d,l))return!0}return!1}return e?"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Fb.prototype.a=function(a){return this.c.u(this.j,this.v,a)};Fb.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+P(this.j);return a+=P(this.v)};function Ib(a,b,c,d){this.M=a;this.I=b;this.l=c;this.u=d}Ib.prototype.toString=function(){return this.M};var Jb={};
function T(a,b,c,d){if(Jb.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Ib(a,b,c,d);return Jb[a.toString()]=a}T("div",6,1,function(a,b,c){return Q(a,c)/Q(b,c)});T("mod",6,1,function(a,b,c){return Q(a,c)%Q(b,c)});T("*",6,1,function(a,b,c){return Q(a,c)*Q(b,c)});T("+",5,1,function(a,b,c){return Q(a,c)+Q(b,c)});T("-",5,1,function(a,b,c){return Q(a,c)-Q(b,c)});T("<",4,2,function(a,b,c){return Hb(function(a,b){return a<b},a,b,c)});
T(">",4,2,function(a,b,c){return Hb(function(a,b){return a>b},a,b,c)});T("<=",4,2,function(a,b,c){return Hb(function(a,b){return a<=b},a,b,c)});T(">=",4,2,function(a,b,c){return Hb(function(a,b){return a>=b},a,b,c)});var Gb=T("=",3,2,function(a,b,c){return Hb(function(a,b){return a==b},a,b,c,!0)});T("!=",3,2,function(a,b,c){return Hb(function(a,b){return a!=b},a,b,c,!0)});T("and",2,2,function(a,b,c){return S(a,c)&&S(b,c)});T("or",1,2,function(a,b,c){return S(a,c)||S(b,c)});function Kb(a,b){if(b.a.length&&4!=a.l)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");O.call(this,a.l);this.c=a;this.j=b;this.i=a.i;this.b=a.b}n(Kb,O);Kb.prototype.a=function(a){a=this.c.a(a);return Lb(this.j,a)};Kb.prototype.toString=function(){var a="Filter:"+P(this.c);return a+=P(this.j)};function Mb(a,b){if(b.length<a.H)throw Error("Function "+a.o+" expects at least"+a.H+" arguments, "+b.length+" given");if(null!==a.F&&b.length>a.F)throw Error("Function "+a.o+" expects at most "+a.F+" arguments, "+b.length+" given");a.L&&p(b,function(b,d){if(4!=b.l)throw Error("Argument "+d+" to function "+a.o+" is not of type Nodeset: "+b);});O.call(this,a.l);this.C=a;this.c=b;Db(this,a.i||qa(b,function(a){return a.i}));Eb(this,a.K&&!b.length||a.J&&!!b.length||qa(b,function(a){return a.b}))}
n(Mb,O);Mb.prototype.a=function(a){return this.C.u.apply(null,sa(a,this.c))};Mb.prototype.toString=function(){var a="Function: "+this.C;if(this.c.length)var b=q(this.c,function(a,b){return a+P(b)},"Arguments:"),a=a+P(b);return a};function Nb(a,b,c,d,e,f,h,l,x){this.o=a;this.l=b;this.i=c;this.K=d;this.J=e;this.u=f;this.H=h;this.F=void 0!==l?l:h;this.L=!!x}Nb.prototype.toString=function(){return this.o};var Ob={};
function U(a,b,c,d,e,f,h,l){if(Ob.hasOwnProperty(a))throw Error("Function already created: "+a+".");Ob[a]=new Nb(a,b,c,d,!1,e,f,h,l)}U("boolean",2,!1,!1,function(a,b){return S(b,a)},1);U("ceiling",1,!1,!1,function(a,b){return Math.ceil(Q(b,a))},1);U("concat",3,!1,!1,function(a,b){return q(ta(arguments,1),function(b,d){return b+R(d,a)},"")},2,null);U("contains",2,!1,!1,function(a,b,c){b=R(b,a);a=R(c,a);return-1!=b.indexOf(a)},2);U("count",1,!1,!1,function(a,b){return b.a(a).s},1,1,!0);
U("false",2,!1,!1,function(){return!1},0);U("floor",1,!1,!1,function(a,b){return Math.floor(Q(b,a))},1);U("id",4,!1,!1,function(a,b){function c(a){if(F){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return ra(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument;a=R(b,a).split(/\s+/);var f=[];p(a,function(a){a=c(a);!a||0<=na(f,a)||f.push(a)});f.sort(gb);var h=new K;p(f,function(a){M(h,a)});return h},1);
U("lang",2,!1,!1,function(){return!1},1);U("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.h},0);U("local-name",3,!1,!0,function(a,b){return(a=b?Ab(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);U("name",3,!1,!0,function(a,b){return(a=b?Ab(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);U("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
U("normalize-space",3,!1,!0,function(a,b){return(b?R(b,a):I(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);U("not",2,!1,!1,function(a,b){return!S(b,a)},1);U("number",1,!1,!0,function(a,b){return b?Q(b,a):+I(a.a)},0,1);U("position",1,!0,!1,function(a){return a.b},0);U("round",1,!1,!1,function(a,b){return Math.round(Q(b,a))},1);U("starts-with",2,!1,!1,function(a,b,c){b=R(b,a);a=R(c,a);return!b.lastIndexOf(a,0)},2);U("string",3,!1,!0,function(a,b){return b?R(b,a):I(a.a)},0,1);
U("string-length",1,!1,!0,function(a,b){return(b?R(b,a):I(a.a)).length},0,1);U("substring",3,!1,!1,function(a,b,c,d){c=Q(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?Q(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=R(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);U("substring-after",3,!1,!1,function(a,b,c){b=R(b,a);a=R(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
U("substring-before",3,!1,!1,function(a,b,c){b=R(b,a);a=R(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);U("sum",1,!1,!1,function(a,b){a=b.a(a).iterator();b=0;for(var c=a.next();c;c=a.next())b+=+I(c);return b},1,1,!0);U("translate",3,!1,!1,function(a,b,c,d){b=R(b,a);c=R(c,a);var e=R(d,a);d={};for(var f=0;f<c.length;f++)a=c.charAt(f),a in d||(d[a]=e.charAt(f));c="";for(f=0;f<b.length;f++)a=b.charAt(f),c+=a in d?d[a]:a;return c},3);U("true",2,!1,!1,function(){return!0},0);function N(a,b){this.j=a;this.c=void 0!==b?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Pb(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}N.prototype.a=function(a){return null===this.b||this.b==a.nodeType};N.prototype.h=function(){return this.j};
N.prototype.toString=function(){var a="Kind Test: "+this.j;null===this.c||(a+=P(this.c));return a};function Qb(a){O.call(this,3);this.c=a.substring(1,a.length-1)}n(Qb,O);Qb.prototype.a=function(){return this.c};Qb.prototype.toString=function(){return"Literal: "+this.c};function L(a,b){this.o=a.toLowerCase();a="*"==this.o?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():a}L.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=void 0!==a.localName?a.localName:a.nodeName;return"*"!=this.o&&this.o!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};L.prototype.h=function(){return this.o};
L.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.o};function Rb(a){O.call(this,1);this.c=a}n(Rb,O);Rb.prototype.a=function(){return this.c};Rb.prototype.toString=function(){return"Number: "+this.c};function Sb(a,b){O.call(this,a.l);this.j=a;this.c=b;this.i=a.i;this.b=a.b;1==this.c.length&&(a=this.c[0],a.D||a.c!=Tb||(a=a.v,"*"!=a.h()&&(this.h={name:a.h(),B:null})))}n(Sb,O);function Ub(){O.call(this,4)}n(Ub,O);Ub.prototype.a=function(a){var b=new K;a=a.a;9==a.nodeType?M(b,a):M(b,a.ownerDocument);return b};Ub.prototype.toString=function(){return"Root Helper Expression"};function Vb(){O.call(this,4)}n(Vb,O);Vb.prototype.a=function(a){var b=new K;M(b,a.a);return b};Vb.prototype.toString=function(){return"Context Helper Expression"};
function Wb(a){return"/"==a||"//"==a}Sb.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof K))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.s;c++){var e=a[c],f=b.iterator(e.c.A);if(e.i||e.c!=Xb)if(e.i||e.c!=Yb){var h=f.next();for(b=e.a(new D(h));h=f.next();)h=e.a(new D(h)),b=yb(b,h)}else h=f.next(),b=e.a(new D(h));else{for(h=f.next();(b=f.next())&&(!h.contains||h.contains(b))&&b.compareDocumentPosition(h)&8;h=b);b=e.a(new D(h))}}return b};
Sb.prototype.toString=function(){var a="Path Expression:"+P(this.j);if(this.c.length){var b=q(this.c,function(a,b){return a+P(b)},"Steps:");a+=P(b)}return a};function Zb(a,b){this.a=a;this.A=!!b}
function Lb(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=b.iterator(),f=b.s,h,l=0;h=e.next();l++){var x=a.A?f-l:l+1;h=d.a(new D(h,x,f));if("number"==typeof h)x=x==h;else if("string"==typeof h||"boolean"==typeof h)x=!!h;else if(h instanceof K)x=0<h.s;else throw Error("Predicate.evaluate returned an unexpected type.");if(!x){x=e;h=x.h;var E=x.a;if(!E)throw Error("Next must be called at least once before remove.");var ba=E.a,E=E.next;ba?ba.next=E:h.a=E;E?E.a=ba:h.b=ba;h.s--;x.a=null}}return b}
Zb.prototype.toString=function(){return q(this.a,function(a,b){return a+P(b)},"Predicates:")};function V(a,b,c,d){O.call(this,4);this.c=a;this.v=b;this.j=c||new Zb([]);this.D=!!d;b=this.j;b=0<b.a.length?b.a[0].h:null;a.N&&b&&(a=b.name,a=F?a.toLowerCase():a,this.h={name:a,B:b.B});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.l||0==c.l){a=!0;break a}a=!1}this.i=a}n(V,O);
V.prototype.a=function(a){var b=a.a,c=this.h,d=null,e=null,f=0;c&&(d=c.name,e=c.B?R(c.B,a):null,f=1);if(this.D)if(this.i||this.c!=$b)if(b=(new V(ac,new N("node"))).a(a).iterator(),c=b.next())for(a=this.u(c,d,e,f);c=b.next();)a=yb(a,this.u(c,d,e,f));else a=new K;else a=qb(this.v,b,d,e),a=Lb(this.j,a,f);else a=this.u(a.a,d,e,f);return a};V.prototype.u=function(a,b,c,d){a=this.c.C(this.v,a,b,c);return a=Lb(this.j,a,d)};
V.prototype.toString=function(){var a="Step:"+P("Operator: "+(this.D?"//":"/"));this.c.o&&(a+=P("Axis: "+this.c));a+=P(this.v);if(this.j.a.length){var b=q(this.j.a,function(a,b){return a+P(b)},"Predicates:");a+=P(b)}return a};function bc(a,b,c,d){this.o=a;this.C=b;this.A=c;this.N=d}bc.prototype.toString=function(){return this.o};var cc={};function W(a,b,c,d){if(cc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new bc(a,b,c,!!d);return cc[a]=b}
W("ancestor",function(a,b){for(var c=new K;b=b.parentNode;)a.a(b)&&zb(c,b);return c},!0);W("ancestor-or-self",function(a,b){var c=new K;do a.a(b)&&zb(c,b);while(b=b.parentNode);return c},!0);
var Tb=W("attribute",function(a,b){var c=new K,d=a.h();if("style"==d&&F&&b.style)return M(c,new G(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof N&&null===a.b||"*"==d)for(d=0;a=e[d];d++)F?a.nodeValue&&M(c,kb(b,a)):M(c,a);else(a=e.getNamedItem(d))&&(F?a.nodeValue&&M(c,kb(b,a)):M(c,a));return c},!1),$b=W("child",function(a,b,c,d,e){return(F?vb:wb).call(null,a,b,k(c)?c:null,k(d)?d:null,e||new K)},!1,!0);W("descendant",qb,!1,!0);
var ac=W("descendant-or-self",function(a,b,c,d){var e=new K;J(b,c,d)&&a.a(b)&&M(e,b);return qb(a,b,c,d,e)},!1,!0),Xb=W("following",function(a,b,c,d){var e=new K;do for(var f=b;f=f.nextSibling;)J(f,c,d)&&a.a(f)&&M(e,f),e=qb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);W("following-sibling",function(a,b){for(var c=new K;b=b.nextSibling;)a.a(b)&&M(c,b);return c},!1);W("namespace",function(){return new K},!1);
var dc=W("parent",function(a,b){var c=new K;if(9==b.nodeType)return c;if(2==b.nodeType)return M(c,b.ownerElement),c;b=b.parentNode;a.a(b)&&M(c,b);return c},!1),Yb=W("preceding",function(a,b,c,d){var e=new K,f=[];do f.unshift(b);while(b=b.parentNode);for(var h=1,l=f.length;h<l;h++){var x=[];for(b=f[h];b=b.previousSibling;)x.unshift(b);for(var E=0,ba=x.length;E<ba;E++)b=x[E],J(b,c,d)&&a.a(b)&&M(e,b),e=qb(a,b,c,d,e)}return e},!0,!0);
W("preceding-sibling",function(a,b){for(var c=new K;b=b.previousSibling;)a.a(b)&&zb(c,b);return c},!0);var ec=W("self",function(a,b){var c=new K;a.a(b)&&M(c,b);return c},!1);function fc(a){O.call(this,1);this.c=a;this.i=a.i;this.b=a.b}n(fc,O);fc.prototype.a=function(a){return-Q(this.c,a)};fc.prototype.toString=function(){return"Unary Expression: -"+P(this.c)};function gc(a){O.call(this,4);this.c=a;Db(this,qa(this.c,function(a){return a.i}));Eb(this,qa(this.c,function(a){return a.b}))}n(gc,O);gc.prototype.a=function(a){var b=new K;p(this.c,function(c){c=c.a(a);if(!(c instanceof K))throw Error("Path expression must evaluate to NodeSet.");b=yb(b,c)});return b};gc.prototype.toString=function(){return q(this.c,function(a,b){return a+P(b)},"Union Expression:")};function hc(a,b){this.a=a;this.b=b}function ic(a){for(var b,c=[];;){X(a,"Missing right hand side of binary expression.");b=jc(a);var d=a.a.next();if(!d)break;var e=(d=Jb[d]||null)&&d.I;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].I;)b=new Fb(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Fb(c.pop(),c.pop(),b);return b}function X(a,b){if(pb(a.a))throw Error(b);}function kc(a,b){a=a.a.next();if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function lc(a){a=a.a.next();if(")"!=a)throw Error("Bad token: "+a);}function mc(a){a=a.a.next();if(2>a.length)throw Error("Unclosed literal string");return new Qb(a)}
function nc(a){var b=[];if(Wb(H(a.a))){var c=a.a.next();var d=H(a.a);if("/"==c&&(pb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new Ub;d=new Ub;X(a,"Missing next location step.");c=oc(a,c);b.push(c)}else{a:{c=H(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":a.a.next();c=ic(a);X(a,'unclosed "("');kc(a,")");break;case '"':case "'":c=mc(a);break;default:if(isNaN(+c))if(!Pb(c)&&/(?![0-9])[\w]/.test(d)&&"("==H(a.a,
1)){c=a.a.next();c=Ob[c]||null;a.a.next();for(d=[];")"!=H(a.a);){X(a,"Missing function argument list.");d.push(ic(a));if(","!=H(a.a))break;a.a.next()}X(a,"Unclosed function argument list.");lc(a);c=new Mb(c,d)}else{c=null;break a}else c=new Rb(+a.a.next())}"["==H(a.a)&&(d=new Zb(pc(a)),c=new Kb(c,d))}if(c)if(Wb(H(a.a)))d=c;else return c;else c=oc(a,"/"),d=new Vb,b.push(c)}for(;Wb(H(a.a));)c=a.a.next(),X(a,"Missing next location step."),c=oc(a,c),b.push(c);return new Sb(d,b)}
function oc(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==H(a.a)){var c=new V(ec,new N("node"));a.a.next();return c}if(".."==H(a.a))return c=new V(dc,new N("node")),a.a.next(),c;if("@"==H(a.a)){var d=Tb;a.a.next();X(a,"Missing attribute name")}else if("::"==H(a.a,1)){if(!/(?![0-9])[\w]/.test(H(a.a).charAt(0)))throw Error("Bad token: "+a.a.next());var e=a.a.next();d=cc[e]||null;if(!d)throw Error("No axis with name: "+e);a.a.next();X(a,"Missing node name")}else d=$b;e=
H(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==H(a.a,1)){if(!Pb(e))throw Error("Invalid node type: "+e);e=a.a.next();if(!Pb(e))throw Error("Invalid type name: "+e);kc(a,"(");X(a,"Bad nodetype");var f=H(a.a).charAt(0),h=null;if('"'==f||"'"==f)h=mc(a);X(a,"Bad nodetype");lc(a);e=new N(e,h)}else if(e=a.a.next(),f=e.indexOf(":"),-1==f)e=new L(e);else{var h=e.substring(0,f);if("*"==h)var l="*";else if(l=a.b(h),!l)throw Error("Namespace prefix not declared: "+h);e=e.substr(f+1);e=new L(e,l)}else throw Error("Bad token: "+
a.a.next());a=new Zb(pc(a),d.A);return c||new V(d,e,a,"//"==b)}function pc(a){for(var b=[];"["==H(a.a);){a.a.next();X(a,"Missing predicate expression.");var c=ic(a);b.push(c);X(a,"Unclosed predicate expression.");kc(a,"]")}return b}function jc(a){if("-"==H(a.a))return a.a.next(),new fc(jc(a));var b=nc(a);if("|"!=H(a.a))a=b;else{for(b=[b];"|"==a.a.next();)X(a,"Missing next union location path."),b.push(nc(a));a.a.a--;a=new gc(b)}return a};function qc(a){switch(a.nodeType){case 1:return ha(rc,a);case 9:return qc(a.documentElement);case 11:case 10:case 6:case 12:return sc;default:return a.parentNode?qc(a.parentNode):sc}}function sc(){return null}function rc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?rc(a.parentNode,b):null};function tc(a,b){if(!a.length)throw Error("Empty XPath expression.");a=mb(a);if(pb(a))throw Error("Invalid XPath expression.");b?"function"==m(b)||(b=ga(b.lookupNamespaceURI,b)):b=function(){return null};var c=ic(new hc(a,b));if(!pb(a))throw Error("Bad token: "+a.next());this.evaluate=function(a,b){a=c.a(new D(a));return new Y(a,b)}}
function Y(a,b){if(!b)if(a instanceof K)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof K))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof K?Bb(a):""+a;break;case 1:this.numberValue=a instanceof K?+Bb(a):+a;break;case 3:this.booleanValue=a instanceof K?0<a.s:!!a;break;case 4:case 5:case 6:case 7:var c=
a.iterator();var d=[];for(var e=c.next();e;e=c.next())d.push(e instanceof G?e.a:e);this.snapshotLength=a.s;this.invalidIteratorState=!1;break;case 8:case 9:a=Ab(a);this.singleNodeValue=a instanceof G?a.a:a;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");
return a>=d.length||0>a?null:d[a]}}Y.ANY_TYPE=0;Y.NUMBER_TYPE=1;Y.STRING_TYPE=2;Y.BOOLEAN_TYPE=3;Y.UNORDERED_NODE_ITERATOR_TYPE=4;Y.ORDERED_NODE_ITERATOR_TYPE=5;Y.UNORDERED_NODE_SNAPSHOT_TYPE=6;Y.ORDERED_NODE_SNAPSHOT_TYPE=7;Y.ANY_UNORDERED_NODE_TYPE=8;Y.FIRST_ORDERED_NODE_TYPE=9;function uc(a){this.lookupNamespaceURI=qc(a)}
aa("wgxpath.install",function(a,b){a=a||g;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=Y,c.evaluate=function(a,b,c,h){return(new tc(a,c)).evaluate(b,h)},c.createExpression=function(a,b){return new tc(a,b)},c.createNSResolver=function(a){return new uc(a)}});function vc(a,b){b=ma(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b=eb?"styleFloat":"cssFloat";a:{var c=b;var d=9==a.nodeType?a:a.ownerDocument||a.document;if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||wc(a,b);if(null===a)a=null;else if(0<=na(va,b)){b:{var e=a.match(ya);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d&&0<=e&&1>=e)){b=[b,
c,d,e];break b}b=null}if(!b)b:{if(d=a.match(za))if(b=Number(d[1]),c=Number(d[2]),d=Number(d[3]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=ua[b.toLowerCase()];if(!c&&(c="#"==b.charAt(0)?b:"#"+b,4==c.length&&(c=c.replace(wa,"#$1$1$2$2$3$3")),!xa.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function wc(a,b){var c=a.currentStyle||a.style,d=c[b];void 0===d&&"function"==m(c.getPropertyValue)&&(d=c.getPropertyValue(b));if("inherit"!=d)return void 0!==d?d:null;var e;for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;e&&"string"!==typeof e&&(e=e.toString());return(e=!a||1!=a.nodeType||e&&a.tagName.toUpperCase()!=e?null:a)?wc(e,b):null};Na||C&&C&&B(3.6);y&&db(10);$a&&C&&B(4);function xc(a,b){this.w={};this.m=[];this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof xc){d=yc(a);zc(a);var e=[];for(c=0;c<a.m.length;c++)e.push(a.w[a.m[c]])}else{var c=[],f=0;for(d in a)c[f++]=d;d=c;c=[];f=0;for(e in a)c[f++]=a[e];e=c}for(c=0;c<d.length;c++)this.set(d[c],e[c])}}function yc(a){zc(a);return a.m.concat()}
function zc(a){var b,c;if(a.a!=a.m.length){for(b=c=0;c<a.m.length;){var d=a.m[c];Object.prototype.hasOwnProperty.call(a.w,d)&&(a.m[b++]=d);c++}a.m.length=b}if(a.a!=a.m.length){var e={};for(b=c=0;c<a.m.length;)d=a.m[c],Object.prototype.hasOwnProperty.call(e,d)||(a.m[b++]=d,e[d]=1),c++;a.m.length=b}}xc.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.w,a)?this.w[a]:b};
xc.prototype.set=function(a,b){Object.prototype.hasOwnProperty.call(this.w,a)||(this.a++,this.m.push(a));this.w[a]=b};var Ac={};function Z(a,b,c){da(a)&&(a=Ma?a.f:a.g);a=new Bc(a);!b||b in Ac&&!c||(Ac[b]={key:a,shift:!1},c&&(Ac[c]={key:a,shift:!0}));return a}function Bc(a){this.code=a}Z(8);Z(9);Z(13);var Cc=Z(16),Dc=Z(17),Ec=Z(18);Z(19);Z(20);Z(27);Z(32," ");Z(33);Z(34);Z(35);Z(36);Z(37);Z(38);Z(39);Z(40);Z(44);Z(45);Z(46);Z(48,"0",")");Z(49,"1","!");Z(50,"2","@");Z(51,"3","#");Z(52,"4","$");Z(53,"5","%");Z(54,"6","^");Z(55,"7","&");Z(56,"8","*");Z(57,"9","(");Z(65,"a","A");Z(66,"b","B");Z(67,"c","C");Z(68,"d","D");
Z(69,"e","E");Z(70,"f","F");Z(71,"g","G");Z(72,"h","H");Z(73,"i","I");Z(74,"j","J");Z(75,"k","K");Z(76,"l","L");Z(77,"m","M");Z(78,"n","N");Z(79,"o","O");Z(80,"p","P");Z(81,"q","Q");Z(82,"r","R");Z(83,"s","S");Z(84,"t","T");Z(85,"u","U");Z(86,"v","V");Z(87,"w","W");Z(88,"x","X");Z(89,"y","Y");Z(90,"z","Z");var Fc=Z(Pa?{f:91,g:91}:Oa?{f:224,g:91}:{f:0,g:91});Z(Pa?{f:92,g:92}:Oa?{f:224,g:93}:{f:0,g:92});Z(Pa?{f:93,g:93}:Oa?{f:0,g:0}:{f:93,g:null});Z({f:96,g:96},"0");Z({f:97,g:97},"1");
Z({f:98,g:98},"2");Z({f:99,g:99},"3");Z({f:100,g:100},"4");Z({f:101,g:101},"5");Z({f:102,g:102},"6");Z({f:103,g:103},"7");Z({f:104,g:104},"8");Z({f:105,g:105},"9");Z({f:106,g:106},"*");Z({f:107,g:107},"+");Z({f:109,g:109},"-");Z({f:110,g:110},".");Z({f:111,g:111},"/");Z(144);Z(112);Z(113);Z(114);Z(115);Z(116);Z(117);Z(118);Z(119);Z(120);Z(121);Z(122);Z(123);Z({f:107,g:187},"=","+");Z(108,",");Z({f:109,g:189},"-","_");Z(188,",","<");Z(190,".",">");Z(191,"/","?");Z(192,"`","~");Z(219,"[","{");
Z(220,"\\","|");Z(221,"]","}");Z({f:59,g:186},";",":");Z(222,"'",'"');var Gc=new xc;Gc.set(1,Cc);Gc.set(2,Dc);Gc.set(4,Ec);Gc.set(8,Fc);(function(a){var b=new xc;p(yc(a),function(c){b.set(a.get(c).code,c)});return b})(Gc);Ma&&db(12);function Hc(){}
function Ic(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if("array"==m(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Ic(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Jc(d,c),c.push(":"),Ic(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Jc(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var Kc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Lc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Jc(a,b){b.push('"',a.replace(Lc,function(a){var b=Kc[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Kc[a]=b);return b}),'"')};Na||Ma&&db(3.5)||y&&db(8);function Mc(a){function b(a,d){switch(m(a)){case "string":case "number":case "boolean":return a;case "function":return a.toString();case "array":return pa(a,function(a){return b(a,d)});case "object":if(0<=d.indexOf(a))throw new r(13,"Recursive object cannot be transferred");if(w(a,"nodeType")&&(1==a.nodeType||9==a.nodeType)){var c={};c.ELEMENT=Nc(a);return c}if(w(a,"document"))return c={},c.WINDOW=Nc(a),c;d.push(a);if(ca(a))return pa(a,function(a){return b(a,d)});a=Da(a,function(a,b){return"number"==
typeof b||k(b)});return Ea(a,function(a){return b(a,d)});default:return null}}return b(a,[])}function Oc(a,b){return"array"==m(a)?pa(a,function(a){return Oc(a,b)}):da(a)?"function"==typeof a?a:w(a,"ELEMENT")?Pc(a.ELEMENT,b):w(a,"WINDOW")?Pc(a.WINDOW,b):Ea(a,function(a){return Oc(a,b)}):a}function Qc(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.G=ia());b.G||(b.G=ia());return b}function Nc(a){var b=Qc(a.ownerDocument),c=Fa(b,function(b){return b==a});c||(c=":wdc:"+b.G++,b[c]=a);return c}
function Pc(a,b){a=decodeURIComponent(a);b=b||document;var c=Qc(b);if(!w(c,a))throw new r(10,"Element does not exist in cache");var d=c[a];if(w(d,"setInterval")){if(d.closed)throw delete c[a],new r(23,"Window has been closed.");return d}for(var e=d;e;){if(e==b.documentElement)return d;e=e.parentNode}delete c[a];throw new r(10,"Element is no longer attached to the DOM");};aa("_",function(a,b,c){a=[a,b];try{var d;c?d=Pc(c.WINDOW):d=window;var e=Oc(a,d.document),f=vc.apply(null,e);var h={status:0,value:Mc(f)}}catch(l){h={status:w(l,"code")?l.code:13,value:{message:l.message}}}c=[];Ic(new Hc,h,c);return c.join("")});; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
