function(){return (function(){/*

 Copyright The Closure Library Authors.
 Copyright The Closure Compiler Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var b=b||{},c=this||self;try{var f=window}catch(a){f=c};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function l(a,d){this.code=a;this.g=m[a]||n;this.message=d||"";a=this.g.replace(/((?:^|\s+)[a-z])/g,function(e){return e.toUpperCase().replace(/^[\s\xa0]+/g,"")});d=a.length-5;if(d<0||a.indexOf("Error",d)!=d)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}(function(){function a(){}a.prototype=Error.prototype;l.prototype=new a;l.prototype.constructor=l})();var n="unknown error",m={15:"element not selectable",11:"element not visible"};m[31]=n;m[30]=n;m[24]="invalid cookie domain";
m[29]="invalid element coordinates";m[12]="invalid element state";m[32]="invalid selector";m[51]="invalid selector";m[52]="invalid selector";m[17]="javascript error";m[405]="unsupported operation";m[34]="move target out of bounds";m[27]="no such alert";m[7]="no such element";m[8]="no such frame";m[23]="no such window";m[28]="script timeout";m[33]="session not created";m[10]="stale element reference";m[21]="timeout";m[25]="unable to set cookie";m[26]="unexpected alert open";m[13]=n;m[9]="unknown command";var p=b.h&&String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function q(a,d){var e=0;a=p(String(a)).split(".");d=p(String(d)).split(".");for(var t=Math.max(a.length,d.length),k=0;e==0&&k<t;k++){var g=a[k]||"",h=d[k]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(g[0].length==0&&h[0].length==0)break;e=r(g[1].length==0?0:parseInt(g[1],10),h[1].length==0?0:parseInt(h[1],10))||r(g[2].length==0,h[2].length==0)||r(g[2],h[2]);g=g[3];h=h[3]}while(e==0)}return e}function r(a,d){return a<d?-1:a>d?1:0};function u(){var a=c.navigator;return a&&(a=a.userAgent)?a:""}function v(a){return u().indexOf(a)!=-1};function w(){return v("Firefox")||v("FxiOS")}function x(){return(v("Chrome")||v("CriOS"))&&!v("Edge")||v("Silk")};function y(){return v("iPhone")&&!v("iPod")&&!v("iPad")};var z=v("Windows");var A=w(),B=y()||v("iPod"),C=v("iPad"),D=v("Android")&&!(x()||w()||v("Opera")||v("Silk")),E=x(),F=v("Safari")&&!(x()||v("Coast")||v("Opera")||v("Edge")||v("Edg/")||v("OPR")||w()||v("Silk")||v("Android"))&&!(y()||v("iPad")||v("iPod"));function G(a){return(a=a.exec(u()))?a[1]:""}var H=function(){if(A)return G(/Firefox\/([0-9.]+)/);if(E){if(y()||v("iPad")||v("iPod")||v("Macintosh")){var a=G(/CriOS\/([0-9.]+)/);if(a)return a}return G(/Chrome\/([0-9.]+)/)}if(F&&!(y()||v("iPad")||v("iPod")))return G(/Version\/([0-9.]+)/);if(B||C){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(u()))return a[1]+"."+a[2]}else if(D)return(a=G(/Android\s+([0-9.]+)/))?a:G(/Version\/([0-9.]+)/);return""}();var I;if(D){var J=/Android\s+([0-9\.]+)/.exec(u());I=J?J[1]:"0"}else I="0";var K=I;var L=z&&F&&(D?q(K,4)>=0:q(H,4)>=0)&&!(D?q(K,6)>=0:q(H,6)>=0);var M={enableHighAccuracy:!0,maximumAge:Infinity,timeout:5E3};function N(a,d,e){var t=f;e=e||M;var k=t||f;if(L?0:k.navigator!=null&&k.navigator.geolocation!=null)t.navigator.geolocation.getCurrentPosition(a,d,e);else throw new l(13,"Geolocation undefined");}var O=["se_exportedFunctionSymbol"],P=c;O[0]in P||typeof P.execScript=="undefined"||P.execScript("var "+O[0]);for(var Q;O.length&&(Q=O.shift());)O.length||N===void 0?P[Q]&&P[Q]!==Object.prototype[Q]?P=P[Q]:P=P[Q]={}:P[Q]=N;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
