function(){return function(){var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},da="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ea(a,b){if(b){for(var c=da,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&ca(c,d,{configurable:!0,writable:!0,value:f})}}
ea("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=c),a>>>=1)c+=c;return d}});ea("Math.sign",function(a){return a?a:function(a){a=Number(a);return!a||isNaN(a)?a:0<a?1:-1}});var g=this;
function fa(a,b){var c=a.split("."),d=g;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}
function l(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ga(a){var b=l(a);return"array"==b||"object"==b&&"number"==typeof a.length}function m(a){return"string"==typeof a}function ha(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ia(a,b,c){return a.call.apply(a.bind,arguments)}
function ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ka(a,b,c){ka=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return ka.apply(null,arguments)}
function la(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ma=Date.now||function(){return+new Date};function n(a,b){function c(){}c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.K=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};var na=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function oa(a,b){for(var c=0,d=na(String(a)).split("."),e=na(String(b)).split("."),f=Math.max(d.length,e.length),h=0;!c&&h<f;h++){var k=d[h]||"",u=e[h]||"",z=RegExp("(\\d*)(\\D*)","g"),N=RegExp("(\\d*)(\\D*)","g");do{var aa=z.exec(k)||["","",""],ba=N.exec(u)||["","",""];if(0==aa[0].length&&0==ba[0].length)break;c=pa(0==aa[1].length?0:parseInt(aa[1],10),0==ba[1].length?0:parseInt(ba[1],10))||pa(0==aa[2].length,0==ba[2].length)||pa(aa[2],ba[2])}while(!c)}return c}
function pa(a,b){return a<b?-1:a>b?1:0}function qa(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};function ra(a,b){if(m(a))return m(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function p(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function sa(a,b){for(var c=a.length,d=[],e=0,f=m(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d}
function ta(a,b){for(var c=a.length,d=Array(c),e=m(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function q(a,b,c){var d=c;p(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function ua(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function va(a,b){var c;a:{c=a.length;for(var d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:m(a)?a.charAt(c):a[c]}
function wa(a){return Array.prototype.concat.apply(Array.prototype,arguments)}function xa(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var ya={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var za="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Aa=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Ba=/^#(?:[0-9a-f]{3}){1,2}$/i,Ca=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Da=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function Ea(a,b){this.code=a;this.a=r[a]||Fa;this.message=b||"";var c=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=c.length-5;if(0>d||c.indexOf("Error",d)!=d)c+="Error";this.name=c;c=Error(this.message);c.name=this.name;this.stack=c.stack||""}n(Ea,Error);var Fa="unknown error",r={15:"element not selectable",11:"element not visible"};r[31]=Fa;r[30]=Fa;r[24]="invalid cookie domain";r[29]="invalid element coordinates";r[12]="invalid element state";
r[32]="invalid selector";r[51]="invalid selector";r[52]="invalid selector";r[17]="javascript error";r[405]="unsupported operation";r[34]="move target out of bounds";r[27]="no such alert";r[7]="no such element";r[8]="no such frame";r[23]="no such window";r[28]="script timeout";r[33]="session not created";r[10]="stale element reference";r[21]="timeout";r[25]="unable to set cookie";r[26]="unexpected alert open";r[13]=Fa;r[9]="unknown command";Ea.prototype.toString=function(){return this.name+": "+this.message};var t;a:{var Ga=g.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){t=Ha;break a}}t=""}function v(a){return-1!=t.indexOf(a)};function Ia(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function Ja(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function Ka(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function La(){return v("Opera")||v("OPR")}function Ma(){return(v("Chrome")||v("CriOS"))&&!La()&&!v("Edge")};function Na(){return v("iPhone")&&!v("iPod")&&!v("iPad")};var Oa=La(),w=v("Trident")||v("MSIE"),Pa=v("Edge"),x=v("Gecko")&&!(-1!=t.toLowerCase().indexOf("webkit")&&!v("Edge"))&&!(v("Trident")||v("MSIE"))&&!v("Edge"),Qa=-1!=t.toLowerCase().indexOf("webkit")&&!v("Edge"),Ra=v("Macintosh"),Sa=v("Windows");function Ta(){var a=t;if(x)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Pa)return/Edge\/([\d\.]+)/.exec(a);if(w)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Qa)return/WebKit\/(\S+)/.exec(a)}function Ua(){var a=g.document;return a?a.documentMode:void 0}
var Va=function(){if(Oa&&g.opera){var a;var b=g.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Ta())&&(a=b?b[1]:"");return w&&(b=Ua(),null!=b&&b>parseFloat(a))?String(b):a}(),Wa={};function Xa(a){return Wa[a]||(Wa[a]=0<=oa(Va,a))}var Ya=g.document,y=Ya&&w?Ua()||("CSS1Compat"==Ya.compatMode?parseInt(Va,10):5):void 0;var Za=v("Firefox"),$a=Na()||v("iPod"),ab=v("iPad"),A=v("Android")&&!(Ma()||v("Firefox")||La()||v("Silk")),bb=Ma(),cb=v("Safari")&&!(Ma()||v("Coast")||La()||v("Edge")||v("Silk")||v("Android"))&&!(Na()||v("iPad")||v("iPod"));function db(a){return(a=a.exec(t))?a[1]:""}var eb=function(){if(Za)return db(/Firefox\/([0-9.]+)/);if(w||Pa||Oa)return Va;if(bb)return db(/Chrome\/([0-9.]+)/);if(cb&&!(Na()||v("iPad")||v("iPod")))return db(/Version\/([0-9.]+)/);if($a||ab){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(t);if(a)return a[1]+"."+a[2]}else if(A)return(a=db(/Android\s+([0-9.]+)/))?a:db(/Version\/([0-9.]+)/);return""}();var fb,gb;function hb(a){return ib?fb(a):w?0<=oa(y,a):Xa(a)}function jb(a){ib?gb(a):A?oa(kb,a):oa(eb,a)}
var ib=function(){if(!x)return!1;var a=g.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;fb=function(a){return 0<=c.compare(d,""+a)};gb=function(a){c.compare(e,""+a)};return!0}(),lb;if(A){var mb=/Android\s+([0-9\.]+)/.exec(t);lb=mb?mb[1]:"0"}else lb="0";
var kb=lb,nb=w&&!(9<=Number(y));A&&jb(2.3);A&&jb(4);cb&&jb(6);!x&&!w||w&&9<=Number(y)||x&&Xa("1.9.1");w&&Xa("9");function ob(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function pb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(w&&!(9<=Number(y))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?qb(a,b):!c&&ob(e,b)?-1*rb(a,b):!d&&ob(f,a)?rb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=9==a.nodeType?
a:a.ownerDocument||a.document;c=d.createRange();c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(g.Range.START_TO_END,d)}function rb(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return qb(d,a)}function qb(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function B(a,b,c){this.a=a;this.b=b||1;this.h=c||1};var C=w&&!(9<=Number(y)),sb=w&&!(8<=Number(y));function D(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function tb(a,b){var c=sb&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new D(b,a,b.nodeName,c)};function ub(a){this.b=a;this.a=0}function vb(a){a=a.match(wb);for(var b=0;b<a.length;b++)xb.test(a[b])&&a.splice(b,1);return new ub(a)}var wb=RegExp("\\$?(?:(?![0-9-\\.])(?:\\*|[\\w-\\.]+):)?(?![0-9-\\.])(?:\\*|[\\w-\\.]+)|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),xb=/^\s/;function E(a,b){return a.b[a.a+(b||0)]}ub.prototype.next=function(){return this.b[this.a++]};function yb(a){return a.b.length<=a.a};function F(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(C&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),C&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function G(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}sb&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function zb(a,b,c,d,e){return(C?Ab:Bb).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new H)}
function Ab(a,b,c,d,e){if(a instanceof I||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;a=Cb(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var h=[],k=0;b=f[k++];)G(b,c,d)&&h.push(b);f=h}for(k=0;b=f[k++];)"*"==a&&"!"==b.tagName||J(e,b);return e}Db(a,b,c,d,e);return e}
function Bb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!w?(b=b.getElementsByName(d),p(b,function(b){a.a(b)&&J(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),p(b,function(b){b.className==d&&a.a(b)&&J(e,b)})):a instanceof K?Db(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.h()),p(b,function(a){G(a,c,d)&&J(e,a)}));return e}
function Eb(a,b,c,d,e){var f;if((a instanceof I||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var h=Cb(a);if("*"!=h&&(f=sa(f,function(a){return a.tagName&&a.tagName.toLowerCase()==h}),!f))return e;c&&(f=sa(f,function(a){return G(a,c,d)}));p(f,function(a){"*"==h&&("!"==a.tagName||"*"==h&&1!=a.nodeType)||J(e,a)});return e}return Fb(a,b,c,d,e)}function Fb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)G(b,c,d)&&a.a(b)&&J(e,b);return e}
function Db(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)G(b,c,d)&&a.a(b)&&J(e,b),Db(a,b,c,d,e)}function Cb(a){if(a instanceof K){if(8==a.b)return"!";if(null===a.b)return"*"}return a.h()};function H(){this.b=this.a=null;this.s=0}function Gb(a){this.node=a;this.next=this.a=null}function Hb(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f,h=0;c&&d;){f=c.node;var k=d.node;f==k||f instanceof D&&k instanceof D&&f.a==k.a?(f=c,c=c.next,d=d.next):0<pb(c.node,d.node)?(f=d,d=d.next):(f=c,c=c.next);(f.a=e)?e.next=f:a.a=f;e=f;h++}for(f=c||d;f;)f.a=e,e=e.next=f,h++,f=f.next;a.b=e;a.s=h;return a}
H.prototype.unshift=function(a){a=new Gb(a);a.next=this.a;this.b?this.a.a=a:this.a=this.b=a;this.a=a;this.s++};function J(a,b){var c=new Gb(b);c.a=a.b;a.a?a.b.next=c:a.a=a.b=c;a.b=c;a.s++}function Ib(a){return(a=a.a)?a.node:null}function Jb(a){return(a=Ib(a))?F(a):""}H.prototype.iterator=function(a){return new Kb(this,!!a)};function Kb(a,b){this.h=a;this.b=(this.c=b)?a.b:a.a;this.a=null}Kb.prototype.next=function(){var a=this.b;if(a){var b=this.a=a;this.b=this.c?a.a:a.next;return b.node}return null};function L(a){this.m=a;this.b=this.i=!1;this.h=null}function M(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Lb(a,b){a.i=b}function Mb(a,b){a.b=b}function O(a,b){var c=a.a(b);return c instanceof H?+Jb(c):+c}function P(a,b){var c=a.a(b);return c instanceof H?Jb(c):""+c}function Q(a,b){var c=a.a(b);return c instanceof H?!!c.s:!!c};function Nb(a,b,c){L.call(this,a.m);this.c=a;this.j=b;this.w=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==Ob&&(c.b||c.i||4==c.m||0==c.m||!b.h?b.b||b.i||4==b.m||0==b.m||!c.h||(this.h={name:c.h.name,A:b}):this.h={name:b.h.name,A:c})}n(Nb,L);
function R(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof H&&c instanceof H){b=b.iterator();for(d=b.next();d;d=b.next())for(e=c.iterator(),f=e.next();f;f=e.next())if(a(F(d),F(f)))return!0;return!1}if(b instanceof H||c instanceof H){b instanceof H?(e=b,d=c):(e=c,d=b);f=e.iterator();for(var h=typeof d,k=f.next();k;k=f.next()){switch(h){case "number":k=+F(k);break;case "boolean":k=!!F(k);break;case "string":k=F(k);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(k,
d)||e==c&&a(d,k))return!0}return!1}return e?"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Nb.prototype.a=function(a){return this.c.v(this.j,this.w,a)};Nb.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+M(this.j);return a+=M(this.w)};function Pb(a,b,c,d){this.a=a;this.F=b;this.m=c;this.v=d}Pb.prototype.toString=function(){return this.a};var Qb={};
function S(a,b,c,d){if(Qb.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Pb(a,b,c,d);return Qb[a.toString()]=a}S("div",6,1,function(a,b,c){return O(a,c)/O(b,c)});S("mod",6,1,function(a,b,c){return O(a,c)%O(b,c)});S("*",6,1,function(a,b,c){return O(a,c)*O(b,c)});S("+",5,1,function(a,b,c){return O(a,c)+O(b,c)});S("-",5,1,function(a,b,c){return O(a,c)-O(b,c)});S("<",4,2,function(a,b,c){return R(function(a,b){return a<b},a,b,c)});
S(">",4,2,function(a,b,c){return R(function(a,b){return a>b},a,b,c)});S("<=",4,2,function(a,b,c){return R(function(a,b){return a<=b},a,b,c)});S(">=",4,2,function(a,b,c){return R(function(a,b){return a>=b},a,b,c)});var Ob=S("=",3,2,function(a,b,c){return R(function(a,b){return a==b},a,b,c,!0)});S("!=",3,2,function(a,b,c){return R(function(a,b){return a!=b},a,b,c,!0)});S("and",2,2,function(a,b,c){return Q(a,c)&&Q(b,c)});S("or",1,2,function(a,b,c){return Q(a,c)||Q(b,c)});function Rb(a,b){if(b.a.length&&4!=a.m)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");L.call(this,a.m);this.c=a;this.j=b;this.i=a.i;this.b=a.b}n(Rb,L);Rb.prototype.a=function(a){a=this.c.a(a);return Sb(this.j,a)};Rb.prototype.toString=function(){var a;a="Filter:"+M(this.c);return a+=M(this.j)};function Tb(a,b){if(b.length<a.G)throw Error("Function "+a.o+" expects at least"+a.G+" arguments, "+b.length+" given");if(null!==a.D&&b.length>a.D)throw Error("Function "+a.o+" expects at most "+a.D+" arguments, "+b.length+" given");a.H&&p(b,function(b,d){if(4!=b.m)throw Error("Argument "+d+" to function "+a.o+" is not of type Nodeset: "+b);});L.call(this,a.m);this.j=a;this.c=b;Lb(this,a.i||ua(b,function(a){return a.i}));Mb(this,a.J&&!b.length||a.I&&!!b.length||ua(b,function(a){return a.b}))}
n(Tb,L);Tb.prototype.a=function(a){return this.j.v.apply(null,wa(a,this.c))};Tb.prototype.toString=function(){var a="Function: "+this.j;if(this.c.length)var b=q(this.c,function(a,b){return a+M(b)},"Arguments:"),a=a+M(b);return a};function Ub(a,b,c,d,e,f,h,k,u){this.o=a;this.m=b;this.i=c;this.J=d;this.I=e;this.v=f;this.G=h;this.D=void 0!==k?k:h;this.H=!!u}Ub.prototype.toString=function(){return this.o};var Vb={};
function T(a,b,c,d,e,f,h,k){if(Vb.hasOwnProperty(a))throw Error("Function already created: "+a+".");Vb[a]=new Ub(a,b,c,d,!1,e,f,h,k)}T("boolean",2,!1,!1,function(a,b){return Q(b,a)},1);T("ceiling",1,!1,!1,function(a,b){return Math.ceil(O(b,a))},1);T("concat",3,!1,!1,function(a,b){return q(xa(arguments,1),function(b,d){return b+P(d,a)},"")},2,null);T("contains",2,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);return-1!=b.indexOf(a)},2);T("count",1,!1,!1,function(a,b){return b.a(a).s},1,1,!0);
T("false",2,!1,!1,function(){return!1},0);T("floor",1,!1,!1,function(a,b){return Math.floor(O(b,a))},1);T("id",4,!1,!1,function(a,b){function c(a){if(C){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return va(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=P(b,a).split(/\s+/),f=[];p(d,function(a){a=c(a);!a||0<=ra(f,a)||f.push(a)});f.sort(pb);var h=new H;p(f,function(a){J(h,a)});return h},1);
T("lang",2,!1,!1,function(){return!1},1);T("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.h},0);T("local-name",3,!1,!0,function(a,b){var c=b?Ib(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);T("name",3,!1,!0,function(a,b){var c=b?Ib(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);T("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
T("normalize-space",3,!1,!0,function(a,b){return(b?P(b,a):F(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);T("not",2,!1,!1,function(a,b){return!Q(b,a)},1);T("number",1,!1,!0,function(a,b){return b?O(b,a):+F(a.a)},0,1);T("position",1,!0,!1,function(a){return a.b},0);T("round",1,!1,!1,function(a,b){return Math.round(O(b,a))},1);T("starts-with",2,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);return!b.lastIndexOf(a,0)},2);T("string",3,!1,!0,function(a,b){return b?P(b,a):F(a.a)},0,1);
T("string-length",1,!1,!0,function(a,b){return(b?P(b,a):F(a.a)).length},0,1);T("substring",3,!1,!1,function(a,b,c,d){c=O(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?O(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=P(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);T("substring-after",3,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
T("substring-before",3,!1,!1,function(a,b,c){b=P(b,a);a=P(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);T("sum",1,!1,!1,function(a,b){for(var c=b.a(a).iterator(),d=0,e=c.next();e;e=c.next())d+=+F(e);return d},1,1,!0);T("translate",3,!1,!1,function(a,b,c,d){b=P(b,a);c=P(c,a);var e=P(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);T("true",2,!1,!1,function(){return!0},0);function K(a,b){this.j=a;this.c=b?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Wb(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}K.prototype.a=function(a){return null===this.b||this.b==a.nodeType};K.prototype.h=function(){return this.j};
K.prototype.toString=function(){var a="Kind Test: "+this.j;!this.c||(a+=M(this.c));return a};function Xb(a){L.call(this,3);this.c=a.substring(1,a.length-1)}n(Xb,L);Xb.prototype.a=function(){return this.c};Xb.prototype.toString=function(){return"Literal: "+this.c};function I(a,b){this.o=a.toLowerCase();var c;c="*"==this.o?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():c}I.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=void 0!==a.localName?a.localName:a.nodeName;return"*"!=this.o&&this.o!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};I.prototype.h=function(){return this.o};
I.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.o};function Yb(a){L.call(this,1);this.c=a}n(Yb,L);Yb.prototype.a=function(){return this.c};Yb.prototype.toString=function(){return"Number: "+this.c};function Zb(a,b){L.call(this,a.m);this.j=a;this.c=b;this.i=a.i;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.C||c.c!=$b||(c=c.w,"*"!=c.h()&&(this.h={name:c.h(),A:null}))}}n(Zb,L);function ac(){L.call(this,4)}n(ac,L);ac.prototype.a=function(a){var b=new H;a=a.a;9==a.nodeType?J(b,a):J(b,a.ownerDocument);return b};ac.prototype.toString=function(){return"Root Helper Expression"};function bc(){L.call(this,4)}n(bc,L);bc.prototype.a=function(a){var b=new H;J(b,a.a);return b};bc.prototype.toString=function(){return"Context Helper Expression"};
function cc(a){return"/"==a||"//"==a}Zb.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof H))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.s;c++){var e=a[c],f=b.iterator(e.c.a),h;if(e.i||e.c!=dc)if(e.i||e.c!=ec)for(h=f.next(),b=e.a(new B(h));h=f.next();)h=e.a(new B(h)),b=Hb(b,h);else h=f.next(),b=e.a(new B(h));else{for(h=f.next();(b=f.next())&&(!h.contains||h.contains(b))&&b.compareDocumentPosition(h)&8;h=b);b=e.a(new B(h))}}return b};
Zb.prototype.toString=function(){var a;a="Path Expression:"+M(this.j);if(this.c.length){var b=q(this.c,function(a,b){return a+M(b)},"Steps:");a+=M(b)}return a};function fc(a,b){this.a=a;this.b=!!b}
function Sb(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=b.iterator(),f=b.s,h,k=0;h=e.next();k++){var u=a.b?f-k:k+1;h=d.a(new B(h,u,f));if("number"==typeof h)u=u==h;else if("string"==typeof h||"boolean"==typeof h)u=!!h;else if(h instanceof H)u=0<h.s;else throw Error("Predicate.evaluate returned an unexpected type.");if(!u){u=e;h=u.h;var z=u.a;if(!z)throw Error("Next must be called at least once before remove.");var N=z.a,z=z.next;N?N.next=z:h.a=z;z?z.a=N:h.b=N;h.s--;u.a=null}}return b}
fc.prototype.toString=function(){return q(this.a,function(a,b){return a+M(b)},"Predicates:")};function U(a,b,c,d){L.call(this,4);this.c=a;this.w=b;this.j=c||new fc([]);this.C=!!d;b=this.j;b=0<b.a.length?b.a[0].h:null;a.b&&b&&(a=b.name,a=C?a.toLowerCase():a,this.h={name:a,A:b.A});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.m||0==c.m){a=!0;break a}a=!1}this.i=a}n(U,L);
U.prototype.a=function(a){var b=a.a,c=this.h,d=null,e=null,f=0;c&&(d=c.name,e=c.A?P(c.A,a):null,f=1);if(this.C)if(this.i||this.c!=gc)if(b=(new U(hc,new K("node"))).a(a).iterator(),c=b.next())for(a=this.v(c,d,e,f);c=b.next();)a=Hb(a,this.v(c,d,e,f));else a=new H;else a=zb(this.w,b,d,e),a=Sb(this.j,a,f);else a=this.v(a.a,d,e,f);return a};U.prototype.v=function(a,b,c,d){a=this.c.h(this.w,a,b,c);return a=Sb(this.j,a,d)};
U.prototype.toString=function(){var a;a="Step:"+M("Operator: "+(this.C?"//":"/"));this.c.o&&(a+=M("Axis: "+this.c));a+=M(this.w);if(this.j.a.length){var b=q(this.j.a,function(a,b){return a+M(b)},"Predicates:");a+=M(b)}return a};function ic(a,b,c,d){this.o=a;this.h=b;this.a=c;this.b=d}ic.prototype.toString=function(){return this.o};var jc={};function V(a,b,c,d){if(jc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new ic(a,b,c,!!d);return jc[a]=b}
V("ancestor",function(a,b){for(var c=new H,d=b;d=d.parentNode;)a.a(d)&&c.unshift(d);return c},!0);V("ancestor-or-self",function(a,b){var c=new H,d=b;do a.a(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var $b=V("attribute",function(a,b){var c=new H,d=a.h();if("style"==d&&C&&b.style)return J(c,new D(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof K&&null===a.b||"*"==d)for(var d=0,f;f=e[d];d++)C?f.nodeValue&&J(c,tb(b,f)):J(c,f);else(f=e.getNamedItem(d))&&(C?f.nodeValue&&J(c,tb(b,f)):J(c,f));return c},!1),gc=V("child",function(a,b,c,d,e){return(C?Eb:Fb).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new H)},!1,!0);V("descendant",zb,!1,!0);
var hc=V("descendant-or-self",function(a,b,c,d){var e=new H;G(b,c,d)&&a.a(b)&&J(e,b);return zb(a,b,c,d,e)},!1,!0),dc=V("following",function(a,b,c,d){var e=new H;do for(var f=b;f=f.nextSibling;)G(f,c,d)&&a.a(f)&&J(e,f),e=zb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);V("following-sibling",function(a,b){for(var c=new H,d=b;d=d.nextSibling;)a.a(d)&&J(c,d);return c},!1);V("namespace",function(){return new H},!1);
var kc=V("parent",function(a,b){var c=new H;if(9==b.nodeType)return c;if(2==b.nodeType)return J(c,b.ownerElement),c;var d=b.parentNode;a.a(d)&&J(c,d);return c},!1),ec=V("preceding",function(a,b,c,d){var e=new H,f=[];do f.unshift(b);while(b=b.parentNode);for(var h=1,k=f.length;h<k;h++){var u=[];for(b=f[h];b=b.previousSibling;)u.unshift(b);for(var z=0,N=u.length;z<N;z++)b=u[z],G(b,c,d)&&a.a(b)&&J(e,b),e=zb(a,b,c,d,e)}return e},!0,!0);
V("preceding-sibling",function(a,b){for(var c=new H,d=b;d=d.previousSibling;)a.a(d)&&c.unshift(d);return c},!0);var lc=V("self",function(a,b){var c=new H;a.a(b)&&J(c,b);return c},!1);function mc(a){L.call(this,1);this.c=a;this.i=a.i;this.b=a.b}n(mc,L);mc.prototype.a=function(a){return-O(this.c,a)};mc.prototype.toString=function(){return"Unary Expression: -"+M(this.c)};function nc(a){L.call(this,4);this.c=a;Lb(this,ua(this.c,function(a){return a.i}));Mb(this,ua(this.c,function(a){return a.b}))}n(nc,L);nc.prototype.a=function(a){var b=new H;p(this.c,function(c){c=c.a(a);if(!(c instanceof H))throw Error("Path expression must evaluate to NodeSet.");b=Hb(b,c)});return b};nc.prototype.toString=function(){return q(this.c,function(a,b){return a+M(b)},"Union Expression:")};function oc(a,b){this.a=a;this.b=b}function pc(a){for(var b,c=[];;){W(a,"Missing right hand side of binary expression.");b=qc(a);var d=a.a.next();if(!d)break;var e=(d=Qb[d]||null)&&d.F;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].F;)b=new Nb(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Nb(c.pop(),c.pop(),b);return b}function W(a,b){if(yb(a.a))throw Error(b);}function rc(a,b){var c=a.a.next();if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function sc(a){a=a.a.next();if(")"!=a)throw Error("Bad token: "+a);}function tc(a){a=a.a.next();if(2>a.length)throw Error("Unclosed literal string");return new Xb(a)}
function uc(a){var b,c=[],d;if(cc(E(a.a))){b=a.a.next();d=E(a.a);if("/"==b&&(yb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new ac;d=new ac;W(a,"Missing next location step.");b=vc(a,b);c.push(b)}else{a:{b=E(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":a.a.next();b=pc(a);W(a,'unclosed "("');rc(a,")");break;case '"':case "'":b=tc(a);break;default:if(isNaN(+b))if(!Wb(b)&&/(?![0-9])[\w]/.test(d)&&"("==E(a.a,1)){b=
a.a.next();b=Vb[b]||null;a.a.next();for(d=[];")"!=E(a.a);){W(a,"Missing function argument list.");d.push(pc(a));if(","!=E(a.a))break;a.a.next()}W(a,"Unclosed function argument list.");sc(a);b=new Tb(b,d)}else{b=null;break a}else b=new Yb(+a.a.next())}"["==E(a.a)&&(d=new fc(wc(a)),b=new Rb(b,d))}if(b)if(cc(E(a.a)))d=b;else return b;else b=vc(a,"/"),d=new bc,c.push(b)}for(;cc(E(a.a));)b=a.a.next(),W(a,"Missing next location step."),b=vc(a,b),c.push(b);return new Zb(d,c)}
function vc(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==E(a.a))return d=new U(lc,new K("node")),a.a.next(),d;if(".."==E(a.a))return d=new U(kc,new K("node")),a.a.next(),d;var f;if("@"==E(a.a))f=$b,a.a.next(),W(a,"Missing attribute name");else if("::"==E(a.a,1)){if(!/(?![0-9])[\w]/.test(E(a.a).charAt(0)))throw Error("Bad token: "+a.a.next());c=a.a.next();f=jc[c]||null;if(!f)throw Error("No axis with name: "+c);a.a.next();W(a,"Missing node name")}else f=gc;
c=E(a.a);if(/(?![0-9])[\w\*]/.test(c.charAt(0)))if("("==E(a.a,1)){if(!Wb(c))throw Error("Invalid node type: "+c);c=a.a.next();if(!Wb(c))throw Error("Invalid type name: "+c);rc(a,"(");W(a,"Bad nodetype");e=E(a.a).charAt(0);var h=null;if('"'==e||"'"==e)h=tc(a);W(a,"Bad nodetype");sc(a);c=new K(c,h)}else if(c=a.a.next(),e=c.indexOf(":"),-1==e)c=new I(c);else{var h=c.substring(0,e),k;if("*"==h)k="*";else if(k=a.b(h),!k)throw Error("Namespace prefix not declared: "+h);c=c.substr(e+1);c=new I(c,k)}else throw Error("Bad token: "+
a.a.next());e=new fc(wc(a),f.a);return d||new U(f,c,e,"//"==b)}function wc(a){for(var b=[];"["==E(a.a);){a.a.next();W(a,"Missing predicate expression.");var c=pc(a);b.push(c);W(a,"Unclosed predicate expression.");rc(a,"]")}return b}function qc(a){if("-"==E(a.a))return a.a.next(),new mc(qc(a));var b=uc(a);if("|"!=E(a.a))a=b;else{for(b=[b];"|"==a.a.next();)W(a,"Missing next union location path."),b.push(uc(a));a.a.a--;a=new nc(b)}return a};function xc(a){switch(a.nodeType){case 1:return la(yc,a);case 9:return xc(a.documentElement);case 11:case 10:case 6:case 12:return zc;default:return a.parentNode?xc(a.parentNode):zc}}function zc(){return null}function yc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?yc(a.parentNode,b):null};function Ac(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=vb(a);if(yb(c))throw Error("Invalid XPath expression.");b?"function"==l(b)||(b=ka(b.lookupNamespaceURI,b)):b=function(){return null};var d=pc(new oc(c,b));if(!yb(c))throw Error("Bad token: "+c.next());this.evaluate=function(a,b){var c=d.a(new B(a));return new X(c,b)}}
function X(a,b){if(!b)if(a instanceof H)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof H))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof H?Jb(a):""+a;break;case 1:this.numberValue=a instanceof H?+Jb(a):+a;break;case 3:this.booleanValue=a instanceof H?0<a.s:!!a;break;case 4:case 5:case 6:case 7:var d=
a.iterator();c=[];for(var e=d.next();e;e=d.next())c.push(e instanceof D?e.a:e);this.snapshotLength=a.s;this.invalidIteratorState=!1;break;case 8:case 9:d=Ib(a);this.singleNodeValue=d instanceof D?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=
c.length||0>a?null:c[a]}}X.ANY_TYPE=0;X.NUMBER_TYPE=1;X.STRING_TYPE=2;X.BOOLEAN_TYPE=3;X.UNORDERED_NODE_ITERATOR_TYPE=4;X.ORDERED_NODE_ITERATOR_TYPE=5;X.UNORDERED_NODE_SNAPSHOT_TYPE=6;X.ORDERED_NODE_SNAPSHOT_TYPE=7;X.ANY_UNORDERED_NODE_TYPE=8;X.FIRST_ORDERED_NODE_TYPE=9;function Bc(a){this.lookupNamespaceURI=xc(a)}
fa("wgxpath.install",function(a,b){var c=a||g,d=c.Document&&c.Document.prototype||c.document;if(!d.evaluate||b)c.XPathResult=X,d.evaluate=function(a,b,c,d){return(new Ac(a,c)).evaluate(b,d)},d.createExpression=function(a,b){return new Ac(a,b)},d.createNSResolver=function(a){return new Bc(a)}});function Cc(a,b){var c=qa(b);if("float"==c||"cssFloat"==c||"styleFloat"==c)c=nb?"styleFloat":"cssFloat";var d;a:{d=c;var e=9==a.nodeType?a:a.ownerDocument||a.document;if(e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))){d=e[d]||e.getPropertyValue(d)||"";break a}d=""}d=d||Dc(a,c);if(null===d)d=null;else if(0<=ra(za,c)){b:{var f=d.match(Ca);if(f){var c=Number(f[1]),e=Number(f[2]),h=Number(f[3]),f=Number(f[4]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=h&&255>=h&&0<=f&&
1>=f){c=[c,e,h,f];break b}}c=null}if(!c)b:{if(h=d.match(Da))if(c=Number(h[1]),e=Number(h[2]),h=Number(h[3]),0<=c&&255>=c&&0<=e&&255>=e&&0<=h&&255>=h){c=[c,e,h,1];break b}c=null}if(!c)b:{c=d.toLowerCase();e=ya[c.toLowerCase()];if(!e&&(e="#"==c.charAt(0)?c:"#"+c,4==e.length&&(e=e.replace(Aa,"#$1$1$2$2$3$3")),!Ba.test(e))){c=null;break b}c=[parseInt(e.substr(1,2),16),parseInt(e.substr(3,2),16),parseInt(e.substr(5,2),16),1]}d=c?"rgba("+c.join(", ")+")":d}return d}
function Dc(a,b){var c=a.currentStyle||a.style,d=c[b];void 0===d&&"function"==l(c.getPropertyValue)&&(d=c.getPropertyValue(b));if("inherit"!=d)return void 0!==d?d:null;for(c=a.parentNode;c&&1!=c.nodeType&&9!=c.nodeType&&11!=c.nodeType;)c=c.parentNode;return(c=c&&1==c.nodeType?c:null)?Dc(c,b):null};Qa||ib&&jb(3.6);w&&hb(10);A&&jb(4);function Y(a,b){this.u={};this.l=[];this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){var e;if(a instanceof Y)for(d=Ec(a),Fc(a),e=[],c=0;c<a.l.length;c++)e.push(a.u[a.l[c]]);else{var c=[],f=0;for(d in a)c[f++]=d;d=c;c=[];f=0;for(e in a)c[f++]=a[e];e=c}for(c=0;c<d.length;c++)this.set(d[c],e[c])}}function Ec(a){Fc(a);return a.l.concat()}
Y.prototype.clear=function(){this.u={};this.a=this.l.length=0};function Fc(a){if(a.a!=a.l.length){for(var b=0,c=0;b<a.l.length;){var d=a.l[b];Object.prototype.hasOwnProperty.call(a.u,d)&&(a.l[c++]=d);b++}a.l.length=c}if(a.a!=a.l.length){for(var e={},c=b=0;b<a.l.length;)d=a.l[b],Object.prototype.hasOwnProperty.call(e,d)||(a.l[c++]=d,e[d]=1),b++;a.l.length=c}}Y.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.u,a)?this.u[a]:b};
Y.prototype.set=function(a,b){Object.prototype.hasOwnProperty.call(this.u,a)||(this.a++,this.l.push(a));this.u[a]=b};Y.prototype.forEach=function(a,b){for(var c=Ec(this),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};Y.prototype.clone=function(){return new Y(this)};var Gc={};function Z(a,b,c){ha(a)&&(a=x?a.f:a.g);a=new Hc(a);!b||b in Gc&&!c||(Gc[b]={key:a,shift:!1},c&&(Gc[c]={key:a,shift:!0}));return a}function Hc(a){this.code=a}Z(8);Z(9);Z(13);var Ic=Z(16),Jc=Z(17),Kc=Z(18);Z(19);Z(20);Z(27);Z(32," ");Z(33);Z(34);Z(35);Z(36);Z(37);Z(38);Z(39);Z(40);Z(44);Z(45);Z(46);Z(48,"0",")");Z(49,"1","!");Z(50,"2","@");Z(51,"3","#");Z(52,"4","$");Z(53,"5","%");Z(54,"6","^");Z(55,"7","&");Z(56,"8","*");Z(57,"9","(");Z(65,"a","A");Z(66,"b","B");Z(67,"c","C");Z(68,"d","D");
Z(69,"e","E");Z(70,"f","F");Z(71,"g","G");Z(72,"h","H");Z(73,"i","I");Z(74,"j","J");Z(75,"k","K");Z(76,"l","L");Z(77,"m","M");Z(78,"n","N");Z(79,"o","O");Z(80,"p","P");Z(81,"q","Q");Z(82,"r","R");Z(83,"s","S");Z(84,"t","T");Z(85,"u","U");Z(86,"v","V");Z(87,"w","W");Z(88,"x","X");Z(89,"y","Y");Z(90,"z","Z");var Lc=Z(Sa?{f:91,g:91}:Ra?{f:224,g:91}:{f:0,g:91});Z(Sa?{f:92,g:92}:Ra?{f:224,g:93}:{f:0,g:92});Z(Sa?{f:93,g:93}:Ra?{f:0,g:0}:{f:93,g:null});Z({f:96,g:96},"0");Z({f:97,g:97},"1");
Z({f:98,g:98},"2");Z({f:99,g:99},"3");Z({f:100,g:100},"4");Z({f:101,g:101},"5");Z({f:102,g:102},"6");Z({f:103,g:103},"7");Z({f:104,g:104},"8");Z({f:105,g:105},"9");Z({f:106,g:106},"*");Z({f:107,g:107},"+");Z({f:109,g:109},"-");Z({f:110,g:110},".");Z({f:111,g:111},"/");Z(144);Z(112);Z(113);Z(114);Z(115);Z(116);Z(117);Z(118);Z(119);Z(120);Z(121);Z(122);Z(123);Z({f:107,g:187},"=","+");Z(108,",");Z({f:109,g:189},"-","_");Z(188,",","<");Z(190,".",">");Z(191,"/","?");Z(192,"`","~");Z(219,"[","{");
Z(220,"\\","|");Z(221,"]","}");Z({f:59,g:186},";",":");Z(222,"'",'"');var Mc=new Y;Mc.set(1,Ic);Mc.set(2,Jc);Mc.set(4,Kc);Mc.set(8,Lc);(function(a){var b=new Y;p(Ec(a),function(c){b.set(a.get(c).code,c)});return b})(Mc);x&&hb(12);function Nc(){}
function Oc(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if("array"==l(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Oc(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Pc(d,c),c.push(":"),Oc(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Pc(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var Qc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Rc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Pc(a,b){b.push('"',a.replace(Rc,function(a){var b=Qc[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Qc[a]=b);return b}),'"')};Qa||x&&hb(3.5)||w&&hb(8);function Sc(a){switch(l(a)){case "string":case "number":case "boolean":return a;case "function":return a.toString();case "array":return ta(a,Sc);case "object":if(a&&"nodeType"in a&&(1==a.nodeType||9==a.nodeType)){var b={};b.ELEMENT=Tc(a);return b}if(a&&"document"in a)return b={},b.WINDOW=Tc(a),b;if(ga(a))return ta(a,Sc);a=Ia(a,function(a,b){return"number"==typeof b||m(b)});return Ja(a,Sc);default:return null}}
function Uc(a,b){return"array"==l(a)?ta(a,function(a){return Uc(a,b)}):ha(a)?"function"==typeof a?a:a&&"ELEMENT"in a?Vc(a.ELEMENT,b):a&&"WINDOW"in a?Vc(a.WINDOW,b):Ja(a,function(a){return Uc(a,b)}):a}function Wc(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.B=ma());b.B||(b.B=ma());return b}function Tc(a){var b=Wc(a.ownerDocument),c=Ka(b,function(b){return b==a});c||(c=":wdc:"+b.B++,b[c]=a);return c}
function Vc(a,b){a=decodeURIComponent(a);var c=b||document,d=Wc(c);if(!(d&&a in d))throw new Ea(10,"Element does not exist in cache");var e=d[a];if(e&&"setInterval"in e){if(e.closed)throw delete d[a],new Ea(23,"Window has been closed.");return e}for(var f=e;f;){if(f==c.documentElement)return e;f=f.parentNode}delete d[a];throw new Ea(10,"Element is no longer attached to the DOM");};fa("_",function(a,b,c){a=[a,b];var d;try{var e;c?e=Vc(c.WINDOW):e=window;var f=Uc(a,e.document),h=Cc.apply(null,f);d={status:0,value:Sc(h)}}catch(k){d={status:k&&"code"in k?k.code:13,value:{message:k.message}}}c=[];Oc(new Nc,d,c);return c.join("")});; return this._.apply(null,arguments);}.apply({navigator:typeof window!=undefined?window.navigator:null,document:typeof window!=undefined?window.document:null}, arguments);}
