function(){return function(){var h,l=this;function m(a){return void 0!==a}function p(a){return"string"==typeof a}function ba(a){return"number"==typeof a}function ca(a,b){a=a.split(".");var c=l;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ga(a,b,c){return a.call.apply(a.bind,arguments)}
function ha(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ia(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia=ga:ia=ha;return ia.apply(null,arguments)}
function ja(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ka=Date.now||function(){return+new Date};function q(a,b){function c(){}c.prototype=b.prototype;a.V=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.T=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};function la(a){var b=a.length-1;return 0<=b&&a.indexOf(" ",b)==b}var ma=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function na(a,b){var c=0;a=ma(String(a)).split(".");b=ma(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;!c&&e<d;e++){var f=a[e]||"",g=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;c=oa(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||oa(0==f[2].length,0==g[2].length)||oa(f[2],g[2]);f=f[3];g=g[3]}while(!c)}return c}function oa(a,b){return a<b?-1:a>b?1:0}
function pa(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};function qa(a,b){if(p(a))return p(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function r(a,b){for(var c=a.length,d=p(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function ra(a,b){for(var c=a.length,d=[],e=0,f=p(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d}
function sa(a,b){for(var c=a.length,d=Array(c),e=p(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function ta(a,b,c){var d=c;r(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function ua(a,b){for(var c=a.length,d=p(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function va(a,b){for(var c=a.length,d=p(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}
function xa(a,b){a:{for(var c=a.length,d=p(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:p(a)?a.charAt(b):a[b]}function ya(a){return Array.prototype.concat.apply([],arguments)}function za(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Aa={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Ba="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Ca=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Da=/^#(?:[0-9a-f]{3}){1,2}$/i,Ea=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Fa=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function v(a,b){this.code=a;this.a=w[a]||Ga;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}q(v,Error);var Ga="unknown error",w={15:"element not selectable",11:"element not visible"};w[31]=Ga;w[30]=Ga;w[24]="invalid cookie domain";w[29]="invalid element coordinates";w[12]="invalid element state";
w[32]="invalid selector";w[51]="invalid selector";w[52]="invalid selector";w[17]="javascript error";w[405]="unsupported operation";w[34]="move target out of bounds";w[27]="no such alert";w[7]="no such element";w[8]="no such frame";w[23]="no such window";w[28]="script timeout";w[33]="session not created";w[10]="stale element reference";w[21]="timeout";w[25]="unable to set cookie";w[26]="unexpected alert open";w[13]=Ga;w[9]="unknown command";v.prototype.toString=function(){return this.name+": "+this.message};var x;a:{var Ha=l.navigator;if(Ha){var Ia=Ha.userAgent;if(Ia){x=Ia;break a}}x=""}function y(a){return-1!=x.indexOf(a)};function Ja(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function Ka(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function La(a,b){return null!==a&&b in a}function Ma(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function Na(){return(y("Chrome")||y("CriOS"))&&!y("Edge")};function Oa(){return y("iPhone")&&!y("iPod")&&!y("iPad")};function Pa(a,b){var c=Qa;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Ra=y("Opera"),z=y("Trident")||y("MSIE"),Sa=y("Edge"),Ta=y("Gecko")&&!(-1!=x.toLowerCase().indexOf("webkit")&&!y("Edge"))&&!(y("Trident")||y("MSIE"))&&!y("Edge"),Ua=-1!=x.toLowerCase().indexOf("webkit")&&!y("Edge"),Va=y("Macintosh"),Wa=y("Windows");function Xa(){var a=l.document;return a?a.documentMode:void 0}var Ya;
a:{var Za="",$a=function(){var a=x;if(Ta)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Sa)return/Edge\/([\d\.]+)/.exec(a);if(z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ua)return/WebKit\/(\S+)/.exec(a);if(Ra)return/(?:Version)[ \/]?(\S+)/.exec(a)}();$a&&(Za=$a?$a[1]:"");if(z){var ab=Xa();if(null!=ab&&ab>parseFloat(Za)){Ya=String(ab);break a}}Ya=Za}var Qa={};function bb(a){return Pa(a,function(){return 0<=na(Ya,a)})}var cb;var db=l.document;
cb=db&&z?Xa()||("CSS1Compat"==db.compatMode?parseInt(Ya,10):5):void 0;var eb=y("Firefox"),fb=Oa()||y("iPod"),gb=y("iPad"),hb=y("Android")&&!(Na()||y("Firefox")||y("Opera")||y("Silk")),ib=Na(),jb=y("Safari")&&!(Na()||y("Coast")||y("Opera")||y("Edge")||y("Silk")||y("Android"))&&!(Oa()||y("iPad")||y("iPod"));function kb(a){return(a=a.exec(x))?a[1]:""}(function(){if(eb)return kb(/Firefox\/([0-9.]+)/);if(z||Sa||Ra)return Ya;if(ib)return Oa()||y("iPad")||y("iPod")?kb(/CriOS\/([0-9.]+)/):kb(/Chrome\/([0-9.]+)/);if(jb&&!(Oa()||y("iPad")||y("iPod")))return kb(/Version\/([0-9.]+)/);if(fb||gb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(x);if(a)return a[1]+"."+a[2]}else if(hb)return(a=kb(/Android\s+([0-9.]+)/))?a:kb(/Version\/([0-9.]+)/);return""})();var lb,mb;function nb(a){return ob?lb(a):z?0<=na(cb,a):bb(a)}var ob=function(){if(!Ta)return!1;var a=l.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;lb=function(a){return 0<=c.compare(d,""+a)};mb=function(a){c.compare(e,""+a)};return!0}(),pb=z&&!(9<=Number(cb));
hb&&ob&&mb(2.3);hb&&ob&&mb(4);jb&&ob&&mb(6);function qb(a,b){this.x=m(a)?a:0;this.y=m(b)?b:0}h=qb.prototype;h.toString=function(){return"("+this.x+", "+this.y+")"};h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};h.scale=function(a,b){b=ba(b)?b:a;this.x*=a;this.y*=b;return this};function rb(a,b){this.width=a;this.height=b}h=rb.prototype;h.toString=function(){return"("+this.width+" x "+this.height+")"};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};h.scale=function(a,b){b=ba(b)?b:a;this.width*=a;this.height*=b;return this};function sb(a){for(;a&&1!=a.nodeType;)a=a.previousSibling;return a}function tb(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function ub(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(z&&!(9<=Number(cb))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?vb(a,b):!c&&tb(e,b)?-1*wb(a,b):!d&&tb(f,a)?wb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=A(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(l.Range.START_TO_END,a)}function wb(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return vb(b,a)}function vb(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function A(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function xb(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}
function yb(a){this.a=a||l.document||document}yb.prototype.getElementsByTagName=function(a,b){return(b||this.a).getElementsByTagName(String(a))};yb.prototype.contains=tb;function B(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function zb(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var C=z&&!(9<=Number(cb)),Ab=z&&!(8<=Number(cb));function Bb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Cb(a,b){var c=Ab&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Bb(b,a,b.nodeName,c)};function Db(a){this.b=a;this.a=0}function Eb(a){a=a.match(Fb);for(var b=0;b<a.length;b++)Gb.test(a[b])&&a.splice(b,1);return new Db(a)}var Fb=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,Gb=/^\s/;function D(a,b){return a.b[a.a+(b||0)]}Db.prototype.next=function(){return this.b[this.a++]};function Hb(a){return a.b.length<=a.a};function F(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(C&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),C&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function G(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Ab&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Ib(a,b,c,d,e){return(C?Jb:Kb).call(null,a,b,p(c)?c:null,p(d)?d:null,e||new H)}
function Jb(a,b,c,d,e){if(a instanceof Lb||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;var g=Mb(a);if("*"!=g&&(f=b.getElementsByTagName(g),!f))return e;if(c){var k=[];for(a=0;b=f[a++];)G(b,c,d)&&k.push(b);f=k}for(a=0;b=f[a++];)"*"==g&&"!"==b.tagName||I(e,b);return e}Nb(a,b,c,d,e);return e}
function Kb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!z?(b=b.getElementsByName(d),r(b,function(b){a.a(b)&&I(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),r(b,function(b){b.className==d&&a.a(b)&&I(e,b)})):a instanceof J?Nb(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),r(b,function(a){G(a,c,d)&&I(e,a)}));return e}
function Ob(a,b,c,d,e){var f;if((a instanceof Lb||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=Mb(a);if("*"!=g&&(f=ra(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=ra(f,function(a){return G(a,c,d)}));r(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||I(e,a)});return e}return Pb(a,b,c,d,e)}function Pb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)G(b,c,d)&&a.a(b)&&I(e,b);return e}
function Nb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)G(b,c,d)&&a.a(b)&&I(e,b),Nb(a,b,c,d,e)}function Mb(a){if(a instanceof J){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function H(){this.b=this.a=null;this.s=0}function Qb(a){this.node=a;this.next=this.a=null}function Rb(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;){e=c.node;var g=b.node;e==g||e instanceof Bb&&g instanceof Bb&&e.a==g.a?(e=c,c=c.next,b=b.next):0<ub(c.node,b.node)?(e=b,b=b.next):(e=c,c=c.next);(e.a=d)?d.next=e:a.a=e;d=e;f++}for(e=c||b;e;)e.a=d,d=d.next=e,f++,e=e.next;a.b=d;a.s=f;return a}function Sb(a,b){b=new Qb(b);b.next=a.a;a.b?a.a.a=b:a.a=a.b=b;a.a=b;a.s++}
function I(a,b){b=new Qb(b);b.a=a.b;a.a?a.b.next=b:a.a=a.b=b;a.b=b;a.s++}function Tb(a){return(a=a.a)?a.node:null}function Ub(a){return(a=Tb(a))?F(a):""}H.prototype.iterator=function(a){return new Vb(this,!!a)};function Vb(a,b){this.f=a;this.b=(this.A=b)?a.b:a.a;this.a=null}Vb.prototype.next=function(){var a=this.b;if(a){var b=this.a=a;this.b=this.A?a.a:a.next;return b.node}return null};function K(a){this.l=a;this.b=this.i=!1;this.f=null}function L(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Wb(a,b){a.i=b}function Xb(a,b){a.b=b}function M(a,b){a=a.a(b);return a instanceof H?+Ub(a):+a}function N(a,b){a=a.a(b);return a instanceof H?Ub(a):""+a}function Yb(a,b){a=a.a(b);return a instanceof H?!!a.s:!!a};function Zb(a,b,c){K.call(this,a.l);this.c=a;this.j=b;this.v=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==$b&&(c.b||c.i||4==c.l||0==c.l||!b.f?b.b||b.i||4==b.l||0==b.l||!c.f||(this.f={name:c.f.name,B:b}):this.f={name:b.f.name,B:c})}q(Zb,K);
function ac(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof H&&c instanceof H){b=b.iterator();for(d=b.next();d;d=b.next())for(e=c.iterator(),f=e.next();f;f=e.next())if(a(F(d),F(f)))return!0;return!1}if(b instanceof H||c instanceof H){b instanceof H?(e=b,d=c):(e=c,d=b);f=e.iterator();for(var g=typeof d,k=f.next();k;k=f.next()){switch(g){case "number":k=+F(k);break;case "boolean":k=!!F(k);break;case "string":k=F(k);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(k,
d)||e==c&&a(d,k))return!0}return!1}return e?"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Zb.prototype.a=function(a){return this.c.u(this.j,this.v,a)};Zb.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+L(this.j);return a+=L(this.v)};function bc(a,b,c,d){this.P=a;this.L=b;this.l=c;this.u=d}bc.prototype.toString=function(){return this.P};var cc={};
function P(a,b,c,d){if(cc.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new bc(a,b,c,d);return cc[a.toString()]=a}P("div",6,1,function(a,b,c){return M(a,c)/M(b,c)});P("mod",6,1,function(a,b,c){return M(a,c)%M(b,c)});P("*",6,1,function(a,b,c){return M(a,c)*M(b,c)});P("+",5,1,function(a,b,c){return M(a,c)+M(b,c)});P("-",5,1,function(a,b,c){return M(a,c)-M(b,c)});P("<",4,2,function(a,b,c){return ac(function(a,b){return a<b},a,b,c)});
P(">",4,2,function(a,b,c){return ac(function(a,b){return a>b},a,b,c)});P("<=",4,2,function(a,b,c){return ac(function(a,b){return a<=b},a,b,c)});P(">=",4,2,function(a,b,c){return ac(function(a,b){return a>=b},a,b,c)});var $b=P("=",3,2,function(a,b,c){return ac(function(a,b){return a==b},a,b,c,!0)});P("!=",3,2,function(a,b,c){return ac(function(a,b){return a!=b},a,b,c,!0)});P("and",2,2,function(a,b,c){return Yb(a,c)&&Yb(b,c)});P("or",1,2,function(a,b,c){return Yb(a,c)||Yb(b,c)});function dc(a,b){if(b.a.length&&4!=a.l)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");K.call(this,a.l);this.c=a;this.j=b;this.i=a.i;this.b=a.b}q(dc,K);dc.prototype.a=function(a){a=this.c.a(a);return ec(this.j,a)};dc.prototype.toString=function(){var a="Filter:"+L(this.c);return a+=L(this.j)};function fc(a,b){if(b.length<a.K)throw Error("Function "+a.o+" expects at least"+a.K+" arguments, "+b.length+" given");if(null!==a.F&&b.length>a.F)throw Error("Function "+a.o+" expects at most "+a.F+" arguments, "+b.length+" given");a.O&&r(b,function(b,d){if(4!=b.l)throw Error("Argument "+d+" to function "+a.o+" is not of type Nodeset: "+b);});K.call(this,a.l);this.C=a;this.c=b;Wb(this,a.i||ua(b,function(a){return a.i}));Xb(this,a.N&&!b.length||a.M&&!!b.length||ua(b,function(a){return a.b}))}
q(fc,K);fc.prototype.a=function(a){return this.C.u.apply(null,ya(a,this.c))};fc.prototype.toString=function(){var a="Function: "+this.C;if(this.c.length)var b=ta(this.c,function(a,b){return a+L(b)},"Arguments:"),a=a+L(b);return a};function gc(a,b,c,d,e,f,g,k,t){this.o=a;this.l=b;this.i=c;this.N=d;this.M=e;this.u=f;this.K=g;this.F=m(k)?k:g;this.O=!!t}gc.prototype.toString=function(){return this.o};var hc={};
function Q(a,b,c,d,e,f,g,k){if(hc.hasOwnProperty(a))throw Error("Function already created: "+a+".");hc[a]=new gc(a,b,c,d,!1,e,f,g,k)}Q("boolean",2,!1,!1,function(a,b){return Yb(b,a)},1);Q("ceiling",1,!1,!1,function(a,b){return Math.ceil(M(b,a))},1);Q("concat",3,!1,!1,function(a,b){return ta(za(arguments,1),function(b,d){return b+N(d,a)},"")},2,null);Q("contains",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return-1!=b.indexOf(a)},2);Q("count",1,!1,!1,function(a,b){return b.a(a).s},1,1,!0);
Q("false",2,!1,!1,function(){return!1},0);Q("floor",1,!1,!1,function(a,b){return Math.floor(M(b,a))},1);Q("id",4,!1,!1,function(a,b){function c(a){if(C){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return xa(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument;a=N(b,a).split(/\s+/);var f=[];r(a,function(a){a=c(a);!a||0<=qa(f,a)||f.push(a)});f.sort(ub);var g=new H;r(f,function(a){I(g,a)});return g},1);
Q("lang",2,!1,!1,function(){return!1},1);Q("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);Q("local-name",3,!1,!0,function(a,b){return(a=b?Tb(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);Q("name",3,!1,!0,function(a,b){return(a=b?Tb(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);Q("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
Q("normalize-space",3,!1,!0,function(a,b){return(b?N(b,a):F(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);Q("not",2,!1,!1,function(a,b){return!Yb(b,a)},1);Q("number",1,!1,!0,function(a,b){return b?M(b,a):+F(a.a)},0,1);Q("position",1,!0,!1,function(a){return a.b},0);Q("round",1,!1,!1,function(a,b){return Math.round(M(b,a))},1);Q("starts-with",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return!b.lastIndexOf(a,0)},2);Q("string",3,!1,!0,function(a,b){return b?N(b,a):F(a.a)},0,1);
Q("string-length",1,!1,!0,function(a,b){return(b?N(b,a):F(a.a)).length},0,1);Q("substring",3,!1,!1,function(a,b,c,d){c=M(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?M(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=N(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);Q("substring-after",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
Q("substring-before",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);Q("sum",1,!1,!1,function(a,b){a=b.a(a).iterator();b=0;for(var c=a.next();c;c=a.next())b+=+F(c);return b},1,1,!0);Q("translate",3,!1,!1,function(a,b,c,d){b=N(b,a);c=N(c,a);var e=N(d,a);d={};for(var f=0;f<c.length;f++)a=c.charAt(f),a in d||(d[a]=e.charAt(f));c="";for(f=0;f<b.length;f++)a=b.charAt(f),c+=a in d?d[a]:a;return c},3);Q("true",2,!1,!1,function(){return!0},0);function J(a,b){this.j=a;this.c=m(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function ic(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}J.prototype.a=function(a){return null===this.b||this.b==a.nodeType};J.prototype.f=function(){return this.j};
J.prototype.toString=function(){var a="Kind Test: "+this.j;null===this.c||(a+=L(this.c));return a};function jc(a){K.call(this,3);this.c=a.substring(1,a.length-1)}q(jc,K);jc.prototype.a=function(){return this.c};jc.prototype.toString=function(){return"Literal: "+this.c};function Lb(a,b){this.o=a.toLowerCase();a="*"==this.o?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():a}Lb.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=m(a.localName)?a.localName:a.nodeName;return"*"!=this.o&&this.o!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Lb.prototype.f=function(){return this.o};
Lb.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.o};function kc(a){K.call(this,1);this.c=a}q(kc,K);kc.prototype.a=function(){return this.c};kc.prototype.toString=function(){return"Number: "+this.c};function lc(a,b){K.call(this,a.l);this.j=a;this.c=b;this.i=a.i;this.b=a.b;1==this.c.length&&(a=this.c[0],a.D||a.c!=mc||(a=a.v,"*"!=a.f()&&(this.f={name:a.f(),B:null})))}q(lc,K);function nc(){K.call(this,4)}q(nc,K);nc.prototype.a=function(a){var b=new H;a=a.a;9==a.nodeType?I(b,a):I(b,a.ownerDocument);return b};nc.prototype.toString=function(){return"Root Helper Expression"};function oc(){K.call(this,4)}q(oc,K);oc.prototype.a=function(a){var b=new H;I(b,a.a);return b};oc.prototype.toString=function(){return"Context Helper Expression"};
function pc(a){return"/"==a||"//"==a}lc.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof H))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.s;c++){var e=a[c],f=b.iterator(e.c.A);if(e.i||e.c!=qc)if(e.i||e.c!=rc){var g=f.next();for(b=e.a(new zb(g));g=f.next();)g=e.a(new zb(g)),b=Rb(b,g)}else g=f.next(),b=e.a(new zb(g));else{for(g=f.next();(b=f.next())&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new zb(g))}}return b};
lc.prototype.toString=function(){var a="Path Expression:"+L(this.j);if(this.c.length){var b=ta(this.c,function(a,b){return a+L(b)},"Steps:");a+=L(b)}return a};function sc(a,b){this.a=a;this.A=!!b}
function ec(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=b.iterator(),f=b.s,g,k=0;g=e.next();k++){var t=a.A?f-k:k+1;g=d.a(new zb(g,t,f));if("number"==typeof g)t=t==g;else if("string"==typeof g||"boolean"==typeof g)t=!!g;else if(g instanceof H)t=0<g.s;else throw Error("Predicate.evaluate returned an unexpected type.");if(!t){t=e;g=t.f;var u=t.a;if(!u)throw Error("Next must be called at least once before remove.");var n=u.a,u=u.next;n?n.next=u:g.a=u;u?u.a=n:g.b=n;g.s--;t.a=null}}return b}
sc.prototype.toString=function(){return ta(this.a,function(a,b){return a+L(b)},"Predicates:")};function R(a,b,c,d){K.call(this,4);this.c=a;this.v=b;this.j=c||new sc([]);this.D=!!d;b=this.j;b=0<b.a.length?b.a[0].f:null;a.S&&b&&(a=b.name,a=C?a.toLowerCase():a,this.f={name:a,B:b.B});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.l||0==c.l){a=!0;break a}a=!1}this.i=a}q(R,K);
R.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.B?N(c.B,a):null,f=1);if(this.D)if(this.i||this.c!=tc)if(b=(new R(uc,new J("node"))).a(a).iterator(),c=b.next())for(a=this.u(c,d,e,f);c=b.next();)a=Rb(a,this.u(c,d,e,f));else a=new H;else a=Ib(this.v,b,d,e),a=ec(this.j,a,f);else a=this.u(a.a,d,e,f);return a};R.prototype.u=function(a,b,c,d){a=this.c.C(this.v,a,b,c);return a=ec(this.j,a,d)};
R.prototype.toString=function(){var a="Step:"+L("Operator: "+(this.D?"//":"/"));this.c.o&&(a+=L("Axis: "+this.c));a+=L(this.v);if(this.j.a.length){var b=ta(this.j.a,function(a,b){return a+L(b)},"Predicates:");a+=L(b)}return a};function vc(a,b,c,d){this.o=a;this.C=b;this.A=c;this.S=d}vc.prototype.toString=function(){return this.o};var wc={};function S(a,b,c,d){if(wc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new vc(a,b,c,!!d);return wc[a]=b}
S("ancestor",function(a,b){for(var c=new H;b=b.parentNode;)a.a(b)&&Sb(c,b);return c},!0);S("ancestor-or-self",function(a,b){var c=new H;do a.a(b)&&Sb(c,b);while(b=b.parentNode);return c},!0);
var mc=S("attribute",function(a,b){var c=new H,d=a.f();if("style"==d&&C&&b.style)return I(c,new Bb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof J&&null===a.b||"*"==d)for(d=0;a=e[d];d++)C?a.nodeValue&&I(c,Cb(b,a)):I(c,a);else(a=e.getNamedItem(d))&&(C?a.nodeValue&&I(c,Cb(b,a)):I(c,a));return c},!1),tc=S("child",function(a,b,c,d,e){return(C?Ob:Pb).call(null,a,b,p(c)?c:null,p(d)?d:null,e||new H)},!1,!0);S("descendant",Ib,!1,!0);
var uc=S("descendant-or-self",function(a,b,c,d){var e=new H;G(b,c,d)&&a.a(b)&&I(e,b);return Ib(a,b,c,d,e)},!1,!0),qc=S("following",function(a,b,c,d){var e=new H;do for(var f=b;f=f.nextSibling;)G(f,c,d)&&a.a(f)&&I(e,f),e=Ib(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);S("following-sibling",function(a,b){for(var c=new H;b=b.nextSibling;)a.a(b)&&I(c,b);return c},!1);S("namespace",function(){return new H},!1);
var xc=S("parent",function(a,b){var c=new H;if(9==b.nodeType)return c;if(2==b.nodeType)return I(c,b.ownerElement),c;b=b.parentNode;a.a(b)&&I(c,b);return c},!1),rc=S("preceding",function(a,b,c,d){var e=new H,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,k=f.length;g<k;g++){var t=[];for(b=f[g];b=b.previousSibling;)t.unshift(b);for(var u=0,n=t.length;u<n;u++)b=t[u],G(b,c,d)&&a.a(b)&&I(e,b),e=Ib(a,b,c,d,e)}return e},!0,!0);
S("preceding-sibling",function(a,b){for(var c=new H;b=b.previousSibling;)a.a(b)&&Sb(c,b);return c},!0);var yc=S("self",function(a,b){var c=new H;a.a(b)&&I(c,b);return c},!1);function zc(a){K.call(this,1);this.c=a;this.i=a.i;this.b=a.b}q(zc,K);zc.prototype.a=function(a){return-M(this.c,a)};zc.prototype.toString=function(){return"Unary Expression: -"+L(this.c)};function Ac(a){K.call(this,4);this.c=a;Wb(this,ua(this.c,function(a){return a.i}));Xb(this,ua(this.c,function(a){return a.b}))}q(Ac,K);Ac.prototype.a=function(a){var b=new H;r(this.c,function(c){c=c.a(a);if(!(c instanceof H))throw Error("Path expression must evaluate to NodeSet.");b=Rb(b,c)});return b};Ac.prototype.toString=function(){return ta(this.c,function(a,b){return a+L(b)},"Union Expression:")};function Bc(a,b){this.a=a;this.b=b}function Cc(a){for(var b,c=[];;){T(a,"Missing right hand side of binary expression.");b=Dc(a);var d=a.a.next();if(!d)break;var e=(d=cc[d]||null)&&d.L;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].L;)b=new Zb(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Zb(c.pop(),c.pop(),b);return b}function T(a,b){if(Hb(a.a))throw Error(b);}function Ec(a,b){a=a.a.next();if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function Fc(a){a=a.a.next();if(")"!=a)throw Error("Bad token: "+a);}function Gc(a){a=a.a.next();if(2>a.length)throw Error("Unclosed literal string");return new jc(a)}
function Hc(a){var b=[];if(pc(D(a.a))){var c=a.a.next();var d=D(a.a);if("/"==c&&(Hb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new nc;d=new nc;T(a,"Missing next location step.");c=Ic(a,c);b.push(c)}else{a:{c=D(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":a.a.next();c=Cc(a);T(a,'unclosed "("');Ec(a,")");break;case '"':case "'":c=Gc(a);break;default:if(isNaN(+c))if(!ic(c)&&/(?![0-9])[\w]/.test(d)&&"("==D(a.a,
1)){c=a.a.next();c=hc[c]||null;a.a.next();for(d=[];")"!=D(a.a);){T(a,"Missing function argument list.");d.push(Cc(a));if(","!=D(a.a))break;a.a.next()}T(a,"Unclosed function argument list.");Fc(a);c=new fc(c,d)}else{c=null;break a}else c=new kc(+a.a.next())}"["==D(a.a)&&(d=new sc(Jc(a)),c=new dc(c,d))}if(c)if(pc(D(a.a)))d=c;else return c;else c=Ic(a,"/"),d=new oc,b.push(c)}for(;pc(D(a.a));)c=a.a.next(),T(a,"Missing next location step."),c=Ic(a,c),b.push(c);return new lc(d,b)}
function Ic(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==D(a.a)){var c=new R(yc,new J("node"));a.a.next();return c}if(".."==D(a.a))return c=new R(xc,new J("node")),a.a.next(),c;if("@"==D(a.a)){var d=mc;a.a.next();T(a,"Missing attribute name")}else if("::"==D(a.a,1)){if(!/(?![0-9])[\w]/.test(D(a.a).charAt(0)))throw Error("Bad token: "+a.a.next());var e=a.a.next();d=wc[e]||null;if(!d)throw Error("No axis with name: "+e);a.a.next();T(a,"Missing node name")}else d=tc;e=
D(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==D(a.a,1)){if(!ic(e))throw Error("Invalid node type: "+e);e=a.a.next();if(!ic(e))throw Error("Invalid type name: "+e);Ec(a,"(");T(a,"Bad nodetype");var f=D(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=Gc(a);T(a,"Bad nodetype");Fc(a);e=new J(e,g)}else if(e=a.a.next(),f=e.indexOf(":"),-1==f)e=new Lb(e);else{var g=e.substring(0,f);if("*"==g)var k="*";else if(k=a.b(g),!k)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new Lb(e,k)}else throw Error("Bad token: "+
a.a.next());a=new sc(Jc(a),d.A);return c||new R(d,e,a,"//"==b)}function Jc(a){for(var b=[];"["==D(a.a);){a.a.next();T(a,"Missing predicate expression.");var c=Cc(a);b.push(c);T(a,"Unclosed predicate expression.");Ec(a,"]")}return b}function Dc(a){if("-"==D(a.a))return a.a.next(),new zc(Dc(a));var b=Hc(a);if("|"!=D(a.a))a=b;else{for(b=[b];"|"==a.a.next();)T(a,"Missing next union location path."),b.push(Hc(a));a.a.a--;a=new Ac(b)}return a};function Kc(a){switch(a.nodeType){case 1:return ja(Lc,a);case 9:return Kc(a.documentElement);case 11:case 10:case 6:case 12:return Mc;default:return a.parentNode?Kc(a.parentNode):Mc}}function Mc(){return null}function Lc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Lc(a.parentNode,b):null};function Nc(a,b){if(!a.length)throw Error("Empty XPath expression.");a=Eb(a);if(Hb(a))throw Error("Invalid XPath expression.");b?"function"==da(b)||(b=ia(b.lookupNamespaceURI,b)):b=function(){return null};var c=Cc(new Bc(a,b));if(!Hb(a))throw Error("Bad token: "+a.next());this.evaluate=function(a,b){a=c.a(new zb(a));return new U(a,b)}}
function U(a,b){if(!b)if(a instanceof H)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof H))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof H?Ub(a):""+a;break;case 1:this.numberValue=a instanceof H?+Ub(a):+a;break;case 3:this.booleanValue=a instanceof H?0<a.s:!!a;break;case 4:case 5:case 6:case 7:var c=
a.iterator();var d=[];for(var e=c.next();e;e=c.next())d.push(e instanceof Bb?e.a:e);this.snapshotLength=a.s;this.invalidIteratorState=!1;break;case 8:case 9:a=Tb(a);this.singleNodeValue=a instanceof Bb?a.a:a;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");
return a>=d.length||0>a?null:d[a]}}U.ANY_TYPE=0;U.NUMBER_TYPE=1;U.STRING_TYPE=2;U.BOOLEAN_TYPE=3;U.UNORDERED_NODE_ITERATOR_TYPE=4;U.ORDERED_NODE_ITERATOR_TYPE=5;U.UNORDERED_NODE_SNAPSHOT_TYPE=6;U.ORDERED_NODE_SNAPSHOT_TYPE=7;U.ANY_UNORDERED_NODE_TYPE=8;U.FIRST_ORDERED_NODE_TYPE=9;function Oc(a){this.lookupNamespaceURI=Kc(a)}
function Pc(a,b){a=a||l;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=U,c.evaluate=function(a,b,c,g){return(new Nc(a,c)).evaluate(b,g)},c.createExpression=function(a,b){return new Nc(a,b)},c.createNSResolver=function(a){return new Oc(a)}}ca("wgxpath.install",Pc);var V={};V.H=function(){var a={W:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
V.u=function(a,b,c){var d=A(a);if(!d.documentElement)return null;(z||hb)&&Pc(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):V.H;if(z&&!bb(7))return d.evaluate.call(d,b,a,e,c,null);if(!z||9<=Number(cb)){for(var f={},g=d.getElementsByTagName("*"),k=0;k<g.length;++k){var t=g[k],u=t.namespaceURI;if(u&&!f[u]){var n=t.lookupPrefix(u);if(!n)var E=u.match(".*/(\\w+)/?$"),n=E?E[1]:"xhtml";f[u]=n}}var O={},aa;for(aa in f)O[f[aa]]=aa;e=function(a){return O[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(wa){if("TypeError"===wa.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):V.H,d.evaluate(b,a,e,c,null);throw wa;}}catch(wa){if(!Ta||"NS_ERROR_ILLEGAL_VALUE"!=wa.name)throw new v(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+wa);}};V.I=function(a,b){if(!a||1!=a.nodeType)throw new v(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
V.R=function(a,b){var c=function(){var c=V.u(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=A(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||V.I(c,a);return c};
V.U=function(a,b){var c=function(){var c=V.u(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=A(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();r(c,function(b){V.I(b,a)});return c};function Qc(a,b,c,d){this.c=a;this.a=b;this.b=c;this.f=d}h=Qc.prototype;h.toString=function(){return"("+this.c+"t, "+this.a+"r, "+this.b+"b, "+this.f+"l)"};h.contains=function(a){return this&&a?a instanceof Qc?a.f>=this.f&&a.a<=this.a&&a.c>=this.c&&a.b<=this.b:a.x>=this.f&&a.x<=this.a&&a.y>=this.c&&a.y<=this.b:!1};h.ceil=function(){this.c=Math.ceil(this.c);this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.f=Math.ceil(this.f);return this};
h.floor=function(){this.c=Math.floor(this.c);this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.f=Math.floor(this.f);return this};h.round=function(){this.c=Math.round(this.c);this.a=Math.round(this.a);this.b=Math.round(this.b);this.f=Math.round(this.f);return this};h.scale=function(a,b){b=ba(b)?b:a;this.f*=a;this.a*=a;this.c*=b;this.b*=b;return this};function W(a,b,c,d){this.a=a;this.b=b;this.width=c;this.height=d}h=W.prototype;h.toString=function(){return"("+this.a+", "+this.b+" - "+this.width+"w x "+this.height+"h)"};h.contains=function(a){return a instanceof qb?a.x>=this.a&&a.x<=this.a+this.width&&a.y>=this.b&&a.y<=this.b+this.height:this.a<=a.a&&this.a+this.width>=a.a+a.width&&this.b<=a.b&&this.b+this.height>=a.b+a.height};
h.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.scale=function(a,b){b=ba(b)?b:a;this.a*=a;this.width*=a;this.b*=b;this.height*=b;return this};var Rc="function"===typeof ShadowRoot;function Sc(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return B(a)?a:null}
function X(a,b){b=pa(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b=pb?"styleFloat":"cssFloat";a:{var c=b;var d=A(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||Tc(a,b);if(null===a)a=null;else if(0<=qa(Ba,b)){b:{var e=a.match(Ea);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d&&0<=e&&1>=e)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(Fa))if(b=
Number(d[1]),c=Number(d[2]),d=Number(d[3]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=Aa[b.toLowerCase()];if(!c&&(c="#"==b.charAt(0)?b:"#"+b,4==c.length&&(c=c.replace(Ca,"#$1$1$2$2$3$3")),!Da.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function Tc(a,b){var c=a.currentStyle||a.style,d=c[b];!m(d)&&"function"==da(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?m(d)?d:null:(a=Sc(a))?Tc(a,b):null}
function Uc(a,b,c){function d(a){var b=Vc(a);return 0<b.height&&0<b.width?!0:B(a,"PATH")&&(0<b.height||0<b.width)?(a=X(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=X(a,"overflow")&&ua(a.childNodes,function(a){return 3==a.nodeType||B(a)&&d(a)})}function e(a){return Wc(a)==Y&&va(a.childNodes,function(a){return!B(a)||e(a)||!d(a)})}if(!B(a))throw Error("Argument to isShown must be of type Element");if(B(a,"BODY"))return!0;if(B(a,"OPTION")||B(a,"OPTGROUP"))return a=xb(a,function(a){return B(a,"SELECT")}),
!!a&&Uc(a,!0,c);var f=Xc(a);if(f)return!!f.J&&0<f.rect.width&&0<f.rect.height&&Uc(f.J,b,c);if(B(a,"INPUT")&&"hidden"==a.type.toLowerCase()||B(a,"NOSCRIPT"))return!1;f=X(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||Yc(a))&&d(a)?!e(a):!1}
function Zc(a){var b=Rc?function(c){if("none"==X(c,"display"))return!1;do{var d=c.parentNode;if(c.getDestinationInsertionPoints){var e=c.getDestinationInsertionPoints();0<e.length&&(d=e[e.length-1])}if(d instanceof ShadowRoot){if(d.host.shadowRoot!=d)return!1;d=d.host}else!d||9!=d.nodeType&&11!=d.nodeType||(d=null)}while(a&&1!=a.nodeType);return!d||b(d)}:function(a){if("none"==X(a,"display"))return!1;a=Sc(a);return!a||b(a)};return Uc(a,!1,b)}var Y="hidden";
function Wc(a){function b(a){function b(a){return a==g?!0:!X(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==X(a,"position")?!1:!0}var c=X(a,"position");if("fixed"==c)return u=!0,a==g?null:g;for(a=Sc(a);a&&!b(a);)a=Sc(a);return a}function c(a){var b=a;if("visible"==t)if(a==g&&k)b=k;else if(a==k)return{x:"visible",y:"visible"};b={x:X(b,"overflow-x"),y:X(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new yb(f)).a;
a=b.scrollingElement?b.scrollingElement:Ua||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=z&&bb("10")&&b.pageYOffset!=a.scrollTop?new qb(a.scrollLeft,a.scrollTop):new qb(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new qb(a.scrollLeft,a.scrollTop);return a}var e=$c(a);var f=A(a),g=f.documentElement,k=f.body,t=X(g,"overflow"),u;for(a=b(a);a;a=b(a)){var n=c(a);if("visible"!=n.x||"visible"!=n.y){var E=Vc(a);if(!E.width||!E.height)return Y;
var O=e.a<E.a,aa=e.b<E.b;if(O&&"hidden"==n.x||aa&&"hidden"==n.y)return Y;if(O&&"visible"!=n.x||aa&&"visible"!=n.y){O=d(a);aa=e.b<E.b-O.y;if(e.a<E.a-O.x&&"visible"!=n.x||aa&&"visible"!=n.x)return Y;e=Wc(a);return e==Y?Y:"scroll"}O=e.f>=E.a+E.width;E=e.c>=E.b+E.height;if(O&&"hidden"==n.x||E&&"hidden"==n.y)return Y;if(O&&"visible"!=n.x||E&&"visible"!=n.y){if(u&&(n=d(a),e.f>=g.scrollWidth-n.x||e.a>=g.scrollHeight-n.y))return Y;e=Wc(a);return e==Y?Y:"scroll"}}}return"none"}
function Vc(a){var b=Xc(a);if(b)return b.rect;if(B(a,"HTML"))return a=A(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new rb(a.clientWidth,a.clientHeight),new W(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new W(0,0,0,0)}b=new W(c.left,c.top,c.right-c.left,c.bottom-c.top);z&&a.ownerDocument.body&&(a=A(a),b.a-=a.documentElement.clientLeft+a.body.clientLeft,b.b-=a.documentElement.clientTop+a.body.clientTop);
return b}function Xc(a){var b=B(a,"MAP");if(!b&&!B(a,"AREA"))return null;var c=b?a:B(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=V.R('/descendant::*[@usemap = "#'+c.name+'"]',A(c)))&&(e=Vc(d),b||"default"==a.shape.toLowerCase()||(a=ad(a),b=Math.min(Math.max(a.a,0),e.width),c=Math.min(Math.max(a.b,0),e.height),e=new W(b+e.a,c+e.b,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{J:d,rect:e||new W(0,0,0,0)}}
function ad(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new W(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new W(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new W(b,c,d-b,e-c)}return new W(0,0,0,0)}function $c(a){a=Vc(a);return new Qc(a.b,a.a+a.width,a.b+a.height,a.a)}
function bd(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")}function cd(a){var b=[];Rc?dd(a,b):ed(a,b);a=sa(b,bd);return bd(a.join("\n")).replace(/\xa0/g," ")}
function fd(a,b,c){if(B(a,"BR"))b.push("");else{var d=B(a,"TD"),e=X(a,"display"),f=!d&&!(0<=qa(gd,e)),g=m(a.previousElementSibling)?a.previousElementSibling:sb(a.previousSibling),g=g?X(g,"display"):"",k=X(a,"float")||X(a,"cssFloat")||X(a,"styleFloat");!f||"run-in"==g&&"none"==k||/^[\s\xa0]*$/.test(b[b.length-1]||"")||b.push("");var t=Zc(a),u=null,n=null;t&&(u=X(a,"white-space"),n=X(a,"text-transform"));r(a.childNodes,function(a){c(a,b,t,u,n)});a=b[b.length-1]||"";!d&&"table-cell"!=e||!a||la(a)||(b[b.length-
1]+=" ");f&&"run-in"!=e&&!/^[\s\xa0]*$/.test(a)&&b.push("")}}function ed(a,b){fd(a,b,function(a,b,e,f,g){3==a.nodeType&&e?hd(a,b,f,g):B(a)&&ed(a,b)})}var gd="inline inline-block inline-table none table-cell table-column table-column-group".split(" ");
function hd(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=a.replace(/(\r\n|\r|\n)/g,"\n");if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";la(c)&&!a.lastIndexOf(" ",0)&&(a=a.substr(1));b.push(c+a)}
function Yc(a){if(pb){if("relative"==X(a,"position"))return 1;a=X(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return id(a)}function id(a){var b=1,c=X(a,"opacity");c&&(b=Number(c));(a=Sc(a))&&(b*=id(a));return b}
function jd(a,b,c,d,e){var f;if(3==a.nodeType&&c)hd(a,b,d,e);else if(B(a))if(B(a,"CONTENT")){for(f=a;f.parentNode;)f=f.parentNode;f instanceof ShadowRoot?r(a.getDistributedNodes(),function(a){jd(a,b,c,d,e)}):dd(a,b)}else if(B(a,"SHADOW")){for(f=a;f.parentNode;)f=f.parentNode;if(f instanceof ShadowRoot&&(a=f))for(a=a.olderShadowRoot;a;)r(a.childNodes,function(a){jd(a,b,c,d,e)}),a=a.olderShadowRoot}else dd(a,b)}
function dd(a,b){a.shadowRoot&&r(a.shadowRoot.childNodes,function(a){jd(a,b,!0,null,null)});fd(a,b,function(a,b,e,f,g){var c=null;1==a.nodeType?c=a:3==a.nodeType&&(c=a);c&&c.getDestinationInsertionPoints&&0<c.getDestinationInsertionPoints().length||jd(a,b,e,f,g)})};Ua||ob&&ob&&mb(3.6);z&&nb(10);hb&&ob&&mb(4);function kd(a,b){this.w={};this.m=[];this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof kd){d=ld(a);md(a);var e=[];for(c=0;c<a.m.length;c++)e.push(a.w[a.m[c]])}else{var c=[],f=0;for(d in a)c[f++]=d;d=c;c=[];f=0;for(e in a)c[f++]=a[e];e=c}for(c=0;c<d.length;c++)this.set(d[c],e[c])}}function ld(a){md(a);return a.m.concat()}
function md(a){var b,c;if(a.a!=a.m.length){for(b=c=0;c<a.m.length;){var d=a.m[c];Object.prototype.hasOwnProperty.call(a.w,d)&&(a.m[b++]=d);c++}a.m.length=b}if(a.a!=a.m.length){var e={};for(b=c=0;c<a.m.length;)d=a.m[c],Object.prototype.hasOwnProperty.call(e,d)||(a.m[b++]=d,e[d]=1),c++;a.m.length=b}}kd.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.w,a)?this.w[a]:b};
kd.prototype.set=function(a,b){Object.prototype.hasOwnProperty.call(this.w,a)||(this.a++,this.m.push(a));this.w[a]=b};var nd={};function Z(a,b,c){fa(a)&&(a=Ta?a.g:a.h);a=new od(a);!b||b in nd&&!c||(nd[b]={key:a,shift:!1},c&&(nd[c]={key:a,shift:!0}));return a}function od(a){this.code=a}Z(8);Z(9);Z(13);var pd=Z(16),qd=Z(17),rd=Z(18);Z(19);Z(20);Z(27);Z(32," ");Z(33);Z(34);Z(35);Z(36);Z(37);Z(38);Z(39);Z(40);Z(44);Z(45);Z(46);Z(48,"0",")");Z(49,"1","!");Z(50,"2","@");Z(51,"3","#");Z(52,"4","$");Z(53,"5","%");Z(54,"6","^");Z(55,"7","&");Z(56,"8","*");Z(57,"9","(");Z(65,"a","A");Z(66,"b","B");Z(67,"c","C");Z(68,"d","D");
Z(69,"e","E");Z(70,"f","F");Z(71,"g","G");Z(72,"h","H");Z(73,"i","I");Z(74,"j","J");Z(75,"k","K");Z(76,"l","L");Z(77,"m","M");Z(78,"n","N");Z(79,"o","O");Z(80,"p","P");Z(81,"q","Q");Z(82,"r","R");Z(83,"s","S");Z(84,"t","T");Z(85,"u","U");Z(86,"v","V");Z(87,"w","W");Z(88,"x","X");Z(89,"y","Y");Z(90,"z","Z");var sd=Z(Wa?{g:91,h:91}:Va?{g:224,h:91}:{g:0,h:91});Z(Wa?{g:92,h:92}:Va?{g:224,h:93}:{g:0,h:92});Z(Wa?{g:93,h:93}:Va?{g:0,h:0}:{g:93,h:null});Z({g:96,h:96},"0");Z({g:97,h:97},"1");
Z({g:98,h:98},"2");Z({g:99,h:99},"3");Z({g:100,h:100},"4");Z({g:101,h:101},"5");Z({g:102,h:102},"6");Z({g:103,h:103},"7");Z({g:104,h:104},"8");Z({g:105,h:105},"9");Z({g:106,h:106},"*");Z({g:107,h:107},"+");Z({g:109,h:109},"-");Z({g:110,h:110},".");Z({g:111,h:111},"/");Z(144);Z(112);Z(113);Z(114);Z(115);Z(116);Z(117);Z(118);Z(119);Z(120);Z(121);Z(122);Z(123);Z({g:107,h:187},"=","+");Z(108,",");Z({g:109,h:189},"-","_");Z(188,",","<");Z(190,".",">");Z(191,"/","?");Z(192,"`","~");Z(219,"[","{");
Z(220,"\\","|");Z(221,"]","}");Z({g:59,h:186},";",":");Z(222,"'",'"');var td=new kd;td.set(1,pd);td.set(2,qd);td.set(4,rd);td.set(8,sd);(function(a){var b=new kd;r(ld(a),function(c){b.set(a.get(c).code,c)});return b})(td);Ta&&nb(12);function ud(){}
function vd(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if("array"==da(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),vd(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),wd(d,c),c.push(":"),vd(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":wd(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var xd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},yd=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function wd(a,b){b.push('"',a.replace(yd,function(a){var b=xd[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),xd[a]=b);return b}),'"')};Ua||Ta&&nb(3.5)||z&&nb(8);function zd(a){function b(a,d){switch(da(a)){case "string":case "number":case "boolean":return a;case "function":return a.toString();case "array":return sa(a,function(a){return b(a,d)});case "object":if(0<=d.indexOf(a))throw new v(13,"Recursive object cannot be transferred");if(La(a,"nodeType")&&(1==a.nodeType||9==a.nodeType)){var c={};c.ELEMENT=Ad(a);return c}if(La(a,"document"))return c={},c.WINDOW=Ad(a),c;d.push(a);if(ea(a))return sa(a,function(a){return b(a,d)});a=Ja(a,function(a,b){return ba(b)||
p(b)});return Ka(a,function(a){return b(a,d)});default:return null}}return b(a,[])}function Bd(a,b){return"array"==da(a)?sa(a,function(a){return Bd(a,b)}):fa(a)?"function"==typeof a?a:La(a,"ELEMENT")?Cd(a.ELEMENT,b):La(a,"WINDOW")?Cd(a.WINDOW,b):Ka(a,function(a){return Bd(a,b)}):a}function Dd(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.G=ka());b.G||(b.G=ka());return b}function Ad(a){var b=Dd(a.ownerDocument),c=Ma(b,function(b){return b==a});c||(c=":wdc:"+b.G++,b[c]=a);return c}
function Cd(a,b){a=decodeURIComponent(a);b=b||document;var c=Dd(b);if(!La(c,a))throw new v(10,"Element does not exist in cache");var d=c[a];if(La(d,"setInterval")){if(d.closed)throw delete c[a],new v(23,"Window has been closed.");return d}for(var e=d;e;){if(e==b.documentElement)return d;e=e.parentNode}delete c[a];throw new v(10,"Element is no longer attached to the DOM");};ca("_",function(a,b){a=[a];try{var c;b?c=Cd(b.WINDOW):c=window;var d=Bd(a,c.document),e=cd.apply(null,d);var f={status:0,value:zd(e)}}catch(g){f={status:La(g,"code")?g.code:13,value:{message:g.message}}}b=[];vd(new ud,f,b);return b.join("")});; return this._.apply(null,arguments);}.apply({navigator:typeof window!='undefined'?window.navigator:null,document:typeof window!='undefined'?window.document:null}, arguments);}
