function(){return function(){var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},da="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ea(a,b){if(b){for(var c=da,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&aa(c,d,{configurable:!0,writable:!0,value:f})}}
ea("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=c),a>>>=1)c+=c;return d}});ea("Math.sign",function(a){return a?a:function(a){a=Number(a);return!a||isNaN(a)?a:0<a?1:-1}});var k=this;
function fa(a,b){var c=a.split("."),d=k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}
function l(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ga(a){var b=l(a);return"array"==b||"object"==b&&"number"==typeof a.length}function m(a){return"string"==typeof a}function ha(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ia(a,b,c){return a.call.apply(a.bind,arguments)}
function ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ka(a,b,c){ka=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return ka.apply(null,arguments)}
function la(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var ma=Date.now||function(){return+new Date};function n(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.G=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};function p(a,b){this.code=a;this.a=q[a]||na;this.message=b||"";var c=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=c.length-5;if(0>d||c.indexOf("Error",d)!=d)c+="Error";this.name=c;c=Error(this.message);c.name=this.name;this.stack=c.stack||""}n(p,Error);var na="unknown error",q={15:"element not selectable",11:"element not visible"};q[31]=na;q[30]=na;q[24]="invalid cookie domain";q[29]="invalid element coordinates";q[12]="invalid element state";
q[32]="invalid selector";q[51]="invalid selector";q[52]="invalid selector";q[17]="javascript error";q[405]="unsupported operation";q[34]="move target out of bounds";q[27]="no such alert";q[7]="no such element";q[8]="no such frame";q[23]="no such window";q[28]="script timeout";q[33]="session not created";q[10]="stale element reference";q[21]="timeout";q[25]="unable to set cookie";q[26]="unexpected alert open";q[13]=na;q[9]="unknown command";p.prototype.toString=function(){return this.name+": "+this.message};var oa=window;var pa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function qa(a,b){for(var c=0,d=pa(String(a)).split("."),e=pa(String(b)).split("."),f=Math.max(d.length,e.length),g=0;!c&&g<f;g++){var h=d[g]||"",u=e[g]||"",B=RegExp("(\\d*)(\\D*)","g"),N=RegExp("(\\d*)(\\D*)","g");do{var ba=B.exec(h)||["","",""],ca=N.exec(u)||["","",""];if(0==ba[0].length&&0==ca[0].length)break;c=ra(0==ba[1].length?0:parseInt(ba[1],10),0==ca[1].length?0:parseInt(ca[1],10))||ra(0==ba[2].length,0==ca[2].length)||ra(ba[2],ca[2])}while(!c)}return c}
function ra(a,b){return a<b?-1:a>b?1:0};function r(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function sa(a,b){for(var c=a.length,d=[],e=0,f=m(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d}function ta(a,b){for(var c=a.length,d=Array(c),e=m(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function t(a,b,c){var d=c;r(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}
function ua(a,b){for(var c=a.length,d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function va(a,b){var c;a:{c=a.length;for(var d=m(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:m(a)?a.charAt(c):a[c]}function wa(a){return Array.prototype.concat.apply(Array.prototype,arguments)}function xa(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var v;a:{var ya=k.navigator;if(ya){var za=ya.userAgent;if(za){v=za;break a}}v=""}function w(a){return-1!=v.indexOf(a)};function Aa(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function Ba(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function Ca(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function Da(){return w("Opera")||w("OPR")}function Ea(){return(w("Chrome")||w("CriOS"))&&!Da()&&!w("Edge")};function Fa(){return w("iPhone")&&!w("iPod")&&!w("iPad")};var Ga=Da(),x=w("Trident")||w("MSIE"),Ha=w("Edge"),Ia=w("Gecko")&&!(-1!=v.toLowerCase().indexOf("webkit")&&!w("Edge"))&&!(w("Trident")||w("MSIE"))&&!w("Edge"),Ja=-1!=v.toLowerCase().indexOf("webkit")&&!w("Edge");function Ka(){var a=v;if(Ia)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ha)return/Edge\/([\d\.]+)/.exec(a);if(x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ja)return/WebKit\/(\S+)/.exec(a)}function La(){var a=k.document;return a?a.documentMode:void 0}
var Ma=function(){if(Ga&&k.opera){var a;var b=k.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Ka())&&(a=b?b[1]:"");return x&&(b=La(),null!=b&&b>parseFloat(a))?String(b):a}(),Na={};function Oa(a){return Na[a]||(Na[a]=0<=qa(Ma,a))}var Pa=k.document,y=Pa&&x?La()||("CSS1Compat"==Pa.compatMode?parseInt(Ma,10):5):void 0;!Ia&&!x||x&&9<=Number(y)||Ia&&Oa("1.9.1");x&&Oa("9");function Qa(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Ra(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(x&&!(9<=Number(y))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Sa(a,b):!c&&Qa(e,b)?-1*Ta(a,b):!d&&Qa(f,a)?Ta(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=9==a.nodeType?
a:a.ownerDocument||a.document;c=d.createRange();c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(k.Range.START_TO_END,d)}function Ta(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return Sa(d,a)}function Sa(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1};var Ua=w("Firefox"),Va=Fa()||w("iPod"),Wa=w("iPad"),Xa=w("Android")&&!(Ea()||w("Firefox")||Da()||w("Silk")),Ya=Ea(),Za=w("Safari")&&!(Ea()||w("Coast")||Da()||w("Edge")||w("Silk")||w("Android"))&&!(Fa()||w("iPad")||w("iPod"));function $a(a){return(a=a.exec(v))?a[1]:""}var ab=function(){if(Ua)return $a(/Firefox\/([0-9.]+)/);if(x||Ha||Ga)return Ma;if(Ya)return $a(/Chrome\/([0-9.]+)/);if(Za&&!(Fa()||w("iPad")||w("iPod")))return $a(/Version\/([0-9.]+)/);if(Va||Wa){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(v);if(a)return a[1]+"."+a[2]}else if(Xa)return(a=$a(/Android\s+([0-9.]+)/))?a:$a(/Version\/([0-9.]+)/);return""}();var bb,cb;function db(a){eb?cb(a):Xa?qa(fb,a):qa(ab,a)}var eb=function(){if(!Ia)return!1;var a=k.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;bb=function(a){return 0<=c.compare(d,""+a)};cb=function(a){c.compare(e,""+a)};return!0}(),gb;
if(Xa){var hb=/Android\s+([0-9\.]+)/.exec(v);gb=hb?hb[1]:"0"}else gb="0";var fb=gb;Xa&&db(2.3);Xa&&db(4);Za&&db(6);function ib(a,b){return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function z(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var A=x&&!(9<=Number(y)),jb=x&&!(8<=Number(y));function C(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function kb(a,b){var c=jb&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new C(b,a,b.nodeName,c)};function lb(a){this.b=a;this.a=0}function mb(a){a=a.match(nb);for(var b=0;b<a.length;b++)ob.test(a[b])&&a.splice(b,1);return new lb(a)}var nb=RegExp("\\$?(?:(?![0-9-\\.])(?:\\*|[\\w-\\.]+):)?(?![0-9-\\.])(?:\\*|[\\w-\\.]+)|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),ob=/^\s/;function D(a,b){return a.b[a.a+(b||0)]}function E(a){return a.b[a.a++]}function pb(a){return a.b.length<=a.a};function F(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(A&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),A&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function G(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}jb&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function qb(a,b,c,d,e){return(A?rb:sb).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new H)}
function rb(a,b,c,d,e){if(a instanceof I||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;a=tb(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var g=[],h=0;b=f[h++];)G(b,c,d)&&g.push(b);f=g}for(h=0;b=f[h++];)"*"==a&&"!"==b.tagName||J(e,b);return e}ub(a,b,c,d,e);return e}
function sb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!x?(b=b.getElementsByName(d),r(b,function(b){a.a(b)&&J(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),r(b,function(b){b.className==d&&a.a(b)&&J(e,b)})):a instanceof K?ub(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),r(b,function(a){G(a,c,d)&&J(e,a)}));return e}
function vb(a,b,c,d,e){var f;if((a instanceof I||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=tb(a);if("*"!=g&&(f=sa(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=sa(f,function(a){return G(a,c,d)}));r(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||J(e,a)});return e}return wb(a,b,c,d,e)}function wb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)G(b,c,d)&&a.a(b)&&J(e,b);return e}
function ub(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)G(b,c,d)&&a.a(b)&&J(e,b),ub(a,b,c,d,e)}function tb(a){if(a instanceof K){if(8==a.b)return"!";if(null===a.b)return"*"}return a.f()};function H(){this.b=this.a=null;this.l=0}function xb(a){this.node=a;this.a=this.b=null}function yb(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f,g=0;c&&d;){f=c.node;var h=d.node;f==h||f instanceof C&&h instanceof C&&f.a==h.a?(f=c,c=c.a,d=d.a):0<Ra(c.node,d.node)?(f=d,d=d.a):(f=c,c=c.a);(f.b=e)?e.a=f:a.a=f;e=f;g++}for(f=c||d;f;)f.b=e,e=e.a=f,g++,f=f.a;a.b=e;a.l=g;return a}H.prototype.unshift=function(a){a=new xb(a);a.a=this.a;this.b?this.a.b=a:this.a=this.b=a;this.a=a;this.l++};
function J(a,b){var c=new xb(b);c.b=a.b;a.a?a.b.a=c:a.a=a.b=c;a.b=c;a.l++}function zb(a){return(a=a.a)?a.node:null}function Ab(a){return(a=zb(a))?F(a):""}function L(a,b){return new Bb(a,!!b)}function Bb(a,b){this.f=a;this.b=(this.c=b)?a.b:a.a;this.a=null}function M(a){var b=a.b;if(b){var c=a.a=b;a.b=a.c?b.b:b.a;return c.node}return null};function O(a){this.i=a;this.b=this.g=!1;this.f=null}function P(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Cb(a,b){a.g=b}function Db(a,b){a.b=b}function Q(a,b){var c=a.a(b);return c instanceof H?+Ab(c):+c}function R(a,b){var c=a.a(b);return c instanceof H?Ab(c):""+c}function S(a,b){var c=a.a(b);return c instanceof H?!!c.l:!!c};function Eb(a,b,c){O.call(this,a.i);this.c=a;this.h=b;this.o=c;this.g=b.g||c.g;this.b=b.b||c.b;this.c==Fb&&(c.b||c.g||4==c.i||0==c.i||!b.f?b.b||b.g||4==b.i||0==b.i||!c.f||(this.f={name:c.f.name,s:b}):this.f={name:b.f.name,s:c})}n(Eb,O);
function T(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof H&&c instanceof H){b=L(b);for(d=M(b);d;d=M(b))for(e=L(c),f=M(e);f;f=M(e))if(a(F(d),F(f)))return!0;return!1}if(b instanceof H||c instanceof H){b instanceof H?(e=b,d=c):(e=c,d=b);f=L(e);for(var g=typeof d,h=M(f);h;h=M(f)){switch(g){case "number":h=+F(h);break;case "boolean":h=!!F(h);break;case "string":h=F(h);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(h,d)||e==c&&a(d,h))return!0}return!1}return e?"boolean"==
typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}Eb.prototype.a=function(a){return this.c.m(this.h,this.o,a)};Eb.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+P(this.h);return a+=P(this.o)};function Gb(a,b,c,d){this.a=a;this.A=b;this.i=c;this.m=d}Gb.prototype.toString=function(){return this.a};var Hb={};
function U(a,b,c,d){if(Hb.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Gb(a,b,c,d);return Hb[a.toString()]=a}U("div",6,1,function(a,b,c){return Q(a,c)/Q(b,c)});U("mod",6,1,function(a,b,c){return Q(a,c)%Q(b,c)});U("*",6,1,function(a,b,c){return Q(a,c)*Q(b,c)});U("+",5,1,function(a,b,c){return Q(a,c)+Q(b,c)});U("-",5,1,function(a,b,c){return Q(a,c)-Q(b,c)});U("<",4,2,function(a,b,c){return T(function(a,b){return a<b},a,b,c)});
U(">",4,2,function(a,b,c){return T(function(a,b){return a>b},a,b,c)});U("<=",4,2,function(a,b,c){return T(function(a,b){return a<=b},a,b,c)});U(">=",4,2,function(a,b,c){return T(function(a,b){return a>=b},a,b,c)});var Fb=U("=",3,2,function(a,b,c){return T(function(a,b){return a==b},a,b,c,!0)});U("!=",3,2,function(a,b,c){return T(function(a,b){return a!=b},a,b,c,!0)});U("and",2,2,function(a,b,c){return S(a,c)&&S(b,c)});U("or",1,2,function(a,b,c){return S(a,c)||S(b,c)});function Ib(a,b){if(b.a.length&&4!=a.i)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");O.call(this,a.i);this.c=a;this.h=b;this.g=a.g;this.b=a.b}n(Ib,O);Ib.prototype.a=function(a){a=this.c.a(a);return Jb(this.h,a)};Ib.prototype.toString=function(){var a;a="Filter:"+P(this.c);return a+=P(this.h)};function Kb(a,b){if(b.length<a.B)throw Error("Function "+a.j+" expects at least"+a.B+" arguments, "+b.length+" given");if(null!==a.w&&b.length>a.w)throw Error("Function "+a.j+" expects at most "+a.w+" arguments, "+b.length+" given");a.C&&r(b,function(b,d){if(4!=b.i)throw Error("Argument "+d+" to function "+a.j+" is not of type Nodeset: "+b);});O.call(this,a.i);this.h=a;this.c=b;Cb(this,a.g||ua(b,function(a){return a.g}));Db(this,a.F&&!b.length||a.D&&!!b.length||ua(b,function(a){return a.b}))}
n(Kb,O);Kb.prototype.a=function(a){return this.h.m.apply(null,wa(a,this.c))};Kb.prototype.toString=function(){var a="Function: "+this.h;if(this.c.length)var b=t(this.c,function(a,b){return a+P(b)},"Arguments:"),a=a+P(b);return a};function Lb(a,b,c,d,e,f,g,h,u){this.j=a;this.i=b;this.g=c;this.F=d;this.D=e;this.m=f;this.B=g;this.w=void 0!==h?h:g;this.C=!!u}Lb.prototype.toString=function(){return this.j};var Mb={};
function V(a,b,c,d,e,f,g,h){if(Mb.hasOwnProperty(a))throw Error("Function already created: "+a+".");Mb[a]=new Lb(a,b,c,d,!1,e,f,g,h)}V("boolean",2,!1,!1,function(a,b){return S(b,a)},1);V("ceiling",1,!1,!1,function(a,b){return Math.ceil(Q(b,a))},1);V("concat",3,!1,!1,function(a,b){return t(xa(arguments,1),function(b,d){return b+R(d,a)},"")},2,null);V("contains",2,!1,!1,function(a,b,c){b=R(b,a);a=R(c,a);return-1!=b.indexOf(a)},2);V("count",1,!1,!1,function(a,b){return b.a(a).l},1,1,!0);
V("false",2,!1,!1,function(){return!1},0);V("floor",1,!1,!1,function(a,b){return Math.floor(Q(b,a))},1);
V("id",4,!1,!1,function(a,b){function c(a){if(A){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return va(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=R(b,a).split(/\s+/),f=[];r(d,function(a){a=c(a);var b;if(!(b=!a)){a:if(m(f))b=m(a)&&1==a.length?f.indexOf(a,0):-1;else{for(b=0;b<f.length;b++)if(b in f&&f[b]===a)break a;b=-1}b=0<=b}b||f.push(a)});f.sort(Ra);var g=new H;r(f,function(a){J(g,a)});return g},1);
V("lang",2,!1,!1,function(){return!1},1);V("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);V("local-name",3,!1,!0,function(a,b){var c=b?zb(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);V("name",3,!1,!0,function(a,b){var c=b?zb(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);V("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
V("normalize-space",3,!1,!0,function(a,b){return(b?R(b,a):F(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);V("not",2,!1,!1,function(a,b){return!S(b,a)},1);V("number",1,!1,!0,function(a,b){return b?Q(b,a):+F(a.a)},0,1);V("position",1,!0,!1,function(a){return a.b},0);V("round",1,!1,!1,function(a,b){return Math.round(Q(b,a))},1);V("starts-with",2,!1,!1,function(a,b,c){b=R(b,a);a=R(c,a);return!b.lastIndexOf(a,0)},2);V("string",3,!1,!0,function(a,b){return b?R(b,a):F(a.a)},0,1);
V("string-length",1,!1,!0,function(a,b){return(b?R(b,a):F(a.a)).length},0,1);V("substring",3,!1,!1,function(a,b,c,d){c=Q(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?Q(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=R(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);V("substring-after",3,!1,!1,function(a,b,c){b=R(b,a);a=R(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
V("substring-before",3,!1,!1,function(a,b,c){b=R(b,a);a=R(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);V("sum",1,!1,!1,function(a,b){for(var c=L(b.a(a)),d=0,e=M(c);e;e=M(c))d+=+F(e);return d},1,1,!0);V("translate",3,!1,!1,function(a,b,c,d){b=R(b,a);c=R(c,a);var e=R(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);V("true",2,!1,!1,function(){return!0},0);function K(a,b){this.h=a;this.c=b?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Nb(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}K.prototype.a=function(a){return null===this.b||this.b==a.nodeType};K.prototype.f=function(){return this.h};
K.prototype.toString=function(){var a="Kind Test: "+this.h;!this.c||(a+=P(this.c));return a};function Ob(a){O.call(this,3);this.c=a.substring(1,a.length-1)}n(Ob,O);Ob.prototype.a=function(){return this.c};Ob.prototype.toString=function(){return"Literal: "+this.c};function I(a,b){this.j=a.toLowerCase();var c;c="*"==this.j?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():c}I.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=void 0!==a.localName?a.localName:a.nodeName;return"*"!=this.j&&this.j!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};I.prototype.f=function(){return this.j};
I.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.j};function Pb(a){O.call(this,1);this.c=a}n(Pb,O);Pb.prototype.a=function(){return this.c};Pb.prototype.toString=function(){return"Number: "+this.c};function Qb(a,b){O.call(this,a.i);this.h=a;this.c=b;this.g=a.g;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.v||c.c!=Rb||(c=c.o,"*"!=c.f()&&(this.f={name:c.f(),s:null}))}}n(Qb,O);function Sb(){O.call(this,4)}n(Sb,O);Sb.prototype.a=function(a){var b=new H;a=a.a;9==a.nodeType?J(b,a):J(b,a.ownerDocument);return b};Sb.prototype.toString=function(){return"Root Helper Expression"};function Tb(){O.call(this,4)}n(Tb,O);Tb.prototype.a=function(a){var b=new H;J(b,a.a);return b};Tb.prototype.toString=function(){return"Context Helper Expression"};
function Ub(a){return"/"==a||"//"==a}Qb.prototype.a=function(a){var b=this.h.a(a);if(!(b instanceof H))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.l;c++){var e=a[c],f=L(b,e.c.a),g;if(e.g||e.c!=Vb)if(e.g||e.c!=Wb)for(g=M(f),b=e.a(new z(g));g=M(f);)g=e.a(new z(g)),b=yb(b,g);else g=M(f),b=e.a(new z(g));else{for(g=M(f);(b=M(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new z(g))}}return b};
Qb.prototype.toString=function(){var a;a="Path Expression:"+P(this.h);if(this.c.length){var b=t(this.c,function(a,b){return a+P(b)},"Steps:");a+=P(b)}return a};function Xb(a,b){this.a=a;this.b=!!b}
function Jb(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=L(b),f=b.l,g,h=0;g=M(e);h++){var u=a.b?f-h:h+1;g=d.a(new z(g,u,f));if("number"==typeof g)u=u==g;else if("string"==typeof g||"boolean"==typeof g)u=!!g;else if(g instanceof H)u=0<g.l;else throw Error("Predicate.evaluate returned an unexpected type.");if(!u){u=e;g=u.f;var B=u.a;if(!B)throw Error("Next must be called at least once before remove.");var N=B.b,B=B.a;N?N.a=B:g.a=B;B?B.b=N:g.b=N;g.l--;u.a=null}}return b}
Xb.prototype.toString=function(){return t(this.a,function(a,b){return a+P(b)},"Predicates:")};function W(a,b,c,d){O.call(this,4);this.c=a;this.o=b;this.h=c||new Xb([]);this.v=!!d;b=this.h;b=0<b.a.length?b.a[0].f:null;a.b&&b&&(a=b.name,a=A?a.toLowerCase():a,this.f={name:a,s:b.s});a:{a=this.h;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.g||1==c.i||0==c.i){a=!0;break a}a=!1}this.g=a}n(W,O);
W.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.s?R(c.s,a):null,f=1);if(this.v)if(this.g||this.c!=Yb)if(b=L((new W(Zb,new K("node"))).a(a)),c=M(b))for(a=this.m(c,d,e,f);c=M(b);)a=yb(a,this.m(c,d,e,f));else a=new H;else a=qb(this.o,b,d,e),a=Jb(this.h,a,f);else a=this.m(a.a,d,e,f);return a};W.prototype.m=function(a,b,c,d){a=this.c.f(this.o,a,b,c);return a=Jb(this.h,a,d)};
W.prototype.toString=function(){var a;a="Step:"+P("Operator: "+(this.v?"//":"/"));this.c.j&&(a+=P("Axis: "+this.c));a+=P(this.o);if(this.h.a.length){var b=t(this.h.a,function(a,b){return a+P(b)},"Predicates:");a+=P(b)}return a};function $b(a,b,c,d){this.j=a;this.f=b;this.a=c;this.b=d}$b.prototype.toString=function(){return this.j};var ac={};function X(a,b,c,d){if(ac.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new $b(a,b,c,!!d);return ac[a]=b}
X("ancestor",function(a,b){for(var c=new H,d=b;d=d.parentNode;)a.a(d)&&c.unshift(d);return c},!0);X("ancestor-or-self",function(a,b){var c=new H,d=b;do a.a(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var Rb=X("attribute",function(a,b){var c=new H,d=a.f();if("style"==d&&A&&b.style)return J(c,new C(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof K&&null===a.b||"*"==d)for(var d=0,f;f=e[d];d++)A?f.nodeValue&&J(c,kb(b,f)):J(c,f);else(f=e.getNamedItem(d))&&(A?f.nodeValue&&J(c,kb(b,f)):J(c,f));return c},!1),Yb=X("child",function(a,b,c,d,e){return(A?vb:wb).call(null,a,b,m(c)?c:null,m(d)?d:null,e||new H)},!1,!0);X("descendant",qb,!1,!0);
var Zb=X("descendant-or-self",function(a,b,c,d){var e=new H;G(b,c,d)&&a.a(b)&&J(e,b);return qb(a,b,c,d,e)},!1,!0),Vb=X("following",function(a,b,c,d){var e=new H;do for(var f=b;f=f.nextSibling;)G(f,c,d)&&a.a(f)&&J(e,f),e=qb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);X("following-sibling",function(a,b){for(var c=new H,d=b;d=d.nextSibling;)a.a(d)&&J(c,d);return c},!1);X("namespace",function(){return new H},!1);
var bc=X("parent",function(a,b){var c=new H;if(9==b.nodeType)return c;if(2==b.nodeType)return J(c,b.ownerElement),c;var d=b.parentNode;a.a(d)&&J(c,d);return c},!1),Wb=X("preceding",function(a,b,c,d){var e=new H,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,h=f.length;g<h;g++){var u=[];for(b=f[g];b=b.previousSibling;)u.unshift(b);for(var B=0,N=u.length;B<N;B++)b=u[B],G(b,c,d)&&a.a(b)&&J(e,b),e=qb(a,b,c,d,e)}return e},!0,!0);
X("preceding-sibling",function(a,b){for(var c=new H,d=b;d=d.previousSibling;)a.a(d)&&c.unshift(d);return c},!0);var cc=X("self",function(a,b){var c=new H;a.a(b)&&J(c,b);return c},!1);function dc(a){O.call(this,1);this.c=a;this.g=a.g;this.b=a.b}n(dc,O);dc.prototype.a=function(a){return-Q(this.c,a)};dc.prototype.toString=function(){return"Unary Expression: -"+P(this.c)};function ec(a){O.call(this,4);this.c=a;Cb(this,ua(this.c,function(a){return a.g}));Db(this,ua(this.c,function(a){return a.b}))}n(ec,O);ec.prototype.a=function(a){var b=new H;r(this.c,function(c){c=c.a(a);if(!(c instanceof H))throw Error("Path expression must evaluate to NodeSet.");b=yb(b,c)});return b};ec.prototype.toString=function(){return t(this.c,function(a,b){return a+P(b)},"Union Expression:")};function fc(a,b){this.a=a;this.b=b}function gc(a){for(var b,c=[];;){Y(a,"Missing right hand side of binary expression.");b=hc(a);var d=E(a.a);if(!d)break;var e=(d=Hb[d]||null)&&d.A;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].A;)b=new Eb(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new Eb(c.pop(),c.pop(),b);return b}function Y(a,b){if(pb(a.a))throw Error(b);}function ic(a,b){var c=E(a.a);if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function jc(a){a=E(a.a);if(")"!=a)throw Error("Bad token: "+a);}function kc(a){a=E(a.a);if(2>a.length)throw Error("Unclosed literal string");return new Ob(a)}
function lc(a){var b,c=[],d;if(Ub(D(a.a))){b=E(a.a);d=D(a.a);if("/"==b&&(pb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new Sb;d=new Sb;Y(a,"Missing next location step.");b=mc(a,b);c.push(b)}else{a:{b=D(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":E(a.a);b=gc(a);Y(a,'unclosed "("');ic(a,")");break;case '"':case "'":b=kc(a);break;default:if(isNaN(+b))if(!Nb(b)&&/(?![0-9])[\w]/.test(d)&&"("==D(a.a,1)){b=E(a.a);
b=Mb[b]||null;E(a.a);for(d=[];")"!=D(a.a);){Y(a,"Missing function argument list.");d.push(gc(a));if(","!=D(a.a))break;E(a.a)}Y(a,"Unclosed function argument list.");jc(a);b=new Kb(b,d)}else{b=null;break a}else b=new Pb(+E(a.a))}"["==D(a.a)&&(d=new Xb(nc(a)),b=new Ib(b,d))}if(b)if(Ub(D(a.a)))d=b;else return b;else b=mc(a,"/"),d=new Tb,c.push(b)}for(;Ub(D(a.a));)b=E(a.a),Y(a,"Missing next location step."),b=mc(a,b),c.push(b);return new Qb(d,c)}
function mc(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==D(a.a))return d=new W(cc,new K("node")),E(a.a),d;if(".."==D(a.a))return d=new W(bc,new K("node")),E(a.a),d;var f;if("@"==D(a.a))f=Rb,E(a.a),Y(a,"Missing attribute name");else if("::"==D(a.a,1)){if(!/(?![0-9])[\w]/.test(D(a.a).charAt(0)))throw Error("Bad token: "+E(a.a));c=E(a.a);f=ac[c]||null;if(!f)throw Error("No axis with name: "+c);E(a.a);Y(a,"Missing node name")}else f=Yb;c=D(a.a);if(/(?![0-9])[\w\*]/.test(c.charAt(0)))if("("==
D(a.a,1)){if(!Nb(c))throw Error("Invalid node type: "+c);c=E(a.a);if(!Nb(c))throw Error("Invalid type name: "+c);ic(a,"(");Y(a,"Bad nodetype");e=D(a.a).charAt(0);var g=null;if('"'==e||"'"==e)g=kc(a);Y(a,"Bad nodetype");jc(a);c=new K(c,g)}else if(c=E(a.a),e=c.indexOf(":"),-1==e)c=new I(c);else{var g=c.substring(0,e),h;if("*"==g)h="*";else if(h=a.b(g),!h)throw Error("Namespace prefix not declared: "+g);c=c.substr(e+1);c=new I(c,h)}else throw Error("Bad token: "+E(a.a));e=new Xb(nc(a),f.a);return d||
new W(f,c,e,"//"==b)}function nc(a){for(var b=[];"["==D(a.a);){E(a.a);Y(a,"Missing predicate expression.");var c=gc(a);b.push(c);Y(a,"Unclosed predicate expression.");ic(a,"]")}return b}function hc(a){if("-"==D(a.a))return E(a.a),new dc(hc(a));var b=lc(a);if("|"!=D(a.a))a=b;else{for(b=[b];"|"==E(a.a);)Y(a,"Missing next union location path."),b.push(lc(a));a.a.a--;a=new ec(b)}return a};function oc(a){switch(a.nodeType){case 1:return la(pc,a);case 9:return oc(a.documentElement);case 11:case 10:case 6:case 12:return qc;default:return a.parentNode?oc(a.parentNode):qc}}function qc(){return null}function pc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?pc(a.parentNode,b):null};function rc(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=mb(a);if(pb(c))throw Error("Invalid XPath expression.");b?"function"==l(b)||(b=ka(b.lookupNamespaceURI,b)):b=function(){return null};var d=gc(new fc(c,b));if(!pb(c))throw Error("Bad token: "+E(c));this.evaluate=function(a,b){var c=d.a(new z(a));return new Z(c,b)}}
function Z(a,b){if(!b)if(a instanceof H)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof H))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof H?Ab(a):""+a;break;case 1:this.numberValue=a instanceof H?+Ab(a):+a;break;case 3:this.booleanValue=a instanceof H?0<a.l:!!a;break;case 4:case 5:case 6:case 7:var d=
L(a);c=[];for(var e=M(d);e;e=M(d))c.push(e instanceof C?e.a:e);this.snapshotLength=a.l;this.invalidIteratorState=!1;break;case 8:case 9:d=zb(a);this.singleNodeValue=d instanceof C?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=c.length||
0>a?null:c[a]}}Z.ANY_TYPE=0;Z.NUMBER_TYPE=1;Z.STRING_TYPE=2;Z.BOOLEAN_TYPE=3;Z.UNORDERED_NODE_ITERATOR_TYPE=4;Z.ORDERED_NODE_ITERATOR_TYPE=5;Z.UNORDERED_NODE_SNAPSHOT_TYPE=6;Z.ORDERED_NODE_SNAPSHOT_TYPE=7;Z.ANY_UNORDERED_NODE_TYPE=8;Z.FIRST_ORDERED_NODE_TYPE=9;function sc(a){this.lookupNamespaceURI=oc(a)}
fa("wgxpath.install",function(a,b){var c=a||k,d=c.Document&&c.Document.prototype||c.document;if(!d.evaluate||b)c.XPathResult=Z,d.evaluate=function(a,b,c,d){return(new rc(a,c)).evaluate(b,d)},d.createExpression=function(a,b){return new rc(a,b)},d.createNSResolver=function(a){return new sc(a)}});function tc(a){if(ib(a,"FRAME")||ib(a,"IFRAME")){var b;a:{try{var c;if(!(c=a.contentWindow)){var d;if(a.contentDocument){var e=a.contentDocument;d=e?e.parentWindow||e.defaultView:window}else d=null;c=d}b=c;break a}catch(f){}b=null}return b}throw new p(8,"The given element isn't a frame or an iframe.");};function uc(){}
function vc(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if("array"==l(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),vc(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),wc(d,c),c.push(":"),vc(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":wc(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var xc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},yc=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function wc(a,b){b.push('"',a.replace(yc,function(a){var b=xc[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),xc[a]=b);return b}),'"')};Ja||Ia&&(eb?bb(3.5):x?0<=qa(y,3.5):Oa(3.5))||x&&(eb?bb(8):x?qa(y,8):Oa(8));function zc(a){switch(l(a)){case "string":case "number":case "boolean":return a;case "function":return a.toString();case "array":return ta(a,zc);case "object":if(a&&"nodeType"in a&&(1==a.nodeType||9==a.nodeType)){var b={};b.ELEMENT=Ac(a);return b}if(a&&"document"in a)return b={},b.WINDOW=Ac(a),b;if(ga(a))return ta(a,zc);a=Aa(a,function(a,b){return"number"==typeof b||m(b)});return Ba(a,zc);default:return null}}
function Bc(a,b){return"array"==l(a)?ta(a,function(a){return Bc(a,b)}):ha(a)?"function"==typeof a?a:a&&"ELEMENT"in a?Cc(a.ELEMENT,b):a&&"WINDOW"in a?Cc(a.WINDOW,b):Ba(a,function(a){return Bc(a,b)}):a}function Dc(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.u=ma());b.u||(b.u=ma());return b}function Ac(a){var b=Dc(a.ownerDocument),c=Ca(b,function(b){return b==a});c||(c=":wdc:"+b.u++,b[c]=a);return c}
function Cc(a,b){a=decodeURIComponent(a);var c=b||document,d=Dc(c);if(!(d&&a in d))throw new p(10,"Element does not exist in cache");var e=d[a];if(e&&"setInterval"in e){if(e.closed)throw delete d[a],new p(23,"Window has been closed.");return e}for(var f=e;f;){if(f==c.documentElement)return e;f=f.parentNode}delete d[a];throw new p(10,"Element is no longer attached to the DOM");};fa("_",function(a){a=[a];var b=tc,c=window||oa,d;try{a:{var e=b;if(m(e))try{b=new c.Function(e);break a}catch(g){if(x&&c.execScript){c.execScript(";");b=new c.Function(e);break a}throw g;}b=c==window?e:new c.Function("return ("+e+").apply(null,arguments);")}var f=Bc(a,c.document);d={status:0,value:zc(b.apply(null,f))}}catch(g){d={status:g&&"code"in g?g.code:13,value:{message:g.message}}}f=[];vc(new uc,d,f);return f.join("")});; return this._.apply(null,arguments);}.apply({navigator:typeof window!=undefined?window.navigator:null,document:typeof window!=undefined?window.document:null}, arguments);}
