function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var b=this||self;try{var c=window}catch(a){c=b};function h(a,d){this.code=a;this.state=k[a]||l;this.message=d||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(f){return f.toUpperCase().replace(/^[\s\xa0]+/g,"")});d=a.length-5;if(d<0||a.indexOf("Error",d)!=d)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}(function(){function a(){}a.prototype=Error.prototype;h.prototype=new a;h.prototype.constructor=h})();var l="unknown error",k={15:"element not selectable",11:"element not visible"};k[31]=l;k[30]=l;
k[24]="invalid cookie domain";k[29]="invalid element coordinates";k[12]="invalid element state";k[32]="invalid selector";k[51]="invalid selector";k[52]="invalid selector";k[17]="javascript error";k[405]="unsupported operation";k[34]="move target out of bounds";k[27]="no such alert";k[7]="no such element";k[8]="no such frame";k[23]="no such window";k[28]="script timeout";k[33]="session not created";k[10]="stale element reference";k[21]="timeout";k[25]="unable to set cookie";k[26]="unexpected alert open";
k[13]=l;k[9]="unknown command";h.prototype.toString=function(){return this.name+": "+this.message};var m=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function n(a,d){var f=0;a=m(String(a)).split(".");d=m(String(d)).split(".");var t=Math.max(a.length,d.length);for(let u=0;f==0&&u<t;u++){var e=a[u]||"",g=d[u]||"";do{e=/(\d*)(\D*)(.*)/.exec(e)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(e[0].length==0&&g[0].length==0)break;f=p(e[1].length==0?0:parseInt(e[1],10),g[1].length==0?0:parseInt(g[1],10))||p(e[2].length==0,g[2].length==0)||p(e[2],g[2]);e=e[3];g=g[3]}while(f==0)}return f}function p(a,d){return a<d?-1:a>d?1:0};var r=class{constructor(a){if(q!==q)throw Error("SafeUrl is not meant to be built directly");this.j=a}toString(){return this.j.toString()}},q={};new r("about:invalid#zClosurez");new r("about:blank");const v={};class w{constructor(){if(v!==v)throw Error("SafeStyle is not meant to be built directly");this.i=""}toString(){return this.i.toString()}}new w;const x={};class y{constructor(){if(x!==x)throw Error("SafeStyleSheet is not meant to be built directly");this.h=""}toString(){return this.h.toString()}}new y;function z(){var a=b.navigator;return a&&(a=a.userAgent)?a:""}function A(a){return z().indexOf(a)!=-1};function B(){return A("Firefox")||A("FxiOS")}function C(){return(A("Chrome")||A("CriOS"))&&!A("Edge")||A("Silk")};const D={};class E{constructor(){var a=b.trustedTypes&&b.trustedTypes.emptyHTML||"";if(D!==D)throw Error("SafeHtml is not meant to be built directly");this.g=a}toString(){return this.g.toString()}}new E;function F(){return A("iPhone")&&!A("iPod")&&!A("iPad")};var G=A("Windows");var H=B(),I=F()||A("iPod"),J=A("iPad"),K=A("Android")&&!(C()||B()||A("Opera")||A("Silk")),L=C(),M=A("Safari")&&!(C()||A("Coast")||A("Opera")||A("Edge")||A("Edg/")||A("OPR")||B()||A("Silk")||A("Android"))&&!(F()||A("iPad")||A("iPod"));function N(a){return(a=a.exec(z()))?a[1]:""}var O=function(){if(H)return N(/Firefox\/([0-9.]+)/);if(L){if(F()||A("iPad")||A("iPod")||A("Macintosh")){var a=N(/CriOS\/([0-9.]+)/);if(a)return a}return N(/Chrome\/([0-9.]+)/)}if(M&&!(F()||A("iPad")||A("iPod")))return N(/Version\/([0-9.]+)/);if(I||J){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(z()))return a[1]+"."+a[2]}else if(K)return(a=N(/Android\s+([0-9.]+)/))?a:N(/Version\/([0-9.]+)/);return""}();var P;if(K){var Q=/Android\s+([0-9\.]+)/.exec(z());P=Q?Q[1]:"0"}else P="0";var R=P;var S=G&&M&&(K?n(R,4)>=0:n(O,4)>=0)&&!(K?n(R,6)>=0:n(O,6)>=0);var T={enableHighAccuracy:!0,maximumAge:Infinity,timeout:5E3};function U(a,d,f){var t=c;f=f||T;var e=t||c;if(S?0:e.navigator!=null&&e.navigator.geolocation!=null)t.navigator.geolocation.getCurrentPosition(a,d,f);else throw new h(13,"Geolocation undefined");}var V=["se_exportedFunctionSymbol"],W=b;V[0]in W||typeof W.execScript=="undefined"||W.execScript("var "+V[0]);for(var X;V.length&&(X=V.shift());)V.length||U===void 0?W=W[X]&&W[X]!==Object.prototype[X]?W[X]:W[X]={}:W[X]=U;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
