function(){return (function(){/*

 Copyright The Closure Library Authors.
 Copyright The Closure Compiler Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var d=this||self;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var g=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var h={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var k="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),l=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,m=/^#(?:[0-9a-f]{3}){1,2}$/i,n=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,p=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function q(){var a=d.navigator;return a&&(a=a.userAgent)?a:""}function r(a){return q().indexOf(a)!=-1};function t(){return r("Firefox")||r("FxiOS")}function u(){return(r("Chrome")||r("CriOS"))&&!r("Edge")||r("Silk")};function v(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};function w(){return r("iPhone")&&!r("iPod")&&!r("iPad")};var x=t(),y=w()||r("iPod"),z=r("iPad"),A=r("Android")&&!(u()||t()||r("Opera")||r("Silk")),B=u(),C=r("Safari")&&!(u()||r("Coast")||r("Opera")||r("Edge")||r("Edg/")||r("OPR")||t()||r("Silk")||r("Android"))&&!(w()||r("iPad")||r("iPod"));function D(a){return(a=a.exec(q()))?a[1]:""}(function(){if(x)return D(/Firefox\/([0-9.]+)/);if(B){if(w()||r("iPad")||r("iPod")||r("Macintosh")){var a=D(/CriOS\/([0-9.]+)/);if(a)return a}return D(/Chrome\/([0-9.]+)/)}if(C&&!(w()||r("iPad")||r("iPod")))return D(/Version\/([0-9.]+)/);if(y||z){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(q()))return a[1]+"."+a[2]}else if(A)return(a=D(/Android\s+([0-9.]+)/))?a:D(/Version\/([0-9.]+)/);return""})();function E(a,b){var c=a.currentStyle||a.style,e=c[b];e===void 0&&typeof c.getPropertyValue==="function"&&(e=c.getPropertyValue(b));if(e!="inherit")return e!==void 0?e:null;var f;for(a=a.parentNode;a&&a.nodeType!=1&&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode;f&&typeof f!=="string"&&(f=f.toString());return(f=(a instanceof HTMLFormElement?!a||a.nodeType!=1||f&&"FORM"!=f:!a||a.nodeType!=1||f&&a.tagName.toUpperCase()!=f)?null:a)?E(f,b):null};function F(a,b){b=v(b);if(b=="float"||b=="cssFloat"||b=="styleFloat")b="cssFloat";a:{var c=b;var e=a.nodeType==9?a:a.ownerDocument||a.document;if(e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))){c=e[c]||e.getPropertyValue(c)||"";break a}c=""}a=c||E(a,b);if(a===null)a=null;else if(g(k,b)>=0){b:{var f=a.match(n);if(f&&(b=Number(f[1]),c=Number(f[2]),e=Number(f[3]),f=Number(f[4]),b>=0&&b<=255&&c>=0&&c<=255&&e>=0&&e<=255&&f>=0&&f<=1)){b=[b,c,e,f];break b}b=null}if(!b)b:{if(e=
a.match(p))if(b=Number(e[1]),c=Number(e[2]),e=Number(e[3]),b>=0&&b<=255&&c>=0&&c<=255&&e>=0&&e<=255){b=[b,c,e,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=h[b.toLowerCase()];if(!c&&(c=b.charAt(0)=="#"?b:"#"+b,c.length==4&&(c=c.replace(l,"#$1$1$2$2$3$3")),!m.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}var G=["se_exportedFunctionSymbol"],H=d;
G[0]in H||typeof H.execScript=="undefined"||H.execScript("var "+G[0]);for(var I;G.length&&(I=G.shift());)G.length||F===void 0?H[I]&&H[I]!==Object.prototype[I]?H=H[I]:H=H[I]={}:H[I]=F;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
