function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var b=this||self;var k=class extends Error{constructor(a,d){super(d||"");this.code=a;this.state=c[a]||g;this.message=d||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(f){return f.toUpperCase().replace(/^[\s\xa0]+/g,"")});d=a.length-5;if(d<0||a.indexOf("Error",d)!=d)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}},g="unknown error",c={15:"element not selectable",11:"element not visible"};c[31]=g;c[30]=g;c[24]="invalid cookie domain";c[29]="invalid element coordinates";
c[12]="invalid element state";c[32]="invalid selector";c[51]="invalid selector";c[52]="invalid selector";c[17]="javascript error";c[405]="unsupported operation";c[34]="move target out of bounds";c[27]="no such alert";c[7]="no such element";c[8]="no such frame";c[23]="no such window";c[28]="script timeout";c[33]="session not created";c[10]="stale element reference";c[21]="timeout";c[25]="unable to set cookie";c[26]="unexpected alert open";c[13]=g;c[9]="unknown command";
k.prototype.toString=function(){return this.name+": "+this.message};(class{constructor(a,d){this.m=a===l&&d||""}}).prototype.toString=function(){return"Const{"+this.m+"}"};var l={};var n=class{constructor(a){if(m!==m)throw Error("SafeUrl is not meant to be built directly");this.l=a}toString(){return this.l.toString()}},m={};new n("about:invalid#zClosurez");new n("about:blank");var p={};class q{constructor(){if(p!==p)throw Error("SafeStyle is not meant to be built directly");this.j=""}toString(){return this.j.toString()}}new q;var r={};class t{constructor(){if(r!==r)throw Error("SafeStyleSheet is not meant to be built directly");this.i=""}toString(){return this.i.toString()}}new t;function u(){var a=b.navigator;return a&&(a=a.userAgent)?a:""}function v(a){return u().indexOf(a)!=-1};function w(){return v("Firefox")||v("FxiOS")}function x(){return(v("Chrome")||v("CriOS"))&&!v("Edge")||v("Silk")};var y={};class z{constructor(){var a=b.trustedTypes&&b.trustedTypes.emptyHTML||"";if(y!==y)throw Error("SafeHtml is not meant to be built directly");this.h=a}toString(){return this.h.toString()}}new z;function A(){return v("iPhone")&&!v("iPod")&&!v("iPad")};var B=w(),C=A()||v("iPod"),D=v("iPad"),E=v("Android")&&!(x()||w()||v("Opera")||v("Silk")),F=x(),G=v("Safari")&&!(x()||v("Coast")||v("Opera")||v("Edge")||v("Edg/")||v("OPR")||w()||v("Silk")||v("Android"))&&!(A()||v("iPad")||v("iPod"));function H(a){return(a=a.exec(u()))?a[1]:""}(function(){if(B)return H(/Firefox\/([0-9.]+)/);if(F){if(A()||v("iPad")||v("iPod")||v("Macintosh")){var a=H(/CriOS\/([0-9.]+)/);if(a)return a}return H(/Chrome\/([0-9.]+)/)}if(G&&!(A()||v("iPad")||v("iPod")))return H(/Version\/([0-9.]+)/);if(C||D){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(u()))return a[1]+"."+a[2]}else if(E)return(a=H(/Android\s+([0-9.]+)/))?a:H(/Version\/([0-9.]+)/);return""})();function I(a,d){a=decodeURIComponent(a);d=d||document;var f=d||document;var e=f.$wdc_;e||(e=f.$wdc_={},e.g=Date.now());e.g||(e.g=Date.now());f=e;if(!(f!==null&&a in f))throw new k(10,"Element does not exist in cache");e=f[a];a:if(e!==null&&"setInterval"in e)d=!!e.closed;else{for(var h=e;h;){if(h==d.documentElement){d=!1;break a}h.host&&h.nodeType===11&&(h=h.host);h=h.parentNode}d=!0}if(!d)return e;delete f[a];if(e!==null&&"setInterval"in e)throw new k(23,"Window has been closed.");throw new k(10,
"Element is no longer attached to the DOM");}var J=["se_exportedFunctionSymbol"],K=b;J[0]in K||typeof K.execScript=="undefined"||K.execScript("var "+J[0]);for(var L;J.length&&(L=J.shift());)J.length||I===void 0?K=K[L]&&K[L]!==Object.prototype[L]?K[L]:K[L]={}:K[L]=I;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
