function(){return (function(){var aa=this||self;function ba(a){return"string"==typeof a}function ca(a,b){a=a.split(".");var c=aa;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ha(a,b,c){return a.call.apply(a.bind,arguments)}
function ia(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function ja(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja=ha:ja=ia;return ja.apply(null,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var la=Date.now||function(){return+new Date};function g(a,b){function c(){}c.prototype=b.prototype;a.I=b.prototype;a.prototype=new c;a.prototype.constructor=a}
function ma(a,b,c){var d=arguments.callee.caller;if("undefined"!==typeof d.I){for(var e=Array(arguments.length-1),f=1;f<arguments.length;f++)e[f-1]=arguments[f];d.I.constructor.apply(a,e)}else{if("string"!=typeof b&&"symbol"!=typeof b)throw Error("method names provided to goog.base must be a string or a symbol");e=Array(arguments.length-2);for(f=2;f<arguments.length;f++)e[f-2]=arguments[f];f=!1;for(var h=a.constructor.prototype;h;h=Object.getPrototypeOf(h))if(h[b]===d)f=!0;else if(f){h[b].apply(a,
e);return}if(a[b]===d)a.constructor.prototype[b].apply(a,e);else throw Error("goog.base called from a method of one name to a method of a different name");}};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function l(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var na=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},n=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},p=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},q=Array.prototype.reduce?function(a,b,c){return Array.prototype.reduce.call(a,b,c)}:function(a,b,c){var d=c;n(a,function(e,f){d=b.call(void 0,d,e,f,a)});return d},oa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,
d[e],e,a))return!0;return!1};function pa(a){return Array.prototype.concat.apply([],arguments)}function qa(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var ra=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function sa(a){var b=0;a=ra(String(a)).split(".");for(var c=ra("4").split("."),d=Math.max(a.length,c.length),e=0;0==b&&e<d;e++){var f=a[e]||"",h=c[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;b=ta(0==f[1].length?0:parseInt(f[1],10),0==h[1].length?0:parseInt(h[1],10))||ta(0==f[2].length,0==h[2].length)||ta(f[2],h[2]);f=f[3];h=h[3]}while(0==b)}return b}function ta(a,b){return a<b?-1:a>b?1:0};var r;a:{var ua=aa.navigator;if(ua){var va=ua.userAgent;if(va){r=va;break a}}r=""}function t(a){return-1!=r.indexOf(a)};function wa(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function xa(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function v(a,b){return null!==a&&b in a}function ya(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function za(){return t("Firefox")||t("FxiOS")}function Aa(){return(t("Chrome")||t("CriOS"))&&!t("Edge")};function Ba(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};function Ca(){return t("iPhone")&&!t("iPod")&&!t("iPad")};var Da=t("Macintosh"),Ea=t("Windows");function Fa(a){this.b=a;this.a=0}function Ga(a){a=a.match(Ha);for(var b=0;b<a.length;b++)Ja.test(a[b])&&a.splice(b,1);return new Fa(a)}var Ha=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,Ja=/^\s/;function x(a,b){return a.b[a.a+(b||0)]}function y(a){return a.b[a.a++]}function Ka(a){return a.b.length<=a.a};function La(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Ma(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Na(a,b):!c&&La(e,b)?-1*Oa(a,b):!d&&La(f,a)?Oa(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=z(a);c=d.createRange();c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);
a.collapse(!0);return c.compareBoundaryPoints(aa.Range.START_TO_END,a)}function Oa(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Na(b,a)}function Na(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function z(a){return 9==a.nodeType?a:a.ownerDocument||a.document};function A(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;c=0;var d=[];for(b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return b}
function B(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Pa(a,b,c,d,e){return Qa.call(null,a,b,ba(c)?c:null,ba(d)?d:null,e||new C)}
function Qa(a,b,c,d,e){b.getElementsByName&&d&&"name"==c?(b=b.getElementsByName(d),n(b,function(f){a.a(f)&&e.add(f)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),n(b,function(f){f.className==d&&a.a(f)&&e.add(f)})):a instanceof D?Ra(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),n(b,function(f){B(f,c,d)&&e.add(f)}));return e}function Ra(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)B(b,c,d)&&a.a(b)&&e.add(b),Ra(a,b,c,d,e)};function C(){this.b=this.a=null;this.o=0}function Sa(a){this.f=a;this.a=this.b=null}function Ta(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;)c.f==b.f?(e=c,c=c.a,b=b.a):0<Ma(c.f,b.f)?(e=b,b=b.a):(e=c,c=c.a),(e.b=d)?d.a=e:a.a=e,d=e,f++;for(e=c||b;e;)e.b=d,d=d.a=e,f++,e=e.a;a.b=d;a.o=f;return a}function Ua(a,b){b=new Sa(b);b.a=a.a;a.b?a.a.b=b:a.a=a.b=b;a.a=b;a.o++}C.prototype.add=function(a){a=new Sa(a);a.b=this.b;this.a?this.b.a=a:this.a=this.b=a;this.b=a;this.o++};
function Va(a){return(a=a.a)?a.f:null}function Wa(a){return(a=Va(a))?A(a):""}function E(a,b){return new Xa(a,!!b)}function Xa(a,b){this.f=a;this.b=(this.v=b)?a.b:a.a;this.a=null}function F(a){var b=a.b;if(null==b)return null;var c=a.a=b;a.b=a.v?b.b:b.a;return c.f};function G(a){this.l=a;this.b=this.i=!1;this.f=null}function H(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Ya(a,b){a.i=b}function Za(a,b){a.b=b}function J(a,b){a=a.a(b);return a instanceof C?+Wa(a):+a}function K(a,b){a=a.a(b);return a instanceof C?Wa(a):""+a}function $a(a,b){a=a.a(b);return a instanceof C?!!a.o:!!a};function ab(a,b,c){G.call(this,a.l);this.c=a;this.j=b;this.u=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==bb&&(c.b||c.i||4==c.l||0==c.l||!b.f?b.b||b.i||4==b.l||0==b.l||!c.f||(this.f={name:c.f.name,A:b}):this.f={name:b.f.name,A:c})}g(ab,G);
function cb(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof C&&c instanceof C){b=E(b);for(d=F(b);d;d=F(b))for(e=E(c),f=F(e);f;f=F(e))if(a(A(d),A(f)))return!0;return!1}if(b instanceof C||c instanceof C){b instanceof C?(e=b,d=c):(e=c,d=b);f=E(e);for(var h=typeof d,m=F(f);m;m=F(f)){switch(h){case "number":m=+A(m);break;case "boolean":m=!!A(m);break;case "string":m=A(m);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(m,d)||e==c&&a(d,m))return!0}return!1}return e?"boolean"==
typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}ab.prototype.a=function(a){return this.c.s(this.j,this.u,a)};ab.prototype.toString=function(){var a="Binary Expression: "+this.c;a+=H(this.j);return a+=H(this.u)};function db(a,b,c,d){this.M=a;this.H=b;this.l=c;this.s=d}db.prototype.toString=function(){return this.M};var eb={};
function L(a,b,c,d){if(eb.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new db(a,b,c,d);return eb[a.toString()]=a}L("div",6,1,function(a,b,c){return J(a,c)/J(b,c)});L("mod",6,1,function(a,b,c){return J(a,c)%J(b,c)});L("*",6,1,function(a,b,c){return J(a,c)*J(b,c)});L("+",5,1,function(a,b,c){return J(a,c)+J(b,c)});L("-",5,1,function(a,b,c){return J(a,c)-J(b,c)});L("<",4,2,function(a,b,c){return cb(function(d,e){return d<e},a,b,c)});
L(">",4,2,function(a,b,c){return cb(function(d,e){return d>e},a,b,c)});L("<=",4,2,function(a,b,c){return cb(function(d,e){return d<=e},a,b,c)});L(">=",4,2,function(a,b,c){return cb(function(d,e){return d>=e},a,b,c)});var bb=L("=",3,2,function(a,b,c){return cb(function(d,e){return d==e},a,b,c,!0)});L("!=",3,2,function(a,b,c){return cb(function(d,e){return d!=e},a,b,c,!0)});L("and",2,2,function(a,b,c){return $a(a,c)&&$a(b,c)});L("or",1,2,function(a,b,c){return $a(a,c)||$a(b,c)});function fb(a,b){if(b.a.length&&4!=a.l)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");G.call(this,a.l);this.c=a;this.j=b;this.i=a.i;this.b=a.b}g(fb,G);fb.prototype.a=function(a){a=this.c.a(a);return gb(this.j,a)};fb.prototype.toString=function(){var a="Filter:"+H(this.c);return a+=H(this.j)};function hb(a,b){if(b.length<a.G)throw Error("Function "+a.m+" expects at least"+a.G+" arguments, "+b.length+" given");if(null!==a.D&&b.length>a.D)throw Error("Function "+a.m+" expects at most "+a.D+" arguments, "+b.length+" given");a.L&&n(b,function(c,d){if(4!=c.l)throw Error("Argument "+d+" to function "+a.m+" is not of type Nodeset: "+c);});G.call(this,a.l);this.B=a;this.c=b;Ya(this,a.i||oa(b,function(c){return c.i}));Za(this,a.K&&!b.length||a.J&&!!b.length||oa(b,function(c){return c.b}))}
g(hb,G);hb.prototype.a=function(a){return this.B.s.apply(null,pa(a,this.c))};hb.prototype.toString=function(){var a="Function: "+this.B;if(this.c.length){var b=q(this.c,function(c,d){return c+H(d)},"Arguments:");a+=H(b)}return a};function ib(a,b,c,d,e,f,h,m){this.m=a;this.l=b;this.i=c;this.K=d;this.J=!1;this.s=e;this.G=f;this.D=void 0!==h?h:f;this.L=!!m}ib.prototype.toString=function(){return this.m};var jb={};
function M(a,b,c,d,e,f,h,m){if(jb.hasOwnProperty(a))throw Error("Function already created: "+a+".");jb[a]=new ib(a,b,c,d,e,f,h,m)}M("boolean",2,!1,!1,function(a,b){return $a(b,a)},1);M("ceiling",1,!1,!1,function(a,b){return Math.ceil(J(b,a))},1);M("concat",3,!1,!1,function(a,b){return q(qa(arguments,1),function(c,d){return c+K(d,a)},"")},2,null);M("contains",2,!1,!1,function(a,b,c){b=K(b,a);a=K(c,a);return-1!=b.indexOf(a)},2);M("count",1,!1,!1,function(a,b){return b.a(a).o},1,1,!0);
M("false",2,!1,!1,function(){return!1},0);M("floor",1,!1,!1,function(a,b){return Math.floor(J(b,a))},1);M("id",4,!1,!1,function(a,b){var c=a.a,d=9==c.nodeType?c:c.ownerDocument;a=K(b,a).split(/\s+/);var e=[];n(a,function(h){h=d.getElementById(h);!h||0<=na(e,h)||e.push(h)});e.sort(Ma);var f=new C;n(e,function(h){f.add(h)});return f},1);M("lang",2,!1,!1,function(){return!1},1);M("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);
M("local-name",3,!1,!0,function(a,b){return(a=b?Va(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);M("name",3,!1,!0,function(a,b){return(a=b?Va(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);M("namespace-uri",3,!0,!1,function(){return""},0,1,!0);M("normalize-space",3,!1,!0,function(a,b){return(b?K(b,a):A(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);M("not",2,!1,!1,function(a,b){return!$a(b,a)},1);M("number",1,!1,!0,function(a,b){return b?J(b,a):+A(a.a)},0,1);
M("position",1,!0,!1,function(a){return a.b},0);M("round",1,!1,!1,function(a,b){return Math.round(J(b,a))},1);M("starts-with",2,!1,!1,function(a,b,c){b=K(b,a);a=K(c,a);return 0==b.lastIndexOf(a,0)},2);M("string",3,!1,!0,function(a,b){return b?K(b,a):A(a.a)},0,1);M("string-length",1,!1,!0,function(a,b){return(b?K(b,a):A(a.a)).length},0,1);
M("substring",3,!1,!1,function(a,b,c,d){c=J(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?J(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=K(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);M("substring-after",3,!1,!1,function(a,b,c){b=K(b,a);a=K(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
M("substring-before",3,!1,!1,function(a,b,c){b=K(b,a);a=K(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);M("sum",1,!1,!1,function(a,b){a=E(b.a(a));b=0;for(var c=F(a);c;c=F(a))b+=+A(c);return b},1,1,!0);M("translate",3,!1,!1,function(a,b,c,d){b=K(b,a);c=K(c,a);var e=K(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);M("true",2,!1,!1,function(){return!0},0);function D(a,b){this.j=a;this.c=void 0!==b?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function kb(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}D.prototype.a=function(a){return null===this.b||this.b==a.nodeType};D.prototype.f=function(){return this.j};
D.prototype.toString=function(){var a="Kind Test: "+this.j;null===this.c||(a+=H(this.c));return a};function lb(a){G.call(this,3);this.c=a.substring(1,a.length-1)}g(lb,G);lb.prototype.a=function(){return this.c};lb.prototype.toString=function(){return"Literal: "+this.c};function mb(a,b){this.m=a.toLowerCase();a="*"==this.m?"*":"http://www.w3.org/1999/xhtml";this.b=b?b.toLowerCase():a}mb.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=void 0!==a.localName?a.localName:a.nodeName;return"*"!=this.m&&this.m!=b.toLowerCase()?!1:"*"==this.b?!0:this.b==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};mb.prototype.f=function(){return this.m};
mb.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.b?"":this.b+":")+this.m};function nb(a){G.call(this,1);this.c=a}g(nb,G);nb.prototype.a=function(){return this.c};nb.prototype.toString=function(){return"Number: "+this.c};function ob(a,b){G.call(this,a.l);this.j=a;this.c=b;this.i=a.i;this.b=a.b;1==this.c.length&&(a=this.c[0],a.C||a.c!=pb||(a=a.u,"*"!=a.f()&&(this.f={name:a.f(),A:null})))}g(ob,G);function qb(){G.call(this,4)}g(qb,G);qb.prototype.a=function(a){var b=new C;a=a.a;9==a.nodeType?b.add(a):b.add(a.ownerDocument);return b};qb.prototype.toString=function(){return"Root Helper Expression"};function rb(){G.call(this,4)}g(rb,G);rb.prototype.a=function(a){var b=new C;b.add(a.a);return b};rb.prototype.toString=function(){return"Context Helper Expression"};
function sb(a){return"/"==a||"//"==a}ob.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof C))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.o;c++){var e=a[c],f=E(b,e.c.v);if(e.i||e.c!=tb)if(e.i||e.c!=ub){var h=F(f);for(b=e.a(new l(h));null!=(h=F(f));)h=e.a(new l(h)),b=Ta(b,h)}else h=F(f),b=e.a(new l(h));else{for(h=F(f);(b=F(f))&&(!h.contains||h.contains(b))&&b.compareDocumentPosition(h)&8;h=b);b=e.a(new l(h))}}return b};
ob.prototype.toString=function(){var a="Path Expression:"+H(this.j);if(this.c.length){var b=q(this.c,function(c,d){return c+H(d)},"Steps:");a+=H(b)}return a};function vb(a,b){this.a=a;this.v=!!b}
function gb(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=E(b),f=b.o,h,m=0;h=F(e);m++){var k=a.v?f-m:m+1;h=d.a(new l(h,k,f));if("number"==typeof h)k=k==h;else if("string"==typeof h||"boolean"==typeof h)k=!!h;else if(h instanceof C)k=0<h.o;else throw Error("Predicate.evaluate returned an unexpected type.");if(!k){k=e;h=k.f;var w=k.a;if(!w)throw Error("Next must be called at least once before remove.");var I=w.b;w=w.a;I?I.a=w:h.a=w;w?w.b=I:h.b=I;h.o--;k.a=null}}return b}
vb.prototype.toString=function(){return q(this.a,function(a,b){return a+H(b)},"Predicates:")};function P(a,b,c,d){G.call(this,4);this.c=a;this.u=b;this.j=c||new vb([]);this.C=!!d;b=this.j;b=0<b.a.length?b.a[0].f:null;a.N&&b&&(this.f={name:b.name,A:b.A});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.l||0==c.l){a=!0;break a}a=!1}this.i=a}g(P,G);
P.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.A?K(c.A,a):null,f=1);if(this.C)if(this.i||this.c!=wb)if(b=E((new P(xb,new D("node"))).a(a)),c=F(b))for(a=this.s(c,d,e,f);null!=(c=F(b));)a=Ta(a,this.s(c,d,e,f));else a=new C;else a=Pa(this.u,b,d,e),a=gb(this.j,a,f);else a=this.s(a.a,d,e,f);return a};P.prototype.s=function(a,b,c,d){a=this.c.B(this.u,a,b,c);return a=gb(this.j,a,d)};
P.prototype.toString=function(){var a="Step:"+H("Operator: "+(this.C?"//":"/"));this.c.m&&(a+=H("Axis: "+this.c));a+=H(this.u);if(this.j.a.length){var b=q(this.j.a,function(c,d){return c+H(d)},"Predicates:");a+=H(b)}return a};function yb(a,b,c,d){this.m=a;this.B=b;this.v=c;this.N=d}yb.prototype.toString=function(){return this.m};var zb={};function Q(a,b,c,d){if(zb.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new yb(a,b,c,!!d);return zb[a]=b}
Q("ancestor",function(a,b){for(var c=new C;b=b.parentNode;)a.a(b)&&Ua(c,b);return c},!0);Q("ancestor-or-self",function(a,b){var c=new C;do a.a(b)&&Ua(c,b);while(b=b.parentNode);return c},!0);
var pb=Q("attribute",function(a,b){var c=new C,d=a.f();if(b=b.attributes)if(a instanceof D&&null===a.b||"*"==d)for(a=0;d=b[a];a++)c.add(d);else(d=b.getNamedItem(d))&&c.add(d);return c},!1),wb=Q("child",function(a,b,c,d,e){c=ba(c)?c:null;d=ba(d)?d:null;e=e||new C;for(b=b.firstChild;b;b=b.nextSibling)B(b,c,d)&&a.a(b)&&e.add(b);return e},!1,!0);Q("descendant",Pa,!1,!0);
var xb=Q("descendant-or-self",function(a,b,c,d){var e=new C;B(b,c,d)&&a.a(b)&&e.add(b);return Pa(a,b,c,d,e)},!1,!0),tb=Q("following",function(a,b,c,d){var e=new C;do for(var f=b;f=f.nextSibling;)B(f,c,d)&&a.a(f)&&e.add(f),e=Pa(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);Q("following-sibling",function(a,b){for(var c=new C;b=b.nextSibling;)a.a(b)&&c.add(b);return c},!1);Q("namespace",function(){return new C},!1);
var Ab=Q("parent",function(a,b){var c=new C;if(9==b.nodeType)return c;if(2==b.nodeType)return c.add(b.ownerElement),c;b=b.parentNode;a.a(b)&&c.add(b);return c},!1),ub=Q("preceding",function(a,b,c,d){var e=new C,f=[];do f.unshift(b);while(b=b.parentNode);for(var h=1,m=f.length;h<m;h++){var k=[];for(b=f[h];b=b.previousSibling;)k.unshift(b);for(var w=0,I=k.length;w<I;w++)b=k[w],B(b,c,d)&&a.a(b)&&e.add(b),e=Pa(a,b,c,d,e)}return e},!0,!0);
Q("preceding-sibling",function(a,b){for(var c=new C;b=b.previousSibling;)a.a(b)&&Ua(c,b);return c},!0);var Bb=Q("self",function(a,b){var c=new C;a.a(b)&&c.add(b);return c},!1);function Cb(a){G.call(this,1);this.c=a;this.i=a.i;this.b=a.b}g(Cb,G);Cb.prototype.a=function(a){return-J(this.c,a)};Cb.prototype.toString=function(){return"Unary Expression: -"+H(this.c)};function Db(a){G.call(this,4);this.c=a;Ya(this,oa(this.c,function(b){return b.i}));Za(this,oa(this.c,function(b){return b.b}))}g(Db,G);Db.prototype.a=function(a){var b=new C;n(this.c,function(c){c=c.a(a);if(!(c instanceof C))throw Error("Path expression must evaluate to NodeSet.");b=Ta(b,c)});return b};Db.prototype.toString=function(){return q(this.c,function(a,b){return a+H(b)},"Union Expression:")};function Eb(a,b){this.a=a;this.b=b}function Fb(a){for(var b,c=[];;){R(a,"Missing right hand side of binary expression.");b=Gb(a);var d=y(a.a);if(!d)break;var e=(d=eb[d]||null)&&d.H;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].H;)b=new ab(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new ab(c.pop(),c.pop(),b);return b}function R(a,b){if(Ka(a.a))throw Error(b);}function Hb(a,b){a=y(a.a);if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function Ib(a){a=y(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Jb(a){a=y(a.a);if(2>a.length)throw Error("Unclosed literal string");return new lb(a)}
function Kb(a){var b=[];if(sb(x(a.a))){var c=y(a.a);var d=x(a.a);if("/"==c&&(Ka(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new qb;d=new qb;R(a,"Missing next location step.");c=Lb(a,c);b.push(c)}else{a:{c=x(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":y(a.a);c=Fb(a);R(a,'unclosed "("');Hb(a,")");break;case '"':case "'":c=Jb(a);break;default:if(isNaN(+c))if(!kb(c)&&/(?![0-9])[\w]/.test(d)&&"("==x(a.a,1)){c=y(a.a);
c=jb[c]||null;y(a.a);for(d=[];")"!=x(a.a);){R(a,"Missing function argument list.");d.push(Fb(a));if(","!=x(a.a))break;y(a.a)}R(a,"Unclosed function argument list.");Ib(a);c=new hb(c,d)}else{c=null;break a}else c=new nb(+y(a.a))}"["==x(a.a)&&(d=new vb(Mb(a)),c=new fb(c,d))}if(c)if(sb(x(a.a)))d=c;else return c;else c=Lb(a,"/"),d=new rb,b.push(c)}for(;sb(x(a.a));)c=y(a.a),R(a,"Missing next location step."),c=Lb(a,c),b.push(c);return new ob(d,b)}
function Lb(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==x(a.a)){var c=new P(Bb,new D("node"));y(a.a);return c}if(".."==x(a.a))return c=new P(Ab,new D("node")),y(a.a),c;if("@"==x(a.a)){var d=pb;y(a.a);R(a,"Missing attribute name")}else if("::"==x(a.a,1)){if(!/(?![0-9])[\w]/.test(x(a.a).charAt(0)))throw Error("Bad token: "+y(a.a));var e=y(a.a);d=zb[e]||null;if(!d)throw Error("No axis with name: "+e);y(a.a);R(a,"Missing node name")}else d=wb;e=x(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==
x(a.a,1)){if(!kb(e))throw Error("Invalid node type: "+e);e=y(a.a);if(!kb(e))throw Error("Invalid type name: "+e);Hb(a,"(");R(a,"Bad nodetype");var f=x(a.a).charAt(0),h=null;if('"'==f||"'"==f)h=Jb(a);R(a,"Bad nodetype");Ib(a);e=new D(e,h)}else if(e=y(a.a),f=e.indexOf(":"),-1==f)e=new mb(e);else{h=e.substring(0,f);if("*"==h)var m="*";else if(m=a.b(h),!m)throw Error("Namespace prefix not declared: "+h);e=e.substr(f+1);e=new mb(e,m)}else throw Error("Bad token: "+y(a.a));a=new vb(Mb(a),d.v);return c||
new P(d,e,a,"//"==b)}function Mb(a){for(var b=[];"["==x(a.a);){y(a.a);R(a,"Missing predicate expression.");var c=Fb(a);b.push(c);R(a,"Unclosed predicate expression.");Hb(a,"]")}return b}function Gb(a){if("-"==x(a.a))return y(a.a),new Cb(Gb(a));var b=Kb(a);if("|"!=x(a.a))a=b;else{for(b=[b];"|"==y(a.a);)R(a,"Missing next union location path."),b.push(Kb(a));a.a.a--;a=new Db(b)}return a};function Nb(a){switch(a.nodeType){case 1:return ka(Ob,a);case 9:return Nb(a.documentElement);case 11:case 10:case 6:case 12:return Pb;default:return a.parentNode?Nb(a.parentNode):Pb}}function Pb(){return null}function Ob(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Ob(a.parentNode,b):null};function Qb(a,b){if(!a.length)throw Error("Empty XPath expression.");a=Ga(a);if(Ka(a))throw Error("Invalid XPath expression.");b?"function"==da(b)||(b=ja(b.lookupNamespaceURI,b)):b=function(){return null};var c=Fb(new Eb(a,b));if(!Ka(a))throw Error("Bad token: "+y(a));this.evaluate=function(d,e){d=c.a(new l(d));return new S(d,e)}}
function S(a,b){if(0==b)if(a instanceof C)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof C))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof C?Wa(a):""+a;break;case 1:this.numberValue=a instanceof C?+Wa(a):+a;break;case 3:this.booleanValue=a instanceof C?0<a.o:!!a;break;case 4:case 5:case 6:case 7:var c=
E(a);var d=[];for(var e=F(c);e;e=F(c))d.push(e);this.snapshotLength=a.o;this.invalidIteratorState=!1;break;case 8:case 9:this.singleNodeValue=Va(a);break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(h){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return h>=d.length||0>h?null:d[h]}}S.ANY_TYPE=0;
S.NUMBER_TYPE=1;S.STRING_TYPE=2;S.BOOLEAN_TYPE=3;S.UNORDERED_NODE_ITERATOR_TYPE=4;S.ORDERED_NODE_ITERATOR_TYPE=5;S.UNORDERED_NODE_SNAPSHOT_TYPE=6;S.ORDERED_NODE_SNAPSHOT_TYPE=7;S.ANY_UNORDERED_NODE_TYPE=8;S.FIRST_ORDERED_NODE_TYPE=9;function Rb(a){this.lookupNamespaceURI=Nb(a)}
function Sb(a,b){a=a||aa;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=S,c.evaluate=function(d,e,f,h){return(new Qb(d,f)).evaluate(e,h)},c.createExpression=function(d,e){return new Qb(d,e)},c.createNSResolver=function(d){return new Rb(d)}}ca("wgxpath.install",Sb);ca("wgxpath.install",Sb);var Tb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Ub="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Vb=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Wb=/^#(?:[0-9a-f]{3}){1,2}$/i,Xb=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Yb=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function T(a,b){this.code=a;this.a=U[a]||Zb;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}g(T,Error);var Zb="unknown error",U={15:"element not selectable",11:"element not visible"};U[31]=Zb;U[30]=Zb;U[24]="invalid cookie domain";U[29]="invalid element coordinates";U[12]="invalid element state";
U[32]="invalid selector";U[51]="invalid selector";U[52]="invalid selector";U[17]="javascript error";U[405]="unsupported operation";U[34]="move target out of bounds";U[27]="no such alert";U[7]="no such element";U[8]="no such frame";U[23]="no such window";U[28]="script timeout";U[33]="session not created";U[10]="stale element reference";U[21]="timeout";U[25]="unable to set cookie";U[26]="unexpected alert open";U[13]=Zb;U[9]="unknown command";var $b=za(),ac=Ca()||t("iPod"),bc=t("iPad"),cc=t("Android")&&!(Aa()||za()||t("Opera")||t("Silk")),dc=Aa(),ec=t("Safari")&&!(Aa()||t("Coast")||t("Opera")||t("Edge")||t("Edg/")||t("OPR")||za()||t("Silk")||t("Android"))&&!(Ca()||t("iPad")||t("iPod"));function fc(a){return(a=a.exec(r))?a[1]:""}var gc=function(){if($b)return fc(/Firefox\/([0-9.]+)/);if(dc)return Ca()||t("iPad")||t("iPod")?fc(/CriOS\/([0-9.]+)/):fc(/Chrome\/([0-9.]+)/);if(ec&&!(Ca()||t("iPad")||t("iPod")))return fc(/Version\/([0-9.]+)/);if(ac||bc){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(r);if(a)return a[1]+"."+a[2]}else if(cc)return(a=fc(/Android\s+([0-9.]+)/))?a:fc(/Version\/([0-9.]+)/);return""}();var hc=bc||ac,ic;if(cc){var jc=/Android\s+([0-9\.]+)/.exec(r);ic=jc?jc[1]:"0"}else ic="0";var kc=ic;function lc(a,b){b=Ba(b);if("float"==b||"cssFloat"==b||"styleFloat"==b)b="cssFloat";a:{var c=b;var d=z(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||mc(a,b);if(null===a)a=null;else if(0<=na(Ub,b)){b:{var e=a.match(Xb);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d&&0<=e&&1>=e)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(Yb))if(b=
Number(d[1]),c=Number(d[2]),d=Number(d[3]),0<=b&&255>=b&&0<=c&&255>=c&&0<=d&&255>=d){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=Tb[b.toLowerCase()];if(!c&&(c="#"==b.charAt(0)?b:"#"+b,4==c.length&&(c=c.replace(Vb,"#$1$1$2$2$3$3")),!Wb.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function mc(a,b){var c=a.currentStyle||a.style,d=c[b];void 0===d&&"function"==da(c.getPropertyValue)&&(d=c.getPropertyValue(b));if("inherit"!=d)return void 0!==d?d:null;var e;for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;e&&"string"!==typeof e&&(e=e.toString());return(e=!a||1!=a.nodeType||e&&a.tagName.toUpperCase()!=e?null:a)?mc(e,b):null};var nc=aa.JSON.stringify;function oc(a){function b(c,d){switch(da(c)){case "string":case "number":case "boolean":return c;case "function":return c.toString();case "array":return p(c,function(f){return b(f,d)});case "object":if(0<=d.indexOf(c))throw new T(17,"Recursive object cannot be transferred");if(v(c,"nodeType")&&(1==c.nodeType||9==c.nodeType)){var e={};e.ELEMENT=pc(c);return e}if(v(c,"document"))return e={},e.WINDOW=pc(c),e;d.push(c);if(ea(c))return p(c,function(f){return b(f,d)});c=wa(c,function(f,h){return"number"==
typeof h||ba(h)});return xa(c,function(f){return b(f,d)});default:return null}}return b(a,[])}function qc(a,b){return"array"==da(a)?p(a,function(c){return qc(c,b)}):fa(a)?"function"==typeof a?a:v(a,"ELEMENT")?rc(a.ELEMENT,b):v(a,"WINDOW")?rc(a.WINDOW,b):xa(a,function(c){return qc(c,b)}):a}function sc(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.F=la());b.F||(b.F=la());return b}function pc(a){var b=sc(a.ownerDocument),c=ya(b,function(d){return d==a});c||(c=":wdc:"+b.F++,b[c]=a);return c}
function rc(a,b){a=decodeURIComponent(a);b=b||document;var c=sc(b);if(!v(c,a))throw new T(10,"Element does not exist in cache");var d=c[a];if(v(d,"setInterval")){if(d.closed)throw delete c[a],new T(23,"Window has been closed.");return d}for(var e=d;e;){if(e==b.documentElement)return d;e.host&&11===e.nodeType&&(e=e.host);e=e.parentNode}delete c[a];throw new T(10,"Element is no longer attached to the DOM");};var tc=cc?!(cc?0<=sa(kc):0<=sa(gc)):!hc;function V(a,b,c){this.a=a;this.b=b;this.f=c}V.prototype.create=function(a){a=z(a).createEvent("HTMLEvents");a.initEvent(this.a,this.b,this.f);return a};V.prototype.toString=function(){return this.a};function W(a,b,c){ma(this,a,b,c)}g(W,V);
W.prototype.create=function(a,b){if(this==uc)throw new T(9,"Browser does not support a mouse pixel scroll event.");var c=z(a);a=c?c.parentWindow||c.defaultView:window;c=c.createEvent("MouseEvents");this==vc&&(c.wheelDelta=b.wheelDelta);c.initMouseEvent(this.a,this.b,this.f,a,1,b.clientX,b.clientY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);return c};function wc(a,b,c){ma(this,a,b,c)}g(wc,V);
wc.prototype.create=function(a,b){a=z(a).createEvent("Events");a.initEvent(this.a,this.b,this.f);a.altKey=b.altKey;a.ctrlKey=b.ctrlKey;a.metaKey=b.metaKey;a.shiftKey=b.shiftKey;a.keyCode=b.charCode||b.keyCode;a.charCode=this==xc?a.keyCode:0;return a};function yc(a,b,c){ma(this,a,b,c)}g(yc,V);
yc.prototype.create=function(a,b){function c(N){N=p(N,function(u){return h.createTouch(m,a,u.identifier,u.pageX,u.pageY,u.screenX,u.screenY)});return h.createTouchList.apply(h,N)}function d(N){var u=p(N,function(O){return{identifier:O.identifier,screenX:O.screenX,screenY:O.screenY,clientX:O.clientX,clientY:O.clientY,pageX:O.pageX,pageY:O.pageY,target:a}});u.item=function(O){return u[O]};return u}function e(N){return p(N,function(u){return new Touch({identifier:u.identifier,screenX:u.screenX,screenY:u.screenY,
clientX:u.clientX,clientY:u.clientY,pageX:u.pageX,pageY:u.pageY,target:a})})}function f(N,u){switch(N){case 1:return d(u);case 2:return c(u);case 3:return e(u)}return null}var h=z(a),m=h?h.parentWindow||h.defaultView:window;if(tc)var k=1;else if(TouchEvent.prototype.initTouchEvent)k=2;else if(TouchEvent&&0<TouchEvent.length)k=3;else throw new T(9,"Not able to create touch events in this browser");var w=f(k,b.changedTouches),I=b.touches==b.changedTouches?w:f(k,b.touches),Ia=b.targetTouches==b.changedTouches?
w:f(k,b.targetTouches);if(1==k)k=h.createEvent("MouseEvents"),k.initMouseEvent(this.a,this.b,this.f,m,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,b.relatedTarget),k.touches=I,k.targetTouches=Ia,k.changedTouches=w,k.scale=b.scale,k.rotation=b.rotation;else if(2==k)k=h.createEvent("TouchEvent"),0==k.initTouchEvent.length?k.initTouchEvent(I,Ia,w,this.a,m,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey):k.initTouchEvent(this.a,this.b,this.f,m,1,0,0,b.clientX,b.clientY,
b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,I,Ia,w,b.scale,b.rotation),k.relatedTarget=b.relatedTarget;else if(3==k)k=new TouchEvent(this.a,{touches:I,targetTouches:Ia,changedTouches:w,bubbles:this.b,cancelable:this.f,ctrlKey:b.ctrlKey,shiftKey:b.shiftKey,altKey:b.altKey,metaKey:b.metaKey});else throw new T(9,"Illegal TouchEventStrategy_ value (this is a bug)");return k};function X(a,b,c){ma(this,a,b,c)}g(X,V);X.prototype.create=function(){throw new T(9,"Browser does not support MSGesture events.");};
function Y(a,b,c){ma(this,a,b,c)}g(Y,V);Y.prototype.create=function(){throw new T(9,"Browser does not support MSPointer events.");};new W("click",!0,!0);new W("contextmenu",!0,!0);new W("dblclick",!0,!0);new W("mousedown",!0,!0);new W("mousemove",!0,!1);new W("mouseout",!0,!0);new W("mouseover",!0,!0);new W("mouseup",!0,!0);var vc=new W("mousewheel",!0,!0),uc=new W("MozMousePixelScroll",!0,!0);new wc("keydown",!0,!0);var xc=new wc("keypress",!0,!0);new wc("keyup",!0,!0);new yc("touchend",!0,!0);
new yc("touchmove",!0,!0);new yc("touchstart",!0,!0);new X("MSGestureChange",!0,!0);new X("MSGestureEnd",!0,!0);new X("MSGestureHold",!0,!0);new X("MSGestureStart",!0,!0);new X("MSGestureTap",!0,!0);new X("MSInertiaStart",!0,!0);new Y("MSGotPointerCapture",!0,!1);new Y("MSLostPointerCapture",!0,!1);new Y("MSPointerCancel",!0,!0);new Y("MSPointerDown",!0,!0);new Y("MSPointerMove",!0,!0);new Y("MSPointerOver",!0,!0);new Y("MSPointerOut",!0,!0);new Y("MSPointerUp",!0,!0);function zc(a,b){this.b={};this.a=[];this.f=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof zc)for(c=Ac(a),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}
function Ac(a){if(a.f!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Object.prototype.hasOwnProperty.call(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.f!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],Object.prototype.hasOwnProperty.call(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}return a.a.concat()}zc.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.b,a)?this.b[a]:b};
zc.prototype.set=function(a,b){Object.prototype.hasOwnProperty.call(this.b,a)||(this.f++,this.a.push(a));this.b[a]=b};var Bc={};function Z(a,b,c){fa(a)&&(a=a.g);a=new Cc(a);!b||b in Bc&&!c||(Bc[b]={key:a,shift:!1},c&&(Bc[c]={key:a,shift:!0}));return a}function Cc(a){this.code=a}Z(8);Z(9);Z(13);var Dc=Z(16),Ec=Z(17),Fc=Z(18);Z(19);Z(20);Z(27);Z(32," ");Z(33);Z(34);Z(35);Z(36);Z(37);Z(38);Z(39);Z(40);Z(44);Z(45);Z(46);Z(48,"0",")");Z(49,"1","!");Z(50,"2","@");Z(51,"3","#");Z(52,"4","$");Z(53,"5","%");Z(54,"6","^");Z(55,"7","&");Z(56,"8","*");Z(57,"9","(");Z(65,"a","A");Z(66,"b","B");Z(67,"c","C");Z(68,"d","D");
Z(69,"e","E");Z(70,"f","F");Z(71,"g","G");Z(72,"h","H");Z(73,"i","I");Z(74,"j","J");Z(75,"k","K");Z(76,"l","L");Z(77,"m","M");Z(78,"n","N");Z(79,"o","O");Z(80,"p","P");Z(81,"q","Q");Z(82,"r","R");Z(83,"s","S");Z(84,"t","T");Z(85,"u","U");Z(86,"v","V");Z(87,"w","W");Z(88,"x","X");Z(89,"y","Y");Z(90,"z","Z");var Gc=Z(Ea?{h:91,g:91}:Da?{h:224,g:91}:{h:0,g:91});Z(Ea?{h:92,g:92}:Da?{h:224,g:93}:{h:0,g:92});Z(Ea?{h:93,g:93}:Da?{h:0,g:0}:{h:93,g:null});Z({h:96,g:96},"0");Z({h:97,g:97},"1");
Z({h:98,g:98},"2");Z({h:99,g:99},"3");Z({h:100,g:100},"4");Z({h:101,g:101},"5");Z({h:102,g:102},"6");Z({h:103,g:103},"7");Z({h:104,g:104},"8");Z({h:105,g:105},"9");Z({h:106,g:106},"*");Z({h:107,g:107},"+");Z({h:109,g:109},"-");Z({h:110,g:110},".");Z({h:111,g:111},"/");Z(144);Z(112);Z(113);Z(114);Z(115);Z(116);Z(117);Z(118);Z(119);Z(120);Z(121);Z(122);Z(123);Z({h:107,g:187},"=","+");Z(108,",");Z({h:109,g:189},"-","_");Z(188,",","<");Z(190,".",">");Z(191,"/","?");Z(192,"`","~");Z(219,"[","{");
Z(220,"\\","|");Z(221,"]","}");Z({h:59,g:186},";",":");Z(222,"'",'"');var Hc=new zc;Hc.set(1,Dc);Hc.set(2,Ec);Hc.set(4,Fc);Hc.set(8,Gc);(function(a){var b=new zc;n(Ac(a),function(c){b.set(a.get(c).code,c)});return b})(Hc);ca("_",function(a,b,c){a=[a,b];try{var d;c?d=rc(c.WINDOW):d=window;var e=qc(a,d.document),f=lc.apply(null,e);var h={status:0,value:oc(f)}}catch(m){h={status:v(m,"code")?m.code:13,value:{message:m.message}}}return nc(h)});; return this._.apply(null,arguments);}).apply(window, arguments);}
