function(){return (function(){var aa=this||self;function ba(a){return"string"==typeof a}function ca(a,b){a=a.split(".");var c=aa;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ha(a,b,c){return a.call.apply(a.bind,arguments)}
function ia(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function ja(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja=ha:ja=ia;return ja.apply(null,arguments)}
function ka(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var la=Date.now||function(){return+new Date};function h(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a}
function ma(a,b,c){var d=arguments.callee.caller;if("undefined"!==typeof d.K){for(var e=Array(arguments.length-1),f=1;f<arguments.length;f++)e[f-1]=arguments[f];d.K.constructor.apply(a,e)}else{if("string"!=typeof b&&"symbol"!=typeof b)throw Error("method names provided to goog.base must be a string or a symbol");e=Array(arguments.length-2);for(f=2;f<arguments.length;f++)e[f-2]=arguments[f];f=!1;for(var g=a.constructor.prototype;g;g=Object.getPrototypeOf(g))if(g[b]===d)f=!0;else if(f){g[b].apply(a,
e);return}if(a[b]===d)a.constructor.prototype[b].apply(a,e);else throw Error("goog.base called from a method of one name to a method of a different name");}};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function m(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var na=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},n=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},p=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},oa=Array.prototype.reduce?function(a,b,c){return Array.prototype.reduce.call(a,b,c)}:function(a,b,c){var d=c;n(a,function(e,f){d=b.call(void 0,d,e,f,a)});return d},pa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,
d[e],e,a))return!0;return!1};function qa(a){return Array.prototype.concat.apply([],arguments)}function ra(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var sa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function ta(a){var b=0;a=sa(String(a)).split(".");for(var c=sa("4").split("."),d=Math.max(a.length,c.length),e=0;0==b&&e<d;e++){var f=a[e]||"",g=c[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==f[0].length&&0==g[0].length)break;b=ua(0==f[1].length?0:parseInt(f[1],10),0==g[1].length?0:parseInt(g[1],10))||ua(0==f[2].length,0==g[2].length)||ua(f[2],g[2]);f=f[3];g=g[3]}while(0==b)}return b}function ua(a,b){return a<b?-1:a>b?1:0};var va;a:{var wa=aa.navigator;if(wa){var xa=wa.userAgent;if(xa){va=xa;break a}}va=""}function t(a){return-1!=va.indexOf(a)};function ya(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function za(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function u(a,b){return null!==a&&b in a}function Aa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function Ba(){return t("Firefox")||t("FxiOS")}function Ca(){return(t("Chrome")||t("CriOS"))&&!t("Edge")};function Da(){return t("iPhone")&&!t("iPod")&&!t("iPad")};var Ea=t("Macintosh"),Fa=t("Windows");function Ga(a){this.b=a;this.a=0}function Ha(a){a=a.match(Ia);for(var b=0;b<a.length;b++)Ja.test(a[b])&&a.splice(b,1);return new Ga(a)}var Ia=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,Ja=/^\s/;function v(a,b){return a.b[a.a+(b||0)]}function w(a){return a.b[a.a++]}function Ka(a){return a.b.length<=a.a};function La(a,b){this.width=a;this.height=b}La.prototype.aspectRatio=function(){return this.width/this.height};La.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};La.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};La.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
La.prototype.scale=function(a,b){this.width*=a;this.height*="number"===typeof b?b:a;return this};function Ma(a){return a?a.parentWindow||a.defaultView:window}function Na(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Oa(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Pa(a,b):!c&&Na(e,b)?-1*Qa(a,b):!d&&Na(f,a)?Qa(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=x(a);c=d.createRange();c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);
a.collapse(!0);return c.compareBoundaryPoints(aa.Range.START_TO_END,a)}function Qa(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Pa(b,a)}function Pa(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function x(a){return 9==a.nodeType?a:a.ownerDocument||a.document};function y(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;c=0;var d=[];for(b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return b}
function Ra(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Sa(a,b,c,d,e){return Ta.call(null,a,b,ba(c)?c:null,ba(d)?d:null,e||new z)}
function Ta(a,b,c,d,e){b.getElementsByName&&d&&"name"==c?(b=b.getElementsByName(d),n(b,function(f){a.a(f)&&e.add(f)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),n(b,function(f){f.className==d&&a.a(f)&&e.add(f)})):a instanceof A?Ua(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),n(b,function(f){Ra(f,c,d)&&e.add(f)}));return e}function Ua(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)Ra(b,c,d)&&a.a(b)&&e.add(b),Ua(a,b,c,d,e)};function z(){this.b=this.a=null;this.o=0}function Va(a){this.f=a;this.a=this.b=null}function Wa(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;)c.f==b.f?(e=c,c=c.a,b=b.a):0<Oa(c.f,b.f)?(e=b,b=b.a):(e=c,c=c.a),(e.b=d)?d.a=e:a.a=e,d=e,f++;for(e=c||b;e;)e.b=d,d=d.a=e,f++,e=e.a;a.b=d;a.o=f;return a}function Xa(a,b){b=new Va(b);b.a=a.a;a.b?a.a.b=b:a.a=a.b=b;a.a=b;a.o++}z.prototype.add=function(a){a=new Va(a);a.b=this.b;this.a?this.b.a=a:this.a=this.b=a;this.b=a;this.o++};
function Ya(a){return(a=a.a)?a.f:null}function Za(a){return(a=Ya(a))?y(a):""}function B(a,b){return new $a(a,!!b)}function $a(a,b){this.f=a;this.b=(this.v=b)?a.b:a.a;this.a=null}function E(a){var b=a.b;if(null==b)return null;var c=a.a=b;a.b=a.v?b.b:b.a;return c.f};function F(a){this.l=a;this.b=this.i=!1;this.f=null}function G(a){return"\n  "+a.toString().split("\n").join("\n  ")}function ab(a,b){a.i=b}function bb(a,b){a.b=b}function H(a,b){a=a.a(b);return a instanceof z?+Za(a):+a}function I(a,b){a=a.a(b);return a instanceof z?Za(a):""+a}function cb(a,b){a=a.a(b);return a instanceof z?!!a.o:!!a};function db(a,b,c){F.call(this,a.l);this.c=a;this.j=b;this.u=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==eb&&(c.b||c.i||4==c.l||0==c.l||!b.f?b.b||b.i||4==b.l||0==b.l||!c.f||(this.f={name:c.f.name,A:b}):this.f={name:b.f.name,A:c})}h(db,F);
function fb(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof z&&c instanceof z){b=B(b);for(d=E(b);d;d=E(b))for(e=B(c),f=E(e);f;f=E(e))if(a(y(d),y(f)))return!0;return!1}if(b instanceof z||c instanceof z){b instanceof z?(e=b,d=c):(e=c,d=b);f=B(e);for(var g=typeof d,l=E(f);l;l=E(f)){switch(g){case "number":l=+y(l);break;case "boolean":l=!!y(l);break;case "string":l=y(l);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(l,d)||e==c&&a(d,l))return!0}return!1}return e?"boolean"==
typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}db.prototype.a=function(a){return this.c.s(this.j,this.u,a)};db.prototype.toString=function(){var a="Binary Expression: "+this.c;a+=G(this.j);return a+=G(this.u)};function gb(a,b,c,d){this.O=a;this.J=b;this.l=c;this.s=d}gb.prototype.toString=function(){return this.O};var hb={};
function J(a,b,c,d){if(hb.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new gb(a,b,c,d);return hb[a.toString()]=a}J("div",6,1,function(a,b,c){return H(a,c)/H(b,c)});J("mod",6,1,function(a,b,c){return H(a,c)%H(b,c)});J("*",6,1,function(a,b,c){return H(a,c)*H(b,c)});J("+",5,1,function(a,b,c){return H(a,c)+H(b,c)});J("-",5,1,function(a,b,c){return H(a,c)-H(b,c)});J("<",4,2,function(a,b,c){return fb(function(d,e){return d<e},a,b,c)});
J(">",4,2,function(a,b,c){return fb(function(d,e){return d>e},a,b,c)});J("<=",4,2,function(a,b,c){return fb(function(d,e){return d<=e},a,b,c)});J(">=",4,2,function(a,b,c){return fb(function(d,e){return d>=e},a,b,c)});var eb=J("=",3,2,function(a,b,c){return fb(function(d,e){return d==e},a,b,c,!0)});J("!=",3,2,function(a,b,c){return fb(function(d,e){return d!=e},a,b,c,!0)});J("and",2,2,function(a,b,c){return cb(a,c)&&cb(b,c)});J("or",1,2,function(a,b,c){return cb(a,c)||cb(b,c)});function ib(a,b){if(b.a.length&&4!=a.l)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");F.call(this,a.l);this.c=a;this.j=b;this.i=a.i;this.b=a.b}h(ib,F);ib.prototype.a=function(a){a=this.c.a(a);return jb(this.j,a)};ib.prototype.toString=function(){var a="Filter:"+G(this.c);return a+=G(this.j)};function kb(a,b){if(b.length<a.I)throw Error("Function "+a.m+" expects at least"+a.I+" arguments, "+b.length+" given");if(null!==a.D&&b.length>a.D)throw Error("Function "+a.m+" expects at most "+a.D+" arguments, "+b.length+" given");a.N&&n(b,function(c,d){if(4!=c.l)throw Error("Argument "+d+" to function "+a.m+" is not of type Nodeset: "+c);});F.call(this,a.l);this.B=a;this.c=b;ab(this,a.i||pa(b,function(c){return c.i}));bb(this,a.M&&!b.length||a.L&&!!b.length||pa(b,function(c){return c.b}))}
h(kb,F);kb.prototype.a=function(a){return this.B.s.apply(null,qa(a,this.c))};kb.prototype.toString=function(){var a="Function: "+this.B;if(this.c.length){var b=oa(this.c,function(c,d){return c+G(d)},"Arguments:");a+=G(b)}return a};function lb(a,b,c,d,e,f,g,l){this.m=a;this.l=b;this.i=c;this.M=d;this.L=!1;this.s=e;this.I=f;this.D=void 0!==g?g:f;this.N=!!l}lb.prototype.toString=function(){return this.m};var mb={};
function K(a,b,c,d,e,f,g,l){if(mb.hasOwnProperty(a))throw Error("Function already created: "+a+".");mb[a]=new lb(a,b,c,d,e,f,g,l)}K("boolean",2,!1,!1,function(a,b){return cb(b,a)},1);K("ceiling",1,!1,!1,function(a,b){return Math.ceil(H(b,a))},1);K("concat",3,!1,!1,function(a,b){return oa(ra(arguments,1),function(c,d){return c+I(d,a)},"")},2,null);K("contains",2,!1,!1,function(a,b,c){b=I(b,a);a=I(c,a);return-1!=b.indexOf(a)},2);K("count",1,!1,!1,function(a,b){return b.a(a).o},1,1,!0);
K("false",2,!1,!1,function(){return!1},0);K("floor",1,!1,!1,function(a,b){return Math.floor(H(b,a))},1);K("id",4,!1,!1,function(a,b){var c=a.a,d=9==c.nodeType?c:c.ownerDocument;a=I(b,a).split(/\s+/);var e=[];n(a,function(g){g=d.getElementById(g);!g||0<=na(e,g)||e.push(g)});e.sort(Oa);var f=new z;n(e,function(g){f.add(g)});return f},1);K("lang",2,!1,!1,function(){return!1},1);K("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);
K("local-name",3,!1,!0,function(a,b){return(a=b?Ya(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);K("name",3,!1,!0,function(a,b){return(a=b?Ya(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);K("namespace-uri",3,!0,!1,function(){return""},0,1,!0);K("normalize-space",3,!1,!0,function(a,b){return(b?I(b,a):y(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);K("not",2,!1,!1,function(a,b){return!cb(b,a)},1);K("number",1,!1,!0,function(a,b){return b?H(b,a):+y(a.a)},0,1);
K("position",1,!0,!1,function(a){return a.b},0);K("round",1,!1,!1,function(a,b){return Math.round(H(b,a))},1);K("starts-with",2,!1,!1,function(a,b,c){b=I(b,a);a=I(c,a);return 0==b.lastIndexOf(a,0)},2);K("string",3,!1,!0,function(a,b){return b?I(b,a):y(a.a)},0,1);K("string-length",1,!1,!0,function(a,b){return(b?I(b,a):y(a.a)).length},0,1);
K("substring",3,!1,!1,function(a,b,c,d){c=H(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?H(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=I(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);K("substring-after",3,!1,!1,function(a,b,c){b=I(b,a);a=I(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
K("substring-before",3,!1,!1,function(a,b,c){b=I(b,a);a=I(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);K("sum",1,!1,!1,function(a,b){a=B(b.a(a));b=0;for(var c=E(a);c;c=E(a))b+=+y(c);return b},1,1,!0);K("translate",3,!1,!1,function(a,b,c,d){b=I(b,a);c=I(c,a);var e=I(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);K("true",2,!1,!1,function(){return!0},0);function A(a,b){this.j=a;this.c=void 0!==b?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function nb(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}A.prototype.a=function(a){return null===this.b||this.b==a.nodeType};A.prototype.f=function(){return this.j};
A.prototype.toString=function(){var a="Kind Test: "+this.j;null===this.c||(a+=G(this.c));return a};function ob(a){F.call(this,3);this.c=a.substring(1,a.length-1)}h(ob,F);ob.prototype.a=function(){return this.c};ob.prototype.toString=function(){return"Literal: "+this.c};function pb(a,b){this.m=a.toLowerCase();a="*"==this.m?"*":"http://www.w3.org/1999/xhtml";this.b=b?b.toLowerCase():a}pb.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=void 0!==a.localName?a.localName:a.nodeName;return"*"!=this.m&&this.m!=b.toLowerCase()?!1:"*"==this.b?!0:this.b==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};pb.prototype.f=function(){return this.m};
pb.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.b?"":this.b+":")+this.m};function qb(a){F.call(this,1);this.c=a}h(qb,F);qb.prototype.a=function(){return this.c};qb.prototype.toString=function(){return"Number: "+this.c};function rb(a,b){F.call(this,a.l);this.j=a;this.c=b;this.i=a.i;this.b=a.b;1==this.c.length&&(a=this.c[0],a.C||a.c!=sb||(a=a.u,"*"!=a.f()&&(this.f={name:a.f(),A:null})))}h(rb,F);function tb(){F.call(this,4)}h(tb,F);tb.prototype.a=function(a){var b=new z;a=a.a;9==a.nodeType?b.add(a):b.add(a.ownerDocument);return b};tb.prototype.toString=function(){return"Root Helper Expression"};function ub(){F.call(this,4)}h(ub,F);ub.prototype.a=function(a){var b=new z;b.add(a.a);return b};ub.prototype.toString=function(){return"Context Helper Expression"};
function vb(a){return"/"==a||"//"==a}rb.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof z))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.o;c++){var e=a[c],f=B(b,e.c.v);if(e.i||e.c!=wb)if(e.i||e.c!=xb){var g=E(f);for(b=e.a(new m(g));null!=(g=E(f));)g=e.a(new m(g)),b=Wa(b,g)}else g=E(f),b=e.a(new m(g));else{for(g=E(f);(b=E(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new m(g))}}return b};
rb.prototype.toString=function(){var a="Path Expression:"+G(this.j);if(this.c.length){var b=oa(this.c,function(c,d){return c+G(d)},"Steps:");a+=G(b)}return a};function yb(a,b){this.a=a;this.v=!!b}
function jb(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=B(b),f=b.o,g,l=0;g=E(e);l++){var k=a.v?f-l:l+1;g=d.a(new m(g,k,f));if("number"==typeof g)k=k==g;else if("string"==typeof g||"boolean"==typeof g)k=!!g;else if(g instanceof z)k=0<g.o;else throw Error("Predicate.evaluate returned an unexpected type.");if(!k){k=e;g=k.f;var q=k.a;if(!q)throw Error("Next must be called at least once before remove.");var D=q.b;q=q.a;D?D.a=q:g.a=q;q?q.b=D:g.b=D;g.o--;k.a=null}}return b}
yb.prototype.toString=function(){return oa(this.a,function(a,b){return a+G(b)},"Predicates:")};function M(a,b,c,d){F.call(this,4);this.c=a;this.u=b;this.j=c||new yb([]);this.C=!!d;b=this.j;b=0<b.a.length?b.a[0].f:null;a.R&&b&&(this.f={name:b.name,A:b.A});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.l||0==c.l){a=!0;break a}a=!1}this.i=a}h(M,F);
M.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.A?I(c.A,a):null,f=1);if(this.C)if(this.i||this.c!=zb)if(b=B((new M(Ab,new A("node"))).a(a)),c=E(b))for(a=this.s(c,d,e,f);null!=(c=E(b));)a=Wa(a,this.s(c,d,e,f));else a=new z;else a=Sa(this.u,b,d,e),a=jb(this.j,a,f);else a=this.s(a.a,d,e,f);return a};M.prototype.s=function(a,b,c,d){a=this.c.B(this.u,a,b,c);return a=jb(this.j,a,d)};
M.prototype.toString=function(){var a="Step:"+G("Operator: "+(this.C?"//":"/"));this.c.m&&(a+=G("Axis: "+this.c));a+=G(this.u);if(this.j.a.length){var b=oa(this.j.a,function(c,d){return c+G(d)},"Predicates:");a+=G(b)}return a};function Bb(a,b,c,d){this.m=a;this.B=b;this.v=c;this.R=d}Bb.prototype.toString=function(){return this.m};var Cb={};function N(a,b,c,d){if(Cb.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new Bb(a,b,c,!!d);return Cb[a]=b}
N("ancestor",function(a,b){for(var c=new z;b=b.parentNode;)a.a(b)&&Xa(c,b);return c},!0);N("ancestor-or-self",function(a,b){var c=new z;do a.a(b)&&Xa(c,b);while(b=b.parentNode);return c},!0);
var sb=N("attribute",function(a,b){var c=new z,d=a.f();if(b=b.attributes)if(a instanceof A&&null===a.b||"*"==d)for(a=0;d=b[a];a++)c.add(d);else(d=b.getNamedItem(d))&&c.add(d);return c},!1),zb=N("child",function(a,b,c,d,e){c=ba(c)?c:null;d=ba(d)?d:null;e=e||new z;for(b=b.firstChild;b;b=b.nextSibling)Ra(b,c,d)&&a.a(b)&&e.add(b);return e},!1,!0);N("descendant",Sa,!1,!0);
var Ab=N("descendant-or-self",function(a,b,c,d){var e=new z;Ra(b,c,d)&&a.a(b)&&e.add(b);return Sa(a,b,c,d,e)},!1,!0),wb=N("following",function(a,b,c,d){var e=new z;do for(var f=b;f=f.nextSibling;)Ra(f,c,d)&&a.a(f)&&e.add(f),e=Sa(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);N("following-sibling",function(a,b){for(var c=new z;b=b.nextSibling;)a.a(b)&&c.add(b);return c},!1);N("namespace",function(){return new z},!1);
var Db=N("parent",function(a,b){var c=new z;if(9==b.nodeType)return c;if(2==b.nodeType)return c.add(b.ownerElement),c;b=b.parentNode;a.a(b)&&c.add(b);return c},!1),xb=N("preceding",function(a,b,c,d){var e=new z,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,l=f.length;g<l;g++){var k=[];for(b=f[g];b=b.previousSibling;)k.unshift(b);for(var q=0,D=k.length;q<D;q++)b=k[q],Ra(b,c,d)&&a.a(b)&&e.add(b),e=Sa(a,b,c,d,e)}return e},!0,!0);
N("preceding-sibling",function(a,b){for(var c=new z;b=b.previousSibling;)a.a(b)&&Xa(c,b);return c},!0);var Eb=N("self",function(a,b){var c=new z;a.a(b)&&c.add(b);return c},!1);function Fb(a){F.call(this,1);this.c=a;this.i=a.i;this.b=a.b}h(Fb,F);Fb.prototype.a=function(a){return-H(this.c,a)};Fb.prototype.toString=function(){return"Unary Expression: -"+G(this.c)};function Gb(a){F.call(this,4);this.c=a;ab(this,pa(this.c,function(b){return b.i}));bb(this,pa(this.c,function(b){return b.b}))}h(Gb,F);Gb.prototype.a=function(a){var b=new z;n(this.c,function(c){c=c.a(a);if(!(c instanceof z))throw Error("Path expression must evaluate to NodeSet.");b=Wa(b,c)});return b};Gb.prototype.toString=function(){return oa(this.c,function(a,b){return a+G(b)},"Union Expression:")};function Hb(a,b){this.a=a;this.b=b}function Ib(a){for(var b,c=[];;){O(a,"Missing right hand side of binary expression.");b=Jb(a);var d=w(a.a);if(!d)break;var e=(d=hb[d]||null)&&d.J;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].J;)b=new db(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new db(c.pop(),c.pop(),b);return b}function O(a,b){if(Ka(a.a))throw Error(b);}function Kb(a,b){a=w(a.a);if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function Lb(a){a=w(a.a);if(")"!=a)throw Error("Bad token: "+a);}function Mb(a){a=w(a.a);if(2>a.length)throw Error("Unclosed literal string");return new ob(a)}
function Nb(a){var b=[];if(vb(v(a.a))){var c=w(a.a);var d=v(a.a);if("/"==c&&(Ka(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new tb;d=new tb;O(a,"Missing next location step.");c=Ob(a,c);b.push(c)}else{a:{c=v(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":w(a.a);c=Ib(a);O(a,'unclosed "("');Kb(a,")");break;case '"':case "'":c=Mb(a);break;default:if(isNaN(+c))if(!nb(c)&&/(?![0-9])[\w]/.test(d)&&"("==v(a.a,1)){c=w(a.a);
c=mb[c]||null;w(a.a);for(d=[];")"!=v(a.a);){O(a,"Missing function argument list.");d.push(Ib(a));if(","!=v(a.a))break;w(a.a)}O(a,"Unclosed function argument list.");Lb(a);c=new kb(c,d)}else{c=null;break a}else c=new qb(+w(a.a))}"["==v(a.a)&&(d=new yb(Pb(a)),c=new ib(c,d))}if(c)if(vb(v(a.a)))d=c;else return c;else c=Ob(a,"/"),d=new ub,b.push(c)}for(;vb(v(a.a));)c=w(a.a),O(a,"Missing next location step."),c=Ob(a,c),b.push(c);return new rb(d,b)}
function Ob(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==v(a.a)){var c=new M(Eb,new A("node"));w(a.a);return c}if(".."==v(a.a))return c=new M(Db,new A("node")),w(a.a),c;if("@"==v(a.a)){var d=sb;w(a.a);O(a,"Missing attribute name")}else if("::"==v(a.a,1)){if(!/(?![0-9])[\w]/.test(v(a.a).charAt(0)))throw Error("Bad token: "+w(a.a));var e=w(a.a);d=Cb[e]||null;if(!d)throw Error("No axis with name: "+e);w(a.a);O(a,"Missing node name")}else d=zb;e=v(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==
v(a.a,1)){if(!nb(e))throw Error("Invalid node type: "+e);e=w(a.a);if(!nb(e))throw Error("Invalid type name: "+e);Kb(a,"(");O(a,"Bad nodetype");var f=v(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=Mb(a);O(a,"Bad nodetype");Lb(a);e=new A(e,g)}else if(e=w(a.a),f=e.indexOf(":"),-1==f)e=new pb(e);else{g=e.substring(0,f);if("*"==g)var l="*";else if(l=a.b(g),!l)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new pb(e,l)}else throw Error("Bad token: "+w(a.a));a=new yb(Pb(a),d.v);return c||
new M(d,e,a,"//"==b)}function Pb(a){for(var b=[];"["==v(a.a);){w(a.a);O(a,"Missing predicate expression.");var c=Ib(a);b.push(c);O(a,"Unclosed predicate expression.");Kb(a,"]")}return b}function Jb(a){if("-"==v(a.a))return w(a.a),new Fb(Jb(a));var b=Nb(a);if("|"!=v(a.a))a=b;else{for(b=[b];"|"==w(a.a);)O(a,"Missing next union location path."),b.push(Nb(a));a.a.a--;a=new Gb(b)}return a};function Qb(a){switch(a.nodeType){case 1:return ka(Rb,a);case 9:return Qb(a.documentElement);case 11:case 10:case 6:case 12:return Sb;default:return a.parentNode?Qb(a.parentNode):Sb}}function Sb(){return null}function Rb(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Rb(a.parentNode,b):null};function Tb(a,b){if(!a.length)throw Error("Empty XPath expression.");a=Ha(a);if(Ka(a))throw Error("Invalid XPath expression.");b?"function"==da(b)||(b=ja(b.lookupNamespaceURI,b)):b=function(){return null};var c=Ib(new Hb(a,b));if(!Ka(a))throw Error("Bad token: "+w(a));this.evaluate=function(d,e){d=c.a(new m(d));return new P(d,e)}}
function P(a,b){if(0==b)if(a instanceof z)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof z))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof z?Za(a):""+a;break;case 1:this.numberValue=a instanceof z?+Za(a):+a;break;case 3:this.booleanValue=a instanceof z?0<a.o:!!a;break;case 4:case 5:case 6:case 7:var c=
B(a);var d=[];for(var e=E(c);e;e=E(c))d.push(e);this.snapshotLength=a.o;this.invalidIteratorState=!1;break;case 8:case 9:this.singleNodeValue=Ya(a);break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(g){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return g>=d.length||0>g?null:d[g]}}P.ANY_TYPE=0;
P.NUMBER_TYPE=1;P.STRING_TYPE=2;P.BOOLEAN_TYPE=3;P.UNORDERED_NODE_ITERATOR_TYPE=4;P.ORDERED_NODE_ITERATOR_TYPE=5;P.UNORDERED_NODE_SNAPSHOT_TYPE=6;P.ORDERED_NODE_SNAPSHOT_TYPE=7;P.ANY_UNORDERED_NODE_TYPE=8;P.FIRST_ORDERED_NODE_TYPE=9;function Ub(a){this.lookupNamespaceURI=Qb(a)}
function Vb(a,b){a=a||aa;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=P,c.evaluate=function(d,e,f,g){return(new Tb(d,f)).evaluate(e,g)},c.createExpression=function(d,e){return new Tb(d,e)},c.createNSResolver=function(d){return new Ub(d)}}ca("wgxpath.install",Vb);ca("wgxpath.install",Vb);function Q(a,b){this.code=a;this.a=R[a]||Wb;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}h(Q,Error);var Wb="unknown error",R={15:"element not selectable",11:"element not visible"};R[31]=Wb;R[30]=Wb;R[24]="invalid cookie domain";R[29]="invalid element coordinates";R[12]="invalid element state";
R[32]="invalid selector";R[51]="invalid selector";R[52]="invalid selector";R[17]="javascript error";R[405]="unsupported operation";R[34]="move target out of bounds";R[27]="no such alert";R[7]="no such element";R[8]="no such frame";R[23]="no such window";R[28]="script timeout";R[33]="session not created";R[10]="stale element reference";R[21]="timeout";R[25]="unable to set cookie";R[26]="unexpected alert open";R[13]=Wb;R[9]="unknown command";var Xb=Ba(),Yb=Da()||t("iPod"),Zb=t("iPad"),$b=t("Android")&&!(Ca()||Ba()||t("Opera")||t("Silk")),ac=Ca(),bc=t("Safari")&&!(Ca()||t("Coast")||t("Opera")||t("Edge")||t("Edg/")||t("OPR")||Ba()||t("Silk")||t("Android"))&&!(Da()||t("iPad")||t("iPod"));function cc(a){return(a=a.exec(va))?a[1]:""}var dc=function(){if(Xb)return cc(/Firefox\/([0-9.]+)/);if(ac)return Da()||t("iPad")||t("iPod")?cc(/CriOS\/([0-9.]+)/):cc(/Chrome\/([0-9.]+)/);if(bc&&!(Da()||t("iPad")||t("iPod")))return cc(/Version\/([0-9.]+)/);if(Yb||Zb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(va);if(a)return a[1]+"."+a[2]}else if($b)return(a=cc(/Android\s+([0-9.]+)/))?a:cc(/Version\/([0-9.]+)/);return""}();var ec=Zb||Yb,fc;if($b){var gc=/Android\s+([0-9\.]+)/.exec(va);fc=gc?gc[1]:"0"}else fc="0";var hc=fc;function ic(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};var S={};S.G=function(){var a={T:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
S.s=function(a,b,c){var d=x(a);if(!d.documentElement)return null;$b&&Vb(Ma(d));try{for(var e=d.createNSResolver?d.createNSResolver(d.documentElement):S.G,f={},g=d.getElementsByTagName("*"),l=0;l<g.length;++l){var k=g[l],q=k.namespaceURI;if(q&&!f[q]){var D=k.lookupPrefix(q);if(!D){var W=q.match(".*/(\\w+)/?$");D=W?W[1]:"xhtml"}f[q]=D}}var L={},r;for(r in f)L[f[r]]=r;e=function(C){return L[C]||null};try{return d.evaluate(b,a,e,c,null)}catch(C){if("TypeError"===C.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):
S.G,d.evaluate(b,a,e,c,null);throw C;}}catch(C){throw new Q(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+C);}};S.H=function(a,b){if(!a||1!=a.nodeType)throw new Q(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
S.P=function(a,b){var c=function(){var d=S.s(b,a,9);return d?d.singleNodeValue||null:b.selectSingleNode?(d=x(b),d.setProperty&&d.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||S.H(c,a);return c};
S.S=function(a,b){var c=function(){var d=S.s(b,a,7);if(d){for(var e=d.snapshotLength,f=[],g=0;g<e;++g)f.push(d.snapshotItem(g));return f}return b.selectNodes?(d=x(b),d.setProperty&&d.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();n(c,function(d){S.H(d,a)});return c};function T(a,b,c,d){this.a=a;this.b=b;this.width=c;this.height=d}T.prototype.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};T.prototype.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
T.prototype.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};T.prototype.scale=function(a,b){b="number"===typeof b?b:a;this.a*=a;this.width*=a;this.b*=b;this.height*=b;return this};function jc(a){var b;var c=ic(a,"MAP");if(c||ic(a,"AREA")){var d=c?a:ic(a.parentNode,"MAP")?a.parentNode:null,e=b=null;if(d&&d.name&&(b=S.P('/descendant::*[@usemap = "#'+d.name+'"]',x(d)))&&(e=jc(b),!c&&"default"!=a.shape.toLowerCase())){c=kc(a);d=Math.min(Math.max(c.a,0),e.width);var f=Math.min(Math.max(c.b,0),e.height);e=new T(d+e.a,f+e.b,Math.min(c.width,e.width-d),Math.min(c.height,e.height-f))}b={image:b,rect:e||new T(0,0,0,0)}}else b=null;if(b)return b.rect;if(ic(a,"HTML"))return a=(Ma(x(a))||
window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new La(a.clientWidth,a.clientHeight),new T(0,0,a.width,a.height);try{var g=a.getBoundingClientRect()}catch(l){return new T(0,0,0,0)}return new T(g.left,g.top,g.right-g.left,g.bottom-g.top)}
function kc(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){b=a[0];var c=a[1];return new T(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new T(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){b=a[0];c=a[1];for(var d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new T(b,c,d-b,e-c)}return new T(0,0,0,0)};var lc=aa.JSON.stringify;function mc(a){function b(c,d){switch(da(c)){case "string":case "number":case "boolean":return c;case "function":return c.toString();case "array":return p(c,function(f){return b(f,d)});case "object":if(0<=d.indexOf(c))throw new Q(17,"Recursive object cannot be transferred");if(u(c,"nodeType")&&(1==c.nodeType||9==c.nodeType)){var e={};e.ELEMENT=nc(c);return e}if(u(c,"document"))return e={},e.WINDOW=nc(c),e;d.push(c);if(ea(c))return p(c,function(f){return b(f,d)});c=ya(c,function(f,g){return"number"==
typeof g||ba(g)});return za(c,function(f){return b(f,d)});default:return null}}return b(a,[])}function oc(a,b){return"array"==da(a)?p(a,function(c){return oc(c,b)}):fa(a)?"function"==typeof a?a:u(a,"ELEMENT")?pc(a.ELEMENT,b):u(a,"WINDOW")?pc(a.WINDOW,b):za(a,function(c){return oc(c,b)}):a}function qc(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.F=la());b.F||(b.F=la());return b}function nc(a){var b=qc(a.ownerDocument),c=Aa(b,function(d){return d==a});c||(c=":wdc:"+b.F++,b[c]=a);return c}
function pc(a,b){a=decodeURIComponent(a);b=b||document;var c=qc(b);if(!u(c,a))throw new Q(10,"Element does not exist in cache");var d=c[a];if(u(d,"setInterval")){if(d.closed)throw delete c[a],new Q(23,"Window has been closed.");return d}for(var e=d;e;){if(e==b.documentElement)return d;e.host&&11===e.nodeType&&(e=e.host);e=e.parentNode}delete c[a];throw new Q(10,"Element is no longer attached to the DOM");};var rc=$b?!($b?0<=ta(hc):0<=ta(dc)):!ec;function U(a,b,c){this.a=a;this.b=b;this.f=c}U.prototype.create=function(a){a=x(a).createEvent("HTMLEvents");a.initEvent(this.a,this.b,this.f);return a};U.prototype.toString=function(){return this.a};function V(a,b,c){ma(this,a,b,c)}h(V,U);
V.prototype.create=function(a,b){if(this==sc)throw new Q(9,"Browser does not support a mouse pixel scroll event.");var c=x(a);a=Ma(c);c=c.createEvent("MouseEvents");this==tc&&(c.wheelDelta=b.wheelDelta);c.initMouseEvent(this.a,this.b,this.f,a,1,b.clientX,b.clientY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);return c};function uc(a,b,c){ma(this,a,b,c)}h(uc,U);
uc.prototype.create=function(a,b){a=x(a).createEvent("Events");a.initEvent(this.a,this.b,this.f);a.altKey=b.altKey;a.ctrlKey=b.ctrlKey;a.metaKey=b.metaKey;a.shiftKey=b.shiftKey;a.keyCode=b.charCode||b.keyCode;a.charCode=this==vc?a.keyCode:0;return a};function wc(a,b,c){ma(this,a,b,c)}h(wc,U);
wc.prototype.create=function(a,b){function c(L){L=p(L,function(r){return g.createTouch(l,a,r.identifier,r.pageX,r.pageY,r.screenX,r.screenY)});return g.createTouchList.apply(g,L)}function d(L){var r=p(L,function(C){return{identifier:C.identifier,screenX:C.screenX,screenY:C.screenY,clientX:C.clientX,clientY:C.clientY,pageX:C.pageX,pageY:C.pageY,target:a}});r.item=function(C){return r[C]};return r}function e(L){return p(L,function(r){return new Touch({identifier:r.identifier,screenX:r.screenX,screenY:r.screenY,
clientX:r.clientX,clientY:r.clientY,pageX:r.pageX,pageY:r.pageY,target:a})})}function f(L,r){switch(L){case 1:return d(r);case 2:return c(r);case 3:return e(r)}return null}var g=x(a),l=Ma(g);if(rc)var k=1;else if(TouchEvent.prototype.initTouchEvent)k=2;else if(TouchEvent&&0<TouchEvent.length)k=3;else throw new Q(9,"Not able to create touch events in this browser");var q=f(k,b.changedTouches),D=b.touches==b.changedTouches?q:f(k,b.touches),W=b.targetTouches==b.changedTouches?q:f(k,b.targetTouches);
if(1==k)k=g.createEvent("MouseEvents"),k.initMouseEvent(this.a,this.b,this.f,l,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,b.relatedTarget),k.touches=D,k.targetTouches=W,k.changedTouches=q,k.scale=b.scale,k.rotation=b.rotation;else if(2==k)k=g.createEvent("TouchEvent"),0==k.initTouchEvent.length?k.initTouchEvent(D,W,q,this.a,l,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey):k.initTouchEvent(this.a,this.b,this.f,l,1,0,0,b.clientX,b.clientY,b.ctrlKey,b.altKey,
b.shiftKey,b.metaKey,D,W,q,b.scale,b.rotation),k.relatedTarget=b.relatedTarget;else if(3==k)k=new TouchEvent(this.a,{touches:D,targetTouches:W,changedTouches:q,bubbles:this.b,cancelable:this.f,ctrlKey:b.ctrlKey,shiftKey:b.shiftKey,altKey:b.altKey,metaKey:b.metaKey});else throw new Q(9,"Illegal TouchEventStrategy_ value (this is a bug)");return k};function X(a,b,c){ma(this,a,b,c)}h(X,U);X.prototype.create=function(){throw new Q(9,"Browser does not support MSGesture events.");};
function Y(a,b,c){ma(this,a,b,c)}h(Y,U);Y.prototype.create=function(){throw new Q(9,"Browser does not support MSPointer events.");};new V("click",!0,!0);new V("contextmenu",!0,!0);new V("dblclick",!0,!0);new V("mousedown",!0,!0);new V("mousemove",!0,!1);new V("mouseout",!0,!0);new V("mouseover",!0,!0);new V("mouseup",!0,!0);var tc=new V("mousewheel",!0,!0),sc=new V("MozMousePixelScroll",!0,!0);new uc("keydown",!0,!0);var vc=new uc("keypress",!0,!0);new uc("keyup",!0,!0);new wc("touchend",!0,!0);
new wc("touchmove",!0,!0);new wc("touchstart",!0,!0);new X("MSGestureChange",!0,!0);new X("MSGestureEnd",!0,!0);new X("MSGestureHold",!0,!0);new X("MSGestureStart",!0,!0);new X("MSGestureTap",!0,!0);new X("MSInertiaStart",!0,!0);new Y("MSGotPointerCapture",!0,!1);new Y("MSLostPointerCapture",!0,!1);new Y("MSPointerCancel",!0,!0);new Y("MSPointerDown",!0,!0);new Y("MSPointerMove",!0,!0);new Y("MSPointerOver",!0,!0);new Y("MSPointerOut",!0,!0);new Y("MSPointerUp",!0,!0);function xc(a,b){this.b={};this.a=[];this.f=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof xc)for(c=yc(a),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}
function yc(a){if(a.f!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];Object.prototype.hasOwnProperty.call(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.f!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],Object.prototype.hasOwnProperty.call(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}return a.a.concat()}xc.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.b,a)?this.b[a]:b};
xc.prototype.set=function(a,b){Object.prototype.hasOwnProperty.call(this.b,a)||(this.f++,this.a.push(a));this.b[a]=b};var zc={};function Z(a,b,c){fa(a)&&(a=a.g);a=new Ac(a);!b||b in zc&&!c||(zc[b]={key:a,shift:!1},c&&(zc[c]={key:a,shift:!0}));return a}function Ac(a){this.code=a}Z(8);Z(9);Z(13);var Bc=Z(16),Cc=Z(17),Dc=Z(18);Z(19);Z(20);Z(27);Z(32," ");Z(33);Z(34);Z(35);Z(36);Z(37);Z(38);Z(39);Z(40);Z(44);Z(45);Z(46);Z(48,"0",")");Z(49,"1","!");Z(50,"2","@");Z(51,"3","#");Z(52,"4","$");Z(53,"5","%");Z(54,"6","^");Z(55,"7","&");Z(56,"8","*");Z(57,"9","(");Z(65,"a","A");Z(66,"b","B");Z(67,"c","C");Z(68,"d","D");
Z(69,"e","E");Z(70,"f","F");Z(71,"g","G");Z(72,"h","H");Z(73,"i","I");Z(74,"j","J");Z(75,"k","K");Z(76,"l","L");Z(77,"m","M");Z(78,"n","N");Z(79,"o","O");Z(80,"p","P");Z(81,"q","Q");Z(82,"r","R");Z(83,"s","S");Z(84,"t","T");Z(85,"u","U");Z(86,"v","V");Z(87,"w","W");Z(88,"x","X");Z(89,"y","Y");Z(90,"z","Z");var Ec=Z(Fa?{h:91,g:91}:Ea?{h:224,g:91}:{h:0,g:91});Z(Fa?{h:92,g:92}:Ea?{h:224,g:93}:{h:0,g:92});Z(Fa?{h:93,g:93}:Ea?{h:0,g:0}:{h:93,g:null});Z({h:96,g:96},"0");Z({h:97,g:97},"1");
Z({h:98,g:98},"2");Z({h:99,g:99},"3");Z({h:100,g:100},"4");Z({h:101,g:101},"5");Z({h:102,g:102},"6");Z({h:103,g:103},"7");Z({h:104,g:104},"8");Z({h:105,g:105},"9");Z({h:106,g:106},"*");Z({h:107,g:107},"+");Z({h:109,g:109},"-");Z({h:110,g:110},".");Z({h:111,g:111},"/");Z(144);Z(112);Z(113);Z(114);Z(115);Z(116);Z(117);Z(118);Z(119);Z(120);Z(121);Z(122);Z(123);Z({h:107,g:187},"=","+");Z(108,",");Z({h:109,g:189},"-","_");Z(188,",","<");Z(190,".",">");Z(191,"/","?");Z(192,"`","~");Z(219,"[","{");
Z(220,"\\","|");Z(221,"]","}");Z({h:59,g:186},";",":");Z(222,"'",'"');var Fc=new xc;Fc.set(1,Bc);Fc.set(2,Cc);Fc.set(4,Dc);Fc.set(8,Ec);(function(a){var b=new xc;n(yc(a),function(c){b.set(a.get(c).code,c)});return b})(Fc);function Gc(a,b,c){try{var d;c?d=pc(c.WINDOW):d=window;var e=oc(b,d.document),f=a.apply(null,e);var g={status:0,value:mc(f)}}catch(l){g={status:u(l,"code")?l.code:13,value:{message:l.message}}}return lc(g)};ca("_",function(a,b){return Gc(function(c){var d=jc(c);c=d.height;d=d.width;d=Math.floor(d);c=Math.floor(c);return{width:d,height:c}},[a],b)});; return this._.apply(null,arguments);}).apply(window, arguments);}
