function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var b=this||self;try{var c=window}catch(a){c=b};var l=class extends Error{constructor(){super("Geolocation undefined");this.code=13;this.state=h[13]||k;this.message="Geolocation undefined";var a=this.state.replace(/((?:^|\s+)[a-z])/g,function(f){return f.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=a.length-5;if(d<0||a.indexOf("Error",d)!=d)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}},k="unknown error",h={15:"element not selectable",11:"element not visible"};h[31]=k;h[30]=k;h[24]="invalid cookie domain";
h[29]="invalid element coordinates";h[12]="invalid element state";h[32]="invalid selector";h[51]="invalid selector";h[52]="invalid selector";h[17]="javascript error";h[405]="unsupported operation";h[34]="move target out of bounds";h[27]="no such alert";h[7]="no such element";h[8]="no such frame";h[23]="no such window";h[28]="script timeout";h[33]="session not created";h[10]="stale element reference";h[21]="timeout";h[25]="unable to set cookie";h[26]="unexpected alert open";h[13]=k;h[9]="unknown command";
l.prototype.toString=function(){return this.name+": "+this.message};(class{constructor(a,d){this.l=a===m&&d||""}}).prototype.toString=function(){return"Const{"+this.l+"}"};var m={};var n=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function p(a,d){var f=0;a=n(String(a)).split(".");d=n(String(d)).split(".");var r=Math.max(a.length,d.length);for(let t=0;f==0&&t<r;t++){var e=a[t]||"",g=d[t]||"";do{e=/(\d*)(\D*)(.*)/.exec(e)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(e[0].length==0&&g[0].length==0)break;f=q(e[1].length==0?0:parseInt(e[1],10),g[1].length==0?0:parseInt(g[1],10))||q(e[2].length==0,g[2].length==0)||q(e[2],g[2]);e=e[3];g=g[3]}while(f==0)}return f}function q(a,d){return a<d?-1:a>d?1:0};var v=class{constructor(a){if(u!==u)throw Error("SafeUrl is not meant to be built directly");this.j=a}toString(){return this.j.toString()}},u={};new v("about:invalid#zClosurez");new v("about:blank");var w={};class x{constructor(){if(w!==w)throw Error("SafeStyle is not meant to be built directly");this.i=""}toString(){return this.i.toString()}}new x;var y={};class z{constructor(){if(y!==y)throw Error("SafeStyleSheet is not meant to be built directly");this.h=""}toString(){return this.h.toString()}}new z;function A(){var a=b.navigator;return a&&(a=a.userAgent)?a:""}function B(a){return A().indexOf(a)!=-1};function C(){return B("Firefox")||B("FxiOS")}function D(){return(B("Chrome")||B("CriOS"))&&!B("Edge")||B("Silk")};var E={};class F{constructor(){var a=b.trustedTypes&&b.trustedTypes.emptyHTML||"";if(E!==E)throw Error("SafeHtml is not meant to be built directly");this.g=a}toString(){return this.g.toString()}}new F;function G(){return B("iPhone")&&!B("iPod")&&!B("iPad")};var H=B("Windows");var I=C(),J=G()||B("iPod"),K=B("iPad"),L=B("Android")&&!(D()||C()||B("Opera")||B("Silk")),M=D(),N=B("Safari")&&!(D()||B("Coast")||B("Opera")||B("Edge")||B("Edg/")||B("OPR")||C()||B("Silk")||B("Android"))&&!(G()||B("iPad")||B("iPod"));function O(a){return(a=a.exec(A()))?a[1]:""}var P=function(){if(I)return O(/Firefox\/([0-9.]+)/);if(M){if(G()||B("iPad")||B("iPod")||B("Macintosh")){var a=O(/CriOS\/([0-9.]+)/);if(a)return a}return O(/Chrome\/([0-9.]+)/)}if(N&&!(G()||B("iPad")||B("iPod")))return O(/Version\/([0-9.]+)/);if(J||K){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(A()))return a[1]+"."+a[2]}else if(L)return(a=O(/Android\s+([0-9.]+)/))?a:O(/Version\/([0-9.]+)/);return""}();var Q;if(L){var R=/Android\s+([0-9\.]+)/.exec(A());Q=R?R[1]:"0"}else Q="0";var S=Q;var T=H&&N&&(L?p(S,4)>=0:p(P,4)>=0)&&!(L?p(S,6)>=0:p(P,6)>=0);var U={enableHighAccuracy:!0,maximumAge:Infinity,timeout:5E3};function V(a,d,f){var r=c;f=f||U;var e=r||c;if(T?0:e.navigator!=null&&e.navigator.geolocation!=null)r.navigator.geolocation.getCurrentPosition(a,d,f);else throw new l;}var W=["se_exportedFunctionSymbol"],X=b;W[0]in X||typeof X.execScript=="undefined"||X.execScript("var "+W[0]);for(var Y;W.length&&(Y=W.shift());)W.length||V===void 0?X=X[Y]&&X[Y]!==Object.prototype[Y]?X[Y]:X[Y]={}:X[Y]=V;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
