function(){return function(){var h,ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ca="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function da(a,b){if(b){for(var c=ca,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&ba(c,d,{configurable:!0,writable:!0,value:f})}}
da("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=c),a>>>=1)c+=c;return d}});da("Math.sign",function(a){return a?a:function(a){a=Number(a);return!a||isNaN(a)?a:0<a?1:-1}});var l=this;function m(a){return void 0!==a}
function ea(a,b){var c=a.split("."),d=l;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&m(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}
function fa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ga(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function n(a){return"string"==typeof a}function ha(a){return"number"==typeof a}function ia(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ja(a,b,c){return a.call.apply(a.bind,arguments)}
function ka(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function la(a,b,c){la=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja:ka;return la.apply(null,arguments)}
function ma(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var na=Date.now||function(){return+new Date};function q(a,b){function c(){}c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.O=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};var oa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function pa(a,b){for(var c=0,d=oa(String(a)).split("."),e=oa(String(b)).split("."),f=Math.max(d.length,e.length),g=0;!c&&g<f;g++){var k=d[g]||"",t=e[g]||"",u=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var w=u.exec(k)||["","",""],C=p.exec(t)||["","",""];if(0==w[0].length&&0==C[0].length)break;c=qa(0==w[1].length?0:parseInt(w[1],10),0==C[1].length?0:parseInt(C[1],10))||qa(0==w[2].length,0==C[2].length)||qa(w[2],C[2])}while(!c)}return c}function qa(a,b){return a<b?-1:a>b?1:0}
function ra(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};function sa(a,b){if(n(a))return n(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1}function r(a,b){for(var c=a.length,d=n(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function ta(a,b){for(var c=a.length,d=[],e=0,f=n(a)?a.split(""):a,g=0;g<c;g++)if(g in f){var k=f[g];b.call(void 0,k,g,a)&&(d[e++]=k)}return d}
function va(a,b){for(var c=a.length,d=Array(c),e=n(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d}function wa(a,b,c){var d=c;r(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function xa(a,b){for(var c=a.length,d=n(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}function ya(a,b){for(var c=a.length,d=n(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0}
function za(a,b){var c;a:{c=a.length;for(var d=n(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:n(a)?a.charAt(c):a[c]}function Aa(a){return Array.prototype.concat.apply(Array.prototype,arguments)}function Ba(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Ca={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var Da="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),Ea=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,Fa=/^#(?:[0-9a-f]{3}){1,2}$/i,Ga=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,Ha=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function Ia(a,b){this.code=a;this.a=v[a]||Ja;this.message=b||"";var c=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")}),d=c.length-5;if(0>d||c.indexOf("Error",d)!=d)c+="Error";this.name=c;c=Error(this.message);c.name=this.name;this.stack=c.stack||""}q(Ia,Error);var Ja="unknown error",v={15:"element not selectable",11:"element not visible"};v[31]=Ja;v[30]=Ja;v[24]="invalid cookie domain";v[29]="invalid element coordinates";v[12]="invalid element state";
v[32]="invalid selector";v[51]="invalid selector";v[52]="invalid selector";v[17]="javascript error";v[405]="unsupported operation";v[34]="move target out of bounds";v[27]="no such alert";v[7]="no such element";v[8]="no such frame";v[23]="no such window";v[28]="script timeout";v[33]="session not created";v[10]="stale element reference";v[21]="timeout";v[25]="unable to set cookie";v[26]="unexpected alert open";v[13]=Ja;v[9]="unknown command";Ia.prototype.toString=function(){return this.name+": "+this.message};var x;a:{var Ka=l.navigator;if(Ka){var La=Ka.userAgent;if(La){x=La;break a}}x=""}function y(a){return-1!=x.indexOf(a)};function Ma(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function Na(a,b){var c={},d;for(d in a)c[d]=b.call(void 0,a[d],d,a);return c}function Oa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return c};function Pa(){return y("Opera")||y("OPR")}function Qa(){return(y("Chrome")||y("CriOS"))&&!Pa()&&!y("Edge")};function Ra(){return y("iPhone")&&!y("iPod")&&!y("iPad")};var Sa=Pa(),z=y("Trident")||y("MSIE"),Ta=y("Edge"),A=y("Gecko")&&!(-1!=x.toLowerCase().indexOf("webkit")&&!y("Edge"))&&!(y("Trident")||y("MSIE"))&&!y("Edge"),Ua=-1!=x.toLowerCase().indexOf("webkit")&&!y("Edge"),Va=y("Macintosh"),Wa=y("Windows");function Xa(){var a=x;if(A)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ta)return/Edge\/([\d\.]+)/.exec(a);if(z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ua)return/WebKit\/(\S+)/.exec(a)}function Ya(){var a=l.document;return a?a.documentMode:void 0}
var Za=function(){if(Sa&&l.opera){var a;var b=l.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Xa())&&(a=b?b[1]:"");return z&&(b=Ya(),null!=b&&b>parseFloat(a))?String(b):a}(),$a={};function ab(a){return $a[a]||($a[a]=0<=pa(Za,a))}var bb=l.document,cb=bb&&z?Ya()||("CSS1Compat"==bb.compatMode?parseInt(Za,10):5):void 0;var db=y("Firefox"),eb=Ra()||y("iPod"),fb=y("iPad"),gb=y("Android")&&!(Qa()||y("Firefox")||Pa()||y("Silk")),hb=Qa(),ib=y("Safari")&&!(Qa()||y("Coast")||Pa()||y("Edge")||y("Silk")||y("Android"))&&!(Ra()||y("iPad")||y("iPod"));function jb(a){return(a=a.exec(x))?a[1]:""}var kb=function(){if(db)return jb(/Firefox\/([0-9.]+)/);if(z||Ta||Sa)return Za;if(hb)return jb(/Chrome\/([0-9.]+)/);if(ib&&!(Ra()||y("iPad")||y("iPod")))return jb(/Version\/([0-9.]+)/);if(eb||fb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(x);if(a)return a[1]+"."+a[2]}else if(gb)return(a=jb(/Android\s+([0-9.]+)/))?a:jb(/Version\/([0-9.]+)/);return""}();var lb,mb;function nb(a){return ob?lb(a):z?0<=pa(cb,a):ab(a)}function pb(a){ob?mb(a):gb?pa(qb,a):pa(kb,a)}
var ob=function(){if(!A)return!1;var a=l.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;lb=function(a){return 0<=c.compare(d,""+a)};mb=function(a){c.compare(e,""+a)};return!0}(),rb;if(gb){var sb=/Android\s+([0-9\.]+)/.exec(x);rb=sb?sb[1]:"0"}else rb="0";
var qb=rb,tb=z&&!(9<=Number(cb));gb&&pb(2.3);gb&&pb(4);ib&&pb(6);!A&&!z||z&&9<=Number(cb)||A&&ab("1.9.1");z&&ab("9");function ub(a,b){this.x=m(a)?a:0;this.y=m(b)?b:0}h=ub.prototype;h.clone=function(){return new ub(this.x,this.y)};h.toString=function(){return"("+this.x+", "+this.y+")"};h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};h.scale=function(a,b){var c=ha(b)?b:a;this.x*=a;this.y*=c;return this};function vb(a,b){this.width=a;this.height=b}h=vb.prototype;h.clone=function(){return new vb(this.width,this.height)};h.toString=function(){return"("+this.width+" x "+this.height+")"};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.scale=function(a,b){var c=ha(b)?b:a;this.width*=a;this.height*=c;return this};function wb(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function xb(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(z&&!(9<=Number(cb))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?yb(a,b):!c&&wb(e,b)?-1*zb(a,b):!d&&wb(f,a)?zb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=B(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(l.Range.START_TO_END,d)}function zb(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return yb(d,a)}function yb(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1}function B(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Ab(a,b){a=a.parentNode;for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}
function Bb(a){this.a=a||l.document||document}Bb.prototype.contains=wb;function D(a,b){return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function Cb(a,b,c){this.a=a;this.b=b||1;this.h=c||1};var E=z&&!(9<=Number(cb)),Db=z&&!(8<=Number(cb));function Eb(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function Fb(a,b){var c=Db&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new Eb(b,a,b.nodeName,c)};function Gb(a){this.b=a;this.a=0}function Hb(a){a=a.match(Ib);for(var b=0;b<a.length;b++)Jb.test(a[b])&&a.splice(b,1);return new Gb(a)}var Ib=RegExp("\\$?(?:(?![0-9-\\.])(?:\\*|[\\w-\\.]+):)?(?![0-9-\\.])(?:\\*|[\\w-\\.]+)|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),Jb=/^\s/;function F(a,b){return a.b[a.a+(b||0)]}Gb.prototype.next=function(){return this.b[this.a++]};function Kb(a){return a.b.length<=a.a};function G(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(E&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),E&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function H(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}Db&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function Lb(a,b,c,d,e){return(E?Mb:Nb).call(null,a,b,n(c)?c:null,n(d)?d:null,e||new I)}
function Mb(a,b,c,d,e){if(a instanceof Ob||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;a=Pb(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var g=[],k=0;b=f[k++];)H(b,c,d)&&g.push(b);f=g}for(k=0;b=f[k++];)"*"==a&&"!"==b.tagName||J(e,b);return e}Qb(a,b,c,d,e);return e}
function Nb(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!z?(b=b.getElementsByName(d),r(b,function(b){a.a(b)&&J(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),r(b,function(b){b.className==d&&a.a(b)&&J(e,b)})):a instanceof K?Qb(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.h()),r(b,function(a){H(a,c,d)&&J(e,a)}));return e}
function Rb(a,b,c,d,e){var f;if((a instanceof Ob||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var g=Pb(a);if("*"!=g&&(f=ta(f,function(a){return a.tagName&&a.tagName.toLowerCase()==g}),!f))return e;c&&(f=ta(f,function(a){return H(a,c,d)}));r(f,function(a){"*"==g&&("!"==a.tagName||"*"==g&&1!=a.nodeType)||J(e,a)});return e}return Sb(a,b,c,d,e)}function Sb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)H(b,c,d)&&a.a(b)&&J(e,b);return e}
function Qb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)H(b,c,d)&&a.a(b)&&J(e,b),Qb(a,b,c,d,e)}function Pb(a){if(a instanceof K){if(8==a.b)return"!";if(null===a.b)return"*"}return a.h()};function I(){this.b=this.a=null;this.s=0}function Tb(a){this.node=a;this.next=this.a=null}function Ub(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f,g=0;c&&d;){f=c.node;var k=d.node;f==k||f instanceof Eb&&k instanceof Eb&&f.a==k.a?(f=c,c=c.next,d=d.next):0<xb(c.node,d.node)?(f=d,d=d.next):(f=c,c=c.next);(f.a=e)?e.next=f:a.a=f;e=f;g++}for(f=c||d;f;)f.a=e,e=e.next=f,g++,f=f.next;a.b=e;a.s=g;return a}
I.prototype.unshift=function(a){a=new Tb(a);a.next=this.a;this.b?this.a.a=a:this.a=this.b=a;this.a=a;this.s++};function J(a,b){var c=new Tb(b);c.a=a.b;a.a?a.b.next=c:a.a=a.b=c;a.b=c;a.s++}function Vb(a){return(a=a.a)?a.node:null}function Wb(a){return(a=Vb(a))?G(a):""}I.prototype.iterator=function(a){return new Xb(this,!!a)};function Xb(a,b){this.h=a;this.b=(this.c=b)?a.b:a.a;this.a=null}Xb.prototype.next=function(){var a=this.b;if(a){var b=this.a=a;this.b=this.c?a.a:a.next;return b.node}return null};function L(a){this.m=a;this.b=this.i=!1;this.h=null}function M(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Yb(a,b){a.i=b}function Zb(a,b){a.b=b}function N(a,b){var c=a.a(b);return c instanceof I?+Wb(c):+c}function O(a,b){var c=a.a(b);return c instanceof I?Wb(c):""+c}function $b(a,b){var c=a.a(b);return c instanceof I?!!c.s:!!c};function ac(a,b,c){L.call(this,a.m);this.c=a;this.j=b;this.w=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==bc&&(c.b||c.i||4==c.m||0==c.m||!b.h?b.b||b.i||4==b.m||0==b.m||!c.h||(this.h={name:c.h.name,A:b}):this.h={name:b.h.name,A:c})}q(ac,L);
function cc(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof I&&c instanceof I){b=b.iterator();for(d=b.next();d;d=b.next())for(e=c.iterator(),f=e.next();f;f=e.next())if(a(G(d),G(f)))return!0;return!1}if(b instanceof I||c instanceof I){b instanceof I?(e=b,d=c):(e=c,d=b);f=e.iterator();for(var g=typeof d,k=f.next();k;k=f.next()){switch(g){case "number":k=+G(k);break;case "boolean":k=!!G(k);break;case "string":k=G(k);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(k,
d)||e==c&&a(d,k))return!0}return!1}return e?"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}ac.prototype.a=function(a){return this.c.u(this.j,this.w,a)};ac.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+M(this.j);return a+=M(this.w)};function dc(a,b,c,d){this.a=a;this.I=b;this.m=c;this.u=d}dc.prototype.toString=function(){return this.a};var ec={};
function P(a,b,c,d){if(ec.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new dc(a,b,c,d);return ec[a.toString()]=a}P("div",6,1,function(a,b,c){return N(a,c)/N(b,c)});P("mod",6,1,function(a,b,c){return N(a,c)%N(b,c)});P("*",6,1,function(a,b,c){return N(a,c)*N(b,c)});P("+",5,1,function(a,b,c){return N(a,c)+N(b,c)});P("-",5,1,function(a,b,c){return N(a,c)-N(b,c)});P("<",4,2,function(a,b,c){return cc(function(a,b){return a<b},a,b,c)});
P(">",4,2,function(a,b,c){return cc(function(a,b){return a>b},a,b,c)});P("<=",4,2,function(a,b,c){return cc(function(a,b){return a<=b},a,b,c)});P(">=",4,2,function(a,b,c){return cc(function(a,b){return a>=b},a,b,c)});var bc=P("=",3,2,function(a,b,c){return cc(function(a,b){return a==b},a,b,c,!0)});P("!=",3,2,function(a,b,c){return cc(function(a,b){return a!=b},a,b,c,!0)});P("and",2,2,function(a,b,c){return $b(a,c)&&$b(b,c)});P("or",1,2,function(a,b,c){return $b(a,c)||$b(b,c)});function fc(a,b){if(b.a.length&&4!=a.m)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");L.call(this,a.m);this.c=a;this.j=b;this.i=a.i;this.b=a.b}q(fc,L);fc.prototype.a=function(a){a=this.c.a(a);return gc(this.j,a)};fc.prototype.toString=function(){var a;a="Filter:"+M(this.c);return a+=M(this.j)};function hc(a,b){if(b.length<a.J)throw Error("Function "+a.o+" expects at least"+a.J+" arguments, "+b.length+" given");if(null!==a.D&&b.length>a.D)throw Error("Function "+a.o+" expects at most "+a.D+" arguments, "+b.length+" given");a.N&&r(b,function(b,d){if(4!=b.m)throw Error("Argument "+d+" to function "+a.o+" is not of type Nodeset: "+b);});L.call(this,a.m);this.j=a;this.c=b;Yb(this,a.i||xa(b,function(a){return a.i}));Zb(this,a.M&&!b.length||a.L&&!!b.length||xa(b,function(a){return a.b}))}
q(hc,L);hc.prototype.a=function(a){return this.j.u.apply(null,Aa(a,this.c))};hc.prototype.toString=function(){var a="Function: "+this.j;if(this.c.length)var b=wa(this.c,function(a,b){return a+M(b)},"Arguments:"),a=a+M(b);return a};function ic(a,b,c,d,e,f,g,k,t){this.o=a;this.m=b;this.i=c;this.M=d;this.L=e;this.u=f;this.J=g;this.D=m(k)?k:g;this.N=!!t}ic.prototype.toString=function(){return this.o};var jc={};
function Q(a,b,c,d,e,f,g,k){if(jc.hasOwnProperty(a))throw Error("Function already created: "+a+".");jc[a]=new ic(a,b,c,d,!1,e,f,g,k)}Q("boolean",2,!1,!1,function(a,b){return $b(b,a)},1);Q("ceiling",1,!1,!1,function(a,b){return Math.ceil(N(b,a))},1);Q("concat",3,!1,!1,function(a,b){return wa(Ba(arguments,1),function(b,d){return b+O(d,a)},"")},2,null);Q("contains",2,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);return-1!=b.indexOf(a)},2);Q("count",1,!1,!1,function(a,b){return b.a(a).s},1,1,!0);
Q("false",2,!1,!1,function(){return!1},0);Q("floor",1,!1,!1,function(a,b){return Math.floor(N(b,a))},1);Q("id",4,!1,!1,function(a,b){function c(a){if(E){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return za(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=O(b,a).split(/\s+/),f=[];r(d,function(a){a=c(a);!a||0<=sa(f,a)||f.push(a)});f.sort(xb);var g=new I;r(f,function(a){J(g,a)});return g},1);
Q("lang",2,!1,!1,function(){return!1},1);Q("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.h},0);Q("local-name",3,!1,!0,function(a,b){var c=b?Vb(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);Q("name",3,!1,!0,function(a,b){var c=b?Vb(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);Q("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
Q("normalize-space",3,!1,!0,function(a,b){return(b?O(b,a):G(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);Q("not",2,!1,!1,function(a,b){return!$b(b,a)},1);Q("number",1,!1,!0,function(a,b){return b?N(b,a):+G(a.a)},0,1);Q("position",1,!0,!1,function(a){return a.b},0);Q("round",1,!1,!1,function(a,b){return Math.round(N(b,a))},1);Q("starts-with",2,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);return!b.lastIndexOf(a,0)},2);Q("string",3,!1,!0,function(a,b){return b?O(b,a):G(a.a)},0,1);
Q("string-length",1,!1,!0,function(a,b){return(b?O(b,a):G(a.a)).length},0,1);Q("substring",3,!1,!1,function(a,b,c,d){c=N(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?N(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=O(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);Q("substring-after",3,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
Q("substring-before",3,!1,!1,function(a,b,c){b=O(b,a);a=O(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);Q("sum",1,!1,!1,function(a,b){for(var c=b.a(a).iterator(),d=0,e=c.next();e;e=c.next())d+=+G(e);return d},1,1,!0);Q("translate",3,!1,!1,function(a,b,c,d){b=O(b,a);c=O(c,a);var e=O(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);Q("true",2,!1,!1,function(){return!0},0);function K(a,b){this.j=a;this.c=m(b)?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function kc(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}K.prototype.a=function(a){return null===this.b||this.b==a.nodeType};K.prototype.h=function(){return this.j};
K.prototype.toString=function(){var a="Kind Test: "+this.j;!this.c||(a+=M(this.c));return a};function lc(a){L.call(this,3);this.c=a.substring(1,a.length-1)}q(lc,L);lc.prototype.a=function(){return this.c};lc.prototype.toString=function(){return"Literal: "+this.c};function Ob(a,b){this.o=a.toLowerCase();var c;c="*"==this.o?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():c}Ob.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=m(a.localName)?a.localName:a.nodeName;return"*"!=this.o&&this.o!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};Ob.prototype.h=function(){return this.o};
Ob.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.o};function mc(a){L.call(this,1);this.c=a}q(mc,L);mc.prototype.a=function(){return this.c};mc.prototype.toString=function(){return"Number: "+this.c};function nc(a,b){L.call(this,a.m);this.j=a;this.c=b;this.i=a.i;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.B||c.c!=oc||(c=c.w,"*"!=c.h()&&(this.h={name:c.h(),A:null}))}}q(nc,L);function pc(){L.call(this,4)}q(pc,L);pc.prototype.a=function(a){var b=new I;a=a.a;9==a.nodeType?J(b,a):J(b,a.ownerDocument);return b};pc.prototype.toString=function(){return"Root Helper Expression"};function qc(){L.call(this,4)}q(qc,L);qc.prototype.a=function(a){var b=new I;J(b,a.a);return b};qc.prototype.toString=function(){return"Context Helper Expression"};
function rc(a){return"/"==a||"//"==a}nc.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof I))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.s;c++){var e=a[c],f=b.iterator(e.c.a),g;if(e.i||e.c!=sc)if(e.i||e.c!=tc)for(g=f.next(),b=e.a(new Cb(g));g=f.next();)g=e.a(new Cb(g)),b=Ub(b,g);else g=f.next(),b=e.a(new Cb(g));else{for(g=f.next();(b=f.next())&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new Cb(g))}}return b};
nc.prototype.toString=function(){var a;a="Path Expression:"+M(this.j);if(this.c.length){var b=wa(this.c,function(a,b){return a+M(b)},"Steps:");a+=M(b)}return a};function uc(a,b){this.a=a;this.b=!!b}
function gc(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=b.iterator(),f=b.s,g,k=0;g=e.next();k++){var t=a.b?f-k:k+1;g=d.a(new Cb(g,t,f));if("number"==typeof g)t=t==g;else if("string"==typeof g||"boolean"==typeof g)t=!!g;else if(g instanceof I)t=0<g.s;else throw Error("Predicate.evaluate returned an unexpected type.");if(!t){t=e;g=t.h;var u=t.a;if(!u)throw Error("Next must be called at least once before remove.");var p=u.a,u=u.next;p?p.next=u:g.a=u;u?u.a=p:g.b=p;g.s--;t.a=null}}return b}
uc.prototype.toString=function(){return wa(this.a,function(a,b){return a+M(b)},"Predicates:")};function R(a,b,c,d){L.call(this,4);this.c=a;this.w=b;this.j=c||new uc([]);this.B=!!d;b=this.j;b=0<b.a.length?b.a[0].h:null;a.b&&b&&(a=b.name,a=E?a.toLowerCase():a,this.h={name:a,A:b.A});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.m||0==c.m){a=!0;break a}a=!1}this.i=a}q(R,L);
R.prototype.a=function(a){var b=a.a,c=this.h,d=null,e=null,f=0;c&&(d=c.name,e=c.A?O(c.A,a):null,f=1);if(this.B)if(this.i||this.c!=vc)if(b=(new R(wc,new K("node"))).a(a).iterator(),c=b.next())for(a=this.u(c,d,e,f);c=b.next();)a=Ub(a,this.u(c,d,e,f));else a=new I;else a=Lb(this.w,b,d,e),a=gc(this.j,a,f);else a=this.u(a.a,d,e,f);return a};R.prototype.u=function(a,b,c,d){a=this.c.h(this.w,a,b,c);return a=gc(this.j,a,d)};
R.prototype.toString=function(){var a;a="Step:"+M("Operator: "+(this.B?"//":"/"));this.c.o&&(a+=M("Axis: "+this.c));a+=M(this.w);if(this.j.a.length){var b=wa(this.j.a,function(a,b){return a+M(b)},"Predicates:");a+=M(b)}return a};function xc(a,b,c,d){this.o=a;this.h=b;this.a=c;this.b=d}xc.prototype.toString=function(){return this.o};var yc={};function S(a,b,c,d){if(yc.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new xc(a,b,c,!!d);return yc[a]=b}
S("ancestor",function(a,b){for(var c=new I,d=b;d=d.parentNode;)a.a(d)&&c.unshift(d);return c},!0);S("ancestor-or-self",function(a,b){var c=new I,d=b;do a.a(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var oc=S("attribute",function(a,b){var c=new I,d=a.h();if("style"==d&&E&&b.style)return J(c,new Eb(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof K&&null===a.b||"*"==d)for(var d=0,f;f=e[d];d++)E?f.nodeValue&&J(c,Fb(b,f)):J(c,f);else(f=e.getNamedItem(d))&&(E?f.nodeValue&&J(c,Fb(b,f)):J(c,f));return c},!1),vc=S("child",function(a,b,c,d,e){return(E?Rb:Sb).call(null,a,b,n(c)?c:null,n(d)?d:null,e||new I)},!1,!0);S("descendant",Lb,!1,!0);
var wc=S("descendant-or-self",function(a,b,c,d){var e=new I;H(b,c,d)&&a.a(b)&&J(e,b);return Lb(a,b,c,d,e)},!1,!0),sc=S("following",function(a,b,c,d){var e=new I;do for(var f=b;f=f.nextSibling;)H(f,c,d)&&a.a(f)&&J(e,f),e=Lb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);S("following-sibling",function(a,b){for(var c=new I,d=b;d=d.nextSibling;)a.a(d)&&J(c,d);return c},!1);S("namespace",function(){return new I},!1);
var zc=S("parent",function(a,b){var c=new I;if(9==b.nodeType)return c;if(2==b.nodeType)return J(c,b.ownerElement),c;var d=b.parentNode;a.a(d)&&J(c,d);return c},!1),tc=S("preceding",function(a,b,c,d){var e=new I,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,k=f.length;g<k;g++){var t=[];for(b=f[g];b=b.previousSibling;)t.unshift(b);for(var u=0,p=t.length;u<p;u++)b=t[u],H(b,c,d)&&a.a(b)&&J(e,b),e=Lb(a,b,c,d,e)}return e},!0,!0);
S("preceding-sibling",function(a,b){for(var c=new I,d=b;d=d.previousSibling;)a.a(d)&&c.unshift(d);return c},!0);var Ac=S("self",function(a,b){var c=new I;a.a(b)&&J(c,b);return c},!1);function Bc(a){L.call(this,1);this.c=a;this.i=a.i;this.b=a.b}q(Bc,L);Bc.prototype.a=function(a){return-N(this.c,a)};Bc.prototype.toString=function(){return"Unary Expression: -"+M(this.c)};function Cc(a){L.call(this,4);this.c=a;Yb(this,xa(this.c,function(a){return a.i}));Zb(this,xa(this.c,function(a){return a.b}))}q(Cc,L);Cc.prototype.a=function(a){var b=new I;r(this.c,function(c){c=c.a(a);if(!(c instanceof I))throw Error("Path expression must evaluate to NodeSet.");b=Ub(b,c)});return b};Cc.prototype.toString=function(){return wa(this.c,function(a,b){return a+M(b)},"Union Expression:")};function Dc(a,b){this.a=a;this.b=b}function Ec(a){for(var b,c=[];;){T(a,"Missing right hand side of binary expression.");b=Fc(a);var d=a.a.next();if(!d)break;var e=(d=ec[d]||null)&&d.I;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].I;)b=new ac(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new ac(c.pop(),c.pop(),b);return b}function T(a,b){if(Kb(a.a))throw Error(b);}function Gc(a,b){var c=a.a.next();if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function Hc(a){a=a.a.next();if(")"!=a)throw Error("Bad token: "+a);}function Ic(a){a=a.a.next();if(2>a.length)throw Error("Unclosed literal string");return new lc(a)}
function Jc(a){var b,c=[],d;if(rc(F(a.a))){b=a.a.next();d=F(a.a);if("/"==b&&(Kb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new pc;d=new pc;T(a,"Missing next location step.");b=Kc(a,b);c.push(b)}else{a:{b=F(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":a.a.next();b=Ec(a);T(a,'unclosed "("');Gc(a,")");break;case '"':case "'":b=Ic(a);break;default:if(isNaN(+b))if(!kc(b)&&/(?![0-9])[\w]/.test(d)&&"("==F(a.a,1)){b=
a.a.next();b=jc[b]||null;a.a.next();for(d=[];")"!=F(a.a);){T(a,"Missing function argument list.");d.push(Ec(a));if(","!=F(a.a))break;a.a.next()}T(a,"Unclosed function argument list.");Hc(a);b=new hc(b,d)}else{b=null;break a}else b=new mc(+a.a.next())}"["==F(a.a)&&(d=new uc(Lc(a)),b=new fc(b,d))}if(b)if(rc(F(a.a)))d=b;else return b;else b=Kc(a,"/"),d=new qc,c.push(b)}for(;rc(F(a.a));)b=a.a.next(),T(a,"Missing next location step."),b=Kc(a,b),c.push(b);return new nc(d,c)}
function Kc(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==F(a.a))return d=new R(Ac,new K("node")),a.a.next(),d;if(".."==F(a.a))return d=new R(zc,new K("node")),a.a.next(),d;var f;if("@"==F(a.a))f=oc,a.a.next(),T(a,"Missing attribute name");else if("::"==F(a.a,1)){if(!/(?![0-9])[\w]/.test(F(a.a).charAt(0)))throw Error("Bad token: "+a.a.next());c=a.a.next();f=yc[c]||null;if(!f)throw Error("No axis with name: "+c);a.a.next();T(a,"Missing node name")}else f=vc;
c=F(a.a);if(/(?![0-9])[\w\*]/.test(c.charAt(0)))if("("==F(a.a,1)){if(!kc(c))throw Error("Invalid node type: "+c);c=a.a.next();if(!kc(c))throw Error("Invalid type name: "+c);Gc(a,"(");T(a,"Bad nodetype");e=F(a.a).charAt(0);var g=null;if('"'==e||"'"==e)g=Ic(a);T(a,"Bad nodetype");Hc(a);c=new K(c,g)}else if(c=a.a.next(),e=c.indexOf(":"),-1==e)c=new Ob(c);else{var g=c.substring(0,e),k;if("*"==g)k="*";else if(k=a.b(g),!k)throw Error("Namespace prefix not declared: "+g);c=c.substr(e+1);c=new Ob(c,k)}else throw Error("Bad token: "+
a.a.next());e=new uc(Lc(a),f.a);return d||new R(f,c,e,"//"==b)}function Lc(a){for(var b=[];"["==F(a.a);){a.a.next();T(a,"Missing predicate expression.");var c=Ec(a);b.push(c);T(a,"Unclosed predicate expression.");Gc(a,"]")}return b}function Fc(a){if("-"==F(a.a))return a.a.next(),new Bc(Fc(a));var b=Jc(a);if("|"!=F(a.a))a=b;else{for(b=[b];"|"==a.a.next();)T(a,"Missing next union location path."),b.push(Jc(a));a.a.a--;a=new Cc(b)}return a};function Mc(a){switch(a.nodeType){case 1:return ma(Nc,a);case 9:return Mc(a.documentElement);case 11:case 10:case 6:case 12:return Oc;default:return a.parentNode?Mc(a.parentNode):Oc}}function Oc(){return null}function Nc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?Nc(a.parentNode,b):null};function Pc(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=Hb(a);if(Kb(c))throw Error("Invalid XPath expression.");b?"function"==fa(b)||(b=la(b.lookupNamespaceURI,b)):b=function(){return null};var d=Ec(new Dc(c,b));if(!Kb(c))throw Error("Bad token: "+c.next());this.evaluate=function(a,b){var c=d.a(new Cb(a));return new U(c,b)}}
function U(a,b){if(!b)if(a instanceof I)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof I))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof I?Wb(a):""+a;break;case 1:this.numberValue=a instanceof I?+Wb(a):+a;break;case 3:this.booleanValue=a instanceof I?0<a.s:!!a;break;case 4:case 5:case 6:case 7:var d=
a.iterator();c=[];for(var e=d.next();e;e=d.next())c.push(e instanceof Eb?e.a:e);this.snapshotLength=a.s;this.invalidIteratorState=!1;break;case 8:case 9:d=Vb(a);this.singleNodeValue=d instanceof Eb?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");
return a>=c.length||0>a?null:c[a]}}U.ANY_TYPE=0;U.NUMBER_TYPE=1;U.STRING_TYPE=2;U.BOOLEAN_TYPE=3;U.UNORDERED_NODE_ITERATOR_TYPE=4;U.ORDERED_NODE_ITERATOR_TYPE=5;U.UNORDERED_NODE_SNAPSHOT_TYPE=6;U.ORDERED_NODE_SNAPSHOT_TYPE=7;U.ANY_UNORDERED_NODE_TYPE=8;U.FIRST_ORDERED_NODE_TYPE=9;function Qc(a){this.lookupNamespaceURI=Mc(a)}
function Rc(a,b){var c=a||l,d=c.Document&&c.Document.prototype||c.document;if(!d.evaluate||b)c.XPathResult=U,d.evaluate=function(a,b,c,d){return(new Pc(a,c)).evaluate(b,d)},d.createExpression=function(a,b){return new Pc(a,b)},d.createNSResolver=function(a){return new Qc(a)}}ea("wgxpath.install",Rc);var V={};V.F=function(){var a={S:"http://www.w3.org/2000/svg"};return function(b){return a[b]||null}}();
V.u=function(a,b,c){var d=B(a);if(!d.documentElement)return null;(z||gb)&&Rc(d?d.parentWindow||d.defaultView:window);try{var e=d.createNSResolver?d.createNSResolver(d.documentElement):V.F;if(z&&!ab(7))return d.evaluate.call(d,b,a,e,c,null);if(!z||9<=Number(cb)){for(var f={},g=d.getElementsByTagName("*"),k=0;k<g.length;++k){var t=g[k],u=t.namespaceURI;if(u&&!f[u]){var p=t.lookupPrefix(u);if(!p)var w=u.match(".*/(\\w+)/?$"),p=w?w[1]:"xhtml";f[u]=p}}var C={},aa;for(aa in f)C[f[aa]]=aa;e=function(a){return C[a]||
null}}try{return d.evaluate(b,a,e,c,null)}catch(ua){if("TypeError"===ua.name)return e=d.createNSResolver?d.createNSResolver(d.documentElement):V.F,d.evaluate(b,a,e,c,null);throw ua;}}catch(ua){if(!A||"NS_ERROR_ILLEGAL_VALUE"!=ua.name)throw new Ia(32,"Unable to locate an element with the xpath expression "+b+" because of the following error:\n"+ua);}};V.G=function(a,b){if(!a||1!=a.nodeType)throw new Ia(32,'The result of the xpath expression "'+b+'" is: '+a+". It should be an element.");};
V.K=function(a,b){var c=function(){var c=V.u(b,a,9);return c?c.singleNodeValue||null:b.selectSingleNode?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectSingleNode(a)):null}();null===c||V.G(c,a);return c};
V.P=function(a,b){var c=function(){var c=V.u(b,a,7);if(c){for(var e=c.snapshotLength,f=[],g=0;g<e;++g)f.push(c.snapshotItem(g));return f}return b.selectNodes?(c=B(b),c.setProperty&&c.setProperty("SelectionLanguage","XPath"),b.selectNodes(a)):[]}();r(c,function(b){V.G(b,a)});return c};function Sc(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}h=Sc.prototype;h.clone=function(){return new Sc(this.top,this.right,this.bottom,this.left)};h.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};h.contains=function(a){return this&&a?a instanceof Sc?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
h.scale=function(a,b){var c=ha(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};function W(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}h=W.prototype;h.clone=function(){return new W(this.left,this.top,this.width,this.height)};h.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};h.contains=function(a){return a instanceof W?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
h.scale=function(a,b){var c=ha(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};function Tc(a){for(a=a.parentNode;a&&1!=a.nodeType&&9!=a.nodeType&&11!=a.nodeType;)a=a.parentNode;return D(a)?a:null}
function X(a,b){var c=ra(b);if("float"==c||"cssFloat"==c||"styleFloat"==c)c=tb?"styleFloat":"cssFloat";var d;a:{d=c;var e=B(a);if(e.defaultView&&e.defaultView.getComputedStyle&&(e=e.defaultView.getComputedStyle(a,null))){d=e[d]||e.getPropertyValue(d)||"";break a}d=""}d=d||Uc(a,c);if(null===d)d=null;else if(0<=sa(Da,c)){b:{var f=d.match(Ga);if(f){var c=Number(f[1]),e=Number(f[2]),g=Number(f[3]),f=Number(f[4]);if(0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g&&0<=f&&1>=f){c=[c,e,g,f];break b}}c=null}if(!c)b:{if(g=
d.match(Ha))if(c=Number(g[1]),e=Number(g[2]),g=Number(g[3]),0<=c&&255>=c&&0<=e&&255>=e&&0<=g&&255>=g){c=[c,e,g,1];break b}c=null}if(!c)b:{c=d.toLowerCase();e=Ca[c.toLowerCase()];if(!e&&(e="#"==c.charAt(0)?c:"#"+c,4==e.length&&(e=e.replace(Ea,"#$1$1$2$2$3$3")),!Fa.test(e))){c=null;break b}c=[parseInt(e.substr(1,2),16),parseInt(e.substr(3,2),16),parseInt(e.substr(5,2),16),1]}d=c?"rgba("+c.join(", ")+")":d}return d}
function Uc(a,b){var c=a.currentStyle||a.style,d=c[b];!m(d)&&"function"==fa(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=d?m(d)?d:null:(c=Tc(a))?Uc(c,b):null}
function Vc(a,b,c){function d(a){var b=Wc(a);return 0<b.height&&0<b.width?!0:D(a,"PATH")&&(0<b.height||0<b.width)?(a=X(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=X(a,"overflow")&&xa(a.childNodes,function(a){return 3==a.nodeType||D(a)&&d(a)})}function e(a){return Xc(a)==Y&&ya(a.childNodes,function(a){return!D(a)||e(a)||!d(a)})}if(!D(a))throw Error("Argument to isShown must be of type Element");if(D(a,"BODY"))return!0;if(D(a,"OPTION")||D(a,"OPTGROUP"))return a=Ab(a,function(a){return D(a,"SELECT")}),
!!a&&Vc(a,!0,c);var f=Yc(a);if(f)return!!f.H&&0<f.rect.width&&0<f.rect.height&&Vc(f.H,b,c);if(D(a,"INPUT")&&"hidden"==a.type.toLowerCase()||D(a,"NOSCRIPT"))return!1;f=X(a,"visibility");return"collapse"!=f&&"hidden"!=f&&c(a)&&(b||Zc(a))&&d(a)?!e(a):!1}function $c(a,b){function c(a){if("none"==X(a,"display"))return!1;a=Tc(a);return!a||c(a)}return Vc(a,!!b,c)}var Y="hidden";
function Xc(a){function b(a){function b(a){return a==g?!0:!X(a,"display").lastIndexOf("inline",0)||"absolute"==c&&"static"==X(a,"position")?!1:!0}var c=X(a,"position");if("fixed"==c)return u=!0,a==g?null:g;for(a=Tc(a);a&&!b(a);)a=Tc(a);return a}function c(a){var b=a;if("visible"==t)if(a==g&&k)b=k;else if(a==k)return{x:"visible",y:"visible"};b={x:X(b,"overflow-x"),y:X(b,"overflow-y")};a==g&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}function d(a){if(a==g){var b=(new Bb(f)).a;
a=b.scrollingElement?b.scrollingElement:Ua||"CSS1Compat"!=b.compatMode?b.body||b.documentElement:b.documentElement;b=b.parentWindow||b.defaultView;a=z&&ab("10")&&b.pageYOffset!=a.scrollTop?new ub(a.scrollLeft,a.scrollTop):new ub(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}else a=new ub(a.scrollLeft,a.scrollTop);return a}var e=ad(a),f=B(a),g=f.documentElement,k=f.body,t=X(g,"overflow"),u;for(a=b(a);a;a=b(a)){var p=c(a);if("visible"!=p.x||"visible"!=p.y){var w=Wc(a);if(!w.width||!w.height)return Y;
var C=e.right<w.left,aa=e.bottom<w.top;if(C&&"hidden"==p.x||aa&&"hidden"==p.y)return Y;if(C&&"visible"!=p.x||aa&&"visible"!=p.y){C=d(a);aa=e.bottom<w.top-C.y;if(e.right<w.left-C.x&&"visible"!=p.x||aa&&"visible"!=p.x)return Y;e=Xc(a);return e==Y?Y:"scroll"}C=e.left>=w.left+w.width;w=e.top>=w.top+w.height;if(C&&"hidden"==p.x||w&&"hidden"==p.y)return Y;if(C&&"visible"!=p.x||w&&"visible"!=p.y){if(u&&(p=d(a),e.left>=g.scrollWidth-p.x||e.right>=g.scrollHeight-p.y))return Y;e=Xc(a);return e==Y?Y:"scroll"}}}return"none"}
function Wc(a){var b=Yc(a);if(b)return b.rect;if(D(a,"HTML"))return a=B(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a="CSS1Compat"==a.compatMode?a.documentElement:a.body,a=new vb(a.clientWidth,a.clientHeight),new W(0,0,a.width,a.height);var c;try{c=a.getBoundingClientRect()}catch(d){return new W(0,0,0,0)}b=new W(c.left,c.top,c.right-c.left,c.bottom-c.top);z&&a.ownerDocument.body&&(a=B(a),b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+
a.body.clientTop);return b}function Yc(a){var b=D(a,"MAP");if(!b&&!D(a,"AREA"))return null;var c=b?a:D(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;c&&c.name&&(d=V.K('/descendant::*[@usemap = "#'+c.name+'"]',B(c)))&&(e=Wc(d),b||"default"==a.shape.toLowerCase()||(a=bd(a),b=Math.min(Math.max(a.left,0),e.width),c=Math.min(Math.max(a.top,0),e.height),e=new W(b+e.left,c+e.top,Math.min(a.width,e.width-b),Math.min(a.height,e.height-c))));return{H:d,rect:e||new W(0,0,0,0)}}
function bd(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new W(b,c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new W(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,e=c,f=2;f+1<a.length;f+=2)b=Math.min(b,a[f]),d=Math.max(d,a[f]),c=Math.min(c,a[f+1]),e=Math.max(e,a[f+1]);return new W(b,c,d-b,e-c)}return new W(0,0,0,0)}function ad(a){a=Wc(a);return new Sc(a.top,a.left+a.width,a.top+a.height,a.left)}
function Zc(a){if(tb){if("relative"==X(a,"position"))return 1;a=X(a,"filter");return(a=a.match(/^alpha\(opacity=(\d*)\)/)||a.match(/^progid:DXImageTransform.Microsoft.Alpha\(Opacity=(\d*)\)/))?Number(a[1])/100:1}return cd(a)}function cd(a){var b=1,c=X(a,"opacity");c&&(b=Number(c));(a=Tc(a))&&(b*=cd(a));return b};Ua||ob&&pb(3.6);z&&nb(10);gb&&pb(4);function dd(a,b){this.v={};this.l=[];this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){var e;if(a instanceof dd)for(d=ed(a),fd(a),e=[],c=0;c<a.l.length;c++)e.push(a.v[a.l[c]]);else{var c=[],f=0;for(d in a)c[f++]=d;d=c;c=[];f=0;for(e in a)c[f++]=a[e];e=c}for(c=0;c<d.length;c++)this.set(d[c],e[c])}}function ed(a){fd(a);return a.l.concat()}h=dd.prototype;
h.clear=function(){this.v={};this.a=this.l.length=0};function fd(a){if(a.a!=a.l.length){for(var b=0,c=0;b<a.l.length;){var d=a.l[b];Object.prototype.hasOwnProperty.call(a.v,d)&&(a.l[c++]=d);b++}a.l.length=c}if(a.a!=a.l.length){for(var e={},c=b=0;b<a.l.length;)d=a.l[b],Object.prototype.hasOwnProperty.call(e,d)||(a.l[c++]=d,e[d]=1),b++;a.l.length=c}}h.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.v,a)?this.v[a]:b};
h.set=function(a,b){Object.prototype.hasOwnProperty.call(this.v,a)||(this.a++,this.l.push(a));this.v[a]=b};h.forEach=function(a,b){for(var c=ed(this),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new dd(this)};var gd={};function Z(a,b,c){ia(a)&&(a=A?a.f:a.g);a=new hd(a);!b||b in gd&&!c||(gd[b]={key:a,shift:!1},c&&(gd[c]={key:a,shift:!0}));return a}function hd(a){this.code=a}Z(8);Z(9);Z(13);var id=Z(16),jd=Z(17),kd=Z(18);Z(19);Z(20);Z(27);Z(32," ");Z(33);Z(34);Z(35);Z(36);Z(37);Z(38);Z(39);Z(40);Z(44);Z(45);Z(46);Z(48,"0",")");Z(49,"1","!");Z(50,"2","@");Z(51,"3","#");Z(52,"4","$");Z(53,"5","%");Z(54,"6","^");Z(55,"7","&");Z(56,"8","*");Z(57,"9","(");Z(65,"a","A");Z(66,"b","B");Z(67,"c","C");Z(68,"d","D");
Z(69,"e","E");Z(70,"f","F");Z(71,"g","G");Z(72,"h","H");Z(73,"i","I");Z(74,"j","J");Z(75,"k","K");Z(76,"l","L");Z(77,"m","M");Z(78,"n","N");Z(79,"o","O");Z(80,"p","P");Z(81,"q","Q");Z(82,"r","R");Z(83,"s","S");Z(84,"t","T");Z(85,"u","U");Z(86,"v","V");Z(87,"w","W");Z(88,"x","X");Z(89,"y","Y");Z(90,"z","Z");var ld=Z(Wa?{f:91,g:91}:Va?{f:224,g:91}:{f:0,g:91});Z(Wa?{f:92,g:92}:Va?{f:224,g:93}:{f:0,g:92});Z(Wa?{f:93,g:93}:Va?{f:0,g:0}:{f:93,g:null});Z({f:96,g:96},"0");Z({f:97,g:97},"1");
Z({f:98,g:98},"2");Z({f:99,g:99},"3");Z({f:100,g:100},"4");Z({f:101,g:101},"5");Z({f:102,g:102},"6");Z({f:103,g:103},"7");Z({f:104,g:104},"8");Z({f:105,g:105},"9");Z({f:106,g:106},"*");Z({f:107,g:107},"+");Z({f:109,g:109},"-");Z({f:110,g:110},".");Z({f:111,g:111},"/");Z(144);Z(112);Z(113);Z(114);Z(115);Z(116);Z(117);Z(118);Z(119);Z(120);Z(121);Z(122);Z(123);Z({f:107,g:187},"=","+");Z(108,",");Z({f:109,g:189},"-","_");Z(188,",","<");Z(190,".",">");Z(191,"/","?");Z(192,"`","~");Z(219,"[","{");
Z(220,"\\","|");Z(221,"]","}");Z({f:59,g:186},";",":");Z(222,"'",'"');var md=new dd;md.set(1,id);md.set(2,jd);md.set(4,kd);md.set(8,ld);(function(a){var b=new dd;r(ed(a),function(c){b.set(a.get(c).code,c)});return b})(md);A&&nb(12);function nd(){}
function od(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if("array"==fa(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),od(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),pd(d,c),c.push(":"),od(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":pd(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var qd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},rd=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function pd(a,b){b.push('"',a.replace(rd,function(a){var b=qd[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),qd[a]=b);return b}),'"')};Ua||A&&nb(3.5)||z&&nb(8);function sd(a){switch(fa(a)){case "string":case "number":case "boolean":return a;case "function":return a.toString();case "array":return va(a,sd);case "object":if(a&&"nodeType"in a&&(1==a.nodeType||9==a.nodeType)){var b={};b.ELEMENT=td(a);return b}if(a&&"document"in a)return b={},b.WINDOW=td(a),b;if(ga(a))return va(a,sd);a=Ma(a,function(a,b){return ha(b)||n(b)});return Na(a,sd);default:return null}}
function ud(a,b){return"array"==fa(a)?va(a,function(a){return ud(a,b)}):ia(a)?"function"==typeof a?a:a&&"ELEMENT"in a?vd(a.ELEMENT,b):a&&"WINDOW"in a?vd(a.WINDOW,b):Na(a,function(a){return ud(a,b)}):a}function wd(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.C=na());b.C||(b.C=na());return b}function td(a){var b=wd(a.ownerDocument),c=Oa(b,function(b){return b==a});c||(c=":wdc:"+b.C++,b[c]=a);return c}
function vd(a,b){a=decodeURIComponent(a);var c=b||document,d=wd(c);if(!(d&&a in d))throw new Ia(10,"Element does not exist in cache");var e=d[a];if(e&&"setInterval"in e){if(e.closed)throw delete d[a],new Ia(23,"Window has been closed.");return e}for(var f=e;f;){if(f==c.documentElement)return e;f=f.parentNode}delete d[a];throw new Ia(10,"Element is no longer attached to the DOM");};ea("_",function(a,b){var c=[a,!0],d;try{var e;b?e=vd(b.WINDOW):e=window;var f=ud(c,e.document),g=$c.apply(null,f);d={status:0,value:sd(g)}}catch(k){d={status:k&&"code"in k?k.code:13,value:{message:k.message}}}c=[];od(new nd,d,c);return c.join("")});; return this._.apply(null,arguments);}.apply({navigator:typeof window!=undefined?window.navigator:null,document:typeof window!=undefined?window.document:null}, arguments);}
