function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var d=this||self;const g=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(let c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},h=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){var c=a.length,f=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)e in f&&b.call(void 0,f[e],e,a)},k=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,
b,void 0)}:function(a,b){var c=a.length,f=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)if(e in f&&b.call(void 0,f[e],e,a))return!0;return!1};var m=class{constructor(a){if(l!==l)throw Error("SafeUrl is not meant to be built directly");this.j=a}toString(){return this.j.toString()}},l={};new m("about:invalid#zClosurez");new m("about:blank");const n={};class p{constructor(){if(n!==n)throw Error("SafeStyle is not meant to be built directly");this.i=""}toString(){return this.i.toString()}}new p;const q={};class r{constructor(){if(q!==q)throw Error("SafeStyleSheet is not meant to be built directly");this.h=""}toString(){return this.h.toString()}}new r;function t(){var a=d.navigator;return a&&(a=a.userAgent)?a:""}function u(a){return t().indexOf(a)!=-1};function v(){return u("Firefox")||u("FxiOS")}function w(){return(u("Chrome")||u("CriOS"))&&!u("Edge")||u("Silk")};const x={};class y{constructor(){var a=d.trustedTypes&&d.trustedTypes.emptyHTML||"";if(x!==x)throw Error("SafeHtml is not meant to be built directly");this.g=a}toString(){return this.g.toString()}}new y;function z(){return u("iPhone")&&!u("iPod")&&!u("iPad")};var A=v(),B=z()||u("iPod"),C=u("iPad"),D=u("Android")&&!(w()||v()||u("Opera")||u("Silk")),E=w(),F=u("Safari")&&!(w()||u("Coast")||u("Opera")||u("Edge")||u("Edg/")||u("OPR")||v()||u("Silk")||u("Android"))&&!(z()||u("iPad")||u("iPod"));function G(a){return(a=a.exec(t()))?a[1]:""}(function(){if(A)return G(/Firefox\/([0-9.]+)/);if(E){if(z()||u("iPad")||u("iPod")||u("Macintosh")){var a=G(/CriOS\/([0-9.]+)/);if(a)return a}return G(/Chrome\/([0-9.]+)/)}if(F&&!(z()||u("iPad")||u("iPod")))return G(/Version\/([0-9.]+)/);if(B||C){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(t()))return a[1]+"."+a[2]}else if(D)return(a=G(/Android\s+([0-9.]+)/))?a:G(/Version\/([0-9.]+)/);return""})();function H(a){var b="tabindex";return b=="style"?I(a.style.cssText):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var J=RegExp("[;]+(?=(?:(?:[^\"]*\"){2})*[^\"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\\([^()]*\\))*[^()]*$)");function I(a){var b=[];h(a.split(J),function(c){var f=c.indexOf(":");f>0&&(c=[c.slice(0,f),c.slice(f+1)],c.length==2&&b.push(c[0].toLowerCase(),":",c[1],";"))});b=b.join("");return b=b.charAt(b.length-1)==";"?b:b+";"}
function K(a,b){b&&typeof b!=="string"&&(b=b.toString());return a instanceof HTMLFormElement?!!a&&a.nodeType==1&&(!b||"FORM"==b):!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)};var L="A AREA BUTTON INPUT LABEL SELECT TEXTAREA".split(" "),M="text search tel url email password number".split(" ");function N(a,b){return K(a,"INPUT")?a.type.toLowerCase()==b:!1}function O(a){function b(c){if(c.contentEditable=="inherit"){for(c=c.parentNode;c&&c.nodeType!=1&&c.nodeType!=9&&c.nodeType!=11;)c=c.parentNode;return(c=K(c)?c:null)?b(c):!1}return c.contentEditable=="true"}return a.contentEditable===void 0?!1:a.isContentEditable===void 0?b(a):a.isContentEditable}
function P(a){return((K(a,"TEXTAREA")?!0:K(a,"INPUT")?g(M,a.type.toLowerCase())>=0:O(a)?!0:!1)||(K(a,"INPUT")?a.type.toLowerCase()=="file":!1)||N(a,"range")||N(a,"date")||N(a,"month")||N(a,"week")||N(a,"time")||N(a,"datetime-local")||N(a,"color"))&&!a.readOnly};function Q(a){return k(L,function(b){return K(a,b)})||H(a)!=null&&Number(a.tabIndex)>=0||P(a)}var R=["se_exportedFunctionSymbol"],S=d;R[0]in S||typeof S.execScript=="undefined"||S.execScript("var "+R[0]);for(var T;R.length&&(T=R.shift());)R.length||Q===void 0?S=S[T]&&S[T]!==Object.prototype[T]?S[T]:S[T]={}:S[T]=Q;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
