function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var d=this||self;const g=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(let c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},h=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){var c=a.length,f=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)e in f&&b.call(void 0,f[e],e,a)},k=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,
b,void 0)}:function(a,b){var c=a.length,f=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)if(e in f&&b.call(void 0,f[e],e,a))return!0;return!1};(class{constructor(a,b){this.l=a===l&&b||""}}).prototype.toString=function(){return"Const{"+this.l+"}"};var l={};var n=class{constructor(a){if(m!==m)throw Error("SafeUrl is not meant to be built directly");this.j=a}toString(){return this.j.toString()}},m={};new n("about:invalid#zClosurez");new n("about:blank");var p={};class q{constructor(){if(p!==p)throw Error("SafeStyle is not meant to be built directly");this.i=""}toString(){return this.i.toString()}}new q;var r={};class t{constructor(){if(r!==r)throw Error("SafeStyleSheet is not meant to be built directly");this.h=""}toString(){return this.h.toString()}}new t;function u(){var a=d.navigator;return a&&(a=a.userAgent)?a:""}function v(a){return u().indexOf(a)!=-1};function w(){return v("Firefox")||v("FxiOS")}function x(){return(v("Chrome")||v("CriOS"))&&!v("Edge")||v("Silk")};var y={};class z{constructor(){var a=d.trustedTypes&&d.trustedTypes.emptyHTML||"";if(y!==y)throw Error("SafeHtml is not meant to be built directly");this.g=a}toString(){return this.g.toString()}}new z;function A(){return v("iPhone")&&!v("iPod")&&!v("iPad")};var B=w(),C=A()||v("iPod"),D=v("iPad"),E=v("Android")&&!(x()||w()||v("Opera")||v("Silk")),F=x(),G=v("Safari")&&!(x()||v("Coast")||v("Opera")||v("Edge")||v("Edg/")||v("OPR")||w()||v("Silk")||v("Android"))&&!(A()||v("iPad")||v("iPod"));function H(a){return(a=a.exec(u()))?a[1]:""}(function(){if(B)return H(/Firefox\/([0-9.]+)/);if(F){if(A()||v("iPad")||v("iPod")||v("Macintosh")){var a=H(/CriOS\/([0-9.]+)/);if(a)return a}return H(/Chrome\/([0-9.]+)/)}if(G&&!(A()||v("iPad")||v("iPod")))return H(/Version\/([0-9.]+)/);if(C||D){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(u()))return a[1]+"."+a[2]}else if(E)return(a=H(/Android\s+([0-9.]+)/))?a:H(/Version\/([0-9.]+)/);return""})();function I(a){var b="tabindex";return b=="style"?J(a.style.cssText):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var K=RegExp("[;]+(?=(?:(?:[^\"]*\"){2})*[^\"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\\([^()]*\\))*[^()]*$)");function J(a){var b=[];h(a.split(K),function(c){var f=c.indexOf(":");f>0&&(c=[c.slice(0,f),c.slice(f+1)],c.length==2&&b.push(c[0].toLowerCase(),":",c[1],";"))});a=b.join("");return a.charAt(a.length-1)==";"?a:a+";"}
function L(a,b){b&&typeof b!=="string"&&(b=b.toString());return a instanceof HTMLFormElement?!!a&&a.nodeType==1&&(!b||"FORM"==b):!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)};var M="A AREA BUTTON INPUT LABEL SELECT TEXTAREA".split(" "),N="text search tel url email password number".split(" ");function O(a,b){return L(a,"INPUT")?a.type.toLowerCase()==b:!1}function P(a){function b(c){if(c.contentEditable=="inherit"){for(c=c.parentNode;c&&c.nodeType!=1&&c.nodeType!=9&&c.nodeType!=11;)c=c.parentNode;return(c=L(c)?c:null)?b(c):!1}return c.contentEditable=="true"}return a.contentEditable===void 0?!1:a.isContentEditable===void 0?b(a):a.isContentEditable}
function Q(a){return((L(a,"TEXTAREA")?!0:L(a,"INPUT")?g(N,a.type.toLowerCase())>=0:P(a)?!0:!1)||(L(a,"INPUT")?a.type.toLowerCase()=="file":!1)||O(a,"range")||O(a,"date")||O(a,"month")||O(a,"week")||O(a,"time")||O(a,"datetime-local")||O(a,"color"))&&!a.readOnly};function R(a){return k(M,function(b){return L(a,b)})||I(a)!=null&&Number(a.tabIndex)>=0||Q(a)}var S=["se_exportedFunctionSymbol"],T=d;S[0]in T||typeof T.execScript=="undefined"||T.execScript("var "+S[0]);for(var U;S.length&&(U=S.shift());)S.length||R===void 0?T=T[U]&&T[U]!==Object.prototype[U]?T[U]:T[U]={}:T[U]=R;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
