function(){return (function(){var h=this||self;function k(a){return"string"==typeof a}function aa(a,b){a=a.split(".");var c=h;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ca(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function l(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?l=ca:l=da;return l.apply(null,arguments)}function ea(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function m(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function p(a,b,c){this.a=a;this.b=b||1;this.f=c||1};var fa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},q=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},r=Array.prototype.reduce?function(a,b,c){return Array.prototype.reduce.call(a,
b,c)}:function(a,b,c){var d=c;q(a,function(e,f){d=b.call(void 0,d,e,f,a)});return d},t=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};function ha(a){return Array.prototype.concat.apply([],arguments)}function ia(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var u;a:{var ja=h.navigator;if(ja){var ka=ja.userAgent;if(ka){u=ka;break a}}u=""}function v(a){return-1!=u.indexOf(a)};function la(){return v("Firefox")||v("FxiOS")}function ma(){return(v("Chrome")||v("CriOS"))&&!v("Edge")};function na(){return v("iPhone")&&!v("iPod")&&!v("iPad")};function oa(a){this.b=a;this.a=0}function pa(a){a=a.match(qa);for(var b=0;b<a.length;b++)ra.test(a[b])&&a.splice(b,1);return new oa(a)}var qa=/\$?(?:(?![0-9-\.])(?:\*|[\w-\.]+):)?(?![0-9-\.])(?:\*|[\w-\.]+)|\/\/|\.\.|::|\d+(?:\.\d*)?|\.\d+|"[^"]*"|'[^']*'|[!<>]=|\s+|./g,ra=/^\s/;function x(a,b){return a.b[a.a+(b||0)]}function y(a){return a.b[a.a++]}function sa(a){return a.b.length<=a.a};function ta(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function ua(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?va(a,b):!c&&ta(e,b)?-1*wa(a,b):!d&&ta(f,a)?wa(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=9==a.nodeType?a:a.ownerDocument||a.document;c=d.createRange();c.selectNode(a);c.collapse(!0);
a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(h.Range.START_TO_END,a)}function wa(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return va(b,a)}function va(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1};function z(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;c=0;var d=[];for(b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return b}
function B(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function C(a,b,c,d,e){return xa.call(null,a,b,k(c)?c:null,k(d)?d:null,e||new D)}
function xa(a,b,c,d,e){b.getElementsByName&&d&&"name"==c?(b=b.getElementsByName(d),q(b,function(f){a.a(f)&&e.add(f)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),q(b,function(f){f.className==d&&a.a(f)&&e.add(f)})):a instanceof E?ya(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.f()),q(b,function(f){B(f,c,d)&&e.add(f)}));return e}function ya(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)B(b,c,d)&&a.a(b)&&e.add(b),ya(a,b,c,d,e)};function D(){this.b=this.a=null;this.l=0}function za(a){this.f=a;this.a=this.b=null}function Aa(a,b){if(!a.a)return b;if(!b.a)return a;var c=a.a;b=b.a;for(var d=null,e,f=0;c&&b;)c.f==b.f?(e=c,c=c.a,b=b.a):0<ua(c.f,b.f)?(e=b,b=b.a):(e=c,c=c.a),(e.b=d)?d.a=e:a.a=e,d=e,f++;for(e=c||b;e;)e.b=d,d=d.a=e,f++,e=e.a;a.b=d;a.l=f;return a}function Ba(a,b){b=new za(b);b.a=a.a;a.b?a.a.b=b:a.a=a.b=b;a.a=b;a.l++}D.prototype.add=function(a){a=new za(a);a.b=this.b;this.a?this.b.a=a:this.a=this.b=a;this.b=a;this.l++};
function Ca(a){return(a=a.a)?a.f:null}function Da(a){return(a=Ca(a))?z(a):""}function F(a,b){return new Ea(a,!!b)}function Ea(a,b){this.f=a;this.b=(this.s=b)?a.b:a.a;this.a=null}function G(a){var b=a.b;if(null==b)return null;var c=a.a=b;a.b=a.s?b.b:b.a;return c.f};function H(a){this.i=a;this.b=this.g=!1;this.f=null}function I(a){return"\n  "+a.toString().split("\n").join("\n  ")}function Fa(a,b){a.g=b}function Ga(a,b){a.b=b}function J(a,b){a=a.a(b);return a instanceof D?+Da(a):+a}function K(a,b){a=a.a(b);return a instanceof D?Da(a):""+a}function L(a,b){a=a.a(b);return a instanceof D?!!a.l:!!a};function M(a,b,c){H.call(this,a.i);this.c=a;this.h=b;this.o=c;this.g=b.g||c.g;this.b=b.b||c.b;this.c==Ha&&(c.b||c.g||4==c.i||0==c.i||!b.f?b.b||b.g||4==b.i||0==b.i||!c.f||(this.f={name:c.f.name,u:b}):this.f={name:b.f.name,u:c})}m(M,H);
function N(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof D&&c instanceof D){b=F(b);for(d=G(b);d;d=G(b))for(e=F(c),f=G(e);f;f=G(e))if(a(z(d),z(f)))return!0;return!1}if(b instanceof D||c instanceof D){b instanceof D?(e=b,d=c):(e=c,d=b);f=F(e);for(var g=typeof d,n=G(f);n;n=G(f)){switch(g){case "number":n=+z(n);break;case "boolean":n=!!z(n);break;case "string":n=z(n);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(n,d)||e==c&&a(d,n))return!0}return!1}return e?"boolean"==
typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}M.prototype.a=function(a){return this.c.m(this.h,this.o,a)};M.prototype.toString=function(){var a="Binary Expression: "+this.c;a+=I(this.h);return a+=I(this.o)};function Ia(a,b,c,d){this.I=a;this.D=b;this.i=c;this.m=d}Ia.prototype.toString=function(){return this.I};var Ja={};
function P(a,b,c,d){if(Ja.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new Ia(a,b,c,d);return Ja[a.toString()]=a}P("div",6,1,function(a,b,c){return J(a,c)/J(b,c)});P("mod",6,1,function(a,b,c){return J(a,c)%J(b,c)});P("*",6,1,function(a,b,c){return J(a,c)*J(b,c)});P("+",5,1,function(a,b,c){return J(a,c)+J(b,c)});P("-",5,1,function(a,b,c){return J(a,c)-J(b,c)});P("<",4,2,function(a,b,c){return N(function(d,e){return d<e},a,b,c)});
P(">",4,2,function(a,b,c){return N(function(d,e){return d>e},a,b,c)});P("<=",4,2,function(a,b,c){return N(function(d,e){return d<=e},a,b,c)});P(">=",4,2,function(a,b,c){return N(function(d,e){return d>=e},a,b,c)});var Ha=P("=",3,2,function(a,b,c){return N(function(d,e){return d==e},a,b,c,!0)});P("!=",3,2,function(a,b,c){return N(function(d,e){return d!=e},a,b,c,!0)});P("and",2,2,function(a,b,c){return L(a,c)&&L(b,c)});P("or",1,2,function(a,b,c){return L(a,c)||L(b,c)});function Ka(a,b){if(b.a.length&&4!=a.i)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");H.call(this,a.i);this.c=a;this.h=b;this.g=a.g;this.b=a.b}m(Ka,H);Ka.prototype.a=function(a){a=this.c.a(a);return La(this.h,a)};Ka.prototype.toString=function(){var a="Filter:"+I(this.c);return a+=I(this.h)};function Ma(a,b){if(b.length<a.C)throw Error("Function "+a.j+" expects at least"+a.C+" arguments, "+b.length+" given");if(null!==a.B&&b.length>a.B)throw Error("Function "+a.j+" expects at most "+a.B+" arguments, "+b.length+" given");a.H&&q(b,function(c,d){if(4!=c.i)throw Error("Argument "+d+" to function "+a.j+" is not of type Nodeset: "+c);});H.call(this,a.i);this.v=a;this.c=b;Fa(this,a.g||t(b,function(c){return c.g}));Ga(this,a.G&&!b.length||a.F&&!!b.length||t(b,function(c){return c.b}))}m(Ma,H);
Ma.prototype.a=function(a){return this.v.m.apply(null,ha(a,this.c))};Ma.prototype.toString=function(){var a="Function: "+this.v;if(this.c.length){var b=r(this.c,function(c,d){return c+I(d)},"Arguments:");a+=I(b)}return a};function Na(a,b,c,d,e,f,g,n){this.j=a;this.i=b;this.g=c;this.G=d;this.F=!1;this.m=e;this.C=f;this.B=void 0!==g?g:f;this.H=!!n}Na.prototype.toString=function(){return this.j};var Oa={};
function Q(a,b,c,d,e,f,g,n){if(Oa.hasOwnProperty(a))throw Error("Function already created: "+a+".");Oa[a]=new Na(a,b,c,d,e,f,g,n)}Q("boolean",2,!1,!1,function(a,b){return L(b,a)},1);Q("ceiling",1,!1,!1,function(a,b){return Math.ceil(J(b,a))},1);Q("concat",3,!1,!1,function(a,b){return r(ia(arguments,1),function(c,d){return c+K(d,a)},"")},2,null);Q("contains",2,!1,!1,function(a,b,c){b=K(b,a);a=K(c,a);return-1!=b.indexOf(a)},2);Q("count",1,!1,!1,function(a,b){return b.a(a).l},1,1,!0);
Q("false",2,!1,!1,function(){return!1},0);Q("floor",1,!1,!1,function(a,b){return Math.floor(J(b,a))},1);Q("id",4,!1,!1,function(a,b){var c=a.a,d=9==c.nodeType?c:c.ownerDocument;a=K(b,a).split(/\s+/);var e=[];q(a,function(g){g=d.getElementById(g);!g||0<=fa(e,g)||e.push(g)});e.sort(ua);var f=new D;q(e,function(g){f.add(g)});return f},1);Q("lang",2,!1,!1,function(){return!1},1);Q("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.f},0);
Q("local-name",3,!1,!0,function(a,b){return(a=b?Ca(b.a(a)):a.a)?a.localName||a.nodeName.toLowerCase():""},0,1,!0);Q("name",3,!1,!0,function(a,b){return(a=b?Ca(b.a(a)):a.a)?a.nodeName.toLowerCase():""},0,1,!0);Q("namespace-uri",3,!0,!1,function(){return""},0,1,!0);Q("normalize-space",3,!1,!0,function(a,b){return(b?K(b,a):z(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);Q("not",2,!1,!1,function(a,b){return!L(b,a)},1);Q("number",1,!1,!0,function(a,b){return b?J(b,a):+z(a.a)},0,1);
Q("position",1,!0,!1,function(a){return a.b},0);Q("round",1,!1,!1,function(a,b){return Math.round(J(b,a))},1);Q("starts-with",2,!1,!1,function(a,b,c){b=K(b,a);a=K(c,a);return 0==b.lastIndexOf(a,0)},2);Q("string",3,!1,!0,function(a,b){return b?K(b,a):z(a.a)},0,1);Q("string-length",1,!1,!0,function(a,b){return(b?K(b,a):z(a.a)).length},0,1);
Q("substring",3,!1,!1,function(a,b,c,d){c=J(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?J(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=K(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);Q("substring-after",3,!1,!1,function(a,b,c){b=K(b,a);a=K(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
Q("substring-before",3,!1,!1,function(a,b,c){b=K(b,a);a=K(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);Q("sum",1,!1,!1,function(a,b){a=F(b.a(a));b=0;for(var c=G(a);c;c=G(a))b+=+z(c);return b},1,1,!0);Q("translate",3,!1,!1,function(a,b,c,d){b=K(b,a);c=K(c,a);var e=K(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);Q("true",2,!1,!1,function(){return!0},0);function E(a,b){this.h=a;this.c=void 0!==b?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Pa(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}E.prototype.a=function(a){return null===this.b||this.b==a.nodeType};E.prototype.f=function(){return this.h};
E.prototype.toString=function(){var a="Kind Test: "+this.h;null===this.c||(a+=I(this.c));return a};function Qa(a){H.call(this,3);this.c=a.substring(1,a.length-1)}m(Qa,H);Qa.prototype.a=function(){return this.c};Qa.prototype.toString=function(){return"Literal: "+this.c};function R(a,b){this.j=a.toLowerCase();a="*"==this.j?"*":"http://www.w3.org/1999/xhtml";this.b=b?b.toLowerCase():a}R.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=void 0!==a.localName?a.localName:a.nodeName;return"*"!=this.j&&this.j!=b.toLowerCase()?!1:"*"==this.b?!0:this.b==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};R.prototype.f=function(){return this.j};
R.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.b?"":this.b+":")+this.j};function Ra(a){H.call(this,1);this.c=a}m(Ra,H);Ra.prototype.a=function(){return this.c};Ra.prototype.toString=function(){return"Number: "+this.c};function Sa(a,b){H.call(this,a.i);this.h=a;this.c=b;this.g=a.g;this.b=a.b;1==this.c.length&&(a=this.c[0],a.A||a.c!=Ta||(a=a.o,"*"!=a.f()&&(this.f={name:a.f(),u:null})))}m(Sa,H);function S(){H.call(this,4)}m(S,H);S.prototype.a=function(a){var b=new D;a=a.a;9==a.nodeType?b.add(a):b.add(a.ownerDocument);return b};S.prototype.toString=function(){return"Root Helper Expression"};function Ua(){H.call(this,4)}m(Ua,H);Ua.prototype.a=function(a){var b=new D;b.add(a.a);return b};Ua.prototype.toString=function(){return"Context Helper Expression"};
function Va(a){return"/"==a||"//"==a}Sa.prototype.a=function(a){var b=this.h.a(a);if(!(b instanceof D))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.l;c++){var e=a[c],f=F(b,e.c.s);if(e.g||e.c!=Wa)if(e.g||e.c!=Xa){var g=G(f);for(b=e.a(new p(g));null!=(g=G(f));)g=e.a(new p(g)),b=Aa(b,g)}else g=G(f),b=e.a(new p(g));else{for(g=G(f);(b=G(f))&&(!g.contains||g.contains(b))&&b.compareDocumentPosition(g)&8;g=b);b=e.a(new p(g))}}return b};
Sa.prototype.toString=function(){var a="Path Expression:"+I(this.h);if(this.c.length){var b=r(this.c,function(c,d){return c+I(d)},"Steps:");a+=I(b)}return a};function Ya(a,b){this.a=a;this.s=!!b}
function La(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=F(b),f=b.l,g,n=0;g=G(e);n++){var w=a.s?f-n:n+1;g=d.a(new p(g,w,f));if("number"==typeof g)w=w==g;else if("string"==typeof g||"boolean"==typeof g)w=!!g;else if(g instanceof D)w=0<g.l;else throw Error("Predicate.evaluate returned an unexpected type.");if(!w){w=e;g=w.f;var A=w.a;if(!A)throw Error("Next must be called at least once before remove.");var O=A.b;A=A.a;O?O.a=A:g.a=A;A?A.b=O:g.b=O;g.l--;w.a=null}}return b}
Ya.prototype.toString=function(){return r(this.a,function(a,b){return a+I(b)},"Predicates:")};function T(a,b,c,d){H.call(this,4);this.c=a;this.o=b;this.h=c||new Ya([]);this.A=!!d;b=this.h;b=0<b.a.length?b.a[0].f:null;a.J&&b&&(this.f={name:b.name,u:b.u});a:{a=this.h;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.g||1==c.i||0==c.i){a=!0;break a}a=!1}this.g=a}m(T,H);
T.prototype.a=function(a){var b=a.a,c=this.f,d=null,e=null,f=0;c&&(d=c.name,e=c.u?K(c.u,a):null,f=1);if(this.A)if(this.g||this.c!=Za)if(b=F((new T($a,new E("node"))).a(a)),c=G(b))for(a=this.m(c,d,e,f);null!=(c=G(b));)a=Aa(a,this.m(c,d,e,f));else a=new D;else a=C(this.o,b,d,e),a=La(this.h,a,f);else a=this.m(a.a,d,e,f);return a};T.prototype.m=function(a,b,c,d){a=this.c.v(this.o,a,b,c);return a=La(this.h,a,d)};
T.prototype.toString=function(){var a="Step:"+I("Operator: "+(this.A?"//":"/"));this.c.j&&(a+=I("Axis: "+this.c));a+=I(this.o);if(this.h.a.length){var b=r(this.h.a,function(c,d){return c+I(d)},"Predicates:");a+=I(b)}return a};function ab(a,b,c,d){this.j=a;this.v=b;this.s=c;this.J=d}ab.prototype.toString=function(){return this.j};var bb={};function U(a,b,c,d){if(bb.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new ab(a,b,c,!!d);return bb[a]=b}
U("ancestor",function(a,b){for(var c=new D;b=b.parentNode;)a.a(b)&&Ba(c,b);return c},!0);U("ancestor-or-self",function(a,b){var c=new D;do a.a(b)&&Ba(c,b);while(b=b.parentNode);return c},!0);
var Ta=U("attribute",function(a,b){var c=new D,d=a.f();if(b=b.attributes)if(a instanceof E&&null===a.b||"*"==d)for(a=0;d=b[a];a++)c.add(d);else(d=b.getNamedItem(d))&&c.add(d);return c},!1),Za=U("child",function(a,b,c,d,e){c=k(c)?c:null;d=k(d)?d:null;e=e||new D;for(b=b.firstChild;b;b=b.nextSibling)B(b,c,d)&&a.a(b)&&e.add(b);return e},!1,!0);U("descendant",C,!1,!0);
var $a=U("descendant-or-self",function(a,b,c,d){var e=new D;B(b,c,d)&&a.a(b)&&e.add(b);return C(a,b,c,d,e)},!1,!0),Wa=U("following",function(a,b,c,d){var e=new D;do for(var f=b;f=f.nextSibling;)B(f,c,d)&&a.a(f)&&e.add(f),e=C(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);U("following-sibling",function(a,b){for(var c=new D;b=b.nextSibling;)a.a(b)&&c.add(b);return c},!1);U("namespace",function(){return new D},!1);
var cb=U("parent",function(a,b){var c=new D;if(9==b.nodeType)return c;if(2==b.nodeType)return c.add(b.ownerElement),c;b=b.parentNode;a.a(b)&&c.add(b);return c},!1),Xa=U("preceding",function(a,b,c,d){var e=new D,f=[];do f.unshift(b);while(b=b.parentNode);for(var g=1,n=f.length;g<n;g++){var w=[];for(b=f[g];b=b.previousSibling;)w.unshift(b);for(var A=0,O=w.length;A<O;A++)b=w[A],B(b,c,d)&&a.a(b)&&e.add(b),e=C(a,b,c,d,e)}return e},!0,!0);
U("preceding-sibling",function(a,b){for(var c=new D;b=b.previousSibling;)a.a(b)&&Ba(c,b);return c},!0);var db=U("self",function(a,b){var c=new D;a.a(b)&&c.add(b);return c},!1);function eb(a){H.call(this,1);this.c=a;this.g=a.g;this.b=a.b}m(eb,H);eb.prototype.a=function(a){return-J(this.c,a)};eb.prototype.toString=function(){return"Unary Expression: -"+I(this.c)};function fb(a){H.call(this,4);this.c=a;Fa(this,t(this.c,function(b){return b.g}));Ga(this,t(this.c,function(b){return b.b}))}m(fb,H);fb.prototype.a=function(a){var b=new D;q(this.c,function(c){c=c.a(a);if(!(c instanceof D))throw Error("Path expression must evaluate to NodeSet.");b=Aa(b,c)});return b};fb.prototype.toString=function(){return r(this.c,function(a,b){return a+I(b)},"Union Expression:")};function gb(a,b){this.a=a;this.b=b}function hb(a){for(var b,c=[];;){V(a,"Missing right hand side of binary expression.");b=ib(a);var d=y(a.a);if(!d)break;var e=(d=Ja[d]||null)&&d.D;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].D;)b=new M(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new M(c.pop(),c.pop(),b);return b}function V(a,b){if(sa(a.a))throw Error(b);}function jb(a,b){a=y(a.a);if(a!=b)throw Error("Bad token, expected: "+b+" got: "+a);}
function kb(a){a=y(a.a);if(")"!=a)throw Error("Bad token: "+a);}function lb(a){a=y(a.a);if(2>a.length)throw Error("Unclosed literal string");return new Qa(a)}
function mb(a){var b=[];if(Va(x(a.a))){var c=y(a.a);var d=x(a.a);if("/"==c&&(sa(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new S;d=new S;V(a,"Missing next location step.");c=nb(a,c);b.push(c)}else{a:{c=x(a.a);d=c.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":y(a.a);c=hb(a);V(a,'unclosed "("');jb(a,")");break;case '"':case "'":c=lb(a);break;default:if(isNaN(+c))if(!Pa(c)&&/(?![0-9])[\w]/.test(d)&&"("==x(a.a,1)){c=y(a.a);
c=Oa[c]||null;y(a.a);for(d=[];")"!=x(a.a);){V(a,"Missing function argument list.");d.push(hb(a));if(","!=x(a.a))break;y(a.a)}V(a,"Unclosed function argument list.");kb(a);c=new Ma(c,d)}else{c=null;break a}else c=new Ra(+y(a.a))}"["==x(a.a)&&(d=new Ya(ob(a)),c=new Ka(c,d))}if(c)if(Va(x(a.a)))d=c;else return c;else c=nb(a,"/"),d=new Ua,b.push(c)}for(;Va(x(a.a));)c=y(a.a),V(a,"Missing next location step."),c=nb(a,c),b.push(c);return new Sa(d,b)}
function nb(a,b){if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==x(a.a)){var c=new T(db,new E("node"));y(a.a);return c}if(".."==x(a.a))return c=new T(cb,new E("node")),y(a.a),c;if("@"==x(a.a)){var d=Ta;y(a.a);V(a,"Missing attribute name")}else if("::"==x(a.a,1)){if(!/(?![0-9])[\w]/.test(x(a.a).charAt(0)))throw Error("Bad token: "+y(a.a));var e=y(a.a);d=bb[e]||null;if(!d)throw Error("No axis with name: "+e);y(a.a);V(a,"Missing node name")}else d=Za;e=x(a.a);if(/(?![0-9])[\w\*]/.test(e.charAt(0)))if("("==
x(a.a,1)){if(!Pa(e))throw Error("Invalid node type: "+e);e=y(a.a);if(!Pa(e))throw Error("Invalid type name: "+e);jb(a,"(");V(a,"Bad nodetype");var f=x(a.a).charAt(0),g=null;if('"'==f||"'"==f)g=lb(a);V(a,"Bad nodetype");kb(a);e=new E(e,g)}else if(e=y(a.a),f=e.indexOf(":"),-1==f)e=new R(e);else{g=e.substring(0,f);if("*"==g)var n="*";else if(n=a.b(g),!n)throw Error("Namespace prefix not declared: "+g);e=e.substr(f+1);e=new R(e,n)}else throw Error("Bad token: "+y(a.a));a=new Ya(ob(a),d.s);return c||new T(d,
e,a,"//"==b)}function ob(a){for(var b=[];"["==x(a.a);){y(a.a);V(a,"Missing predicate expression.");var c=hb(a);b.push(c);V(a,"Unclosed predicate expression.");jb(a,"]")}return b}function ib(a){if("-"==x(a.a))return y(a.a),new eb(ib(a));var b=mb(a);if("|"!=x(a.a))a=b;else{for(b=[b];"|"==y(a.a);)V(a,"Missing next union location path."),b.push(mb(a));a.a.a--;a=new fb(b)}return a};function pb(a){switch(a.nodeType){case 1:return ea(qb,a);case 9:return pb(a.documentElement);case 11:case 10:case 6:case 12:return rb;default:return a.parentNode?pb(a.parentNode):rb}}function rb(){return null}function qb(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?qb(a.parentNode,b):null};function sb(a,b){if(!a.length)throw Error("Empty XPath expression.");a=pa(a);if(sa(a))throw Error("Invalid XPath expression.");b?"function"==ba(b)||(b=l(b.lookupNamespaceURI,b)):b=function(){return null};var c=hb(new gb(a,b));if(!sa(a))throw Error("Bad token: "+y(a));this.evaluate=function(d,e){d=c.a(new p(d));return new W(d,e)}}
function W(a,b){if(0==b)if(a instanceof D)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof D))throw Error("value could not be converted to the specified type");this.resultType=b;switch(b){case 2:this.stringValue=a instanceof D?Da(a):""+a;break;case 1:this.numberValue=a instanceof D?+Da(a):+a;break;case 3:this.booleanValue=a instanceof D?0<a.l:!!a;break;case 4:case 5:case 6:case 7:var c=
F(a);var d=[];for(var e=G(c);e;e=G(c))d.push(e);this.snapshotLength=a.l;this.invalidIteratorState=!1;break;case 8:case 9:this.singleNodeValue=Ca(a);break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=d.length?null:d[f++]};this.snapshotItem=function(g){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return g>=d.length||0>g?null:d[g]}}W.ANY_TYPE=0;
W.NUMBER_TYPE=1;W.STRING_TYPE=2;W.BOOLEAN_TYPE=3;W.UNORDERED_NODE_ITERATOR_TYPE=4;W.ORDERED_NODE_ITERATOR_TYPE=5;W.UNORDERED_NODE_SNAPSHOT_TYPE=6;W.ORDERED_NODE_SNAPSHOT_TYPE=7;W.ANY_UNORDERED_NODE_TYPE=8;W.FIRST_ORDERED_NODE_TYPE=9;function tb(a){this.lookupNamespaceURI=pb(a)}
function ub(a,b){a=a||h;var c=a.Document&&a.Document.prototype||a.document;if(!c.evaluate||b)a.XPathResult=W,c.evaluate=function(d,e,f,g){return(new sb(d,f)).evaluate(e,g)},c.createExpression=function(d,e){return new sb(d,e)},c.createNSResolver=function(d){return new tb(d)}}aa("wgxpath.install",ub);aa("wgxpath.install",ub);var vb=la(),wb=na()||v("iPod"),xb=v("iPad"),yb=v("Android")&&!(ma()||la()||v("Opera")||v("Silk")),zb=ma(),Ab=v("Safari")&&!(ma()||v("Coast")||v("Opera")||v("Edge")||v("Edg/")||v("OPR")||la()||v("Silk")||v("Android"))&&!(na()||v("iPad")||v("iPod"));function X(a){return(a=a.exec(u))?a[1]:""}(function(){if(vb)return X(/Firefox\/([0-9.]+)/);if(zb)return na()||v("iPad")||v("iPod")?X(/CriOS\/([0-9.]+)/):X(/Chrome\/([0-9.]+)/);if(Ab&&!(na()||v("iPad")||v("iPod")))return X(/Version\/([0-9.]+)/);if(wb||xb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(u);if(a)return a[1]+"."+a[2]}else if(yb)return(a=X(/Android\s+([0-9.]+)/))?a:X(/Version\/([0-9.]+)/);return""})();function Bb(a){var b="tabindex";return"style"==b?Cb(a.style.cssText):(a=a.getAttributeNode(b))&&a.specified?a.value:null}var Db=/[;]+(?=(?:(?:[^"]*"){2})*[^"]*$)(?=(?:(?:[^']*'){2})*[^']*$)(?=(?:[^()]*\([^()]*\))*[^()]*$)/;function Cb(a){var b=[];q(a.split(Db),function(c){var d=c.indexOf(":");0<d&&(c=[c.slice(0,d),c.slice(d+1)],2==c.length&&b.push(c[0].toLowerCase(),":",c[1],";"))});b=b.join("");return b=";"==b.charAt(b.length-1)?b:b+";"}
function Y(a,b){b&&"string"!==typeof b&&(b=b.toString());return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)};var Eb="A AREA BUTTON INPUT LABEL SELECT TEXTAREA".split(" "),Fb="text search tel url email password number".split(" ");function Z(a,b){return Y(a,"INPUT")?a.type.toLowerCase()==b:!1}function Gb(a){function b(c){if("inherit"==c.contentEditable){for(c=c.parentNode;c&&1!=c.nodeType&&9!=c.nodeType&&11!=c.nodeType;)c=c.parentNode;return(c=Y(c)?c:null)?b(c):!1}return"true"==c.contentEditable}return void 0!==a.contentEditable?void 0!==a.isContentEditable?a.isContentEditable:b(a):!1}
function Hb(a){return((Y(a,"TEXTAREA")?!0:Y(a,"INPUT")?0<=fa(Fb,a.type.toLowerCase()):Gb(a)?!0:!1)||(Y(a,"INPUT")?"file"==a.type.toLowerCase():!1)||Z(a,"range")||Z(a,"date")||Z(a,"month")||Z(a,"week")||Z(a,"time")||Z(a,"datetime-local")||Z(a,"color"))&&!a.readOnly};aa("_",function(a){return t(Eb,function(b){return Y(a,b)})||null!=Bb(a)&&0<=Number(a.tabIndex)||Hb(a)});; return this._.apply(null,arguments);}).apply(window, arguments);}
