function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var f,k=this||self;function m(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a){var b=aa(a);return b=="array"||b=="object"&&typeof a.length=="number"};const ca=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(let c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},da=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){var c=a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},n=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,
b,void 0)}:function(a,b){var c=a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},ea=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){var c=a.length,d=typeof a==="string"?a.split(""):a;for(let e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0};function fa(a){var b=a.length;if(b>0){let c=Array(b);for(let d=0;d<b;d++)c[d]=a[d];return c}return[]};var ha={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",
darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",
ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};var la="backgroundColor borderTopColor borderRightColor borderBottomColor borderLeftColor color outlineColor".split(" "),ma=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,na=/^#(?:[0-9a-f]{3}){1,2}$/i,oa=/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,pa=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i;function r(a,b){this.code=a;this.state=u[a]||w;this.message=b||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(b<0||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}(function(){function a(){}a.prototype=Error.prototype;r.prototype=new a;r.prototype.constructor=r})();var w="unknown error",u={15:"element not selectable",11:"element not visible"};u[31]=w;u[30]=w;
u[24]="invalid cookie domain";u[29]="invalid element coordinates";u[12]="invalid element state";u[32]="invalid selector";u[51]="invalid selector";u[52]="invalid selector";u[17]="javascript error";u[405]="unsupported operation";u[34]="move target out of bounds";u[27]="no such alert";u[7]="no such element";u[8]="no such frame";u[23]="no such window";u[28]="script timeout";u[33]="session not created";u[10]="stale element reference";u[21]="timeout";u[25]="unable to set cookie";u[26]="unexpected alert open";
u[13]=w;u[9]="unknown command";r.prototype.toString=function(){return this.name+": "+this.message};var qa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var z=class{constructor(a){if(x!==x)throw Error("SafeUrl is not meant to be built directly");this.l=a}toString(){return this.l.toString()}},x={};new z("about:invalid#zClosurez");new z("about:blank");const B={};class ra{constructor(){if(B!==B)throw Error("SafeStyle is not meant to be built directly");this.j=""}toString(){return this.j.toString()}}new ra;const C={};class sa{constructor(){if(C!==C)throw Error("SafeStyleSheet is not meant to be built directly");this.i=""}toString(){return this.i.toString()}}new sa;function D(){var a=k.navigator;return a&&(a=a.userAgent)?a:""}function E(a){return D().indexOf(a)!=-1};function F(){return E("Firefox")||E("FxiOS")}function G(){return(E("Chrome")||E("CriOS"))&&!E("Edge")||E("Silk")};const ta={};class ua{constructor(){var a=k.trustedTypes&&k.trustedTypes.emptyHTML||"";if(ta!==ta)throw Error("SafeHtml is not meant to be built directly");this.h=a}toString(){return this.h.toString()}}new ua;function va(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};function H(){return E("iPhone")&&!E("iPod")&&!E("iPad")};var wa=F(),xa=H()||E("iPod"),ya=E("iPad"),za=E("Android")&&!(G()||F()||E("Opera")||E("Silk")),Aa=G(),Ba=E("Safari")&&!(G()||E("Coast")||E("Opera")||E("Edge")||E("Edg/")||E("OPR")||F()||E("Silk")||E("Android"))&&!(H()||E("iPad")||E("iPod"));function I(a){return(a=a.exec(D()))?a[1]:""}(function(){if(wa)return I(/Firefox\/([0-9.]+)/);if(Aa){if(H()||E("iPad")||E("iPod")||E("Macintosh")){var a=I(/CriOS\/([0-9.]+)/);if(a)return a}return I(/Chrome\/([0-9.]+)/)}if(Ba&&!(H()||E("iPad")||E("iPod")))return I(/Version\/([0-9.]+)/);if(xa||ya){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(D()))return a[1]+"."+a[2]}else if(za)return(a=I(/Android\s+([0-9.]+)/))?a:I(/Version\/([0-9.]+)/);return""})();function J(a,b){this.x=a!==void 0?a:0;this.y=b!==void 0?b:0}f=J.prototype;f.clone=function(){return new J(this.x,this.y)};f.toString=function(){return"("+this.x+", "+this.y+")"};f.equals=function(a){return a instanceof J&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};f.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};f.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
f.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};f.translate=function(a,b){a instanceof J?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),typeof b==="number"&&(this.y+=b));return this};f.scale=function(a,b){this.x*=a;this.y*=typeof b==="number"?b:a;return this};function K(a,b){this.width=a;this.height=b}f=K.prototype;f.clone=function(){return new K(this.width,this.height)};f.toString=function(){return"("+this.width+" x "+this.height+")"};f.aspectRatio=function(){return this.width/this.height};f.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};f.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
f.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};f.scale=function(a,b){this.width*=a;this.height*=typeof b==="number"?b:a;return this};function Ca(a,b,c){function d(l){l&&b.appendChild(typeof l==="string"?a.createTextNode(l):l)}for(var e=1;e<c.length;e++){var g=c[e];if(!ba(g)||m(g)&&g.nodeType>0)d(g);else{a:{if(g&&typeof g.length=="number"){if(m(g)){var h=typeof g.item=="function"||typeof g.item=="string";break a}if(typeof g==="function"){h=typeof g.item=="function";break a}}h=!1}da(h?fa(g):g,d)}}}function Da(a){for(;a&&a.nodeType!=1;)a=a.previousSibling;return a}function L(a){return a.nodeType==9?a:a.ownerDocument||a.document}
function Ea(a,b,c){a&&!c&&(a=a.parentNode);for(c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function Fa(a){this.g=a||k.document||document}f=Fa.prototype;f.getElementsByTagName=function(a,b){return(b||this.g).getElementsByTagName(String(a))};f.createElement=function(a){var b=this.g;a=String(a);b.contentType==="application/xhtml+xml"&&(a=a.toLowerCase());return b.createElement(a)};f.createTextNode=function(a){return this.g.createTextNode(String(a))};f.appendChild=function(a,b){a.appendChild(b)};
f.append=function(a,b){Ca(L(a),a,arguments)};f.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
f.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};f.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function M(a,b){b&&typeof b!=="string"&&(b=b.toString());return a instanceof HTMLFormElement?!!a&&a.nodeType==1&&(!b||"FORM"==b):!!a&&a.nodeType==1&&(!b||a.tagName.toUpperCase()==b)};function O(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}f=O.prototype;f.clone=function(){return new O(this.top,this.right,this.bottom,this.left)};f.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};f.contains=function(a){return this&&a?a instanceof O?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
f.expand=function(a,b,c,d){m(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=Number(b),this.bottom+=Number(c),this.left-=Number(d));return this};f.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
f.translate=function(a,b){a instanceof J?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,typeof b==="number"&&(this.top+=b,this.bottom+=b));return this};f.scale=function(a,b){b=typeof b==="number"?b:a;this.left*=a;this.right*=a;this.top*=b;this.bottom*=b;return this};function P(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}f=P.prototype;f.clone=function(){return new P(this.left,this.top,this.width,this.height)};f.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
f.intersection=function(a){var b=Math.max(this.left,a.left),c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top);a=Math.min(this.top+this.height,a.top+a.height);if(d<=a)return this.left=b,this.top=d,this.width=c-b,this.height=a-d,!0}return!1};
f.difference=function(a){b:{var b=Math.max(this.left,a.left);var c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top),e=Math.min(this.top+this.height,a.top+a.height);if(d<=e){b=new P(b,d,c-b,e-d);break b}}b=null}if(b&&b.height&&b.width){b=[];c=this.top;d=this.height;e=this.left+this.width;var g=this.top+this.height,h=a.left+a.width,l=a.top+a.height;a.top>this.top&&(b.push(new P(this.left,this.top,this.width,a.top-this.top)),c=a.top,d-=a.top-this.top);l<g&&(b.push(new P(this.left,
l,this.width,g-l)),d=l-c);a.left>this.left&&b.push(new P(this.left,c,a.left-this.left,d));h<e&&b.push(new P(h,c,e-h,d));a=b}else a=[this.clone()];return a};f.contains=function(a){return a instanceof J?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};f.getSize=function(){return new K(this.width,this.height)};
f.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};f.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};f.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
f.translate=function(a,b){a instanceof J?(this.left+=a.x,this.top+=a.y):(this.left+=a,typeof b==="number"&&(this.top+=b));return this};f.scale=function(a,b){b=typeof b==="number"?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};var Ga=typeof ShadowRoot==="function",Ha="BUTTON INPUT OPTGROUP OPTION SELECT TEXTAREA".split(" ");function Ia(a){return n(Ha,function(b){return M(a,b)})?a.disabled?!1:a.parentNode&&a.parentNode.nodeType==1&&M(a,"OPTGROUP")||M(a,"OPTION")?Ia(a.parentNode):!Ea(a,function(b){var c=b.parentNode;if(c&&M(c,"FIELDSET")&&c.disabled){if(!M(b,"LEGEND"))return!0;for(;b=b.previousElementSibling!==void 0?b.previousElementSibling:Da(b.previousSibling);)if(M(b,"LEGEND"))return!0}return!1},!0):!0}
function Q(a){for(a=a.parentNode;a&&a.nodeType!=1&&a.nodeType!=9&&a.nodeType!=11;)a=a.parentNode;return M(a)?a:null}
function R(a,b){b=va(b);if(b=="float"||b=="cssFloat"||b=="styleFloat")b="cssFloat";a:{var c=b;var d=L(a);if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(a,null))){c=d[c]||d.getPropertyValue(c)||"";break a}c=""}a=c||Ja(a,b);if(a===null)a=null;else if(ca(la,b)>=0){b:{var e=a.match(oa);if(e&&(b=Number(e[1]),c=Number(e[2]),d=Number(e[3]),e=Number(e[4]),b>=0&&b<=255&&c>=0&&c<=255&&d>=0&&d<=255&&e>=0&&e<=1)){b=[b,c,d,e];break b}b=null}if(!b)b:{if(d=a.match(pa))if(b=Number(d[1]),
c=Number(d[2]),d=Number(d[3]),b>=0&&b<=255&&c>=0&&c<=255&&d>=0&&d<=255){b=[b,c,d,1];break b}b=null}if(!b)b:{b=a.toLowerCase();c=ha[b.toLowerCase()];if(!c&&(c=b.charAt(0)=="#"?b:"#"+b,c.length==4&&(c=c.replace(ma,"#$1$1$2$2$3$3")),!na.test(c))){b=null;break b}b=[parseInt(c.substr(1,2),16),parseInt(c.substr(3,2),16),parseInt(c.substr(5,2),16),1]}a=b?"rgba("+b.join(", ")+")":a}return a}
function Ja(a,b){var c=a.currentStyle||a.style,d=c[b];d===void 0&&typeof c.getPropertyValue==="function"&&(d=c.getPropertyValue(b));return d!="inherit"?d!==void 0?d:null:(a=Q(a))?Ja(a,b):null}
function S(a,b,c){function d(h){var l=T(h);if(l.height>0&&l.width>0)return!0;if(M(h,"PATH")&&(l.height>0||l.width>0))return h=R(h,"stroke-width"),!!h&&parseInt(h,10)>0;l=R(h,"visibility");return l!="collapse"&&l!="hidden"&&c(h)?R(h,"overflow")!="hidden"&&n(h.childNodes,function(y){return y.nodeType==3?(y=y.nodeValue,/^[\s]*$/.test(y)&&/[\n\r\t]/.test(y)?!1:!0):M(y)&&d(y)}):!1}function e(h){return V(h)==W&&ea(h.childNodes,function(l){return!M(l)||e(l)||!d(l)})}if(!M(a))throw Error("Argument to isShown must be of type Element");
if(M(a,"BODY"))return!0;if(M(a,"OPTION")||M(a,"OPTGROUP"))return a=Ea(a,function(h){return M(h,"SELECT")}),!!a&&S(a,!0,c);var g=Ka(a);if(g)return!!g.image&&g.rect.width>0&&g.rect.height>0&&S(g.image,b,c);if(M(a,"INPUT")&&a.type.toLowerCase()=="hidden"||M(a,"NOSCRIPT"))return!1;g=R(a,"visibility");return g!="collapse"&&g!="hidden"&&c(a)&&(b||La(a)!=0)&&d(a)?!e(a):!1}
function Ma(a){function b(c){if(M(c)&&(R(c,"display")=="none"||R(c,"content-visibility")=="hidden"))return!1;var d;a:if((d=c.parentNode)&&d.shadowRoot&&c.assignedSlot!==void 0)d=c.assignedSlot?c.assignedSlot.parentNode:null;else if(c.getDestinationInsertionPoints){var e=c.getDestinationInsertionPoints();if(e.length>0){d=e[e.length-1];break a}}if(Ga&&d instanceof ShadowRoot){if(d.host.shadowRoot&&d.host.shadowRoot!==d)return!1;d=d.host}return!d||d.nodeType!=9&&d.nodeType!=11?d&&M(d,"DETAILS")&&!d.open&&
!M(c,"SUMMARY")?!1:!!d&&b(d):!0}return S(a,!0,b)}var W="hidden";
function V(a){function b(p){function q(U){if(U==h)return!0;var ia=R(U,"display");return ia.lastIndexOf("inline",0)==0||ia=="contents"||ja=="absolute"&&R(U,"position")=="static"?!1:!0}var ja=R(p,"position");if(ja=="fixed")return ka=!0,p==h?null:h;for(p=Q(p);p&&!q(p);)p=Q(p);return p}function c(p){var q=p;if(y=="visible")if(p==h&&l)q=l;else if(p==l)return{x:"visible",y:"visible"};q={x:R(q,"overflow-x"),y:R(q,"overflow-y")};p==h&&(q.x=q.x=="visible"?"auto":q.x,q.y=q.y=="visible"?"auto":q.y);return q}
function d(p){if(p==h){var q=(new Fa(g)).g;p=q.scrollingElement?q.scrollingElement:q.body||q.documentElement;q=q.parentWindow||q.defaultView;p=new J(q.pageXOffset||p.scrollLeft,q.pageYOffset||p.scrollTop)}else p=new J(p.scrollLeft,p.scrollTop);return p}var e=Na(a),g=L(a),h=g.documentElement,l=g.body,y=R(h,"overflow"),ka;for(a=b(a);a;a=b(a)){var t=c(a);if(t.x!="visible"||t.y!="visible"){var v=T(a);if(v.width==0||v.height==0)return W;var A=e.right<v.left,N=e.bottom<v.top;if(A&&t.x=="hidden"||N&&t.y==
"hidden")return W;if(A&&t.x!="visible"||N&&t.y!="visible"){A=d(a);N=e.bottom<v.top-A.y;if(e.right<v.left-A.x&&t.x!="visible"||N&&t.x!="visible")return W;e=V(a);return e==W?W:"scroll"}A=e.left>=v.left+v.width;v=e.top>=v.top+v.height;if(A&&t.x=="hidden"||v&&t.y=="hidden")return W;if(A&&t.x!="visible"||v&&t.y!="visible"){if(ka&&(t=d(a),e.left>=h.scrollWidth-t.x||e.right>=h.scrollHeight-t.y))return W;e=V(a);return e==W?W:"scroll"}}}return"none"}
function T(a){var b=Ka(a);if(b)return b.rect;if(M(a,"HTML"))return a=L(a),a=((a?a.parentWindow||a.defaultView:window)||window).document,a=a.compatMode=="CSS1Compat"?a.documentElement:a.body,a=new K(a.clientWidth,a.clientHeight),new P(0,0,a.width,a.height);try{var c=a.getBoundingClientRect()}catch(d){return new P(0,0,0,0)}return new P(c.left,c.top,c.right-c.left,c.bottom-c.top)}
function Ka(a){var b=M(a,"MAP");if(!b&&!M(a,"AREA"))return null;var c=b?a:M(a.parentNode,"MAP")?a.parentNode:null,d=null,e=null;if(c&&c.name){d='*[usemap="#'+c.name+'"]';c=L(c);if(!d)throw new r(32,"No selector specified");d=qa(d);try{var g=c.querySelector(d)}catch(h){throw new r(32,"An invalid or illegal selector was specified");}if(d=g&&g.nodeType==1?g:null)e=T(d),b||a.shape.toLowerCase()=="default"||(a=Oa(a),b=Math.min(Math.max(a.left,0),e.width),g=Math.min(Math.max(a.top,0),e.height),e=new P(b+
e.left,g+e.top,Math.min(a.width,e.width-b),Math.min(a.height,e.height-g)))}return{image:d,rect:e||new P(0,0,0,0)}}
function Oa(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if(b=="rect"&&a.length==4){b=a[0];var c=a[1];return new P(b,c,a[2]-b,a[3]-c)}if(b=="circle"&&a.length==3)return b=a[2],new P(a[0]-b,a[1]-b,2*b,2*b);if(b=="poly"&&a.length>2){b=a[0];c=a[1];for(var d=b,e=c,g=2;g+1<a.length;g+=2)b=Math.min(b,a[g]),d=Math.max(d,a[g]),c=Math.min(c,a[g+1]),e=Math.max(e,a[g+1]);return new P(b,c,d-b,e-c)}return new P(0,0,0,0)}function Na(a){a=T(a);return new O(a.top,a.left+a.width,a.top+a.height,a.left)}
function La(a){var b=1,c=R(a,"opacity");c&&(b=Number(c));(a=Q(a))&&(b*=La(a));return b};function Pa(a){return Ma(a)&&Ia(a)&&R(a,"pointer-events")!="none"}var X=["se_exportedFunctionSymbol"],Y=k;X[0]in Y||typeof Y.execScript=="undefined"||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||Pa===void 0?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=Pa;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
