function(){return function(){var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ca(a,b){if(b){for(var c=ba,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&aa(c,d,{configurable:!0,writable:!0,value:f})}}
ca("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=c),a>>>=1)c+=c;return d}});ca("Math.sign",function(a){return a?a:function(a){a=Number(a);return!a||isNaN(a)?a:0<a?1:-1}});var g=this;
function da(a,b){var c=a.split("."),d=g;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function l(a){return"string"==typeof a}function fa(a,b,c){return a.call.apply(a.bind,arguments)}function ga(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}
function ha(a,b,c){ha=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?fa:ga;return ha.apply(null,arguments)}function ia(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}
function m(a){var b=n;function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.J=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};var ja=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
function ka(a,b){for(var c=0,d=ja(String(a)).split("."),e=ja(String(b)).split("."),f=Math.max(d.length,e.length),h=0;!c&&h<f;h++){var k=d[h]||"",r=e[h]||"",w=RegExp("(\\d*)(\\D*)","g"),M=RegExp("(\\d*)(\\D*)","g");do{var X=w.exec(k)||["","",""],Y=M.exec(r)||["","",""];if(0==X[0].length&&0==Y[0].length)break;c=la(0==X[1].length?0:parseInt(X[1],10),0==Y[1].length?0:parseInt(Y[1],10))||la(0==X[2].length,0==Y[2].length)||la(X[2],Y[2])}while(!c)}return c}function la(a,b){return a<b?-1:a>b?1:0};function p(a,b){for(var c=a.length,d=l(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)}function ma(a,b){for(var c=a.length,d=[],e=0,f=l(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d}function q(a,b,c){var d=c;p(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}function na(a,b){for(var c=a.length,d=l(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1}
function oa(a,b){var c;a:{c=a.length;for(var d=l(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:l(a)?a.charAt(c):a[c]}function pa(a){return Array.prototype.concat.apply(Array.prototype,arguments)}function qa(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var t;a:{var ra=g.navigator;if(ra){var sa=ra.userAgent;if(sa){t=sa;break a}}t=""}function u(a){return-1!=t.indexOf(a)};function ta(){return u("Opera")||u("OPR")}function ua(){return(u("Chrome")||u("CriOS"))&&!ta()&&!u("Edge")};function va(){return u("iPhone")&&!u("iPod")&&!u("iPad")};var wa=ta(),v=u("Trident")||u("MSIE"),xa=u("Edge"),x=u("Gecko")&&!(-1!=t.toLowerCase().indexOf("webkit")&&!u("Edge"))&&!(u("Trident")||u("MSIE"))&&!u("Edge"),ya=-1!=t.toLowerCase().indexOf("webkit")&&!u("Edge"),za=u("Macintosh"),Aa=u("Windows");function Ba(){var a=t;if(x)return/rv\:([^\);]+)(\)|;)/.exec(a);if(xa)return/Edge\/([\d\.]+)/.exec(a);if(v)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ya)return/WebKit\/(\S+)/.exec(a)}function Ca(){var a=g.document;return a?a.documentMode:void 0}
var Da=function(){if(wa&&g.opera){var a;var b=g.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Ba())&&(a=b?b[1]:"");return v&&(b=Ca(),null!=b&&b>parseFloat(a))?String(b):a}(),Ea={};function Fa(a){return Ea[a]||(Ea[a]=0<=ka(Da,a))}var Ga=g.document,y=Ga&&v?Ca()||("CSS1Compat"==Ga.compatMode?parseInt(Da,10):5):void 0;var Ha=u("Firefox"),Ia=va()||u("iPod"),Ja=u("iPad"),z=u("Android")&&!(ua()||u("Firefox")||ta()||u("Silk")),Ka=ua(),La=u("Safari")&&!(ua()||u("Coast")||ta()||u("Edge")||u("Silk")||u("Android"))&&!(va()||u("iPad")||u("iPod"));function Ma(a){return(a=a.exec(t))?a[1]:""}var Na=function(){if(Ha)return Ma(/Firefox\/([0-9.]+)/);if(v||xa||wa)return Da;if(Ka)return Ma(/Chrome\/([0-9.]+)/);if(La&&!(va()||u("iPad")||u("iPod")))return Ma(/Version\/([0-9.]+)/);if(Ia||Ja){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(t);if(a)return a[1]+"."+a[2]}else if(z)return(a=Ma(/Android\s+([0-9.]+)/))?a:Ma(/Version\/([0-9.]+)/);return""}();var Oa,Pa;function Qa(a){return Ra?Oa(a):v?0<=ka(y,a):Fa(a)}function Sa(a){Ra?Pa(a):z?ka(Ta,a):ka(Na,a)}
var Ra=function(){if(!x)return!1;var a=g.Components;if(!a)return!1;try{if(!a.classes)return!1}catch(f){return!1}var b=a.classes,a=a.interfaces,c=b["@mozilla.org/xpcom/version-comparator;1"].getService(a.nsIVersionComparator),b=b["@mozilla.org/xre/app-info;1"].getService(a.nsIXULAppInfo),d=b.platformVersion,e=b.version;Oa=function(a){return 0<=c.compare(d,""+a)};Pa=function(a){c.compare(e,""+a)};return!0}(),Ua;if(z){var Va=/Android\s+([0-9\.]+)/.exec(t);Ua=Va?Va[1]:"0"}else Ua="0";var Ta=Ua;z&&Sa(2.3);
z&&Sa(4);La&&Sa(6);!x&&!v||v&&9<=Number(y)||x&&Fa("1.9.1");v&&Fa("9");function Wa(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function Xa(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(v&&!(9<=Number(y))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Ya(a,b):!c&&Wa(e,b)?-1*Za(a,b):!d&&Wa(f,a)?Za(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=9==a.nodeType?
a:a.ownerDocument||a.document;c=d.createRange();c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(g.Range.START_TO_END,d)}function Za(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return Ya(d,a)}function Ya(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1};/*

 The MIT License

 Copyright (c) 2007 Cybozu Labs, Inc.
 Copyright (c) 2012 Google Inc.

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to
 deal in the Software without restriction, including without limitation the
 rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 IN THE SOFTWARE.
*/
function A(a,b,c){this.a=a;this.b=b||1;this.h=c||1};var B=v&&!(9<=Number(y)),$a=v&&!(8<=Number(y));function C(a,b,c,d){this.a=a;this.nodeName=c;this.nodeValue=d;this.nodeType=2;this.parentNode=this.ownerElement=b}function ab(a,b){var c=$a&&"href"==b.nodeName?a.getAttribute(b.nodeName,2):b.nodeValue;return new C(b,a,b.nodeName,c)};function bb(a){this.b=a;this.a=0}function cb(a){a=a.match(db);for(var b=0;b<a.length;b++)eb.test(a[b])&&a.splice(b,1);return new bb(a)}var db=RegExp("\\$?(?:(?![0-9-\\.])(?:\\*|[\\w-\\.]+):)?(?![0-9-\\.])(?:\\*|[\\w-\\.]+)|\\/\\/|\\.\\.|::|\\d+(?:\\.\\d*)?|\\.\\d+|\"[^\"]*\"|'[^']*'|[!<>]=|\\s+|.","g"),eb=/^\s/;function D(a,b){return a.b[a.a+(b||0)]}bb.prototype.next=function(){return this.b[this.a++]};function fb(a){return a.b.length<=a.a};function E(a){var b=null,c=a.nodeType;1==c&&(b=a.textContent,b=void 0==b||null==b?a.innerText:b,b=void 0==b||null==b?"":b);if("string"!=typeof b)if(B&&"title"==a.nodeName.toLowerCase()&&1==c)b=a.text;else if(9==c||1==c){a=9==c?a.documentElement:a.firstChild;for(var c=0,d=[],b="";a;){do 1!=a.nodeType&&(b+=a.nodeValue),B&&"title"==a.nodeName.toLowerCase()&&(b+=a.text),d[c++]=a;while(a=a.firstChild);for(;c&&!(a=d[--c].nextSibling););}}else b=a.nodeValue;return""+b}
function F(a,b,c){if(null===b)return!0;try{if(!a.getAttribute)return!1}catch(d){return!1}$a&&"class"==b&&(b="className");return null==c?!!a.getAttribute(b):a.getAttribute(b,2)==c}function gb(a,b,c,d,e){return(B?hb:ib).call(null,a,b,l(c)?c:null,l(d)?d:null,e||new G)}
function hb(a,b,c,d,e){if(a instanceof H||8==a.b||c&&null===a.b){var f=b.all;if(!f)return e;a=jb(a);if("*"!=a&&(f=b.getElementsByTagName(a),!f))return e;if(c){for(var h=[],k=0;b=f[k++];)F(b,c,d)&&h.push(b);f=h}for(k=0;b=f[k++];)"*"==a&&"!"==b.tagName||I(e,b);return e}kb(a,b,c,d,e);return e}
function ib(a,b,c,d,e){b.getElementsByName&&d&&"name"==c&&!v?(b=b.getElementsByName(d),p(b,function(b){a.a(b)&&I(e,b)})):b.getElementsByClassName&&d&&"class"==c?(b=b.getElementsByClassName(d),p(b,function(b){b.className==d&&a.a(b)&&I(e,b)})):a instanceof J?kb(a,b,c,d,e):b.getElementsByTagName&&(b=b.getElementsByTagName(a.h()),p(b,function(a){F(a,c,d)&&I(e,a)}));return e}
function lb(a,b,c,d,e){var f;if((a instanceof H||8==a.b||c&&null===a.b)&&(f=b.childNodes)){var h=jb(a);if("*"!=h&&(f=ma(f,function(a){return a.tagName&&a.tagName.toLowerCase()==h}),!f))return e;c&&(f=ma(f,function(a){return F(a,c,d)}));p(f,function(a){"*"==h&&("!"==a.tagName||"*"==h&&1!=a.nodeType)||I(e,a)});return e}return mb(a,b,c,d,e)}function mb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)F(b,c,d)&&a.a(b)&&I(e,b);return e}
function kb(a,b,c,d,e){for(b=b.firstChild;b;b=b.nextSibling)F(b,c,d)&&a.a(b)&&I(e,b),kb(a,b,c,d,e)}function jb(a){if(a instanceof J){if(8==a.b)return"!";if(null===a.b)return"*"}return a.h()};function G(){this.b=this.a=null;this.s=0}function nb(a){this.node=a;this.next=this.a=null}function ob(a,b){if(!a.a)return b;if(!b.a)return a;for(var c=a.a,d=b.a,e=null,f,h=0;c&&d;){f=c.node;var k=d.node;f==k||f instanceof C&&k instanceof C&&f.a==k.a?(f=c,c=c.next,d=d.next):0<Xa(c.node,d.node)?(f=d,d=d.next):(f=c,c=c.next);(f.a=e)?e.next=f:a.a=f;e=f;h++}for(f=c||d;f;)f.a=e,e=e.next=f,h++,f=f.next;a.b=e;a.s=h;return a}
G.prototype.unshift=function(a){a=new nb(a);a.next=this.a;this.b?this.a.a=a:this.a=this.b=a;this.a=a;this.s++};function I(a,b){var c=new nb(b);c.a=a.b;a.a?a.b.next=c:a.a=a.b=c;a.b=c;a.s++}function pb(a){return(a=a.a)?a.node:null}function qb(a){return(a=pb(a))?E(a):""}G.prototype.iterator=function(a){return new rb(this,!!a)};function rb(a,b){this.h=a;this.b=(this.c=b)?a.b:a.a;this.a=null}rb.prototype.next=function(){var a=this.b;if(a){var b=this.a=a;this.b=this.c?a.a:a.next;return b.node}return null};function n(a){this.m=a;this.b=this.i=!1;this.h=null}function K(a){return"\n  "+a.toString().split("\n").join("\n  ")}function sb(a,b){a.i=b}function tb(a,b){a.b=b}function L(a,b){var c=a.a(b);return c instanceof G?+qb(c):+c}function N(a,b){var c=a.a(b);return c instanceof G?qb(c):""+c}function O(a,b){var c=a.a(b);return c instanceof G?!!c.s:!!c};function ub(a,b,c){n.call(this,a.m);this.c=a;this.j=b;this.w=c;this.i=b.i||c.i;this.b=b.b||c.b;this.c==vb&&(c.b||c.i||4==c.m||0==c.m||!b.h?b.b||b.i||4==b.m||0==b.m||!c.h||(this.h={name:c.h.name,A:b}):this.h={name:b.h.name,A:c})}m(ub);
function P(a,b,c,d,e){b=b.a(d);c=c.a(d);var f;if(b instanceof G&&c instanceof G){b=b.iterator();for(d=b.next();d;d=b.next())for(e=c.iterator(),f=e.next();f;f=e.next())if(a(E(d),E(f)))return!0;return!1}if(b instanceof G||c instanceof G){b instanceof G?(e=b,d=c):(e=c,d=b);f=e.iterator();for(var h=typeof d,k=f.next();k;k=f.next()){switch(h){case "number":k=+E(k);break;case "boolean":k=!!E(k);break;case "string":k=E(k);break;default:throw Error("Illegal primitive type for comparison.");}if(e==b&&a(k,
d)||e==c&&a(d,k))return!0}return!1}return e?"boolean"==typeof b||"boolean"==typeof c?a(!!b,!!c):"number"==typeof b||"number"==typeof c?a(+b,+c):a(b,c):a(+b,+c)}ub.prototype.a=function(a){return this.c.v(this.j,this.w,a)};ub.prototype.toString=function(){var a="Binary Expression: "+this.c,a=a+K(this.j);return a+=K(this.w)};function wb(a,b,c,d){this.a=a;this.D=b;this.m=c;this.v=d}wb.prototype.toString=function(){return this.a};var xb={};
function Q(a,b,c,d){if(xb.hasOwnProperty(a))throw Error("Binary operator already created: "+a);a=new wb(a,b,c,d);return xb[a.toString()]=a}Q("div",6,1,function(a,b,c){return L(a,c)/L(b,c)});Q("mod",6,1,function(a,b,c){return L(a,c)%L(b,c)});Q("*",6,1,function(a,b,c){return L(a,c)*L(b,c)});Q("+",5,1,function(a,b,c){return L(a,c)+L(b,c)});Q("-",5,1,function(a,b,c){return L(a,c)-L(b,c)});Q("<",4,2,function(a,b,c){return P(function(a,b){return a<b},a,b,c)});
Q(">",4,2,function(a,b,c){return P(function(a,b){return a>b},a,b,c)});Q("<=",4,2,function(a,b,c){return P(function(a,b){return a<=b},a,b,c)});Q(">=",4,2,function(a,b,c){return P(function(a,b){return a>=b},a,b,c)});var vb=Q("=",3,2,function(a,b,c){return P(function(a,b){return a==b},a,b,c,!0)});Q("!=",3,2,function(a,b,c){return P(function(a,b){return a!=b},a,b,c,!0)});Q("and",2,2,function(a,b,c){return O(a,c)&&O(b,c)});Q("or",1,2,function(a,b,c){return O(a,c)||O(b,c)});function yb(a,b){if(b.a.length&&4!=a.m)throw Error("Primary expression must evaluate to nodeset if filter has predicate(s).");n.call(this,a.m);this.c=a;this.j=b;this.i=a.i;this.b=a.b}m(yb);yb.prototype.a=function(a){a=this.c.a(a);return zb(this.j,a)};yb.prototype.toString=function(){var a;a="Filter:"+K(this.c);return a+=K(this.j)};function Ab(a,b){if(b.length<a.F)throw Error("Function "+a.o+" expects at least"+a.F+" arguments, "+b.length+" given");if(null!==a.C&&b.length>a.C)throw Error("Function "+a.o+" expects at most "+a.C+" arguments, "+b.length+" given");a.G&&p(b,function(b,d){if(4!=b.m)throw Error("Argument "+d+" to function "+a.o+" is not of type Nodeset: "+b);});n.call(this,a.m);this.j=a;this.c=b;sb(this,a.i||na(b,function(a){return a.i}));tb(this,a.I&&!b.length||a.H&&!!b.length||na(b,function(a){return a.b}))}m(Ab);
Ab.prototype.a=function(a){return this.j.v.apply(null,pa(a,this.c))};Ab.prototype.toString=function(){var a="Function: "+this.j;if(this.c.length)var b=q(this.c,function(a,b){return a+K(b)},"Arguments:"),a=a+K(b);return a};function Bb(a,b,c,d,e,f,h,k,r){this.o=a;this.m=b;this.i=c;this.I=d;this.H=e;this.v=f;this.F=h;this.C=void 0!==k?k:h;this.G=!!r}Bb.prototype.toString=function(){return this.o};var Cb={};
function R(a,b,c,d,e,f,h,k){if(Cb.hasOwnProperty(a))throw Error("Function already created: "+a+".");Cb[a]=new Bb(a,b,c,d,!1,e,f,h,k)}R("boolean",2,!1,!1,function(a,b){return O(b,a)},1);R("ceiling",1,!1,!1,function(a,b){return Math.ceil(L(b,a))},1);R("concat",3,!1,!1,function(a,b){return q(qa(arguments,1),function(b,d){return b+N(d,a)},"")},2,null);R("contains",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return-1!=b.indexOf(a)},2);R("count",1,!1,!1,function(a,b){return b.a(a).s},1,1,!0);
R("false",2,!1,!1,function(){return!1},0);R("floor",1,!1,!1,function(a,b){return Math.floor(L(b,a))},1);
R("id",4,!1,!1,function(a,b){function c(a){if(B){var b=e.all[a];if(b){if(b.nodeType&&a==b.id)return b;if(b.length)return oa(b,function(b){return a==b.id})}return null}return e.getElementById(a)}var d=a.a,e=9==d.nodeType?d:d.ownerDocument,d=N(b,a).split(/\s+/),f=[];p(d,function(a){a=c(a);var b;if(!(b=!a)){a:if(l(f))b=l(a)&&1==a.length?f.indexOf(a,0):-1;else{for(b=0;b<f.length;b++)if(b in f&&f[b]===a)break a;b=-1}b=0<=b}b||f.push(a)});f.sort(Xa);var h=new G;p(f,function(a){I(h,a)});return h},1);
R("lang",2,!1,!1,function(){return!1},1);R("last",1,!0,!1,function(a){if(1!=arguments.length)throw Error("Function last expects ()");return a.h},0);R("local-name",3,!1,!0,function(a,b){var c=b?pb(b.a(a)):a.a;return c?c.localName||c.nodeName.toLowerCase():""},0,1,!0);R("name",3,!1,!0,function(a,b){var c=b?pb(b.a(a)):a.a;return c?c.nodeName.toLowerCase():""},0,1,!0);R("namespace-uri",3,!0,!1,function(){return""},0,1,!0);
R("normalize-space",3,!1,!0,function(a,b){return(b?N(b,a):E(a.a)).replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")},0,1);R("not",2,!1,!1,function(a,b){return!O(b,a)},1);R("number",1,!1,!0,function(a,b){return b?L(b,a):+E(a.a)},0,1);R("position",1,!0,!1,function(a){return a.b},0);R("round",1,!1,!1,function(a,b){return Math.round(L(b,a))},1);R("starts-with",2,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);return!b.lastIndexOf(a,0)},2);R("string",3,!1,!0,function(a,b){return b?N(b,a):E(a.a)},0,1);
R("string-length",1,!1,!0,function(a,b){return(b?N(b,a):E(a.a)).length},0,1);R("substring",3,!1,!1,function(a,b,c,d){c=L(c,a);if(isNaN(c)||Infinity==c||-Infinity==c)return"";d=d?L(d,a):Infinity;if(isNaN(d)||-Infinity===d)return"";c=Math.round(c)-1;var e=Math.max(c,0);a=N(b,a);return Infinity==d?a.substring(e):a.substring(e,c+Math.round(d))},2,3);R("substring-after",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);c=b.indexOf(a);return-1==c?"":b.substring(c+a.length)},2);
R("substring-before",3,!1,!1,function(a,b,c){b=N(b,a);a=N(c,a);a=b.indexOf(a);return-1==a?"":b.substring(0,a)},2);R("sum",1,!1,!1,function(a,b){for(var c=b.a(a).iterator(),d=0,e=c.next();e;e=c.next())d+=+E(e);return d},1,1,!0);R("translate",3,!1,!1,function(a,b,c,d){b=N(b,a);c=N(c,a);var e=N(d,a);a={};for(d=0;d<c.length;d++){var f=c.charAt(d);f in a||(a[f]=e.charAt(d))}c="";for(d=0;d<b.length;d++)f=b.charAt(d),c+=f in a?a[f]:f;return c},3);R("true",2,!1,!1,function(){return!0},0);function J(a,b){this.j=a;this.c=b?b:null;this.b=null;switch(a){case "comment":this.b=8;break;case "text":this.b=3;break;case "processing-instruction":this.b=7;break;case "node":break;default:throw Error("Unexpected argument");}}function Db(a){return"comment"==a||"text"==a||"processing-instruction"==a||"node"==a}J.prototype.a=function(a){return null===this.b||this.b==a.nodeType};J.prototype.h=function(){return this.j};
J.prototype.toString=function(){var a="Kind Test: "+this.j;!this.c||(a+=K(this.c));return a};function Eb(a){n.call(this,3);this.c=a.substring(1,a.length-1)}m(Eb);Eb.prototype.a=function(){return this.c};Eb.prototype.toString=function(){return"Literal: "+this.c};function H(a,b){this.o=a.toLowerCase();var c;c="*"==this.o?"*":"http://www.w3.org/1999/xhtml";this.c=b?b.toLowerCase():c}H.prototype.a=function(a){var b=a.nodeType;if(1!=b&&2!=b)return!1;b=void 0!==a.localName?a.localName:a.nodeName;return"*"!=this.o&&this.o!=b.toLowerCase()?!1:"*"==this.c?!0:this.c==(a.namespaceURI?a.namespaceURI.toLowerCase():"http://www.w3.org/1999/xhtml")};H.prototype.h=function(){return this.o};
H.prototype.toString=function(){return"Name Test: "+("http://www.w3.org/1999/xhtml"==this.c?"":this.c+":")+this.o};function Fb(a){n.call(this,1);this.c=a}m(Fb);Fb.prototype.a=function(){return this.c};Fb.prototype.toString=function(){return"Number: "+this.c};function Gb(a,b){n.call(this,a.m);this.j=a;this.c=b;this.i=a.i;this.b=a.b;if(1==this.c.length){var c=this.c[0];c.B||c.c!=Hb||(c=c.w,"*"!=c.h()&&(this.h={name:c.h(),A:null}))}}m(Gb);function Ib(){n.call(this,4)}m(Ib);Ib.prototype.a=function(a){var b=new G;a=a.a;9==a.nodeType?I(b,a):I(b,a.ownerDocument);return b};Ib.prototype.toString=function(){return"Root Helper Expression"};function Jb(){n.call(this,4)}m(Jb);Jb.prototype.a=function(a){var b=new G;I(b,a.a);return b};Jb.prototype.toString=function(){return"Context Helper Expression"};
function Kb(a){return"/"==a||"//"==a}Gb.prototype.a=function(a){var b=this.j.a(a);if(!(b instanceof G))throw Error("Filter expression must evaluate to nodeset.");a=this.c;for(var c=0,d=a.length;c<d&&b.s;c++){var e=a[c],f=b.iterator(e.c.a),h;if(e.i||e.c!=Lb)if(e.i||e.c!=Mb)for(h=f.next(),b=e.a(new A(h));h=f.next();)h=e.a(new A(h)),b=ob(b,h);else h=f.next(),b=e.a(new A(h));else{for(h=f.next();(b=f.next())&&(!h.contains||h.contains(b))&&b.compareDocumentPosition(h)&8;h=b);b=e.a(new A(h))}}return b};
Gb.prototype.toString=function(){var a;a="Path Expression:"+K(this.j);if(this.c.length){var b=q(this.c,function(a,b){return a+K(b)},"Steps:");a+=K(b)}return a};function Nb(a,b){this.a=a;this.b=!!b}
function zb(a,b,c){for(c=c||0;c<a.a.length;c++)for(var d=a.a[c],e=b.iterator(),f=b.s,h,k=0;h=e.next();k++){var r=a.b?f-k:k+1;h=d.a(new A(h,r,f));if("number"==typeof h)r=r==h;else if("string"==typeof h||"boolean"==typeof h)r=!!h;else if(h instanceof G)r=0<h.s;else throw Error("Predicate.evaluate returned an unexpected type.");if(!r){r=e;h=r.h;var w=r.a;if(!w)throw Error("Next must be called at least once before remove.");var M=w.a,w=w.next;M?M.next=w:h.a=w;w?w.a=M:h.b=M;h.s--;r.a=null}}return b}
Nb.prototype.toString=function(){return q(this.a,function(a,b){return a+K(b)},"Predicates:")};function S(a,b,c,d){n.call(this,4);this.c=a;this.w=b;this.j=c||new Nb([]);this.B=!!d;b=this.j;b=0<b.a.length?b.a[0].h:null;a.b&&b&&(a=b.name,a=B?a.toLowerCase():a,this.h={name:a,A:b.A});a:{a=this.j;for(b=0;b<a.a.length;b++)if(c=a.a[b],c.i||1==c.m||0==c.m){a=!0;break a}a=!1}this.i=a}m(S);
S.prototype.a=function(a){var b=a.a,c=this.h,d=null,e=null,f=0;c&&(d=c.name,e=c.A?N(c.A,a):null,f=1);if(this.B)if(this.i||this.c!=Ob)if(b=(new S(Pb,new J("node"))).a(a).iterator(),c=b.next())for(a=this.v(c,d,e,f);c=b.next();)a=ob(a,this.v(c,d,e,f));else a=new G;else a=gb(this.w,b,d,e),a=zb(this.j,a,f);else a=this.v(a.a,d,e,f);return a};S.prototype.v=function(a,b,c,d){a=this.c.h(this.w,a,b,c);return a=zb(this.j,a,d)};
S.prototype.toString=function(){var a;a="Step:"+K("Operator: "+(this.B?"//":"/"));this.c.o&&(a+=K("Axis: "+this.c));a+=K(this.w);if(this.j.a.length){var b=q(this.j.a,function(a,b){return a+K(b)},"Predicates:");a+=K(b)}return a};function Qb(a,b,c,d){this.o=a;this.h=b;this.a=c;this.b=d}Qb.prototype.toString=function(){return this.o};var Rb={};function T(a,b,c,d){if(Rb.hasOwnProperty(a))throw Error("Axis already created: "+a);b=new Qb(a,b,c,!!d);return Rb[a]=b}
T("ancestor",function(a,b){for(var c=new G,d=b;d=d.parentNode;)a.a(d)&&c.unshift(d);return c},!0);T("ancestor-or-self",function(a,b){var c=new G,d=b;do a.a(d)&&c.unshift(d);while(d=d.parentNode);return c},!0);
var Hb=T("attribute",function(a,b){var c=new G,d=a.h();if("style"==d&&B&&b.style)return I(c,new C(b.style,b,"style",b.style.cssText)),c;var e=b.attributes;if(e)if(a instanceof J&&null===a.b||"*"==d)for(var d=0,f;f=e[d];d++)B?f.nodeValue&&I(c,ab(b,f)):I(c,f);else(f=e.getNamedItem(d))&&(B?f.nodeValue&&I(c,ab(b,f)):I(c,f));return c},!1),Ob=T("child",function(a,b,c,d,e){return(B?lb:mb).call(null,a,b,l(c)?c:null,l(d)?d:null,e||new G)},!1,!0);T("descendant",gb,!1,!0);
var Pb=T("descendant-or-self",function(a,b,c,d){var e=new G;F(b,c,d)&&a.a(b)&&I(e,b);return gb(a,b,c,d,e)},!1,!0),Lb=T("following",function(a,b,c,d){var e=new G;do for(var f=b;f=f.nextSibling;)F(f,c,d)&&a.a(f)&&I(e,f),e=gb(a,f,c,d,e);while(b=b.parentNode);return e},!1,!0);T("following-sibling",function(a,b){for(var c=new G,d=b;d=d.nextSibling;)a.a(d)&&I(c,d);return c},!1);T("namespace",function(){return new G},!1);
var Sb=T("parent",function(a,b){var c=new G;if(9==b.nodeType)return c;if(2==b.nodeType)return I(c,b.ownerElement),c;var d=b.parentNode;a.a(d)&&I(c,d);return c},!1),Mb=T("preceding",function(a,b,c,d){var e=new G,f=[];do f.unshift(b);while(b=b.parentNode);for(var h=1,k=f.length;h<k;h++){var r=[];for(b=f[h];b=b.previousSibling;)r.unshift(b);for(var w=0,M=r.length;w<M;w++)b=r[w],F(b,c,d)&&a.a(b)&&I(e,b),e=gb(a,b,c,d,e)}return e},!0,!0);
T("preceding-sibling",function(a,b){for(var c=new G,d=b;d=d.previousSibling;)a.a(d)&&c.unshift(d);return c},!0);var Tb=T("self",function(a,b){var c=new G;a.a(b)&&I(c,b);return c},!1);function Ub(a){n.call(this,1);this.c=a;this.i=a.i;this.b=a.b}m(Ub);Ub.prototype.a=function(a){return-L(this.c,a)};Ub.prototype.toString=function(){return"Unary Expression: -"+K(this.c)};function Vb(a){n.call(this,4);this.c=a;sb(this,na(this.c,function(a){return a.i}));tb(this,na(this.c,function(a){return a.b}))}m(Vb);Vb.prototype.a=function(a){var b=new G;p(this.c,function(c){c=c.a(a);if(!(c instanceof G))throw Error("Path expression must evaluate to NodeSet.");b=ob(b,c)});return b};Vb.prototype.toString=function(){return q(this.c,function(a,b){return a+K(b)},"Union Expression:")};function Wb(a,b){this.a=a;this.b=b}function Xb(a){for(var b,c=[];;){U(a,"Missing right hand side of binary expression.");b=Yb(a);var d=a.a.next();if(!d)break;var e=(d=xb[d]||null)&&d.D;if(!e){a.a.a--;break}for(;c.length&&e<=c[c.length-1].D;)b=new ub(c.pop(),c.pop(),b);c.push(b,d)}for(;c.length;)b=new ub(c.pop(),c.pop(),b);return b}function U(a,b){if(fb(a.a))throw Error(b);}function Zb(a,b){var c=a.a.next();if(c!=b)throw Error("Bad token, expected: "+b+" got: "+c);}
function $b(a){a=a.a.next();if(")"!=a)throw Error("Bad token: "+a);}function ac(a){a=a.a.next();if(2>a.length)throw Error("Unclosed literal string");return new Eb(a)}
function bc(a){var b,c=[],d;if(Kb(D(a.a))){b=a.a.next();d=D(a.a);if("/"==b&&(fb(a.a)||"."!=d&&".."!=d&&"@"!=d&&"*"!=d&&!/(?![0-9])[\w]/.test(d)))return new Ib;d=new Ib;U(a,"Missing next location step.");b=cc(a,b);c.push(b)}else{a:{b=D(a.a);d=b.charAt(0);switch(d){case "$":throw Error("Variable reference not allowed in HTML XPath");case "(":a.a.next();b=Xb(a);U(a,'unclosed "("');Zb(a,")");break;case '"':case "'":b=ac(a);break;default:if(isNaN(+b))if(!Db(b)&&/(?![0-9])[\w]/.test(d)&&"("==D(a.a,1)){b=
a.a.next();b=Cb[b]||null;a.a.next();for(d=[];")"!=D(a.a);){U(a,"Missing function argument list.");d.push(Xb(a));if(","!=D(a.a))break;a.a.next()}U(a,"Unclosed function argument list.");$b(a);b=new Ab(b,d)}else{b=null;break a}else b=new Fb(+a.a.next())}"["==D(a.a)&&(d=new Nb(dc(a)),b=new yb(b,d))}if(b)if(Kb(D(a.a)))d=b;else return b;else b=cc(a,"/"),d=new Jb,c.push(b)}for(;Kb(D(a.a));)b=a.a.next(),U(a,"Missing next location step."),b=cc(a,b),c.push(b);return new Gb(d,c)}
function cc(a,b){var c,d,e;if("/"!=b&&"//"!=b)throw Error('Step op should be "/" or "//"');if("."==D(a.a))return d=new S(Tb,new J("node")),a.a.next(),d;if(".."==D(a.a))return d=new S(Sb,new J("node")),a.a.next(),d;var f;if("@"==D(a.a))f=Hb,a.a.next(),U(a,"Missing attribute name");else if("::"==D(a.a,1)){if(!/(?![0-9])[\w]/.test(D(a.a).charAt(0)))throw Error("Bad token: "+a.a.next());c=a.a.next();f=Rb[c]||null;if(!f)throw Error("No axis with name: "+c);a.a.next();U(a,"Missing node name")}else f=Ob;
c=D(a.a);if(/(?![0-9])[\w\*]/.test(c.charAt(0)))if("("==D(a.a,1)){if(!Db(c))throw Error("Invalid node type: "+c);c=a.a.next();if(!Db(c))throw Error("Invalid type name: "+c);Zb(a,"(");U(a,"Bad nodetype");e=D(a.a).charAt(0);var h=null;if('"'==e||"'"==e)h=ac(a);U(a,"Bad nodetype");$b(a);c=new J(c,h)}else if(c=a.a.next(),e=c.indexOf(":"),-1==e)c=new H(c);else{var h=c.substring(0,e),k;if("*"==h)k="*";else if(k=a.b(h),!k)throw Error("Namespace prefix not declared: "+h);c=c.substr(e+1);c=new H(c,k)}else throw Error("Bad token: "+
a.a.next());e=new Nb(dc(a),f.a);return d||new S(f,c,e,"//"==b)}function dc(a){for(var b=[];"["==D(a.a);){a.a.next();U(a,"Missing predicate expression.");var c=Xb(a);b.push(c);U(a,"Unclosed predicate expression.");Zb(a,"]")}return b}function Yb(a){if("-"==D(a.a))return a.a.next(),new Ub(Yb(a));var b=bc(a);if("|"!=D(a.a))a=b;else{for(b=[b];"|"==a.a.next();)U(a,"Missing next union location path."),b.push(bc(a));a.a.a--;a=new Vb(b)}return a};function ec(a){switch(a.nodeType){case 1:return ia(fc,a);case 9:return ec(a.documentElement);case 11:case 10:case 6:case 12:return gc;default:return a.parentNode?ec(a.parentNode):gc}}function gc(){return null}function fc(a,b){if(a.prefix==b)return a.namespaceURI||"http://www.w3.org/1999/xhtml";var c=a.getAttributeNode("xmlns:"+b);return c&&c.specified?c.value||null:a.parentNode&&9!=a.parentNode.nodeType?fc(a.parentNode,b):null};function hc(a,b){if(!a.length)throw Error("Empty XPath expression.");var c=cb(a);if(fb(c))throw Error("Invalid XPath expression.");b?"function"==ea(b)||(b=ha(b.lookupNamespaceURI,b)):b=function(){return null};var d=Xb(new Wb(c,b));if(!fb(c))throw Error("Bad token: "+c.next());this.evaluate=function(a,b){var c=d.a(new A(a));return new V(c,b)}}
function V(a,b){if(!b)if(a instanceof G)b=4;else if("string"==typeof a)b=2;else if("number"==typeof a)b=1;else if("boolean"==typeof a)b=3;else throw Error("Unexpected evaluation result.");if(2!=b&&1!=b&&3!=b&&!(a instanceof G))throw Error("value could not be converted to the specified type");this.resultType=b;var c;switch(b){case 2:this.stringValue=a instanceof G?qb(a):""+a;break;case 1:this.numberValue=a instanceof G?+qb(a):+a;break;case 3:this.booleanValue=a instanceof G?0<a.s:!!a;break;case 4:case 5:case 6:case 7:var d=
a.iterator();c=[];for(var e=d.next();e;e=d.next())c.push(e instanceof C?e.a:e);this.snapshotLength=a.s;this.invalidIteratorState=!1;break;case 8:case 9:d=pb(a);this.singleNodeValue=d instanceof C?d.a:d;break;default:throw Error("Unknown XPathResult type.");}var f=0;this.iterateNext=function(){if(4!=b&&5!=b)throw Error("iterateNext called with wrong result type");return f>=c.length?null:c[f++]};this.snapshotItem=function(a){if(6!=b&&7!=b)throw Error("snapshotItem called with wrong result type");return a>=
c.length||0>a?null:c[a]}}V.ANY_TYPE=0;V.NUMBER_TYPE=1;V.STRING_TYPE=2;V.BOOLEAN_TYPE=3;V.UNORDERED_NODE_ITERATOR_TYPE=4;V.ORDERED_NODE_ITERATOR_TYPE=5;V.UNORDERED_NODE_SNAPSHOT_TYPE=6;V.ORDERED_NODE_SNAPSHOT_TYPE=7;V.ANY_UNORDERED_NODE_TYPE=8;V.FIRST_ORDERED_NODE_TYPE=9;function ic(a){this.lookupNamespaceURI=ec(a)}
da("wgxpath.install",function(a,b){var c=a||g,d=c.Document&&c.Document.prototype||c.document;if(!d.evaluate||b)c.XPathResult=V,d.evaluate=function(a,b,c,d){return(new hc(a,c)).evaluate(b,d)},d.createExpression=function(a,b){return new hc(a,b)},d.createNSResolver=function(a){return new ic(a)}});ya||Ra&&Sa(3.6);v&&Qa(10);z&&Sa(4);function W(a,b){this.u={};this.l=[];this.a=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){var e;if(a instanceof W)for(d=jc(a),kc(a),e=[],c=0;c<a.l.length;c++)e.push(a.u[a.l[c]]);else{var c=[],f=0;for(d in a)c[f++]=d;d=c;c=[];f=0;for(e in a)c[f++]=a[e];e=c}for(c=0;c<d.length;c++)this.set(d[c],e[c])}}function jc(a){kc(a);return a.l.concat()}
W.prototype.clear=function(){this.u={};this.a=this.l.length=0};function kc(a){if(a.a!=a.l.length){for(var b=0,c=0;b<a.l.length;){var d=a.l[b];Object.prototype.hasOwnProperty.call(a.u,d)&&(a.l[c++]=d);b++}a.l.length=c}if(a.a!=a.l.length){for(var e={},c=b=0;b<a.l.length;)d=a.l[b],Object.prototype.hasOwnProperty.call(e,d)||(a.l[c++]=d,e[d]=1),b++;a.l.length=c}}W.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.u,a)?this.u[a]:b};
W.prototype.set=function(a,b){Object.prototype.hasOwnProperty.call(this.u,a)||(this.a++,this.l.push(a));this.u[a]=b};W.prototype.forEach=function(a,b){for(var c=jc(this),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};W.prototype.clone=function(){return new W(this)};var lc={};function Z(a,b,c){var d=typeof a;("object"==d&&null!=a||"function"==d)&&(a=x?a.f:a.g);a=new mc(a);!b||b in lc&&!c||(lc[b]={key:a,shift:!1},c&&(lc[c]={key:a,shift:!0}));return a}function mc(a){this.code=a}Z(8);Z(9);Z(13);var nc=Z(16),oc=Z(17),pc=Z(18);Z(19);Z(20);Z(27);Z(32," ");Z(33);Z(34);Z(35);Z(36);Z(37);Z(38);Z(39);Z(40);Z(44);Z(45);Z(46);Z(48,"0",")");Z(49,"1","!");Z(50,"2","@");Z(51,"3","#");Z(52,"4","$");Z(53,"5","%");Z(54,"6","^");Z(55,"7","&");Z(56,"8","*");Z(57,"9","(");
Z(65,"a","A");Z(66,"b","B");Z(67,"c","C");Z(68,"d","D");Z(69,"e","E");Z(70,"f","F");Z(71,"g","G");Z(72,"h","H");Z(73,"i","I");Z(74,"j","J");Z(75,"k","K");Z(76,"l","L");Z(77,"m","M");Z(78,"n","N");Z(79,"o","O");Z(80,"p","P");Z(81,"q","Q");Z(82,"r","R");Z(83,"s","S");Z(84,"t","T");Z(85,"u","U");Z(86,"v","V");Z(87,"w","W");Z(88,"x","X");Z(89,"y","Y");Z(90,"z","Z");var qc=Z(Aa?{f:91,g:91}:za?{f:224,g:91}:{f:0,g:91});Z(Aa?{f:92,g:92}:za?{f:224,g:93}:{f:0,g:92});Z(Aa?{f:93,g:93}:za?{f:0,g:0}:{f:93,g:null});
Z({f:96,g:96},"0");Z({f:97,g:97},"1");Z({f:98,g:98},"2");Z({f:99,g:99},"3");Z({f:100,g:100},"4");Z({f:101,g:101},"5");Z({f:102,g:102},"6");Z({f:103,g:103},"7");Z({f:104,g:104},"8");Z({f:105,g:105},"9");Z({f:106,g:106},"*");Z({f:107,g:107},"+");Z({f:109,g:109},"-");Z({f:110,g:110},".");Z({f:111,g:111},"/");Z(144);Z(112);Z(113);Z(114);Z(115);Z(116);Z(117);Z(118);Z(119);Z(120);Z(121);Z(122);Z(123);Z({f:107,g:187},"=","+");Z(108,",");Z({f:109,g:189},"-","_");Z(188,",","<");Z(190,".",">");Z(191,"/","?");
Z(192,"`","~");Z(219,"[","{");Z(220,"\\","|");Z(221,"]","}");Z({f:59,g:186},";",":");Z(222,"'",'"');var rc=new W;rc.set(1,nc);rc.set(2,oc);rc.set(4,pc);rc.set(8,qc);(function(a){var b=new W;p(jc(a),function(c){b.set(a.get(c).code,c)});return b})(rc);x&&Qa(12);ya||x&&Qa(3.5)||v&&Qa(8);da("_",function(){return JSON.stringify({status:0,value:window.location.reload()})});; return this._.apply(null,arguments);}.apply({navigator:typeof window!=undefined?window.navigator:null,document:typeof window!=undefined?window.document:null}, arguments);}
