function(){return (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var e=this||self;try{var f=window}catch(a){f=e};function k(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}
function l(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function m(a){var b=l(a);return b=="array"||b=="object"&&typeof a.length=="number"};function p(a,b){this.code=a;this.state=q[a]||r;this.message=b||"";a=this.state.replace(/((?:^|\s+)[a-z])/g,function(c){return c.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(b<0||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}(function(){function a(){}a.prototype=Error.prototype;p.prototype=new a;p.prototype.constructor=p})();var r="unknown error",q={15:"element not selectable",11:"element not visible"};q[31]=r;q[30]=r;
q[24]="invalid cookie domain";q[29]="invalid element coordinates";q[12]="invalid element state";q[32]="invalid selector";q[51]="invalid selector";q[52]="invalid selector";q[17]="javascript error";q[405]="unsupported operation";q[34]="move target out of bounds";q[27]="no such alert";q[7]="no such element";q[8]="no such frame";q[23]="no such window";q[28]="script timeout";q[33]="session not created";q[10]="stale element reference";q[21]="timeout";q[25]="unable to set cookie";q[26]="unexpected alert open";
q[13]=r;q[9]="unknown command";p.prototype.toString=function(){return this.name+": "+this.message};var u=class{constructor(a){if(t!==t)throw Error("SafeUrl is not meant to be built directly");this.m=a}toString(){return this.m.toString()}},t={};new u("about:invalid#zClosurez");new u("about:blank");const w={};class x{constructor(){if(w!==w)throw Error("SafeStyle is not meant to be built directly");this.l=""}toString(){return this.l.toString()}}new x;function y(a,b){var c={};for(let d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c}function z(a,b){var c={};for(let d in a)c[d]=b.call(void 0,a[d],d,a);return c}function A(a){var b=0;for(let c in a)b++;return b}function B(a,b){return a!==null&&b in a}function C(a,b){for(let c in a)if(b.call(void 0,a[c],c,a))return c};const D={};class E{constructor(){if(D!==D)throw Error("SafeStyleSheet is not meant to be built directly");this.j=""}toString(){return this.j.toString()}}new E;function F(){var a=e.navigator;return a&&(a=a.userAgent)?a:""}function G(a){return F().indexOf(a)!=-1};function H(){return G("Firefox")||G("FxiOS")}function I(){return(G("Chrome")||G("CriOS"))&&!G("Edge")||G("Silk")};const J=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){var c=a.length,d=Array(c),h=typeof a==="string"?a.split(""):a;for(let g=0;g<c;g++)g in h&&(d[g]=b.call(void 0,h[g],g,a));return d};const K={};class L{constructor(){var a=e.trustedTypes&&e.trustedTypes.emptyHTML||"";if(K!==K)throw Error("SafeHtml is not meant to be built directly");this.i=a}toString(){return this.i.toString()}}new L;function M(){return G("iPhone")&&!G("iPod")&&!G("iPad")};var N=H(),O=M()||G("iPod"),aa=G("iPad"),ba=G("Android")&&!(I()||H()||G("Opera")||G("Silk")),ca=I(),da=G("Safari")&&!(I()||G("Coast")||G("Opera")||G("Edge")||G("Edg/")||G("OPR")||H()||G("Silk")||G("Android"))&&!(M()||G("iPad")||G("iPod"));function P(a){return(a=a.exec(F()))?a[1]:""}(function(){if(N)return P(/Firefox\/([0-9.]+)/);if(ca){if(M()||G("iPad")||G("iPod")||G("Macintosh")){var a=P(/CriOS\/([0-9.]+)/);if(a)return a}return P(/Chrome\/([0-9.]+)/)}if(da&&!(M()||G("iPad")||G("iPod")))return P(/Version\/([0-9.]+)/);if(O||aa){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(F()))return a[1]+"."+a[2]}else if(ba)return(a=P(/Android\s+([0-9.]+)/))?a:P(/Version\/([0-9.]+)/);return""})();var ea=JSON.stringify;function fa(a){function b(c,d){switch(l(c)){case "string":case "number":case "boolean":return c;case "function":return c.toString();case "array":return J(c,function(g){return b(g,d)});case "object":if(d.indexOf(c)>=0)throw new p(17,"Recursive object cannot be transferred");if(B(c,"nodeType")&&(c.nodeType==1||c.nodeType==9)){var h={};c=Q(c);h.ELEMENT=c;h["element-6066-11e4-a52e-4f735466cecf"]=c;return h}if(B(c,"document"))return h={},h.WINDOW=Q(c),h;d.push(c);if(m(c))return J(c,function(g){return b(g,
d)});h=y(c,function(g,n){return typeof n==="number"||typeof n==="string"});return z(h,function(g){return b(g,d)});default:return null}}return b(a,[])}function R(a,b){return Array.isArray(a)?J(a,function(c){return R(c,b)}):k(a)?typeof a=="function"?a:B(a,"ELEMENT")?S(a.ELEMENT,b):B(a,"element-6066-11e4-a52e-4f735466cecf")?S(a["element-6066-11e4-a52e-4f735466cecf"],b):B(a,"WINDOW")?S(a.WINDOW,b):z(a,function(c){return R(c,b)}):a}
function T(a){a=a||document;var b=a.$wdc_;b||(b=a.$wdc_={},b.h=Date.now());b.h||(b.h=Date.now());return b}function U(a,b){if(B(b,"setInterval"))return!!b.closed;for(;b;){if(b==a.documentElement)return!1;b.host&&b.nodeType===11&&(b=b.host);b=b.parentNode}return!0}function ha(a){var b=T(a),c;for(c in b){var d=b[c];d&&typeof d==="object"&&U(a,d)&&delete b[c]}}
function Q(a){var b=T(a.ownerDocument);A(b)-1>=200&&ha(a.ownerDocument);var c=C(b,function(d){return d==a});c||(c=":wdc:"+b.h++,b[c]=a);return c}function S(a,b){a=decodeURIComponent(a);b=b||document;var c=T(b);if(!B(c,a))throw new p(10,"Element does not exist in cache");var d=c[a];if(!U(b,d))return d;delete c[a];if(B(d,"setInterval"))throw new p(23,"Window has been closed.");throw new p(10,"Element is no longer attached to the DOM");};function V(a){this.g=a}V.prototype.setItem=function(a,b){try{this.g.setItem(a,b+"")}catch(c){throw new p(13,c.message);}};V.prototype.getItem=function(a){return this.g.getItem(a)};V.prototype.removeItem=function(a){var b=this.getItem(a);this.g.removeItem(a);return b};V.prototype.clear=function(){this.g.clear()};V.prototype.size=function(){return this.g.length};V.prototype.key=function(a){return this.g.key(a)};function ia(a){var b;var c=(b=f)||f;if(c.sessionStorage!=null&&c.sessionStorage.clear!=null)b=new V(b.sessionStorage);else throw new p(13,"Session storage undefined");return b.removeItem(a)};function W(a){a=[a];var b=ia,c=window||f;try{a:{var d=b;if(typeof d==="string")try{b=new c.Function(d);break a}catch(v){throw v;}b=c==window?d:new c.Function("return ("+d+").apply(null,arguments);")}var h=R(a,c.document),g=b.apply(null,h);var n={status:0,value:fa(g)}}catch(v){n=B(v,"code")?v.code:13,n={status:n,value:{message:v.message,error:q[n]||r}}}return ea(n)}var X=["se_exportedFunctionSymbol"],Y=e;X[0]in Y||typeof Y.execScript=="undefined"||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||W===void 0?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=W;; return this.se_exportedFunctionSymbol.apply(null,arguments);}).apply(window, arguments);}
