import type {StringRecord} from '@appium/types';

// WebDriver's "release all modifiers" key. Deliberately absent from VIRTUAL_KEYS below -
// it isn't typed, it's a signal to clear sticky modifier state.
export const NULL_KEY = '\ue000';

// WebDriver PUA-encoded key -> [Automation virtual key name, sticky modifier it represents (if any)].
export const VIRTUAL_KEYS: StringRecord<[string, string | null]> = {
  '\ue001': ['Cancel', null],
  '\ue002': ['Help', null],
  '\ue003': ['Backspace', null],
  '\ue004': ['Tab', null],
  '\ue005': ['Clear', null],
  '\ue006': ['Return', null],
  '\ue007': ['Enter', null],
  '\ue008': ['Shift', 'SHIFT'],
  '\ue050': ['Shift', 'SHIFT'],
  '\ue009': ['Control', 'CONTROL'],
  '\ue051': ['Control', 'CONTROL'],
  '\ue00a': ['Alternate', 'ALT'],
  '\ue052': ['Alternate', 'ALT'],
  '\ue00b': ['Pause', null],
  '\ue00c': ['Escape', null],
  '\ue00d': ['Space', null],
  '\ue00e': ['PageUp', null],
  '\ue054': ['PageUp', null],
  '\ue00f': ['PageDown', null],
  '\ue055': ['PageDown', null],
  '\ue010': ['End', null],
  '\ue056': ['End', null],
  '\ue011': ['Home', null],
  '\ue057': ['Home', null],
  '\ue012': ['LeftArrow', null],
  '\ue058': ['LeftArrow', null],
  '\ue013': ['UpArrow', null],
  '\ue059': ['UpArrow', null],
  '\ue014': ['RightArrow', null],
  '\ue05a': ['RightArrow', null],
  '\ue015': ['DownArrow', null],
  '\ue05b': ['DownArrow', null],
  '\ue016': ['Insert', null],
  '\ue05c': ['Insert', null],
  '\ue017': ['Delete', null],
  '\ue05d': ['Delete', null],
  '\ue018': ['Semicolon', null],
  '\ue019': ['Equals', null],
  '\ue01a': ['NumberPad0', null],
  '\ue01b': ['NumberPad1', null],
  '\ue01c': ['NumberPad2', null],
  '\ue01d': ['NumberPad3', null],
  '\ue01e': ['NumberPad4', null],
  '\ue01f': ['NumberPad5', null],
  '\ue020': ['NumberPad6', null],
  '\ue021': ['NumberPad7', null],
  '\ue022': ['NumberPad8', null],
  '\ue023': ['NumberPad9', null],
  '\ue024': ['NumberPadMultiply', null],
  '\ue025': ['NumberPadAdd', null],
  '\ue026': ['NumberPadSeparator', null],
  '\ue027': ['NumberPadSubtract', null],
  '\ue028': ['NumberPadDecimal', null],
  '\ue029': ['NumberPadDivide', null],
  '\ue031': ['Function1', null],
  '\ue032': ['Function2', null],
  '\ue033': ['Function3', null],
  '\ue034': ['Function4', null],
  '\ue035': ['Function5', null],
  '\ue036': ['Function6', null],
  '\ue037': ['Function7', null],
  '\ue038': ['Function8', null],
  '\ue039': ['Function9', null],
  '\ue03a': ['Function10', null],
  '\ue03b': ['Function11', null],
  '\ue03c': ['Function12', null],
  '\ue03d': ['Meta', 'META'],
  '\ue053': ['Meta', 'META'],
};

// Sticky modifier category (from VIRTUAL_KEYS) -> the Automation virtual key name to release it.
export const MODIFIER_TO_KEY: StringRecord<string> = {
  SHIFT: 'Shift',
  CONTROL: 'Control',
  ALT: 'Alternate',
  META: 'Meta',
};
