# Pull request validation job
variables:
- name: SHOW_XCODE_LOG
  value: true

stages:
- stage: Unit_Tests
  jobs:
  - template: ./templates/node-e2e-template.yml
    parameters:
      nodeVersion: 14.x
- stage: Integration_Tests
  jobs:
  - template: ./templates/remote-debugger-e2e-template.yml
    parameters:
      name: iPhoneX_15_2
      iosVersion: 15.2
      xcodeVersion: 13.2
      deviceName: "iPhone 11"
      vmImage: 'macOS-11'
  - template: ./templates/remote-debugger-e2e-template.yml
    parameters:
      name: iPhoneX_14_5
      iosVersion: 14.5
      xcodeVersion: 12.5
      deviceName: "iPhone 11"
      vmImage: 'macOS-11'
